### PR TITLE
Revert PSROIPooling average logic introduced in 305f0056059b091e0290b…

### PR DESCRIPTION
**Pull request by mateusztabaka**
…983dabd93f655e86e8d

Ticket: 46200

### CODE REVIEW

**Review by ilyachur — COMMENTED** [review]
Why do you revert these changes? Does it a bug in the reference implementation?

**Comment by ilyachur** [comment]
PR https://github.com/openvinotoolkit/openvino/pull/3245 contains original changes

**Comment by mateusztabaka** [comment]
Yes, it was a bug in the reference.

**Comment by ilyachur** [comment]
> Yes, it was a bug in the reference.

Do we have tests which showed this regression?

**Review by ilyachur — APPROVED** [review]

**Comment by mateusztabaka** [comment]
Yes, it was revealed during person-detection-retail-0002 inference tests

**Pull request merged**
