### PR TITLE
[CPU][TESTS] Exclude cpplint check for custom test targets

### PR DESCRIPTION
**Pull request by EgorDuplensky**

### CODE REVIEW

**Review by iefode — DISMISSED** [review]
Why?

**Comment by EgorDuplensky** [comment]
> Why?

These targets are for development purpose only (under specific compilation flags) and not used in CI or anywhere besides local machines.
From development perspective we do not really need to run cpplint for each of these targets (and dozens of them are actually created).

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by iefode** [comment]
> @iefode Could you please a look one more time?

Honestly, i did not see any real arguments to merge these changes and switch off CPP_lint. Anyway CPU tests are repronsibity area of @dmitry-gorokhov

**Comment by dmitry-gorokhov** [comment]
@EgorDuplensky Please make CI green

**Pull request merged**
