### PR TITLE
Scatter nd update new reference implementation

### PR DESCRIPTION
**Pull request by pelszkow**
### Details:
 - new reference implementation for ScatterNdUpdate (drop usage of `CoordinateTransform::index`)

### Tickets:
 - 45859, 37503

### CODE REVIEW

**Comment by jdanieck** [comment]
@pelszkow since #5002 was merged please merge master to remove span from this PR. It'll be easier to review.

**Comment by lazarevevgeny** [comment]
@nshchego, @a-sidorova , @mandrono , please, take a look at this PR.

**Comment by iefode** [comment]
Please add the op name to [this list](https://github.com/openvinotoolkit/openvino/blob/a478475386732c3332c701d210786af7dad96eed/inference-engine/tests/ie_test_utils/functional_test_utils/layer_tests_summary/summarize.py#L24)

**Comment by pelszkow** [comment]
OK I will.

**Review by ggalieroc — APPROVED** [review]

**Review by jdanieck — APPROVED** [review]

**Comment by pelszkow** [comment]
PR is ready for review. Pleas contact me if you have any questions.

**Review by iefode — APPROVED** [review]

**Review by nshchego — APPROVED** [review]

**Pull request merged**
