### PR TITLE
Allow building wheels without isolation

### PR DESCRIPTION
**Pull request by JakubPalIntel**
### Details:
 - Adds cmake option to disable isolation (venv creation) in wheels build. This option is required when build is already running inside venv/virtualenv. 

### Tickets:
 - [EISW-146038](https://jira.devtools.intel.com/browse/EISW-146038)

### CODE REVIEW

**Review by p-wysocki — APPROVED** [review]

**Comment by p-wysocki** [comment]
Is there any place in documentation where we keep the flags description?

**Comment by JakubPalIntel** [comment]
@p-wysocki by looking for wheels related phrases I found these 2 doc files: 

https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/build.md
https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/cmake_options_for_custom_compilation.md

**Comment by pereanub** [comment]
build_jenkins

**Comment by JakubPalIntel** [comment]
Not needed anymore. https://github.com/openvinotoolkit/openvino/pull/27429 will be merged instead.

**Pull request closed without merging**
