### PR TITLE
[CPU] Cherry pick oneDNN ITT fix for lib loading on windows

### PR DESCRIPTION
**Pull request by EgorDuplensky**
### Details:
- No extra changes made, simply cherry-pick commit from oneDNN without any conflicts
- oneDNN fork PR - https://github.com/openvinotoolkit/oneDNN/pull/160

### Tickets:
- 93408

### CODE REVIEW

**Comment by EgorDuplensky** [comment]
@usstq Could you please take a look?

**Comment by usstq** [comment]
@EgorDuplensky  Sorry for late response, I checked the change and it can be summarized as :

 1. `__itt_release_resources/ITT_MUTEX_DESTROY` was introduced which is missing in current oneDNN fork, this function is supposed to frees resources at library unload time, but I didn't see any one calling it so far which is strange.
 2. `DEFAULT_DLLNAME` was removed so user must provide `INTEL_JIT_PROFILER64`/`INTEL_JIT_PROFILER32` to enable collector DLL, which is fine
 3. `src/cpu/x64/jit_uni_binary.cpp` was changed and `avx512_core_fp16` was removed
 
To me, the only big concern is https://github.com/openvinotoolkit/oneDNN/pull/160#discussion_r1032086841 so far

**Review by usstq — APPROVED** [review]
I tested on VC2019 and GCC, as long as __INTEL_COMPILER is not defined as 0, !__INTEL_COMPILER is the same as !defined(__INTEL_COMPILER) in practice, so I guess we can keep that

**Comment by dmitry-gorokhov** [comment]
Merged as part of https://github.com/openvinotoolkit/openvino/pull/14252

**Pull request closed without merging**
