### PR TITLE
[OV][VPUX] - Debug build flags (#14651)

### PR DESCRIPTION
**Pull request by DariaMityagina**
**Copy of https://github.com/openvinotoolkit/openvino/pull/14651** **and https://github.com/openvinotoolkit/openvino/pull/14753**

### REPLACE "/Zi" -> "/Zi /FS" + https://github.com/openvinotoolkit/openvino/pull/13826

- **/Zi -> /Zi /FS**
As it turned out, there is a [similar change with overwriting cmake flags](https://github.com/openvinotoolkit/openvino/blob/master/cmake/developer_package/compile_flags/os_flags.cmake#L311-L314) (/Z7, /Zi, ..) on the OpenVino side.
But instead of doing it [the way it was done in vpux-plugin](https://github.com/intel-innersource/applications.ai.vpu-accelerators.vpux-plugin/pull/1310/files) (now reverted in master - which can be part of the reason of its re-appearance), they change /Zi -> /Z7, which results in object files that also contain full symbolic debug information, and this seems to cause different errors.

- **Remove the config for pdb directory to let each project use own vxxx.pdb file.**
On Windows, the current config makes all cmake projects use bin/intel64/Release directory as intermediate directory for pdb files. Multiple cl.exe and linker.exe randomly access the pdb file at same time and crash for this. Close the config can solve random error:
fatal error C1041: cannot open program database 'xxx\openvino\bin\intel64\Release\vc140.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS

**Ticket:** E#62173, E#58508

Co-authored-by: Xin Wang <xin1.wang@intel.com>

### REPLACE "/Z7" -> "/Zi /FS"
Applying this comment: https://github.com/openvinotoolkit/openvino/pull/14651#issuecomment-1357538476

There are many 'workarounds' related to debug build flags. In different places they are replaced by each other, which causes confusion and possible problems. Examples:

- 17:47:04 C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\bin\intel64\Debug\vpux_mlir_compiler_staticd.lib : fatal error LNK1248: image size (1005C0F3F) exceeds maximum allowable size (FFFFFFFF)
- fatal error C1033: cannot open program database
- fatal error C1041: cannot open program database

### CODE REVIEW

**Comment by DariaMityagina** [comment]
Check:

- [ ] https://vpux-ci-vpuip.ir.intel.com/job/IE-Packages/job/try/job/OpenVINO-Windows10/22067/

**Review by OrestChura — APPROVED** [review]

**Comment by DariaMityagina** [comment]
@ilyachur hi!
Could you review this PR please?

**Comment by ilyachur** [comment]
In general I am ok with such changes, but we need to have an approval to merge it into release branch

**Comment by DariaMityagina** [comment]
> In general I am ok with such changes, but we need to have an approval to merge it into release branch

I see. 
So I need a review either from you or from @ilya-lavrenov, right?
image

**Comment by DariaMityagina** [comment]
@ArtemySkrebkov hi!
Could you please review this PR?

**Comment by ilyachur** [comment]
We don't have a plan to update 2022.3 branch

**Comment by DariaMityagina** [comment]
> We don't have a plan to update 2022.3 branch

Got it. Thanks!

**Comment by Maxim-Doronin** [comment]
> We don't have a plan to update 2022.3 branch

2022.3 is a LTS release, isn't it? If so, where do you plan to continue development for dot releases?

**Comment by DariaMityagina** [comment]
> > We don't have a plan to update 2022.3 branch
> 
> 2022.3 is a LTS release, isn't it? If so, where do you plan to continue development for dot releases?

I heard that 22.3.1 is going to be a LTS release.
@ilyachur could you please enlighten us on this topic?

**Comment by ilyachur** [comment]
Yes 2022.3 is LTS, and we will have new dot releases, but, usually we don't merge everything to LTS release branch with believe that these changes will be included in next LTS release.

**Pull request closed without merging**
