### PR TITLE
[IE][VPU] Removed Mish decomposition

### PR DESCRIPTION
**Pull request by novozhilov-m-m**
Removed Mish decomposition because new Mish kernel implemented, MDK PR: https://github.com/movidius/mdk/pull/14873
  | 10 Images | 100 Images | 1000 Images
-- | -- | -- | --
Myriad performance (FPS) | 1.39 | 1.39 | 1.39
CPU performance (FPS) | 2.27 | 2.22 | 2.26
Myriad map (%) | 59.61 | 60.39 | 73.26
CPU map (%) | 37.63 | 59.61 | 73.32
Myriad coco_precision (%) | 76.35 | 76.32 | 75.71
CPU coco_precision (%) | 71.1 | 76.35 | 75.7

Full dataset accuracy (5000):
map: 70.97%
coco_precision: 73.50%

### CODE REVIEW

**Review by elatkin — COMMENTED** [review]
Please update Myriad firmware

**Comment by evgenytalanin-intel** [comment]
For some reason this is allowed to be merged automatically despite internal check have not passed. Please don't merge this until internal checks will succeed

**Review by evgenytalanin-intel — CHANGES_REQUESTED** [review]
Setting to 'request changes' due to no internal checks completed yet

**Comment by elatkin** [comment]
@novozhilov-m-m 
Do you plan to update this pull-request?

**Review by elatkin — APPROVED** [review]

**Comment by Maxim-Doronin** [comment]
@novozhilov-m-m, please rebase the branch to re-run validation

**Comment by novozhilov-m-m** [comment]
@Maxim-Doronin, I rebased it 2 hours ago on the last master commit

**Review by Maxim-Doronin — APPROVED** [review]

**Comment by Maxim-Doronin** [comment]
@evgenytalanin-intel, have you any objections for now?

**Review by evgenytalanin-intel — APPROVED** [review]

**Pull request merged**
