### PR TITLE
[POT] Fixed FBC unbound error

### PR DESCRIPTION
**Pull request by KodiaqQ**
### Details:
 - *FBC missed spaces fix*

### Tickets:
 - *80923*

### CODE REVIEW

**Review by IndiraSalyahova — APPROVED** [review]

**Review by AlexKoff88 — APPROVED** [review]

**Comment by AlexKoff88** [comment]
@KodiaqQ, what kind of models are affected by this bug and fix?

**Comment by KodiaqQ** [comment]
> @KodiaqQ, what kind of models are affected by this bug and fix?

At least one model is listed on the ticket (see description). But, based on the code, I would like to say that the number of the affected models can be more than one. @IndiraSalyahova could you please confirm the fix is clear and correct?

**Comment by IndiraSalyahova** [comment]
> > @KodiaqQ, what kind of models are affected by this bug and fix?
> 
> At least one model is listed on the ticket (see description). But, based on the code, I would like to say that the number of the affected models can be more than one. @IndiraSalyahova could you please confirm the fix is clear and correct?



> > @KodiaqQ, what kind of models are affected by this bug and fix?
> 
> At least one model is listed on the ticket (see description). But, based on the code, I would like to say that the number of the affected models can be more than one. @IndiraSalyahova could you please confirm the fix is clear and correct?

@KodiaqQ, @AlexKoff88 yes, that's a typo. The error looks like using an undeclared variable and this variable is only declared in the condition and 4 spaces are needed.

**Comment by IndiraSalyahova** [comment]
> > @KodiaqQ, what kind of models are affected by this bug and fix?
> 
> At least one model is listed on the ticket (see description). But, based on the code, I would like to say that the number of the affected models can be more than one. @IndiraSalyahova could you please confirm the fix is clear and correct?



> > @KodiaqQ, what kind of models are affected by this bug and fix?
> 
> At least one model is listed on the ticket (see description). But, based on the code, I would like to say that the number of the affected models can be more than one. @IndiraSalyahova could you please confirm the fix is clear and correct?

@KodiaqQ, @AlexKoff88 yes, that's a typo. The error looks like using an undeclared variable and this variable is only declared in the condition and 4 spaces are needed.

**Pull request merged**
