### PR TITLE
[ONNX] Aligned ReduceL1 behavior #20559

### PR DESCRIPTION
**Pull request by RitikaxShakya**
### Details:
 -I've aligned the ReduceL1 operation with opset 11, 13, and 18. I've registered the function inside the ops_bridge.cpp, created test models, and added them inside onnx_import.in.cpp.

### Tickets:
 - **https://github.com/openvinotoolkit/openvino/issues/20559**

### CODE REVIEW

**Comment by RitikaxShakya** [comment]
@gkrivor @p-wysocki Please take a look at this PR. Thank You!

**Comment by gkrivor** [comment]
build_jenkins

**Comment by RitikaxShakya** [comment]
@gkrivor Hello! If there is anything i need to do from my end, please let me know. Thank you!

**Comment by RitikaxShakya** [comment]
> This PR will be closed in a week because of 2 weeks of no activity.

@gkrivor Hello! Please let me know If there is anything i need to do from my end. Thank you!

**Comment by mlukasze** [comment]
we are willing to merge it, could you please resolve conflicts?

**Comment by RitikaxShakya** [comment]
> we are willing to merge it, could you please resolve conflicts?

Solved conflicts

**Comment by mlukasze** [comment]
build_jenkins

**Comment by mlukasze** [comment]
build_jenkins

**Comment by mlukasze** [comment]
@gkrivor could you take a look, please?

**Comment by mlukasze** [comment]
hey @RitikaxShakya 
could you please resolve conflicts? we will review it very soon
thanks and sorry for the delay, it's on us :(

**Comment by RitikaxShakya** [comment]
> hey @RitikaxShakya could you please resolve conflicts? we will review it very soon thanks and sorry for the delay, it's on us :(

Okay, i will try finishing it this week

**Comment by mlukasze** [comment]
thanks!

**Comment by gkrivor** [comment]
@RitikaxShakya could you rebase your change? There are several changes in the code which should be solved.

**Comment by gkrivor** [comment]
Hi @RitikaxShakya, tell me please if you have any issues with rebasing I'll help.

**Comment by gkrivor** [comment]
Hi @RitikaxShakya , any issues?

**Comment by RitikaxShakya** [comment]
> Hi @RitikaxShakya , any issues?

Yes, i tried rebasing and solve conflicts but it kinda messed up by showing commits that i didn't make, i tried resetting but its also not working. but I have my changes saves so i am thinking to make new PR, is that alright with you ? I would take me a day.

**Comment by gkrivor** [comment]
It is because of merging a master branch. You can try to make a rebasing your branch locally to a current master. It should cleanup common changes and you will see only your changes.
I'm ok with new PR too :)

**Comment by RitikaxShakya** [comment]
> It is because of merging a master branch. You can try to make a rebasing your branch locally to a current master. It should cleanup common changes and you will see only your changes. I'm ok with new PR too :)

Oh okay, i tried this as well but it doesn't cleanup but i will try again, if it works cool, if not then will open a new pr. Thank you!

**Comment by RitikaxShakya** [comment]
> It is because of merging a master branch. You can try to make a rebasing your branch locally to a current master. It should cleanup common changes and you will see only your changes. I'm ok with new PR too :)

Hey I opened new PR [Here](https://github.com/openvinotoolkit/openvino/pull/25909), I have few questions, i have asked them in new PR.

**Pull request closed without merging**
