### PR TITLE
Remove checks for output precision

### PR DESCRIPTION
**Pull request by Tygrikon**
Set user output precision without checks, needed for ICNet

### CODE REVIEW

**Comment by Tygrikon** [comment]
@vinograd47 please take a look

**Comment by Tygrikon** [comment]
Rebuild

**Comment by Tygrikon** [comment]
@ArtemySkrebkov-intel  please take a look too

**Comment by ArtemySkrebkov-intel** [comment]
Please attach Nets-validtion link as a proof.

**Comment by Tygrikon** [comment]
> Please attach Nets-validtion link as a proof.

@ArtemySkrebkov-intel We don't have ICNet in Nets-validation

**Review by vinograd47 — APPROVED** [review]

**Comment by Tygrikon** [comment]
rebuild

**Comment by ArtemySkrebkov-intel** [comment]
@Tygrikon 
We have it in weekly. It is possible to run it manually.

**Review by andrey-markelov — APPROVED** [review]
LGTM

**Comment by Tygrikon** [comment]
@ilya-lavrenov  Could you please merge this mr?

**Pull request merged**
