### PR TITLE
Add SLT to Template Plugin: Loop-5

### PR DESCRIPTION
**Pull request by steve-y**
### Details:
 - *Create template plugin reference tests for target operation: Loop-5*

### Tickets:
 - *64095*

### CODE REVIEW

**Review by jade-cho — APPROVED** [review]

**Comment by ilyachur** [comment]
Please fix CI and merge conflicts

**Comment by steve-y** [comment]
> Please fix CI and merge conflicts

As Wilson commented in #9692, this conflict is due to #9752 and he asked Irina in the sync meeting yesterday. And the TensorIterator and Loop op_reference codes are already implemented in #9752.
This is his comment in #9692, and same to this PR as well;
`@ilyachur @iefode I met a confliction of tensor_iterator.cpp with #9752. The PR created new op reference test in template plugin(docs/template_plugin/tests/functional/op_reference/tensor_iterator.cpp). Then do I need to merge so both test cases exist in the file? Or close this PR without merge?
`
Could you check it please?

**Comment by ilyachur** [comment]
> > Please fix CI and merge conflicts
> 
> As Wilson commented in #9692, this conflict is due to #9752 and he asked Irina in the sync meeting yesterday. And the TensorIterator and Loop op_reference codes are already implemented in #9752. This is his comment in #9692, and same to this PR as well; `@ilyachur @iefode I met a confliction of tensor_iterator.cpp with #9752. The PR created new op reference test in template plugin(docs/template_plugin/tests/functional/op_reference/tensor_iterator.cpp). Then do I need to merge so both test cases exist in the file? Or close this PR without merge? ` Could you check it please?


Please check coverage of tests and if we need to have more test cases, please extend tests.

**Comment by steve-y** [comment]
> Please check coverage of tests and if we need to have more test cases, please extend tests.

This PR has tests of body function with `Add` operation of `trip count` 1 and 5 in `static shape`, and which refers to `cpuFuncTests`. And #9752 has tests of body function with `Add` and `Multiply` operations of `trip count` 3 in `dynamic shape`. So I think #9752 seems to cover this PR. What do you think?

**Comment by steve-y** [comment]
> Please check coverage of tests and if we need to have more test cases, please extend tests.

This PR has tests of body function with Add operation of trip count 1 and 5 in static shape, and which refers to cpuFuncTests. And #9752 has tests of body function with Add and Multiply operations of trip count 3 in dynamic shape. So I added tests of this PR to #9752.

**Review by ilyachur — APPROVED** [review]

**Pull request merged**
