### PR TITLE
[JAX FE] Update JAX version to latest one for testing

### PR DESCRIPTION
**Pull request by rkazants**
**Details:** It is required for validation of Python 3.12 support.

**Tickets:** 150860

### CODE REVIEW

**Comment by p-wysocki** [comment]
Jax tests fail with:
```bash
Exception: Could not trace the TF model with the following error: XlaCallModule from your TensorFlow installation supports up to serialization version 8 but the serialized module needs version 9. You should upgrade TensorFlow, e.g., to tf_nightly.
```

According to the logs the `tensorflow` version being installed is `tensorflow-2.14.1`. Perhaps we should increase the version lower bound? The newest one available is 2.17.

**Comment by ilya-lavrenov** [comment]
JAX FE is not part of release, why is it required for code freeze?

**Comment by rkazants** [comment]
> JAX FE is not part of release, why is it required for code freeze?

There are important tests for TF FE to validate `Xla` operations. JAX tests have two passes via TF FE and JAX FE.

**Comment by ilya-lavrenov** [comment]
tests are not part of the product. 
Its enabling can be done after CF

**Comment by rkazants** [comment]
> tests are not part of the product. Its enabling can be done after CF

No, we cannot switch off them in the master. Let create separate job for Python 3.12 without these tests and have the current Python version with it.

**Comment by ilya-lavrenov** [comment]
```
Exception: Could not trace the TF model with the following error: XlaCallModule from your TensorFlow installation supports up to serialization version 8 but the serialized module needs version 9. You should upgrade TensorFlow, e.g., to tf_nightly
```
I can hardly imagine that we can fix it before CF

**Comment by rkazants** [comment]
> JAX FE is not part of release, why is it required for code freeze?

Some 

> JAX FE is not part of release, why is it required for code freeze?



> ```
> Exception: Could not trace the TF model with the following error: XlaCallModule from your TensorFlow installation supports up to serialization version 8 but the serialized module needs version 9. You should upgrade TensorFlow, e.g., to tf_nightly
> ```
> 
> I can hardly imagine that we can fix it before CF

I am working on it to resolve it asap

**Review by akuporos — APPROVED** [review]

**Pull request merged**
