### PR TITLE
opset4 Convolution/GroupConvolution -> Multiply fusion

### PR DESCRIPTION
**Pull request by GlebKazantaev**
* Added Convolution/GroupConvolution->Multiply fusion based on ops from opset4 (including support of scalars)
* Replaced legacy fusion with new
* Added functional tests
* Added some predicate helpers for smart pattern matching

### CODE REVIEW

**Comment by ilyachur** [comment]
Why do you not remove legacy ConvMultiplyFusion?

**Comment by GlebKazantaev** [comment]
> Why do you not remove legacy ConvMultiplyFusion?

It's still used in other plugins. I'll make transition for them and remove old passes after this PR.

**Comment by GlebKazantaev** [comment]
**This PR must be merged only after internal validation cycle completion**

**Comment by GlebKazantaev** [comment]
**Update:** internal cycle successfully passed.

**Pull request merged**
