### PR TITLE
[nGraph] Adds MakeUnStateful transformation

### PR DESCRIPTION
**Pull request by nkogteva**
### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
is it still valid?

**Comment by nkogteva** [comment]
> is it still valid?

Yes, I just had no time to finish my experiments. But these transformations are needed if we decide to support model with splitted state between plugins in hetero mode.

**Comment by akladiev** [comment]
This PR will be closed in 2 weeks in case of no activity.

**Comment by akladiev** [comment]
This PR was closed because it has been stalled for 2 week with no activity.

**Pull request closed without merging**
