### PR TITLE
Use shell parameter expansion to make getting source path work in non-bash shells

### PR DESCRIPTION
**Pull request by Thodoris1999**
Currently `BASH_SOURCE[0]` was used, which is only available on bash.

I changed it to `${BASH_SOURCE:-$0}` which is supported by at least bash, zsh and dash, as explained by [https://stackoverflow.com/a/68359914/9028340](https://stackoverflow.com/a/68359914/9028340)

It uses shell parameter expansion
https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
https://zsh.sourceforge.io/Doc/Release/Expansion.html#Parameter-Expansion

Addresses #17392

### CODE REVIEW

**Review by Wovchena — APPROVED** [review]
build_jenkins

**Comment by ilya-lavrenov** [comment]
@Thodoris1999 
Could you please also update file https://github.com/openvinotoolkit/openvino/blob/master/.github/dockerfiles/docker_tag with your PR number?

**Comment by ilya-lavrenov** [comment]
build_jenkins

**Comment by Thodoris1999** [comment]
Should I worry about theses failing cases? I don't  have access to openvino-ci.toolbox.iotg.sclab.intel.com

**Comment by Wovchena** [comment]
No. It was a download error.

**Review by ilya-lavrenov — APPROVED** [review]

**Pull request merged**
