### PR TITLE
Add hddl_unite to dependencies.sh/bat (#2467)

### PR DESCRIPTION
**Pull request by asomsiko**

### CODE REVIEW

**Comment by asomsiko** [comment]
@ArtemySkrebkov-intel this should fix KPI compilation test

**Comment by ArtemySkrebkov-intel** [comment]
@sshumihi 
FYI

**Comment by ilya-lavrenov** [comment]
Is it still valid ?

**Comment by ArtemySkrebkov-intel** [comment]
Not relevant anymore.

**Pull request closed without merging**
