### PR TITLE
[chore] Update branch to take other repos from for Azure pipelines

### PR DESCRIPTION
**Pull request by ababushk**
### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

### CODE REVIEW

**Review by ilya-lavrenov — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
could you please do the same for files in https://github.com/openvinotoolkit/openvino_contrib/blob/master/.ci/azure/ ?

**Comment by ababushk** [comment]
You mean on releases/2022/3 branch for openvino_contrib? Sure, I can

**Comment by ilya-lavrenov** [comment]
> You mean on releases/2022/3 branch for openvino_contrib? Sure, I can

yes.

**Comment by ababushk** [comment]
> > You mean on releases/2022/3 branch for openvino_contrib? Sure, I can
> 
> yes.

Done.

**Pull request merged**
