### PR TITLE
LPT Refactoring PR Leftovers

### PR DESCRIPTION
**Pull request by GlebKazantaev**
### Description:
This PR includes several fixes related to the recently merged LPT refactoring PR.

### CODE REVIEW

**Review by v-Golubev — APPROVED** [review]
Changes look good to me, thanks!

**Comment by ilya-lavrenov** [comment]
@v-Golubev Is it still valid?

**Comment by akladiev** [comment]
This PR will be closed in 2 weeks in case of no activity.

**Comment by akladiev** [comment]
This PR was closed because it has been stalled for 2 week with no activity.

**Pull request closed without merging**
