### PR TITLE
Restore CanCreateCacheDirAndDumpBinariesUnicodePath

### PR DESCRIPTION
**Pull request by riverlijunjie**
### Details:
 - Fix tests on Windows to create a cache_dir folder with Unicode symbols

### Tickets:
 - CVS-128116
 - Closes https://github.com/openvinotoolkit/openvino/issues/23072

### CODE REVIEW

**Comment by riverlijunjie** [comment]
In Windows OS, the created `cache_dir name(std::string)` is exact same with `wstring_to_string(cache_path_w)`, but not same with `cache_path_w(std::wstring)`:

image

While in Linux, they are same:
image

So one of solution is to use `wstring_to_string(cache_path_w)` to check existed directory, it is this PR.
Another solution is to enable `ov::cache_dir` to support` std::string` and `std::wstring`

**Comment by vurusovs** [comment]
> In Windows OS, the created `cache_dir name(std::string)` is exact same with `wstring_to_string(cache_path_w)`, but not same with `cache_path_w(std::wstring)`:
> 
> image
> 
> While in Linux, they are same: image
> 
> So one of solution is to use `wstring_to_string(cache_path_w)` to check existed directory, it is this PR. Another solution is to enable `ov::cache_dir` to support` std::string` and `std::wstring`

@riverlijunjie could you check which implementation of `directoryExists` is used? We have one in `common_test_utils/unicode_utils.hpp` and another one in `common_test_utils/file_utils.hpp` (this is included in a file).  It may be the reason of such difference
Anyway, if we were commited that OpenVINO supports wide strings (unicode), cache should also support it

**Comment by riverlijunjie** [comment]
> @riverlijunjie could you check which implementation of `directoryExists` is used? We have one in `common_test_utils/unicode_utils.hpp` and another one in `common_test_utils/file_utils.hpp` (this is included in a file). It may be the reason of such difference Anyway, if we were commited that OpenVINO supports wide strings (unicode), cache should also support it

It goes to `common_test_utils/unicode_utils.hpp` in Windows.

**Comment by ilya-lavrenov** [comment]
BTW, maybe we can remove file utils from common utils? 
and reuse `openvino::util` ones

**Comment by riverlijunjie** [comment]
> BTW, maybe we can remove file utils from common utils? and reuse `openvino::util` ones

Use `bool ov::util::directory_exists(const std::wstring& path)` to replace `inline bool directoryExists(const std::wstring& path)` ?

**Comment by ilya-lavrenov** [comment]
> > BTW, maybe we can remove file utils from common utils? and reuse `openvino::util` ones
> 
> Use `bool ov::util::directory_exists(const std::wstring& path)` to replace `inline bool directoryExists(const std::wstring& path)` ?

Yes, removed duplicates from test file utils.

**Comment by riverlijunjie** [comment]
Another solution: https://github.com/openvinotoolkit/openvino/pull/23100

**Comment by peterchen-intel** [comment]
https://github.com/openvinotoolkit/openvino/pull/23100 was merged, does it mean we can close this one? @riverlijunjie

**Pull request closed without merging**
