### PR TITLE
Migrate Movement 1 Operations (StridedSlice-1)

### PR DESCRIPTION
**Pull request by steve-y**
### Details:
 - *Create template plugin reference tests for target operation: StridedSlice*
 - *Remove ngraph backend files*
 - *Update CMakeLists.txt*
 - *Add R"(.\*ReferenceStridedSliceLayerTest.\*dynamic)" to skip_tests_config.cpp*

### Tickets:
 - *64052*

### CODE REVIEW

**Comment by ilyachur** [comment]
> @ilyachur @iefode After adding shape to tensors (actually changing argument orders), the dynamic shape seems to work except `strided_slice_stride_optional_dynamic` cases. It failed with:
> 
> > unknown file: Failure
> > C++ exception with description "Check 'PartialShape(shape).refines(get_partial_shape())' failed at core/src/runtime/host_tensor.cpp:143:
> > Allocation shape {1, 4} must be compatible with the partial shape: {?,?,?}
> > " thrown in the test body.
> 
> And the error location and the error values are like:
> 
>     * In https://github.com/steve-y/openvino/blob/eed93d588a3ad46daf1992bbe4fc79381fd55159/ngraph/core/src/runtime/host_tensor.cpp#L138
> 
>     * unit-test `get_parital_shape()` returns `{1, 4}` but templateFuncTests `get_partial_shape()` returns `{0, 0, 0}`.
> 
> 
> Their call sequence are as follows:
> 
> templateFuncTests:
> 
>     * ...
> 
>     * CommonReferenceTest::Exec()
> 
>     * CommonReferenceTest::Infer()
> 
>     * InferRequest::Infer()
> 
>     * ...
> 
>     * INTExecutable::call()
> 
>     * StridedSlice::evaluate()
> 
>     * strided_slice::evaluate_strided_slice()
> 
>     * strided_slice::evaluate()
> 
>     * HostTensor::set_shape()
> 
> 
> unit-test:
> 
>     * ...
> 
>     * Executable::call_with_validate()
> 
>     * DynamicExecutable::call()
> 
>     * INTExecutable::call()
> 
>     * StridedSlice::evaluate()
> 
>     * strided_slice::evaluate_strided_slice()
> 
>     * strided_slice::evaluate()
> 
>     * HostTensor::set_shape()
> 
> 
> I've tried to make it run but failed. Could you let me know any suggestion or reference?

Hi @steve-y ,

I don't have an idea why it happens. We need to debug the situation and understand the moment when we loose  shapes.
Because `unit-tests` is using `interpreter_backend` to run reference implementations and `template plugin` uses the same backend inside, need to investigate the issue, maybe it is related with template plugin, maybe not.
In order to understand it we need to find the first place where we get incorrect shapes.

**Comment by steve-y** [comment]
Comparing `strided_slice_0_dynamic` and `strided_slice_stride_optional_dynamic`, the `m_nodes` in `runtime::interpreter::INTExecutable::call()` in int_executable.cpp are like;
`strided_slice_0_dynamic`:
m_mode[0] - Parameter
m_mode[1] - Parameter
m_mode[2] - Parameter
m_mode[3] - Parameter
m_mode[4] - StridedSlice
m_mode[5] - Result

`strided_slice_stride_optional_dynamic`
m_mode[0] - Parameter
m_mode[1] - Parameter
m_mode[2] - Parameter
m_mode[3] - `Constant`
m_mode[4] - StridedSlice
m_mode[5] - Result

In `strided_slice_stride_optional_dynamic` case, unexpected Constant seems to be inserted in the network. And its shape is not defined well, and it generates the exception.

**Comment by ilyachur** [comment]
> Comparing `strided_slice_0_dynamic` and `strided_slice_stride_optional_dynamic`, the `m_nodes` in `runtime::interpreter::INTExecutable::call()` in int_executable.cpp are like; `strided_slice_0_dynamic`: m_mode[0] - Parameter m_mode[1] - Parameter m_mode[2] - Parameter m_mode[3] - Parameter m_mode[4] - StridedSlice m_mode[5] - Result
> 
> `strided_slice_stride_optional_dynamic` m_mode[0] - Parameter m_mode[1] - Parameter m_mode[2] - Parameter m_mode[3] - `Constant` m_mode[4] - StridedSlice m_mode[5] - Result
> 
> In `strided_slice_stride_optional_dynamic` case, unexpected Constant seems to be inserted in the network. And its shape is not defined well, and it generates the exception.

Did we have issues with `strided_slice_stride_optional_dynamic` in backend tests?
Or is it a new test case?

**Comment by steve-y** [comment]
> > Comparing `strided_slice_0_dynamic` and `strided_slice_stride_optional_dynamic`, the `m_nodes` in `runtime::interpreter::INTExecutable::call()` in int_executable.cpp are like; `strided_slice_0_dynamic`: m_mode[0] - Parameter m_mode[1] - Parameter m_mode[2] - Parameter m_mode[3] - Parameter m_mode[4] - StridedSlice m_mode[5] - Result
> > `strided_slice_stride_optional_dynamic` m_mode[0] - Parameter m_mode[1] - Parameter m_mode[2] - Parameter m_mode[3] - `Constant` m_mode[4] - StridedSlice m_mode[5] - Result
> > In `strided_slice_stride_optional_dynamic` case, unexpected Constant seems to be inserted in the network. And its shape is not defined well, and it generates the exception.
> 
> Did we have issues with `strided_slice_stride_optional_dynamic` in backend tests? Or is it a new test case?

`strided_slice_stride_optional_dynamic` is in backend tests with the name of `strided_slice_stride_optional`.
StridedSlice has only dynamic shape tests and static shape tests are added and the original dynamic tests has the suffix `_dynamic`.

**Pull request merged**
