### PR TITLE
[XLink] - Fix Mac build

### PR DESCRIPTION
**Pull request by DariaMityagina**

### CODE REVIEW

**Comment by DariaMityagina** [comment]
@azhogov build https://dev.azure.com/openvinoci/dldt/_build/results?buildId=197383&view=logs&s=96ac2280-8cb4-5df5-99de-dd2da759617d was successful.

**Review by azhogov — APPROVED** [review]

**Comment by DariaMityagina** [comment]
mac build https://dev.azure.com/openvinoci/dldt/_build/results?buildId=197973&view=results was successful.

**Review by Maxim-Doronin — APPROVED** [review]

**Pull request merged**
