### PR TITLE
Transformation from StridedSlice to SpaceToDepth in yolov5

### PR DESCRIPTION
**Pull request by usstq**
### Details:
 - Add stridedslice chain concat pattern matcher to fuse into spacetodepth
 - Add test cases

### Tickets:
 - *CVS-62764*

### CODE REVIEW

**Comment by usstq** [comment]
@GlebKazantaev Hi, Can you help to review this commit, Thanks!

**Comment by andrei-kochin** [comment]
@ilyachur @GlebKazantaev could you please review this change?

**Comment by usstq** [comment]
@GlebKazantaev  Hi Gleb, I've rebased my PR, could you please take a look? thanks!

**Comment by usstq** [comment]
@GlebKazantaev @dmitry-gorokhov  Seems that yolov5 has introduced a better way to express this structure (even w/o using SpaceToDepth)

https://github.com/ultralytics/yolov5/issues/4825

The most recent yolov5 network release already integrated this change, so this transformation is no longer useful for yolov5, should we abandon?

**Pull request closed without merging**
