### PR TITLE
DOCS: Update doxygen version

### PR DESCRIPTION
**Pull request by sgolebiewski-intel**
Updating doxygen to the latest version - 1.9.6. due to the sourceforge issues.

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
> @ilya-lavrenov, @ilyachur it appears there's an issue with: [src/core/include/openvino/pass/pattern/op/branch.hpp](https://github.com/openvinotoolkit/openvino/blob/master/src/core/include/openvino/pass/pattern/op/branch.hpp) file:
> 
> image
> 
> Can you help? Thanks

We need to remove these 2 lines:
https://github.com/openvinotoolkit/openvino/blob/d7e77e30a8a76a3caadfd144388e2ea64b40be59/src/core/include/openvino/pass/pattern/op/branch.hpp#L26-L27
Because there is no actually parameters to that constructor. Could you please do it in current PR?

**Comment by sgolebiewski-intel** [comment]
> > @ilya-lavrenov, @ilyachur it appears there's an issue with: [src/core/include/openvino/pass/pattern/op/branch.hpp](https://github.com/openvinotoolkit/openvino/blob/master/src/core/include/openvino/pass/pattern/op/branch.hpp) file:
> > image
> > Can you help? Thanks
> 
> We need to remove these 2 lines:
> 
> https://github.com/openvinotoolkit/openvino/blob/d7e77e30a8a76a3caadfd144388e2ea64b40be59/src/core/include/openvino/pass/pattern/op/branch.hpp#L26-L27
> 
> 
> Because there is no actually parameters to that constructor. Could you please do it in current PR?

Will do. Thank you for your help :)

**Review by ilya-lavrenov — APPROVED** [review]
Let's check by eyes that documentation is properly generated

**Review by ilyachur — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
Let's also port changes to 2022.3?
The fixes seem useful

**Pull request merged**
