### PR TITLE
Add FP32 <-> BF16 conversion

### PR DESCRIPTION
**Pull request by ecopty**
For supporting BFloat16 DType, conversion from/to FP32 is needed, the MR adds this support

### CODE REVIEW

**Comment by ilyachur** [comment]
Why do we need to have this conversion?

Could you please add tests to check that it works as expected?

**Comment by ecopty** [comment]
@ilyachur it's needed for tests added in kmbplugin https://gitlab-icv.inn.intel.com/inference-engine/kmb-plugin/merge_requests/1991

**Comment by ecopty** [comment]
@ilyachur  can you point to a test where fp16tofp32 conversion is tested, I can add similar ones, the only tests I see are under tests_deprecated

**Comment by ilya-lavrenov** [comment]
> it's needed for tests added in kmbplugin

Maybe we can keep this in kmb tests, then?

**Comment by ecopty** [comment]
@ilya-lavrenov  can you explain why not to add the conversion? BF16 is a type listed in the dtypes in ie_precision.hpp, so why not have the conversion just like we have the conversion for fp16?

**Comment by ilyachur** [comment]
> @ilya-lavrenov can you explain why not to add the conversion? BF16 is a type listed in the dtypes in ie_precision.hpp, so why not have the conversion just like we have the conversion for fp16?

Because looks like these functions are legacy API.
At the current moment we have a nGraph [transformation pass](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/transformations/src/transformations/convert_precision.cpp) which allow to convert different data types. I hope this transformation can be extended for `bf16`.

**Comment by ilya-lavrenov** [comment]
> can you explain why not to add the conversion?

Code to common library is added only when it's used in more than 1 release component. But:
1. Tests it's not a release component and in OpenVINO distribution this code will not used, but it takes extra binary size
2. It's used in 1 place only

**Pull request closed without merging**
