### PR TITLE
Update to python 3.10 for setupvars.sh/bat. Ubuntu22.04 default python 3.10

### PR DESCRIPTION
**Pull request by xipingyan**
### Details:
 - *Ubuntu 22.04 default python version is 3.10, update setupvars.sh/bat to max support 3.10, avoiding to block other test.*
 - *...*

### Tickets:
 - *86847*

### CODE REVIEW

**Comment by helena-intel** [comment]
@jiwaszki  is Python 3.10 supported for OpenVINO Runtime?

**Comment by jiwaszki** [comment]
> @jiwaszki is Python 3.10 supported for OpenVINO Runtime?

There is no official support for Python 3.10. Please refer to "System Requirements" section: https://pypi.org/project/openvino/

**Review by jiwaszki — CHANGES_REQUESTED** [review]
Do not merge.

**Comment by jiwaszki** [comment]
@p-wysocki please check if this PR can be closed

**Comment by p-wysocki** [comment]
The changes made in this PR have already been implemented in https://github.com/openvinotoolkit/openvino/pull/12578, which is currently blocked. Please see ticket 86678. Changes to `setupvars` do not guarantee Python 3.10 support, it needs a lot more work. Please reopen if needed.

**Pull request closed without merging**
