### PR TITLE
Fluid update WW49 2021 from OCV-4.x branch

### PR DESCRIPTION
**Pull request by OrestChura**
### Details:
 - Update includes attempts to fix Coverity warnings

### CODE REVIEW

**Comment by OrestChura** [comment]
@ArtemySkrebkov-intel could you please check if everything's good with VPUX with this revision of fluid (G-API standalone)

**Comment by ArtemySkrebkov-intel** [comment]
https://dsp-ci-icv.inn.intel.com/job/IE-MDK/job/manual/job/Ubuntu-Yocto/2265/

**Comment by ArtemySkrebkov-intel** [comment]
@mznamens @alpkn @andreychekhoninintel 

FYI

**Comment by ArtemySkrebkov-intel** [comment]
The failing tests are known issues, so I am OK to approve the PR. 👍

**Review by ArtemySkrebkov — APPROVED** [review]

**Pull request merged**
