### PR TITLE
CPU: Cherry-pick dest scale unroll fix.

### PR DESCRIPTION
**Pull request by luweizhou2016**
### Details:
 - *Cherry-pick onednn fix VMM unroll issue *
### Tickets:
 - *CVS-110341*

### CODE REVIEW

**Comment by luweizhou2016** [comment]
ONEDNN ticket and link to original patch
https://jira.devtools.intel.com/browse/MFDNN-10036

**Comment by dmitry-gorokhov** [comment]
@luweizhou2016  We are doing migration on OneDNN 3.2. Does this release include required fixes?

**Comment by dmitry-gorokhov** [comment]
> > @luweizhou2016 We are doing migration on OneDNN 3.2. Does this release include required fixes?
> 
> @dmitry-gorokhov , Just checked the ONEDNN rls-v3.2 branch. The fix has been cherry-picked into.

Ok, lets then wait oneDNN 3.2 migration.

**Comment by luweizhou2016** [comment]
Close PR because will merge into ONEDNN 3.2

**Pull request closed without merging**
