### PR TITLE
Reshape-able SliceConverter

### PR DESCRIPTION
**Pull request by yekruglov**
Description: Implement a transform, that convert Slice to StridedSlice, in reshape-able way

JIRA: CVS-41517

Code:
* [x]  Comments
* [x]  Code style (PEP8)
* [x]  Transformation generates reshape-able IR
* [x]  Transformation preserves original framework node names

Validation:
* [x]  Unit tests
* [x]  Framework operation tests N/A: no new operations were enabled
* [x]  Transformation tests
* [x]  e2e model test with an update of ./tests/e2e_oss/utils/reshape_utils.py N/A: no new models were enabled
* [x]  Model Optimizer IR Reader check

Documentation:
* [x]  Supported frameworks operations list N/A: no new operations were enabled
* [x]  Supported **public** models list N/A: no new models were enabled
* [x]  New operations specification N/A: no new operations were enabled
* [x]  Guide on how to convert the **public** model N/A: no new models were enabled
* [x]  User guide update N/A

### CODE REVIEW

**Review by lazarevevgeny — CHANGES_REQUESTED** [review]
Please, run layer tests for the ONNX Slice operation and make sure that all tests pass

**Comment by yekruglov** [comment]
> Please, run layer tests for the ONNX Slice operation and make sure that all tests pass

@lazarevevgeny 36 of 676 failed, working on fix

**Comment by lazarevevgeny** [comment]
@yekruglov, is this PR ready for re-review? If so, could you resolve the comments?

**Comment by yekruglov** [comment]
> @yekruglov, is this PR ready for re-review? If so, could you resolve the comments?

Ready.
Also there was a problem with data types in Select operation, that caused e2e failed.

**Review by lazarevevgeny — APPROVED** [review]

**Pull request merged**
