### PR TITLE
Remove catch(...) code style

### PR DESCRIPTION
**Pull request by panhaiqi**
### Details:
 - *Remove catch(...) code style*

### Tickets:
 - *96402*

### CODE REVIEW

**Comment by riverlijunjie** [comment]
@ilyachur do we need resolve all `catch(...)` in openvino project rather than  only auto plugin?

**Comment by ilya-lavrenov** [comment]
> @ilyachur do we need resolve all `catch(...)` in openvino project rather than only auto plugin?

I vote for all such places

**Comment by ilyachur** [comment]
> > @ilyachur do we need resolve all `catch(...)` in openvino project rather than only auto plugin?
> 
> I vote for all such places

I agree

**Comment by riverlijunjie** [comment]
> > > @ilyachur do we need resolve all `catch(...)` in openvino project rather than only auto plugin?
> > 
> > 
> > I vote for all such places
> 
> I agree

In some case, there are 2 or more `catch-clauses` for one `try`, and the last catch-clause is used as `catch(...)` to catch all other exception, in this case we cannot remove/replace catch(...), for example:
https://github.com/openvinotoolkit/openvino/blob/87b73b4/src/plugins/intel_gpu/src/graph/kernel_runner.cpp#L205-L209
https://github.com/openvinotoolkit/openvino/blob/87b73b4/src/inference/dev_api/cpp_interfaces/interface/ie_iplugin_internal.hpp#L401-L403

**Review by rkazants — CHANGES_REQUESTED** [review]
merge conflicts.
Also, why do we have +444,818 and -893? I think they should be equal if you replace `catch(...)` with `cath(std::exception&)`

**Comment by t-jankowski** [comment]
> merge conflicts. Also, why do we have +444,818 and -893? I think they should be equal if you replace `catch(...)` with `cath(std::exception&)`

There are python build remains - binaries are site_packages. It looks like `.gitignore` is ignored by some IDE git plugin.

**Review by t-jankowski — CHANGES_REQUESTED** [review]
Remove build artifacts - these should never be in a PR.

**Pull request closed without merging**
