### PR TITLE
[CPU] NMS_on_APL

### PR DESCRIPTION
**Pull request by chenhu-wang**
### Details:
 - *NMS_on_APL*

### Tickets:
 - *78611*
 - *78715*
 PR in oneDNN: https://github.com/openvinotoolkit/oneDNN/pull/122

### CODE REVIEW

**Comment by chenhu-wang** [comment]
@dmitry-gorokhov could you please review?

**Comment by chenhu-wang** [comment]
@dmitry-gorokhov Hi, Dmitry. The problem is in [uni_vaddps()](https://github.com/openvinotoolkit/openvino/pull/10649/files#diff-750a89ca15a9463b50fe3f9b1a7400281e243ee383b0ffc8026e904e4282fe92R452) and [uni_vsubps()](https://github.com/openvinotoolkit/openvino/pull/10649/files#diff-750a89ca15a9463b50fe3f9b1a7400281e243ee383b0ffc8026e904e4282fe92R458). After oneDNN changes, there is no need to update here in node implementation.

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
@chenhu-wang please rebase on latest master

**Comment by chenhu-wang** [comment]
> @chenhu-wang please rebase on latest master

@dmitry-gorokhov, rebased and CI is green.

**Pull request merged**
