### PR TITLE
fix concat perf

### PR DESCRIPTION
**Pull request by zhangYiIntel**
### Details:
 - *fix parallel_it_step performance drop*
 - *simplify concat reference implementation*

### Tickets:
 - *96812*

### CODE REVIEW

**Comment by zhangYiIntel** [comment]
@maxnick I put your fix of strides in this PR as well.

**Comment by dmitry-gorokhov** [comment]
> @maxnick I put your fix of strides in this PR as well.

@zhangYiIntel  @maxnick Can we cover that case by tests?

**Comment by zhangYiIntel** [comment]
> > @maxnick I put your fix of strides in this PR as well.
> 
> @zhangYiIntel @maxnick Can we cover that case by tests?

Hi Dmitry, I think our existing tests has already covered this case. The bug is that the inputStrides/outpuStrides may have rank smaller than 6, but in our `parallel_for` algo we access stride between 0 to 5.  Therefore we may have a index overflow. It doesn't trigger error before I think it's because it has zero value in that memory.

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
@ilya-lavrenov @ilyachur fyi, small perf improvement in common parallel routine.

**Comment by dmitry-gorokhov** [comment]
Can be merged after internal perf validation

**Review by ilya-lavrenov — APPROVED** [review]

**Pull request merged**
