### PR TITLE
[CPU] Treat 0 as default value for ovPerfHintNumRequests

### PR DESCRIPTION
**Pull request by Wovchena**
### Tickets:
 - *72095*

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
is it possible to cover this behavior by tests to prevent such situations in the future?

**Comment by Wovchena** [comment]
Well, if you teach me where are the tests, and how to write them, maybe I'll try to answer :)

**Review by myshevts — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
@Wovchena As I can see there are failing tests. Could you please resolve this?

**Comment by Wovchena** [comment]
@dmitry-gorokhov, only with your help :) What do I do wuith
[`16:51:25  FileNotFoundError: [Errno 2] No such file or directory: '/home/jenkins/agent/workspace/private-ci/ie/build-linux-centos76/b/pack/cpack/inference-engine_todo_install.zip'`](https://openvino-ci.intel.com/job/private-ci/job/ie/job/build-linux-centos76/63347/console)

**Comment by dmitry-gorokhov** [comment]
@Wovchena See https://openvino-ci.intel.com/job/private-ci/job/ie/job/ie-tests-linux-ubuntu18-cpu/65169/

**Comment by dmitry-gorokhov** [comment]
Given that this issue blocks performance validation my proposal is to revert original commit: https://github.com/openvinotoolkit/openvino/pull/8924

**Comment by Wovchena** [comment]
Ok

**Pull request closed without merging**
