### PR TITLE
Guide link: Build and Install OpenVINO on openSUSE

### PR DESCRIPTION
**Pull request by cabelo**
### Details:
Tested extensively and is now the official openVINO installation guide on openSUSE.

https://en.opensuse.org/SDB:Install_OpenVINO

This is an individual initiative as an openSUSE Ambassador and Intel Global Innovator.
I'm working in my spare time to finish the official rpm in distribution.

### CODE REVIEW

**Comment by cabelo** [comment]
> Hi @cabelo How this instruction is different from OV official build instruction? We have an unified script https://github.com/openvinotoolkit/openvino/blob/master/install_build_dependencies.sh which has support for zyppper package manager.

@ilya-lavrenov you're right, I corrected the link. It is outdated. evidence below:

https://en.opensuse.org/SDB:Install_OpenVINO#Package_Requirements
https://en.opensuse.org/SDB:Install_OpenVINO#Download:_Github_Instruction

**Comment by ilya-lavrenov** [comment]
The question is not answered :) I still see duplication of OpenVINO build instructions. What is added value in the links you provided?

**Comment by cabelo** [comment]
> The question is not answered :) I still see duplication of OpenVINO build instructions. What is added value in the links you provided?

When people search for openvino compilation information on Google, they find this link:

https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build_linux.md

So I thought it would be interesting to leave the opensuse instructions in this section as well.

**Comment by ilya-lavrenov** [comment]
This https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build_linux.md instruction is generic and work for OpenSUSE as well.

**Comment by cabelo** [comment]
> This https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build_linux.md instruction is generic and work for OpenSUSE as well.

I understand and I'm sorry. If you think it doesn't add value to include the link, you can refuse my request.

I put the opensuse link because I saw the CentOS link.

Thank you for your attention and patience.

**Comment by cabelo** [comment]
Thanks for your support, RPM will be officially ready on opensuse soon.

**Comment by ilya-lavrenov** [comment]
@cabelo 
I suggesting extending a list of validated OSes here
https://github.com/openvinotoolkit/openvino/blob/639c155331db710d9d17199b43967b4e70200585/docs/dev/build_linux.md?plain=1#L4-L6
with openSUSE, because users don't need a separate instruction. 

CentOS is a different instruction, because it contains obsolete software and users need to perform extra steps to install newer cmake, python, activate gcc and so on
It will be removed in 2024 together with CentOS 7 EOL

**Comment by cabelo** [comment]
> with openSUSE, because users don't need a separate instruction.
> 
> CentOS is a different instruction, because it contains obsolete software and users need to perform extra steps to install newer cmake, python, activate gcc and so on It will be removed in 2024 together with CentOS 7 EOL

@ilya-lavrenov  I understand perfectly!

**Pull request closed without merging**
