### PR TITLE
[VPU] - Update MyriadX firmware

### PR DESCRIPTION
**Pull request by DariaMityagina**
Update MyriadX firmware to RC6 in releases/2022/3 branch.
Ticket: #-100688

### CODE REVIEW

**Comment by DariaMityagina** [comment]
@Maxim-Doronin hi!
Could you please take a look?

**Comment by DariaMityagina** [comment]
Got `Fail to patch "Set memory type" command for firmware sc = -2` again.
Will check https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_myriad/third_party/mvnc/src/mvnc_data.c#L174-L175

**Review by AdrianVarlan — APPROVED** [review]

**Review by Maxim-Doronin — APPROVED** [review]

**Comment by Maxim-Doronin** [comment]
Please fill out the PR description

**Comment by DariaMityagina** [comment]
> Please fill out the PR description

Done. Thanks!

**Pull request merged**
