### PR TITLE
【PaddlePaddle Hackathon 4】add paddle softshrink op

### PR DESCRIPTION
**Pull request by Patrick-Star125**
### Details:
add softshrink operation in Paddle front end

### Reference:
- https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Softshrink_cn.html#softshrink

### Unit-test
image

### CODE REVIEW

**Comment by Patrick-Star125** [comment]
seems like float64 can't be supported according to this test error

image

**Comment by ceciliapeng2011** [comment]
please fix code style error. thanks.

**Comment by Patrick-Star125** [comment]
@ceciliapeng2011 Done

**Comment by OpenVINO-dev-contest** [comment]
@Patrick-Star125 per talk, could you help to close this PR, thanks

**Pull request closed without merging**
