### PR TITLE
Revise swish

### PR DESCRIPTION
**Pull request by luweizhou2016**
### Details:
Add description into Swish spec.
Add more check when constructing Swish OP in NGraph.
Change to use RTTI declear/define for Swish OP.
Add type prop , visitor (attributes), SSLT, backend , serialization tests for Swish OP.

### Tickets:
37560

### CODE REVIEW

**Comment by luweizhou2016** [comment]
@lazarevevgeny , can you pls help to review the patches? Thanks!

**Review by ilyachur — APPROVED** [review]

**Comment by luweizhou2016** [comment]
Tag with "DONOT MERGE". Will Update this PR after https://github.com/openvinotoolkit/openvino/pull/6181 is merged first. Aviod duplicate code.

**Comment by ilyachur** [comment]
Please resolve merge conflicts

**Comment by luweizhou2016** [comment]
CI issue is caused by auto merging changes the MKLDNN submodule unexpectly. I have rebased the code and cherry pick the patch. CI issue fixed.

**Pull request merged**
