### PR TITLE
[CPU] Make shape inference only once for the same shape

### PR DESCRIPTION
**Pull request by artkuli**
### Tickets:
 - *90554*

The changes contain making shape inference only once when user tries to use the same `InferenceRequest` to call method `infer()` more times. 
The example which causes problem:
```
core = Core()
model = core.read_model("model.onnx")
compiled_model = core.compile_model(model, "CPU")
request = compiled_model.create_infer_request()
for _, output in enumerate(outputs):
    output_layers.append(compiled_model.output(output))

for _, output in enumerate(outputs):
    output_layers.append(compiled_model.output(output))

for x in range(2):
     request.infer(inputs={"images_tensors": images_tensors})
     for index, output_layer in enumerate(output_layers):
            print("\t", outputs[index], request.get_tensor(outputs[index]).data.shape)
```
After first inference the output `masks` has shape: `(32, 1, 2360, 1380)`
In the next inference the shape is `(63, 1, 2360, 1380)`

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@EgorDuplensky  @maxnick  guys, please take a look on the PR

**Comment by EgorDuplensky** [comment]
@artkuli Could you please briefly describe the root cause of the problem in the PR description?

**Comment by artkuli** [comment]
@EgorDuplensky  Description updated

**Comment by a-sidorova** [comment]
I'm not sure that this fix is correct. Let me explain why
Let's imagine our case: we request several the same infer requests with the same images, shapes. In this PR, as I understand, after first `InferRequest` Loop in which we iterated full count times, for example, 32 times (I mean that `continue condition` is always `true`) the value `lastUsedTripCount` is equal to 32. On the next second `InferRequest`,  `prepareParams()` isn't called (`input shapes` are the same, `trip counts` are the same, `continue conditions` are the same). So  `lastUsedTripCount` isn't reset because `prepareTripCount()` isn't called because of  `prepareParams()` isn't called. And then in `executeDynamicImpl` we don't iterate in loop because `lastUsedTripCount == max_num_iter`. It means that after first `InferRequest` with the same data we don't execute `Loop` op. But if we imagine, that we would have several `InferRequests` with different data but with the same shapes and our Loop would recievs the same `input shapes`, the same `trip count` and `continue condition` but with different data (because of different images). So our Loop isn't executed in this PR. However it should be inferred because of another data.
Thus, it's PR may be correct for the same input shapes but not for the same input data (for example, different images of the same shapes).
Correct me please If I'm wrong

After small look on this problem, I think that the problem is in that after each Loop iteration output shape is incremented. And after each `InferRequest` this statement is saved so we get something like arithmetic progression. Need to investigate it

**Comment by artkuli** [comment]
Closing, the current fix is continuing in the PR: #14041

**Pull request closed without merging**
