### PR TITLE
generator to pytest (special case 2)

### PR DESCRIPTION
**Pull request by PRATHAM-SPS**
### Details:
 - *Replaced the generator's functionality with pytest*

### Tickets:
 - *110705*

### CODE REVIEW

**Comment by PRATHAM-SPS** [comment]
Hii @rkazants @popovaan @mvafin , Just a friendly reminder.

**Review by rkazants — APPROVED** [review]

**Comment by rkazants** [comment]
> Hello @rkazants @popovaan @mvafin I am facing some issues in last 2-3 files I will create PR for each as one resolves.
> 
> **command:- pytest custom_replacement_config_test.py**
> 
> **OUTPUT** -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html =========================== short test summary info ============================ FAILED custom_replacement_config_test.py::TestSchema::test_schema_file - TypeError: test_schema_file() missing 1 required positional argument: 'tran... ==================== 1 failed, 2 passed, 1 warning in 2.45s ====================
> 
> **only 1 test is geting failed any solution for it ?**

@PRATHAM-SPS, can you please try to check `transformation_configs` value? May be its value is None or empty list.
Also, try explicitly set this value in `parametrize` mark.

Best regards,
Roman

**Comment by PRATHAM-SPS** [comment]
Hello @rkazants sorry for the delay, 

 @pytest.mark.parametrize("transformation_config", transformation_configs or [None], ids=lambda x: f"param: {x}")
    def test_schema_file(self, transformation_config):
        if transformation_config is None:
            pytest.skip("No transformation configs found")
        assert load_and_validate_json_config(transformation_config)

I have tried this method but I am getting the same error.

**Comment by rkazants** [comment]
@PRATHAM-SPS, please move to other bunch of files to avoid test-generator then. We can suspend this one for a while.

Best regards,
Roman

**Comment by p-wysocki** [comment]
@rkazants could you please take a look?

**Comment by p-wysocki** [comment]
build_jenkins

**Pull request closed without merging**
