### PR TITLE
Update onednn

### PR DESCRIPTION
**Pull request by RICKIE777**
### Details:
 - *Delete 3D depthwise unimplemented judgments*

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@EgorDuplensky We have to options here: I can direcly merge this above oneDNN 2.7 or you can include this change into your [oneDNN 3.0 migration PR](https://github.com/openvinotoolkit/openvino/pull/15604). Up to you.

**Comment by EgorDuplensky** [comment]
> @EgorDuplensky We have to options here: I can direcly merge this above oneDNN 2.7 or you can include this change into your [oneDNN 3.0 migration PR](https://github.com/openvinotoolkit/openvino/pull/15604). Up to you.

I will correct this on oneDNN 3.0 migration branch by fixing the original commit then.

**Comment by EgorDuplensky** [comment]
@dmitry-gorokhov @RICKIE777
One more thing. It would be good to have a test case for the issue we found.
Since we are going to drop this PR, it can be transformed into the PR with a test case, which will currently fail, but will pass after the PR with the test will be rebased onto oneDNN migration.

**Comment by RICKIE777** [comment]
> @dmitry-gorokhov @RICKIE777 One more thing. It would be good to have a test case for the issue we found. Since we are going to drop this PR, it can be transformed into the PR with a test case, which will currently fail, but will pass after the PR with the test will be rebased onto oneDNN migration.

Thanks @dmitry-gorokhov and @EgorDuplensky.
Maybe this model in JIRA CVS-98185  fits the need. 
In Xeon machine,  if this PR is not merged, the kernel selection is jit_uni_int8:avx2. After merging the PR, the kernel selection should be jit_int8:avx512_core_vnni.

**Comment by EgorDuplensky** [comment]
> > @dmitry-gorokhov @RICKIE777 One more thing. It would be good to have a test case for the issue we found. Since we are going to drop this PR, it can be transformed into the PR with a test case, which will currently fail, but will pass after the PR with the test will be rebased onto oneDNN migration.
> 
> Thanks @dmitry-gorokhov and @EgorDuplensky. Maybe this model in JIRA [CVS-98185](https://jira.devtools.intel.com/browse/CVS-98185) fits the need. In Xeon machine, if this PR is not merged, the kernel selection is jit_uni_int8:avx2. After merging the PR, the kernel selection should be jit_int8:avx512_core_vnni.

The idea is create add a single_layer_test instance which reproduces the issue you observe with the model.
So the next time we occasionally remove this peace of code again the test will fail

**Comment by RICKIE777** [comment]
> > > @dmitry-gorokhov @RICKIE777 One more thing. It would be good to have a test case for the issue we found. Since we are going to drop this PR, it can be transformed into the PR with a test case, which will currently fail, but will pass after the PR with the test will be rebased onto oneDNN migration.
> > 
> > 
> > Thanks @dmitry-gorokhov and @EgorDuplensky. Maybe this model in JIRA [CVS-98185](https://jira.devtools.intel.com/browse/CVS-98185) fits the need. In Xeon machine, if this PR is not merged, the kernel selection is jit_uni_int8:avx2. After merging the PR, the kernel selection should be jit_int8:avx512_core_vnni.
> 
> The idea is to add a single_layer_test instance which reproduces the issue you observe with the model. So the next time we occasionally remove this peace of code again the test will fail

Thanks @EgorDuplensky. I have a question about it. The kernel is jit_int8:avx512_core_vnni. The modified file is jit_avx512_core_x8s8s32_conv_kernel.cpp. 
In which file can I add test cases for quantized int8?  The test cases in the single_layer_test/convolution.cpp file are test float data.

**Comment by RICKIE777** [comment]
The modification has been merged into onednn v3.0_for_ie_master_migration. The onednn team has not yet merged int8 single-layer tests. For the test case of this PR, I have submitted a ticket https://jira.devtools.intel.com/browse/MFDNN-9592. So this PR can be closed.

**Pull request closed without merging**
