### PR TITLE
Upgrade protobuf to 3.18.2

### PR DESCRIPTION
**Pull request by asomsiko**
### Tickets:
 - [CVS-79516](https://jira.devtools.intel.com/browse/CVS-79516)

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
How the binary size is changed?

**Comment by nosovmik** [comment]
There is also some 'protoc' configuration which is used when cross-compiling is enabled: https://github.com/openvinotoolkit/openvino/blob/434d7bbecc9ac1b39f9311f4a696de3c6bf645f2/cmake/dependencies.cmake#L31

Seems like updated 'protoc' package is required to be uploaded on download.01.org as well

**Comment by ilya-lavrenov** [comment]
> There is also some 'protoc' configuration which is used when cross-compiling is enabled:
> 
> https://github.com/openvinotoolkit/openvino/blob/434d7bbecc9ac1b39f9311f4a696de3c6bf645f2/cmake/dependencies.cmake#L31
> 
> Seems like updated 'protoc' package is required to be uploaded on download.01.org as well

do we need protoc and protobuf versions to match or protobuf is BW compatible? E.i. protoc generated files can be used with newer protobuf

**Comment by ilya-lavrenov** [comment]
> > There is also some 'protoc' configuration which is used when cross-compiling is enabled:
> > https://github.com/openvinotoolkit/openvino/blob/434d7bbecc9ac1b39f9311f4a696de3c6bf645f2/cmake/dependencies.cmake#L31
> > 
> > Seems like updated 'protoc' package is required to be uploaded on download.01.org as well
> 
> do we need protoc and protobuf versions to match or protobuf is BW compatible? E.i. protoc generated files can be used with newer protobuf

based on:
```
[](https://openvino-ci.intel.com/blue/organizations/jenkins/private-ci%2Fie%2Fbuild-linux-yocto_kmb/detail/build-linux-yocto_kmb/107732/pipeline#step-200-log-421)[2022-02-16T12:54:59.703Z] [2022-02-16 12:54:53,186] [139941539874560] build ie ERROR: /home/jenkins/agent/workspace/private-ci/ie/build-linux-yocto_kmb/b/build/dldt/src/frontends/tensorflow/node_def.pb.h:996:16: error: request for member ‘GetMap’ in ‘((const tensorflow::NodeDef*)this)->tensorflow::NodeDef::attr_’, which is of non-class type ‘const int’

[2022-02-16T12:54:59.703Z] [2022-02-16 12:54:53,187] [139941539874560] build ie ERROR: /home/jenkins/agent/workspace/private-ci/ie/build-linux-yocto_kmb/b/build/dldt/src/frontends/tensorflow/node_def.pb.h:1001:16: error: request for member ‘MutableMap’ in ‘((tensorflow::NodeDef*)this)->tensorflow::NodeDef::attr_’, which is of non-class type ‘int’
```
Looks like we need to align protoc and protobuf versions :)

**Comment by asomsiko** [comment]
> > Seems like updated 'protoc' package is required to be uploaded on download.01.org as well
> 
> do we need protoc and protobuf versions to match or protobuf is BW compatible? E.i. protoc generated files can be used with newer protobuf

3.19.04 have been uploaded to download.01.org

**Review by ilyachur — APPROVED** [review]

**Review by ilya-lavrenov — APPROVED** [review]

**Pull request merged**
