### PR TITLE
Notify VPU maintainers about PR to more VPU related files

### PR DESCRIPTION
**Pull request by gladilov-gleb**
@evgenytalanin-intel @ababushk @azhogov please check if my change is correct in term of style/syntax of `CODEOWNERS` file. I'm not sure if it's possible to specify a file name.

### CODE REVIEW

**Comment by gladilov-gleb** [comment]
@AndrewBakalinIntel please check if I mentioned all VPU related folders and files in the repo

**Comment by gladilov-gleb** [comment]
@azhogov @evgenytalanin-intel @ababushk I modified only CODEOWNERS file, but pre-commit failed - does it mean we have unstable master?

**Comment by ababushk** [comment]
@gladilov-gleb no, it is an issue with Jenkins job. It is fixed now, but we don't want to restart it for this PR

**Comment by iefode** [comment]
I think, we should review vpu tests too as owners of test infra

**Comment by gladilov-gleb** [comment]
> I think, we should review vpu tests too as owners of test infra

Fixed

**Pull request merged**
