### PR TITLE
Add FakeQuantize op support in TS transformations

### PR DESCRIPTION
**Pull request by itikhono**
Added support for FQ op in TS transformation
Tests

Before
image

After
image

### Tickets:
 - *105091*

### CODE REVIEW

**Comment by jane-intel** [comment]
FQ TS looks legit. I approve this particular change.
However, the "After" graph that you show in the PR description brings more questions. I assume that this is an IR since it is visualized via netron.

- Why quantized weights are kept in a non-compressed form?
- Why Reshape and Transpose are still present on the weights sub-graph and are not optimized out?

**Review by t-jankowski — APPROVED** [review]

**Review by evkotov — COMMENTED** [review]
I don't see how we add FakeQuantize to the list of supported TS operations

**Comment by itikhono** [comment]
> I don't see how we add FakeQuantize to the list of supported TS operations

image

**Review by andrei-kochin — APPROVED** [review]

**Review by evkotov — COMMENTED** [review]
I mean src/common/transformations/src/transformations/transpose_sinking/ts_utils.cpp
bool CanPropagateForwardThrough(Node* node) {

**Comment by itikhono** [comment]
> I mean src/common/transformations/src/transformations/transpose_sinking/ts_utils.cpp bool CanPropagateForwardThrough(Node* node) Without that you could have problems with back propagation

Agree

**Review by evkotov — APPROVED** [review]

**Review by jane-intel — APPROVED** [review]

**Pull request merged**
