### PR TITLE
[DOCS] make non-code text represented properly

### PR DESCRIPTION
**Pull request by andrei-kochin**
Just a small improvement to properly display text nested with code segments

### CODE REVIEW

**Comment by andrei-kochin** [comment]
If there is some file with known doc issues I would appreciate that. Anyway this commit might be the aggregator for all doc improvements identified further.

**Comment by lazarevevgeny** [comment]
@andrew-zaytsev @ntyukaev, please, review the changes.

**Comment by andrei-kochin** [comment]
@aalborov as discussed with @andrew-zaytsev  assigning this PR to you as it looks like you know how to deal with unexpected numeration showed up after my changes(see for example Cutting at the End section): http://openvino-docs.inn.intel.com/PR2717/openvino_docs_MO_DG_prepare_model_convert_model_Cutting_Model.html

**Comment by aalborov** [comment]
The broken lists are fixed now: http://openvino-docs.inn.intel.com/PR2717/openvino_docs_MO_DG_prepare_model_convert_model_Cutting_Model.html

**Review by aalborov — APPROVED** [review]

**Pull request merged**
