### PR TITLE
Fix itt include dir detection

### PR DESCRIPTION
**Pull request by emmanuelattia-philips**
ITT_INCLUDE_DIR was not properly detected when VTune is on the machine.

### CODE REVIEW

**Comment by emmanuelattia-philips** [comment]
I have no idea why ci/jenkins failed, i don't have access to the details

**Comment by asuhov** [comment]
Functional tests for CPU plugin failed. It seems it's a sporadic issue, because they passed after the second run.

**Comment by ilya-lavrenov** [comment]
Reverted the patch which triggers sporadic behavior https://github.com/openvinotoolkit/openvino/pull/756

**Comment by ilya-lavrenov** [comment]
@emmanuelattia-philips sorry for inconvenience. Could you please rebase and the tests will be run once again?

**Comment by emmanuelattia-philips** [comment]
Please notify me when i should retry the azure devops windows seems broken (or big mistake from me ?)

**Comment by ilya-lavrenov** [comment]
seems another issues with azure service provider.. Sure, will notify.

**Pull request merged**
