### PR TITLE
DetectionOutput perf fix

### PR DESCRIPTION
**Pull request by chenhu-wang**
### Details:
 - *DetectionOutput perf fix*

### Tickets:
 - *79085*

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@chenhu-wang  is it ready for review?

**Comment by chenhu-wang** [comment]
> @chenhu-wang is it ready for review?

Now it's ready for review. For DO in this model we have "confidence_threshold="0.009..."", which is very small, not executed in sparsity manner. In such case, letting filter+topk+nms process in same loop should be better from data access perspective. I checked on i7-8700 and Xeon-8180. The perf does not drop any more. Thanks.

**Comment by chenhu-wang** [comment]
> > @chenhu-wang is it ready for review?
> 
> Now it's ready for review. For DO in this model we have "confidence_threshold="0.009..."", which is very small, not executed in sparsity manner. In such case, letting filter+topk+nms process in same loop should be better from data access perspective. I checked on i7-8700 and Xeon-8180. The perf does not drop any more. Thanks.

and, sparsity manner need move filter(by conf_theshold)+topk up before decodeBBox(), such that box number that need decode reduced dramatically to improve perf. If conf_threshold is small, almost all box still need decode.

**Comment by dmitry-gorokhov** [comment]
@mandrono could you please review?

**Comment by dmitry-gorokhov** [comment]
@mandrono could you please also help with internal performance validation?

**Comment by mandrono** [comment]
@chenhu-wang could you rebase on latest master please?

**Comment by chenhu-wang** [comment]
> @chenhu-wang could you rebase on latest master please?

rebased, thanks!

**Comment by mandrono** [comment]
In general the patch looks good to me, but few minor comments.

As far I understood `sparsityThreshold` is some heuristic constant. Could you please add comment about it? And also add const qualifier.

As I can see from test cases all our tests cover `isSparsityWorthwhile == false` case. Is it possible to add tests to cover both cases? Also in `ie_system_conf.cpp` there is `get_cpu_info()`, so we can know L3 cache size. In case if this test will be slow move them to nightly scope. @antonvor maybe you already implement mechanics to discover L3 cache size in your tests?

Validation still in progress

**Comment by dmitry-gorokhov** [comment]
@chenhu-wang As I know there are some possible perf drops. Any progress so far?

**Comment by akladiev** [comment]
This PR will be closed in 2 weeks in case of no activity.

**Comment by chenhu-wang** [comment]
open

**Comment by chenhu-wang** [comment]
reopen

**Comment by chenhu-wang** [comment]
reopen

**Comment by chenhu-wang** [comment]
covered in pr https://github.com/openvinotoolkit/openvino/pull/19773

**Comment by chenhu-wang** [comment]
covered in pr https://github.com/openvinotoolkit/openvino/pull/19773

**Pull request closed without merging**
