### PR TITLE
[Python API] requirements

### PR DESCRIPTION
**Pull request by akuporos**
ticket #36891

### CODE REVIEW

**Comment by generalova-kate** [comment]
Good, but we need a fix for 36893 as well in 2021.1 release. You can combine and remove opencv from requirements.

**Comment by akuporos** [comment]
> Good, but we need a fix for 36893 as well in 2021.1 release. You can combine and remove opencv from requirements.

@generalova-kate 
I'd like doing this in a separate ticket.

**Comment by generalova-kate** [comment]
@akuporos ok

**Review by nkogteva — APPROVED** [review]

**Review by generalova-kate — APPROVED** [review]
Can we add it to 2021.2 release?

**Comment by akuporos** [comment]
> Can we add it to 2021.2 release?

Yes, let's wait when CI pass

**Comment by generalova-kate** [comment]
> > Can we add it to 2021.2 release?
> 
> Yes, let's wait when CI pass

any updates?

**Comment by akuporos** [comment]
> > > Can we add it to 2021.2 release?
> > 
> > 
> > Yes, let's wait when CI pass
> 
> @akuporos
> any updates?

@generalova-kate there is a problem with opencv-python requirements because after replacing ```==``` with ```>=``` the latest version of opencv-python is installed. For some reasons there is no built-in version for the OS which is used in our CI and it failed.

**Pull request merged**
