### PR TITLE
Docs: Update Devices pages to state improved INT8 performance with 11th & 12th gen devices

### PR DESCRIPTION
**Pull request by EdjeElectronics**
### Details:
 - Small edits to Devices pages to indicate that 11th and 12th generation processors have improved performance with INT8 models. This is a specific request from the OpenVINO product team.

### Tickets:
 - N/A

### CODE REVIEW

**Comment by xu-yuan1** [comment]
Hi @EdjeElectronics , I see there are some files not up-to-date comparing to master. Could you solve the conflicts first?

**Comment by EdjeElectronics** [comment]
Hi @xu-yuan1 , thanks for looking at this! Oops, I meant to merge it to the releases/2022/1 branch instead of the master branch. I just changed it to the correct branch. Please let me know if there are still any issues.

**Comment by helena-intel** [comment]
@kblaszczak-intel this PR is for 2022.1, but the content is relevant for 2023.0 too. It would be great if someone could port it.

**Comment by akladiev** [comment]
This PR will be closed in 2 weeks in case of no activity.

**Comment by akladiev** [comment]
This PR was closed because it has been stalled for 2 week with no activity.

**Pull request closed without merging**
