### PR TITLE
Modify test cases which failed during parallel execution

### PR DESCRIPTION
**Pull request by LakshmiGayathri19**
* Addressing the "Known limitation" issue for test cases which failed parallel execution.

### Details:
- Few tests cases failed when parallel execution is enabled.
- These failed test cases are modified in order to execute with out errors.
- After modification, two test cases failed due to inconsistent number of parameters passed to the test case.
- The two test cases which failed due to parameter inconsistency is addressed in this commit.

### Tickets:
 - *ticket-id* - [20919](https://github.com/openvinotoolkit/openvino/issues/20919)

### CODE REVIEW

**Review by rkazants — APPROVED** [review]

**Comment by rkazants** [comment]
build_jenkins

**Comment by rkazants** [comment]
build_jenkins

**Review by rkazants — COMMENTED** [review]
@LakshmiGayathri19, please fix error in test:

```
_ TestKerasZeroPadding2D.test_keras_zeropadding2d_channels_last[ ie_device:CPU - precision:FP16 - params:(['x1'], [[1, 3, 8, 7]], tf.float32, ((5, 1), (3, 4))) ] _

self = <test_tf2_keras_zeropadding2d.TestKerasZeroPadding2D object at 0xffff1ebc32d0>
params = (['x1'], [[1, 3, 8, 7]], tf.float32, ((5, 1), (3, 4)))
ie_device = 'CPU', precision = 'FP16', ir_version = 11
temp_dir = '/__w/openvino/openvino/install/tests/layer_tests/common/out/CPU_test_keras_zeropadding2d_channels_last_08u4u1h'
use_old_api = False

    @pytest.mark.parametrize("params", test_data_channels_last)
    @pytest.mark.nightly
    @pytest.mark.precommit
    def test_keras_zeropadding2d_channels_last(self, params, ie_device, precision, ir_version,
                                               temp_dir, use_old_api):
>       input_names, input_shapes, input_type, padding, data_format = params
E       ValueError: not enough values to unpack (expected 5, got 4)
```

**Comment by rkazants** [comment]
Hi @LakshmiGayathri19, any update on this task?

Best regards,
Roman

**Comment by LakshmiGayathri19** [comment]
Hello @rkazants, 

I didn't find time to work on this. I will be free after two weeks will that be fine ?

**Pull request closed without merging**
