### PR TITLE
Changed structure of nGraph library

### PR DESCRIPTION
**Pull request by ilyachur**
Part of task: 26706
This PR should be merged after: https://github.com/openvinotoolkit/openvino/pull/1657

First commit exists in the PR 1657.
Please take a look only on the second commit.

### CODE REVIEW

**Comment by GlebKazantaev** [comment]
@ilyachur please write description with explaining what was changed in this PR and how new ngraph structure looks like.

**Comment by ilyachur** [comment]
> @ilyachur please write description with explaining what was changed in this PR and how new ngraph structure looks like.

I separated nGraph public API.
nGraph code structure before:
```
ngraph/
    src/
        ngraph/
            CMakeLists.txt
````
new nGraph structure:
```
ngraph/
    core/
        include/
            ngraph/
        src/
            ngraph/
        CMakeLists.txt
```

**Comment by ilya-lavrenov** [comment]
```
        src/
            ngraph/
```
Can we have just `src`?

**Comment by ilyachur** [comment]
> ```
>         src/
>             ngraph/
> ```
> 
> Can we have just `src`?

I don't want to have any differences between src and include folders. In include folder I need the ngraph folder in order to align install and build paths.

**Comment by ilyachur** [comment]
> > ```
> >         src/
> >             ngraph/
> > ```
> > 
> > 
> > Can we have just `src`?
> 
> I don't want to have any differences between src and include folders. In include folder I need the ngraph folder in order to align install and build paths.

@tomdol @postrational @tsocha @mbencer What do you think about it? should we have  `ngraph` inside the `src` folder or not?

**Comment by tomdol** [comment]
I don't have a strong opinion on the additional subdirectory. If it makes the code more aligned between include and src, I'm ok with it. But in general I'm against too many subdirectories, too much indentaion and too many nested namespaces.

**Comment by ilyachur** [comment]
> I don't have a strong opinion on the additional subdirectory. If it makes the code more aligned between include and src, I'm ok with it. But in general I'm against too many subdirectories, too much indentaion and too many nested namespaces.

Cool, I will change structure to:
```
ngraph/
    frontend/
        onnx_import/
    core/
        include/
            ngraph/
        src/
            *.cpp
        CMakeLists.txt
```

And after that will do the same for onnx importer.

**Pull request merged**
