### PR TITLE
[CPU] Fix avx2 bf16 reorder

### PR DESCRIPTION
**Pull request by maxnick**
### Details:
Fix forked oneDNN JIT reorder kernel for the case of bf16 precision and AVX2 ISA.

OneDNN fork PR: https://github.com/openvinotoolkit/oneDNN/pull/253

### Tickets:
 - CVS-145874

### CODE REVIEW

**Comment by maxnick** [comment]
@luweizhou2016 , could you please review?

**Comment by luweizhou2016** [comment]
@maxnick , My understanding is that for avx2 plaform:
bf16->fp32 is still supported in jit_uni_reorder_kernel_f32_t;
fp32->bf16 is not supported in  jit_uni_reorder_kernel_f32_t for the bf16_emu bug?

**Comment by maxnick** [comment]
> @maxnick , My understanding is that for avx2 plaform: bf16->fp32 is still supported in jit_uni_reorder_kernel_f32_t; fp32->bf16 is not supported in jit_uni_reorder_kernel_f32_t for the bf16_emu bug?

fp32->bf16 is not supported by `avx2` as the bf16_emu works only with avx512. Also fp32->bf16 reorders are supported by the `avx2` platforms with the convert NE extension, and of course for AVX512_BF16, as they have native fp32->bf16 conversion instructions.

**Comment by luweizhou2016** [comment]
> > @maxnick , My understanding is that for avx2 plaform: bf16->fp32 is still supported in jit_uni_reorder_kernel_f32_t; fp32->bf16 is not supported in jit_uni_reorder_kernel_f32_t for the bf16_emu bug?
> 
> fp32->bf16 is not supported by `avx2` as the bf16_emu works only with avx512, and the `avx2` instruction set doesn't have dedicated fp32->bf16 conversion instructions. Also fp32->bf16 reorders are supported by the `avx2` platforms with the convert NE extension, and of course for AVX512_BF16, as they have native fp32->bf16 conversion instructions.

Thx for clarifying. Approved.

**Review by luweizhou2016 — APPROVED** [review]

**Pull request merged**
