### PR TITLE
[VPU][Tests] Gather: support outer padding for indices

### PR DESCRIPTION
**Pull request by AndrewBakalinIntel**
Ticket - #44539
Changes:
- Update firmware (in progress)
- Add the test case from the network
- Disable fp32 case, because in this case the network has output `Convert` which receives non-inner stride in its input which is not supported now.
- Support FP16 comparator.

### CODE REVIEW

**Comment by AndrewBakalinIntel** [comment]
@Maxim-Doronin @andrejsokolov could you please take a look?

**Comment by Maxim-Doronin** [comment]
Let's wait for the firmware update and passing tests

**Review by iefode — APPROVED** [review]

**Comment by AndrewBakalinIntel** [comment]
@Maxim-Doronin I've found that the tests were failed because of newly added Convert compactness check on the device side. It supports only inner stride, while dynamically it receives some non-inner strides (it can't be properly detected on the host side, because the upper-bound is fully compact). There were real issues with some cases in `StridedSlice` and `NMS`. The reason why `StridedSlice` were previously passed is that we just got luck in data generating, while for `NMS` we already had a ticket for some cases (#-42828), which now can be closed because the real root cause was the `Convert` stage.

**Comment by Maxim-Doronin** [comment]
Some related tests failed, please, fix them

**Review by Maxim-Doronin — APPROVED** [review]

**Comment by AndrewBakalinIntel** [comment]
@Maxim-Doronin could you please merge it?

**Pull request merged**
