### PR TITLE
[Runtime] INT8 inference documentation update

### PR DESCRIPTION
**Pull request by eshoguli**
### Details:
 - INT8 inference documentation update
 - 
### Tickets:
 - 56490

### CODE REVIEW

**Comment by MaximProshin** [comment]
@AlexKoff88 , please also look at it

**Comment by MaximProshin** [comment]
@dmitry-gorokhov, @AlexKoff88, @vladimir-paramuzov, can you please review it so that it becomes a part of 2021.4?
@andrew-zaytsev FYI

**Comment by AlexKoff88** [comment]
The narrative is corrupted. There is no introduction that explains the purpose of this document.
@MaximProshin, I think you should ask @andrew-zaytsev to review, first.

**Comment by MaximProshin** [comment]
@andrew-zaytsev, can you help to improve the narrative?

**Comment by dmitry-gorokhov** [comment]
@eshoguli  @MaximProshin @AlexKoff88  Given the documentation freeze today shouldn't we merge current version? At least it removes controversial information

**Comment by MaximProshin** [comment]
@dmitry-gorokhov, I asked @andrew-zaytsev to help with it. Hopefully it will be merged.

**Review by azhogov — APPROVED** [review]

**Pull request merged**
