### PR TITLE
generator to pytest 

### PR DESCRIPTION
**Pull request by PRATHAM-SPS**
### Details:
 - *Converting Generator TestCases to Pytest*

### Tickets:
 - *110705*

### CODE REVIEW

**Review by rkazants — APPROVED** [review]

**Comment by rkazants** [comment]
@PRATHAM-SPS, anticipate green CI and let us merge this one.
After that, please open new PR(s) to move other tests in the same way.

Thanks a lot for your work,
Roman

**Review by mvafin — APPROVED** [review]

**Comment by rkazants** [comment]
build_jenkins

**Comment by PRATHAM-SPS** [comment]
Hii @rkazants  @mvafin  I am not able to access CI where it is failing .

**Comment by mvafin** [comment]
> Hii @rkazants @mvafin I am not able to access CI where it is failing .

I restarted failing wheel builder, it seem to fail for a reason not connected with changes.

**Comment by PRATHAM-SPS** [comment]
@mvafin @rkazants Same CI failed another time.

**Comment by rkazants** [comment]
build_jenkins

**Comment by rkazants** [comment]
@PRATHAM-SPS, yes, it was an issue with CI. It looks to be fixed very recently. Please rebase your branch.

**Comment by rkazants** [comment]
build_jenkins

**Comment by PRATHAM-SPS** [comment]
Hii @rkazants @mvafin  all CI have been successfully passed.

**Comment by rkazants** [comment]
@PRATHAM-SPS, congratulation with your first PR merge to OpenVINO. Please continue to replace test-generator with pytest in your next PRs. You can split this effort into separate PRs and it's up to you.

Best regards,
Roman

@andrei-kochin, @moslex, fyi about external contribution.

**Pull request merged**
