### PR TITLE
Update GNA.md

### PR DESCRIPTION
**Pull request by kenkoyanagi**
Added TGL frequency

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
@dorloff is it needed or we can close?

**Comment by ilya-lavrenov** [comment]
@nkogteva do we need this?

**Comment by akladiev** [comment]
This PR will be closed in 2 weeks in case of no activity.

**Comment by akladiev** [comment]
This PR was closed because it has been stalled for 2 week with no activity.

**Pull request closed without merging**
