### PR TITLE
[IE][VPU]: Fix NCE hang due to input dimentions exceed HW limitation

### PR DESCRIPTION
**Pull request by cwzrad**
MyriadX NCE will hang if input height, width, channle exceed the
limitation 2048

Signed-off-by: wenzengc <wenzeng.chen@intel.com>

Jira #-37020

### CODE REVIEW

**Comment by cwzrad** [comment]
@gladilov-gleb 
hi gleb,  Do you know what is the error?  "##[error]We stopped hearing from agent vmssa7a4c0006VX. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610"

**Comment by Maxim-Doronin** [comment]
@cwzrad, please, add functional tests for such cases which will validate the changes

**Comment by cwzrad** [comment]
@Maxim-Doronin, could you please give me some examples how and where to add functional test? Some network will hang on VPU without the fix, so it may need interaction with HW to test it

**Comment by Maxim-Doronin** [comment]
> @Maxim-Doronin, could you please give me some examples how and where to add functional test? Some network will hang on VPU without the fix, so it may need interaction with HW to test it

Convolution per-layer tests are here `inference-engine/tests/functional/plugin/myriad/shared_tests_instances/single_layer_tests/convolution.cpp`
You can take from your networks or pick up such values of the shape of input/output tensors and convolution parameters that without a fix it will not pass, but it will with a fix

**Review by Maxim-Doronin — APPROVED** [review]

**Pull request merged**
