### PR TITLE
[PT FE] Fix Sporadic Quantized Ops Errors

### PR DESCRIPTION
**Pull request by PiotrKrzem**
### Details:
 - Fixes sporadic failures of quantized ops' tests by rounding the input to match the behavior in both frameworks
 - Rounding to more than 5 digits will cause sporadic errors to return since there is a mismatch in rounding in OV/PT

### Tickets:
 - None

### CODE REVIEW

**Comment by mvafin** [comment]
There is still a sporadic issue in `quantized::cat` tests:
`Errors outside threshold range: 1 with max diff 0.900000810623169, expected at most 1 with max diff 0.3001`

**Review by mvafin — CHANGES_REQUESTED** [review]
The sporadic issue is not gone:
`Errors outside threshold range: 1 with max diff 0.9000000357627869, expected at most 1 with max diff 0.3001`
```
FAILED layer_tests/pytorch_tests/test_quantized_cat.py::TestQuantizedCat::test_quantized_cat[ ie_device:CPU - precision:FP32 - dtype:torch.quint8 - zero_point:0 - scale:0.3 ] - AssertionError: Accuracy validation failed
FAILED layer_tests/pytorch_tests/test_quantized_cat.py::TestQuantizedCat::test_quantized_cat[ ie_device:CPU - precision:FP32 - dtype:torch.quint8 - zero_point:1 - scale:0.3 ] - AssertionError: Accuracy validation failed
FAILED layer_tests/pytorch_tests/test_quantized_cat.py::TestQuantizedCat::test_quantized_cat[ ie_device:CPU - precision:FP32 - dtype:torch.qint8 - zero_point:0 - scale:0.3 ] - AssertionError: Accuracy validation failed
```

**Review by PiotrKrzem — COMMENTED** [review]
I changed both zero_points to be 0 in one of the tests and ran the tests for 4h, now it seems to be passing every time

**Comment by mvafin** [comment]
Looks like sporadic issue in cat tests is resolved

**Review by mvafin — APPROVED** [review]

**Pull request merged**
