### PR TITLE
fixed broken doc links

### PR DESCRIPTION
**Pull request by SANTHOSH-MAMIDISETTI**
### Details:
 - *Fixed some minor broken hyperlinks and links in the following : *
 - *CONTRIBUTING.md*
 - *CONTRIBUTING_PR.md*

### Tickets:
 - *no ticket id*
 
###### This looked like a relatively minor issue , hence I didn't create an issue ,instead fixed it and made a PR

@p-wysocki

### CODE REVIEW

**Comment by SANTHOSH-MAMIDISETTI** [comment]
I guess , there is no need for the workflows to run(at least for this case) because it's just a documentation error correction. Thinking we can skip the workflows for now since it's just a quick correction on that front. Saves a bit of hassle and resources. What would you suggest ? @p-wysocki  @tsavina

**Review by sgolebiewski-intel — APPROVED** [review]

**Review by p-wysocki — APPROVED** [review]

**Comment by p-wysocki** [comment]
Thank you for the contribution!

**Comment by SANTHOSH-MAMIDISETTI** [comment]
@p-wysocki  just curious , when might this be merged ? , or is there anything to be done , for it to be merged ?

**Comment by SANTHOSH-MAMIDISETTI** [comment]
> @p-wysocki just curious , when might this be merged ? , or is there anything to be done , for it to be merged ?

I mean this PR is still open , hence asking , if there is anything else to be done from my side

**Comment by p-wysocki** [comment]
@SANTHOSH-MAMIDISETTI I just updated the branch, the CI got stuck for some reason. I'll ask for a merge once the tests pass, it's going to be easier than force merge. :)

**Comment by SANTHOSH-MAMIDISETTI** [comment]
> @SANTHOSH-MAMIDISETTI I just updated the branch, the CI got stuck for some reason. I'll ask for a merge once the tests pass, it's going to be easier than force merge. :)

Thank you @p-wysocki  :)

**Pull request merged**
