### PR TITLE
Moved cpu tests to right folder

### PR DESCRIPTION
**Pull request by ilyachur**
### Details:
 - Fixed CPU tests location

### Tickets:
 - NA

### CODE REVIEW

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by ilyachur** [comment]
@EgorDuplensky Looks like these tests never work.
PR https://github.com/openvinotoolkit/openvino/pull/12981 has changes which cannot be compiled.
Could you please take a look?

**Comment by EgorDuplensky** [comment]
> @EgorDuplensky Looks like these tests never work.
> PR https://github.com/openvinotoolkit/openvino/pull/12981 has changes which cannot be compiled.
> Could you please take a look?

I have this fixed on my local branch and will create a PR asap

**Comment by ilyachur** [comment]
@EgorDuplensky Any plans to move these tests?

**Comment by EgorDuplensky** [comment]
@ilyachur blocked by another urgent activity

**Comment by ilyachur** [comment]
@EgorDuplensky @dmitry-gorokhov  Any progress here?

**Comment by ilya-lavrenov** [comment]
@EgorDuplensky ping

**Comment by EgorDuplensky** [comment]
WIll be done in scope of https://github.com/openvinotoolkit/openvino/pull/17447

**Pull request closed without merging**
