### PR TITLE
Extend support to BF16 in npu plugin

### PR DESCRIPTION
**Pull request by ZoranZomborat**
### Details:
Extend BF16 logic in NPU plugin.
To what it's worth, functional tests on NPU side are running with these changes, although there are some opens in NPU compiler which cause an accuracy;
Until then this PR should be merged to ease up integration on our side.

### Tickets:
[ - *ticket-id*](https://jira.devtools.intel.com/browse/EISW-140090)

### CODE REVIEW

**Review by rzubarev — APPROVED** [review]

**Comment by PatrikStepan** [comment]
build_jenkins

**Comment by ZoranZomborat** [comment]
PR is blocked until we merge work on compiler and create new driver https://github.com/intel-innersource/applications.ai.vpu-accelerators.vpux-plugin/pull/12569

**Comment by ZoranZomborat** [comment]
build_jenkins

**Comment by ZoranZomborat** [comment]
@ArtemySkrebkov @PatrikStepan @Maxim-Doronin can we review this PR please

**Review by razvanapetroaie — APPROVED** [review]

**Comment by ZoranZomborat** [comment]
@ArtemySkrebkov @PatrikStepan @Maxim-Doronin can we merge this PR please

**Review by ArtemySkrebkov — APPROVED** [review]

**Comment by ZoranZomborat** [comment]
Error seem to be related to infrastructure issue:

` E           ImportError: cannot import name 'get_display' from 'bidi' (/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/bidi/__init__.py)`

@ArtemySkrebkov can you check yourself also please.

**Comment by ArtemySkrebkov** [comment]
Does not seem related. I am about to put the PR back to the merge queue.

**Pull request merged**
