### PR TITLE
more models support for pytorch direct convert to IR

### PR DESCRIPTION
**Pull request by cronz**
there are several models supported after [pr2332](https://github.com/openvinotoolkit/openvino/pull/2332#issue-489270273) , however, there are several models include vgg, densenet not supported, please added them to the extensions

### CODE REVIEW

**Comment by lazarevevgeny** [comment]
@cronz , there are so many changes in your PR. Please, rebase properly.

**Comment by cronz** [comment]
> @cronz , there are so many changes in your PR. Please, rebase properly.

the latest code base is sufficient

**Comment by ilyachur** [comment]
> > @cronz , there are so many changes in your PR. Please, rebase properly.
> 
> the latest code base is sufficient

This PR contains a lot of commits from other people. Please rebase your branch and re-check that PR contains only your changes.

**Comment by ilya-lavrenov** [comment]
Direct py-torch support has been merged to contrib repo https://github.com/openvinotoolkit/openvino_contrib/pull/10. Please, submit changes to that repo if you have.

**Pull request closed without merging**
