### PR TITLE
Removed ArgMax ArgMin

### PR DESCRIPTION
**Pull request by ilyachur**

### CODE REVIEW

**Comment by tomdol** [comment]
I'm not sure what's the point of moving the opset0 ops to the tests directory and removing the tests for those ops at the same time. Can you explain?

**Comment by ilyachur** [comment]
> I'm not sure what's the point of moving the opset0 ops to the tests directory and removing the tests for those ops at the same time. Can you explain?

@tomdol I removed tests for v0 operation because their don't used more as nGraph operations, but I should move this operation to tests folder because INTERPRETER backend still use their for generating reference results.
From my point of view all necessary functionality of these v0 operation is covered by tests for INTERPRETER backend. Moreover all v0 operations should be removed when INTERPRETER will be able to use modern operations.

Please correct me if I am wrong. I can return back these tests.

**Comment by tomdol** [comment]
As discussed elsewhere, both ArgMax and ArgMin can be removed entirely from the codebase.

**Comment by ilyachur** [comment]
> As discussed elsewhere, both ArgMax and ArgMin can be removed entirely from the codebase.

Thanks! I removed ArgMax, ArgMin operations.

**Pull request merged**
