### PR TITLE
[IE VPUX][cherry pick #3001] Visitor API deserialization for ops from opset1

### PR DESCRIPTION
**Pull request by nikita-kud**
#44766

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Why do we need it for 2021.2?

**Comment by nikita-kud** [comment]
> Why do we need it for 2021.2?

This is an internal release

**Review by ilyachur — APPROVED** [review]
In general LGTM, but why do you need to port these changes?

**Comment by pvprog** [comment]
Looks good to me.

**Comment by nikita-kud** [comment]
> In general LGTM, but why do you need to port these changes?

discussed offline

**Pull request merged**
