### PR TITLE
Fluid update for er47 (fork)

### PR DESCRIPTION
**Pull request by dbudniko**

### CODE REVIEW

**Review by ArtemySkrebkov-intel — APPROVED** [review]

**Comment by ArtemySkrebkov-intel** [comment]
@azhogov @asomsiko @ababushk  
It seems, the failures are not related to the PR. Please help.

**Review by asomsiko — APPROVED** [review]

**Comment by asomsiko** [comment]
Jenkins CI restarted PR-3306/2

**Comment by dbudniko** [comment]
MyX test failed. Not relevant to PR. How to restart?

**Comment by ilya-lavrenov** [comment]
Restarted

**Comment by dbudniko** [comment]
Could someone please switch of ONNX? This PR is not relevant to ONNX. It's just fail at the beginning. This just blocks our release.

**Comment by ababushk** [comment]
@rblaczkowski could you please help us to fix ONNX stage for this PR?

**Pull request merged**
