### PR TITLE
Fix the strided slice issue when ellipsis_mask has redundant data.

### PR DESCRIPTION
**Pull request by luweizhou2016**
### Details:
 - TF use 32 bitmasks to represent *mask attribute in stridedslice OP. MO seems would convert the 32 bitmasks into a vector including 32 elements when constructing StridedSlice OP.  Current strided-slice doesn't consider this case.  

### Tickets:
 - *CVS-87981*

### CODE REVIEW

**Review by a-sidorova — APPROVED** [review]
Could you please verify using internal validation?

**Comment by luweizhou2016** [comment]
@a-sidorova , Can you pls help to explain more details about the "internal validation" ? Did you mean more E2E accuracy test?

**Comment by a-sidorova** [comment]
@luweizhou2016 I mean that I'd recommend to launch DLB to avoid some possible functional problems on models. Because as we know, the specification of `StridedSlice` op isn't full (for example, there aren't words about ranks of masks and `begin`/`end`/`stride`). So It'd be great if we verify this change on model scope. What do you think?

Note: I have had conversation about this specification with MO Team and I hope that the specification will be updated soon.

**Comment by luweizhou2016** [comment]
>

**Comment by luweizhou2016** [comment]
> >

Yes. Agree with more test.  I also took a look at the OV strideSlice spec when working on the issue. The spec doen't have too much limition on the mask bit value/length. In fact, Dmitry maybe would ask you to run DLB on your side when review the PR  in our sync meeting today. :-)

**Comment by a-sidorova** [comment]
@luweizhou2016 I have attached the results to the ticket. New functional regressions aren't appeared with the PR

**Review by dmitry-gorokhov — APPROVED** [review]

**Pull request merged**
