### PR TITLE
Check transformation callback in bidirectional sequence decomposition

### PR DESCRIPTION
**Pull request by tkrupa-intel**

### CODE REVIEW

**Comment by itikhono** [comment]
Why do we need these changes?
It looks like it will break the bidirectional cases.

**Comment by tkrupa-intel** [comment]
> Why do we need these changes?
> It looks like it will break the bidirectional cases.

In order to enable turning off this decomposition if a plugin chooses to support bidirectional cases directly. It's done the same way in other conversions/decompositions.

**Comment by itikhono** [comment]
> > Why do we need these changes?
> > It looks like it will break the bidirectional cases.
> 
> In order to enable turning off this decomposition if a plugin chooses to support bidirectional cases directly. It's done the same way in other conversions/decompositions.

Where do we plan to use it?
transformation_callback by default?

**Comment by tkrupa-intel** [comment]
It is false by default, plugins has to explicitly set to true if the transformation in question should be disabled.

**Review by itikhono — APPROVED** [review]

**Review by ilyachur — COMMENTED** [review]
Can we add new tests?

**Comment by tkrupa-intel** [comment]
> 
> 
> Can we add new tests?

What kind of tests do you have in mind?

**Comment by ilyachur** [comment]
> > Can we add new tests?
> 
> What kind of tests do you have in mind?

You have changed the transformation. Can we add new tests on transformation to cover these changes?

**Comment by tkrupa-intel** [comment]
> 
> 
> > > Can we add new tests?
> > 
> > 
> > What kind of tests do you have in mind?
> 
> You have changed the transformation. Can we add new tests on transformation to cover these changes?
> I am not sure that we already have tests which covers this line:
> `if (!lstm_sequence || transformation_callback(lstm_sequence))`

From what I can see there is currently no test for this transformation. However, that's beside the point - my change doesn't change the behavior by default because by default the transformation callback is false. A plugin may override it by returning true on this node - that'd disable the decomposition from 1 bidirectional to 2 unidirectional ops. In that scenario the plugin in question will handle the bidirectional case directly and if it goes wrong it will be detected because the plugins already have functional tests for both unidirectional and bidirectional cases. Do we need anything on top of that?

**Comment by itikhono** [comment]
> > > > Can we add new tests?
> > > 
> > > 
> > > What kind of tests do you have in mind?
> > 
> > 
> > You have changed the transformation. Can we add new tests on transformation to cover these changes?
> > I am not sure that we already have tests which covers this line:
> > `if (!lstm_sequence || transformation_callback(lstm_sequence))`
> 
> From what I can see there is currently no test for this transformation. However, that's beside the point - my change doesn't change the behavior by default because by default the transformation callback is false. A plugin may override it by returning true on this node - that'd disable the decomposition from 1 bidirectional to 2 unidirectional ops. In that scenario the plugin in question will handle the bidirectional case directly and if it goes wrong it will be detected because the plugins already have functional tests for both unidirectional and bidirectional cases. Do we need anything on top of that?

Yes, you are right, these transformations are tested with plugin functional tests. I guess it's enough.
But it would be great to add some unit tests, like https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/tests/functional/inference_engine/transformations/batch_to_space_decomposition_test.cpp

**Comment by tkrupa-intel** [comment]
>  But it would be great to add some unit tests, like https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/tests/functional/inference_engine/transformations/batch_to_space_decomposition_test.cpp

I added a commit with tests for this transformation, please take a look, @itikhono.

**Review by ilyachur — APPROVED** [review]

**Pull request merged**
