### PR TITLE
[IE][VPU] Add config option to disable asynchronous DMA on device

### PR DESCRIPTION
**Pull request by adudchen**
### Details:
 - *Add a configuration option to disable asynchronous DMA on device via XLinkWrite, related PR 14969*

### Tickets:
 - *47692*

### CODE REVIEW

**Review by Maxim-Doronin — CHANGES_REQUESTED** [review]
Please, add a private config 
https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/vpu/graph_transformer/include/vpu/private_plugin_config.hpp

and its parsing
https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/vpu/myriad_plugin/myriad_config.cpp#L130

**Review by Maxim-Doronin — APPROVED** [review]

**Review by Maxim-Doronin — COMMENTED** [review]
Please, update the firmware

**Comment by gladilov-gleb** [comment]
@Maxim-Doronin @adudchen 

Don't see a test on new configuration option. Is it scheduled to be introduced in a separate request? If so, I'd like to see corresponding ticket number.

**Comment by Maxim-Doronin** [comment]
> @Maxim-Doronin @adudchen
> 
> Don't see a test on new configuration option. Is it scheduled to be introduced in a separate request? If so, I'd like to see corresponding ticket number.

@adudchen, please link the ticket for adding tests to the original ticket

**Pull request merged**
