### PR TITLE
[CPU]Restrict the remove of convert with only 1 output

### PR DESCRIPTION
**Pull request by zhangYiIntel**
### Details:
 - *Restrict the remove of convert with only 1 output*
 - *...*

### Tickets:
 - *106512*

### CODE REVIEW

**Comment by zhangYiIntel** [comment]
@dmitry-gorokhov This PR fixes the bug of mask-rcnn. There is a Convert with 2 outputs in mask-rcnn for index conversion from int32 to int64. This kind of convert should be excluded from removing.

**Comment by dmitry-gorokhov** [comment]
@zhangYiIntel Can this isssue be covered by sungraph test?

**Comment by zhangYiIntel** [comment]
> @zhangYiIntel Can this isssue be covered by subgraph test?

Yes, let me extend the tests

**Comment by dmitry-gorokhov** [comment]
@zhangYiIntel Have you finished test coverage activity?

**Comment by zhangYiIntel** [comment]
> @zhangYiIntel Have you finished test coverage activity?

Not yet, I am busy with other tasks, let me trigger it today

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
@zhangYiIntel Please resolve conflicts

**Comment by zhangYiIntel** [comment]
Hi @dmitry-gorokhov  I think @v-Golubev has an universal fix #17702  for DropNode in `graph_optimizer.h` which is better than this PR. The original issue 106512 is also fixed by PR17702. I suggest to close this PR.

**Comment by dmitry-gorokhov** [comment]
Closed as not relevant anymore

**Pull request closed without merging**
