### PR TITLE
[IE CLDNN] Use single primitive reduce when axis=1(feature)

### PR DESCRIPTION
**Pull request by hyunback**
primitive performance better than decomposed transformations.

Signed-off-by: hyunback <hyunback.kim@intel.com>

### Details:
 - Currently reduce operations with axis=1(feature) is decomposed to reshape+pooling+reshape. Use primitive reduce performance is better without accuracy difference.

### CODE REVIEW

**Comment by isanghao** [comment]
LGTM

**Review by isanghao — APPROVED** [review]
LGTM

**Review by vladimir-paramuzov — APPROVED** [review]
lgtm. please rebase on top of latest master and have green CI.

**Comment by hyunback** [comment]
@vladimir-paramuzov 
Rebase done and ci pass. Could you merge it?

**Pull request merged**
