### PR TITLE
[CPU] Change mem size computation for CpuBlockedMemoryDesc

### PR DESCRIPTION
**Pull request by mandrono**
### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@mandrono @maxnick I would say we need this to be merged. What are next steps?

**Comment by mandrono** [comment]
> @mandrono @maxnick I would say we need this to be merged. What are next steps?

I have ran DLB, waiting results.

**Comment by dmitry-gorokhov** [comment]
@mandrono Any updates here?

**Comment by mandrono** [comment]
> @mandrono Any updates here?

@dmitry-gorokhov regressions were not found.

**Comment by akladiev** [comment]
This PR will be closed in 2 weeks in case of no activity.

**Comment by akladiev** [comment]
This PR was closed because it has been stalled for 2 week with no activity.

**Pull request closed without merging**
