### PR TITLE
samples: Print verbose error messages to stderr

### PR DESCRIPTION
**Pull request by ktrzcinx**
Printing error root cause is crucial for efficient debugging.

Signed-off-by: Karol Trzcinski <karolx.trzcinski@intel.com>

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
@ktrzcinx please rebase to master, there were some issues in not relevant tests, which were fixed since your last update

**Comment by vladimir-dudnik** [comment]
@azhogov @ilya-lavrenov who is responsible for ngraph ? Why it block a simple PR ?

**Comment by ilyachur** [comment]
> @azhogov @ilya-lavrenov who is responsible for ngraph ? Why it block a simple PR ?

@vladimir-dudnik I am responsible for ngraph, but here I don't see the ngraph group in reviewers.
And moreover I don't see any changes which are related with nGraph.
If the question was about CI, I would like to ask guys from CI team about failures.
Could you try to rebase PR to the latest master?

**Comment by ktrzcinx** [comment]
@ilyachur I rebased to latest `master`

**Review by ilya-lavrenov — APPROVED** [review]

**Review by ilyachur — APPROVED** [review]

**Pull request merged**
