### PR TITLE
Update NumPy dependency

### PR DESCRIPTION
**Pull request by achetver**
### Details:
 - We decide to update NumPy dependency in MO, POT, python bindings, samples, benchmark_tool and cross_check_tool and use <=1.21 version for Python > 3.6
 
### Tickets:
 - 76647

### CODE REVIEW

**Review by evolosen — APPROVED** [review]

**Review by sadolini — APPROVED** [review]

**Review by mvafin — APPROVED** [review]

**Comment by achetver** [comment]
@KodiaqQ @AlexKoff88 Please, take a look at NumPy reqs change in POT.

**Comment by AlexKoff88** [comment]
@eaidova

**Comment by eaidova** [comment]
@achetver what about moving dependency for ov python bindings?
https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/requirements.txt
https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/compatibility/openvino/requirements.txt

**Comment by achetver** [comment]
> @achetver what about moving dependency for ov python bindings? https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/requirements.txt https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/compatibility/openvino/requirements.txt cc @akuporos

Thanks, these files were updated too.

**Pull request closed without merging**
