### PR TITLE
Adapt myriad plugin for new firmware

### PR DESCRIPTION
**Pull request by AdrianVarlan**
### Details:
 - Adapt myriad plugin "magic numbers" for patching ddr memory type

### Tickets:
- https://jira.devtools.intel.com/browse/CVS-93543

### CODE REVIEW

**Review by DariaMityagina — APPROVED** [review]

**Comment by DariaMityagina** [comment]
@AdrianVarlan hi!
When are you going to modify fw version here: https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_myriad/myriad_dependencies.cmake#L16?

**Comment by DariaMityagina** [comment]
Discussed offline. The answer is yes, the dependency cmake file will be modified as well.

> @AdrianVarlan hi! Are you going to modify fw version here: https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_myriad/myriad_dependencies.cmake#L16? And VPU_SUPPORTED_FIRMWARES_HASH as well?

**Comment by DariaMityagina** [comment]
@Maxim-Doronin could you please take a look as well?

**Review by Maxim-Doronin — APPROVED** [review]

**Comment by Maxim-Doronin** [comment]
@openvinotoolkit/openvino-ie-maintainers 
ci/jenkins is not triggered for some reason. Moreover, rebasing the branch to be aligned with the HEAD of master is very frustrating, because changes are being merged every hour. An hour is not enough to complete pre-commit checks.
Please consider merging this PR with incomplete recommit as changes do not affect anything except for the annoying warning during MyriadX e2e testing

**Pull request merged**
