### PR TITLE
Revert "DeformableConv v8: reference implementation (#6514)"

### PR DESCRIPTION
**Pull request by azhogov**
This reverts commit 697c52abfe28ced765a164334d8471a4e089c7a3.

### CODE REVIEW

**Review by evgenytalanin-intel — CHANGES_REQUESTED** [review]
#6746 instead

**Comment by ilyachur** [comment]
PR #6746 was merged

**Comment by azhogov** [comment]
Fixed by https://github.com/openvinotoolkit/openvino/pull/6746

**Pull request closed without merging**
