### PR TITLE
Migrate to new RTTI for all transformations and graph structures

### PR DESCRIPTION
**Pull request by ilyachur**
### Details:
 - Migrate structures to new RTTI

### Tickets:
 - 69447

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
does it affect binary size?

**Comment by ilyachur** [comment]
> does it affect binary size?

|  Library  |  Master (Mb)  |  This branch (Mb)  | 
|---|---|---|
| openvino  | 11.23  |  11.14 | 
| openvino_intel_cpu_plugin | 28.75  |  28.77 |
| openvino_intel_gna_plugin  |  3.47 |  3.48 | 
| openvino_intel_gpu_plugin  |  16.57 |  16.58 | 
| openvino_intel_myriad_plugin  |  5.01 |  5.02 |

**Comment by ilya-lavrenov** [comment]
Let's finish with https://github.com/openvinotoolkit/openvino/pull/10691 first

**Comment by ilya-lavrenov** [comment]
Can be merged now?

**Review by ilya-lavrenov — APPROVED** [review]

**Pull request merged**
