### PR TITLE
Update protobuf to version 3.15.0

### PR DESCRIPTION
**Pull request by artkuli**
### Tickets:
 - *79758*

### CODE REVIEW

**Review by ilya-lavrenov — APPROVED** [review]

**Review by mbencer — APPROVED** [review]

**Review by tomdol — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
is it still valid?

**Comment by artkuli** [comment]
Reopen PR, the update protobuf is required for 2021.4.3 release

**Comment by ilya-lavrenov** [comment]
what prevents un from merging this? do we have tickets / asks to enable CI?

**Comment by artkuli** [comment]
@ilya-lavrenov  As I know, the CI should be enable in nearest future

**Comment by akladiev** [comment]
This PR will be closed in 2 weeks in case of no activity.

**Comment by akladiev** [comment]
This PR was closed because it has been stalled for 2 week with no activity.

**Pull request closed without merging**
