### PR TITLE
Fixed transpose reference

### PR DESCRIPTION
**Pull request by l-bat**
Current transpose reference produces incorrect results

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
@l-bat can we add tests to check that the issue has gone?

**Comment by l-bat** [comment]
> @l-bat can we add tests to check that the issue has gone?

Where the reference implementation is tested?

**Comment by ilyachur** [comment]
@l-bat Could you add new tests to this file: https://github.com/openvinotoolkit/openvino/blob/master/ngraph/test/backend/transpose.in.cpp ?

**Comment by l-bat** [comment]
> @l-bat Could you add new tests to this file: https://github.com/openvinotoolkit/openvino/blob/master/ngraph/test/backend/transpose.in.cpp ?

In this test, the [evaluate_transpose](https://github.com/openvinotoolkit/openvino/blob/master/ngraph/core/src/op/transpose.cpp#L105) is called

**Comment by ilyachur** [comment]
> > @l-bat Could you add new tests to this file: https://github.com/openvinotoolkit/openvino/blob/master/ngraph/test/backend/transpose.in.cpp ?
> 
> In this test, the [evaluate_transpose](https://github.com/openvinotoolkit/openvino/blob/master/ngraph/core/src/op/transpose.cpp#L105) is called

Yes I see, so it means that we need to use reference implementation inside the `Transpose` operation or remove it. As I see at the current moment we don't use this reference implementation in the nGraph. Why do you need this implementation? Can you use `evaluate` method of `Transpose` operation?

**Comment by l-bat** [comment]
@apankratovantonp Do we plan to support `evaluate` method for operations?

**Review by ilya-lavrenov — APPROVED** [review]

**Pull request merged**
