### PR TITLE
Allow to specify both in/out precision, add in/out layout in tests

### PR DESCRIPTION
**Pull request by alpkn**
CVS-39632

Changes in closed plugins are required.

### CODE REVIEW

**Comment by mikhail-treskin** [comment]
@l-bat FYI, probably you will have to make corresponding changes in tests on your side.

**Comment by azhogov** [comment]
CI passed: https://gitlab-icv.inn.intel.com/inference-engine/product-configs/merge_requests/998

**Comment by Maxim-Doronin** [comment]
@azhogov CI was not passed :(
Now myriad function tests fail

**Comment by alpkn** [comment]
@azhogov @Maxim-Doronin 
CI message was likely confused to be sporadic fail.
The caused code (tuple indices) has safer compile-time-fail alternative.

**Comment by evgenytalanin-intel** [comment]
#2622 should be the fix

**Pull request merged**
