### PR TITLE
[NormalizeL2] normalization of reduction axes

### PR DESCRIPTION
**Pull request by artkuli**
### Tickets:
 - *CVS-98160*

### CODE REVIEW

**Comment by artkuli** [comment]
@ilya-lavrenov  test added

**Comment by ilya-lavrenov** [comment]
should we also port this fix into `releases/2022/3` after merge?

**Comment by artkuli** [comment]
> should we also port this fix into `releases/2022/3` after merge?

Good question, I think that we should. @ilyachur what do you think?

**Comment by ilyachur** [comment]
Yes we need to port it

**Review by ilyachur — APPROVED** [review]

**Pull request merged**
