### PR TITLE
[CPU] Add binary post op check to jit_gemm prim desc

### PR DESCRIPTION
**Pull request by liubo-intel**
### Details:
 - *cpu pp_kernel creation will fail for some gemm_convolution + binary post_op cases*
 - *OneDNN fork pr: https://github.com/openvinotoolkit/oneDNN/pull/236* 

### Tickets:
 - *134839*

### CODE REVIEW

**Comment by yuxu42** [comment]
Hi @maxnick Could you please take a review? Thanks!

**Comment by maxnick** [comment]
@luweizhou2016, please review

**Comment by maxnick** [comment]
@liubo-intel , please make a PR to the oneDNN fork so that it can be reviewed conveniently. Also please name the commit in oneDNN fork in following the name convection (see previous PRs).

**Review by luweizhou2016 — APPROVED** [review]
LGTM

**Comment by yuxu42** [comment]
@maxnick Could you please review again? Thanks!

**Review by maxnick — APPROVED** [review]

**Pull request merged**
