### PR TITLE
[GNA] Moved unit test for Import/Export (Renew PR11438)

### PR DESCRIPTION
**Pull request by nkogteva**
### Details:
 - *Deprecated unit test : /src/tests_deprecated/unit/engines/gna/gna_graph_aot_test.cpp called GNAAOTTests*
 - *New test name GNAExportImportTest*
 - *Also copy Gmock API methods used in deprecated test*

### Tickets:
 - *74184*

Original PR https://github.com/openvinotoolkit/openvino/pull/11438

### CODE REVIEW

**Comment by sirzabek** [comment]
Why isn't the deprecated test removed?

**Review by sirzabek — COMMENTED** [review]
Where were the mock methods moved from? I cannot find any changes to the deprecated test in this PR.

**Comment by nkogteva** [comment]
> Where were the mock methods moved from? I cannot find any changes to the deprecated test in this PR.

Legacy part:

`src/tests_deprecated/unit/engines/gna/gna_api_stub.cpp`
`src/tests_deprecated/unit/engines/gna/gna_mock_api.hpp`

**Comment by nkogteva** [comment]
> Why isn't the deprecated test removed?

Fixed

**Comment by sirzabek** [comment]
> * lso moved Gmock API methods used in deprecated test

I mean the original files you mentioned still remain and there are no changes to them. It's not clear to me if this is intentional. Should they be modified or should the Details section of PR say the mock methods were copied, not moved?

**Comment by nkogteva** [comment]
> > * lso moved Gmock API methods used in deprecated test
> 
> I mean the original files you mentioned still remain and there are no changes to them. It's not clear to me if this is intentional. Should they be modified or should the Details section of PR say the mock methods were copied, not moved?

I suppose we should remove them when last test will be removed from deprecated.

**Review by sirzabek — APPROVED** [review]

**Pull request merged**
