### PR TITLE
[Hetero] Update pre processing info

### PR DESCRIPTION
**Pull request by maxim-kurin**
Update layouts for inputs of subgraphs in hetero plugin.

### CODE REVIEW

**Review by ilya-lavrenov — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
Can we port this to master as well?

**Comment by maxim-kurin** [comment]
> Can we port this to master as well?
https://github.com/openvinotoolkit/openvino/pull/4131

**Comment by ArtemySkrebkov-intel** [comment]
I am wondering, how did you find it?  
Is it possible to make a test?

**Comment by ilya-lavrenov** [comment]
> I am wondering, how did you find it?
> Is it possible to make a test?

Maybe we can extend https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/tests/functional/plugin/shared/include/behavior/layout.hpp ?

**Comment by maxim-kurin** [comment]
@ArtemySkrebkov-intel 
It was discovered while I was writing VPUX,CPU hetero sample.

**Review by apankratovantonp — APPROVED** [review]

**Comment by ArtemySkrebkov-intel** [comment]
@maxim-kurin 
We need a test which is run regularly.  
We cannot afford missing Hetero functionality for Gold3 as well.

You can consider re-using tests suggested by @ilya-lavrenov

**Comment by maxim-kurin** [comment]
@ArtemySkrebkov-intel It might be a good idea to merge it today. test might be merged separately (not ready yet)

**Comment by ArtemySkrebkov-intel** [comment]
I am OK to merge it as is to get it included into the following openvino package. The test can be provided later.
@asomsiko @ababushk @ilya-lavrenov  
Please help to merge.

**Comment by ArtemySkrebkov-intel** [comment]
The release branch has the same failures as this branch. 
[2021-02-04T16:31:39.771Z] [  FAILED  ] ie_core_register_plugins.registerPlugins
[2021-02-04T16:31:39.771Z] [  FAILED  ] ie_core_unregister_plugin.unregisterPlugin

I think it is safe to merge.

@ababushk @asomsiko @azhogov 
Can we disable testing MacOS platforms for vpux since we do not support it?

**Review by ArtemySkrebkov-intel — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
> The release branch has the same failures as this branch.
> [2021-02-04T16:31:39.771Z] [ FAILED ] ie_core_register_plugins.registerPlugins
> [2021-02-04T16:31:39.771Z] [ FAILED ] ie_core_unregister_plugin.unregisterPlugin

We need to create `releases/vpux/2021/2` on top of `releases/2021/2` inside testdata repo and test against this branch

**Comment by maxim-kurin** [comment]
> > The release branch has the same failures as this branch.
> > [2021-02-04T16:31:39.771Z] [ FAILED ] ie_core_register_plugins.registerPlugins
> > [2021-02-04T16:31:39.771Z] [ FAILED ] ie_core_unregister_plugin.unregisterPlugin
> 
> We need to create `releases/vpux/2021/2` on top of `releases/2021/2` inside testdata repo and test against this branch

Can you elaborate on this? testdata:releases/2021/2 already has that change, openvino:releases/vpux/2021/2 branch is hard to rebase onto testdata:releases/2021/2. I don't get what I'm supposed to do.

**Comment by maxim-kurin** [comment]
Behavior test MR https://github.com/openvinotoolkit/openvino/pull/4239

**Comment by ilya-lavrenov** [comment]
> Can you elaborate on this? testdata:releases/2021/2 already has that change, openvino:releases/vpux/2021/2 branch is hard to rebase onto testdata:releases/2021/2. I don't get what I'm supposed to do.

https://github.com/openvinotoolkit/openvino/commit/2e6a746722b50aa346fd0c5ec34b09d087596461

**Pull request merged**
