### PR TITLE
Changed ICore interface to return ov::CompiledModel

### PR DESCRIPTION
**Pull request by ilyachur**
### Details:
 - ov::ICore returns the high level CompiledModel

### Tickets:
 - *ticket-id*

### CODE REVIEW

**Comment by ilyachur** [comment]
@songbell It should help to avoid problems with AUTO integration.

**Comment by ilyachur** [comment]
Wrong PR

**Comment by songbell** [comment]
> @songbell It should help to avoid problems with AUTO integration.

em.. my current issue is with ov::Tensor, when call auto/multi/hetero, or even proxy with ov::asyncrequest->get_tensor() should return tensor with all the necessary libaries(inlcuding the libary where the tensor is actuall allocated, such as GPU if the tensor is allocated in GPU).
we will not have problem with gpu2.0 , but currently during migration with gpu1.0, this part is missing, because in 1.0 we only deal with get_blob(),  we need to additionally attach needed library affinity (in 1.0 we were using IInferRequestInternal::setPointerToSo() inferface).

**Comment by ilyachur** [comment]
> > @songbell It should help to avoid problems with AUTO integration.
> 
> em.. my current issue is with ov::Tensor, when call auto/multi/hetero, or even proxy with ov::asyncrequest->get_tensor() should return tensor with all the necessary libaries(inlcuding the libary where the tensor is actuall allocated, such as GPU if the tensor is allocated in GPU). we will not have problem with gpu2.0 , but currently during migration with gpu1.0, this part is missing, because in 1.0 we only deal with get_blob(), we need to additionally attach needed library affinity (in 1.0 we were using IInferRequestInternal::setPointerToSo() inferface).

Please take a look to proxy plugin changes. Hope it should help you.

**Comment by songbell** [comment]
> > > @songbell It should help to avoid problems with AUTO integration.
> > 
> > 
> > em.. my current issue is with ov::Tensor, when call auto/multi/hetero, or even proxy with ov::asyncrequest->get_tensor() should return tensor with all the necessary libaries(inlcuding the libary where the tensor is actuall allocated, such as GPU if the tensor is allocated in GPU). we will not have problem with gpu2.0 , but currently during migration with gpu1.0, this part is missing, because in 1.0 we only deal with get_blob(), we need to additionally attach needed library affinity (in 1.0 we were using IInferRequestInternal::setPointerToSo() inferface).
> 
> Please take a look to proxy plugin changes. Hope it should help you.

yes, I see the fakeVaradic op there, and learned well, thanks! but why close this PR? this PR will help resolve the tensor life cycle issue. I also left a comment in the proxy plugin, please help check there

**Pull request closed without merging**
