### PR TITLE
[GPU] typed_program_node refactoring

### PR DESCRIPTION
**Pull request by Konstantin-Beluchenko**
### Details:
The typed_program_node refactoring avoids a lot of boilerplate code.

### CODE REVIEW

**Comment by wilson-seok** [comment]
@mhnap-lohika Please check performance regression for all models in jenkins CI.

**Review by vladimir-paramuzov — APPROVED** [review]
lgtm

**Comment by wilson-seok** [comment]
@Konstantin-Beluchenko Please resolve conflicts.

**Comment by wilson-seok** [comment]
@Konstantin-Beluchenko Unfortunately your rebase from master included commit of build failure accidently so azure/intel build bot fail now. The fix is now merged. Please rebase this PR again. https://github.com/openvinotoolkit/openvino/commit/eb936e9f3452d4a39d4ff2d20cdd17fb3c05fe78

**Comment by wilson-seok** [comment]
No performance regression in fp32/16 models.

**Review by wilson-seok — APPROVED** [review]

**Pull request merged**
