### PR TITLE
Revert "[IE TEST] Continue run after crash (#10037)"

### PR DESCRIPTION
**Pull request by akladiev**
Unit tests in Windows debug postcommit were broken after #10037
### Tickets:
 - 80081

### CODE REVIEW

**Review by sbalandi — APPROVED** [review]

**Comment by sbalandi** [comment]
looks like root cause is not in #10037

**Comment by sbalandi** [comment]
win debug build also failed, so revert is not fix problem

**Comment by EgorDuplensky** [comment]
Hi, just randomly came across this change (I mean the one is being reverted here)
just wondering, what is the motivation for the change?
In general, why don't we want a test to terminate immediately after SIGSEGV, do we really want to execute the rest of the tests?
Also, for example, catching SIGSEGV and then just continue execution does not seem like a good idea.
Basically everything can happen after this. Probably the tests will continue to execute with some corrupted memory around.

**Comment by sbalandi** [comment]
Hi, @EgorDuplensky , we want to get as many test results as possible after launch. As far as I understand, if something goes wrong, we will see it from the logs, since either all tests are fails, or launch fails between run/setup function

**Pull request closed without merging**
