### PR TITLE
generator to pytest

### PR DESCRIPTION
**Pull request by PRATHAM-SPS**
### Details:
 - *Replaced the generator's functionality with pytest *

### Tickets:
 - *110705*

### CODE REVIEW

**Comment by PRATHAM-SPS** [comment]
command:- python -m unittest discover -p "extractor_test.py"

Output:-
..............WARNING:root:Skipping the case with both in and out port specified, only one port can be specified
......WARNING:root:Skipping the case with both in and out port specified, only one port can be specified
...............................
----------------------------------------------------------------------
Ran 51 tests in 0.214s
OK


command :- pytest "extractor_test.py"

Output:-
================================================================ test session starts =================================================================
platform linux -- Python 3.7.13, pytest-7.2.2, pluggy-1.2.0
rootdir: /home/pratham/Desktop/openvino/openvino/tools/mo
collected 46 items                                                                                                                                   

extractor_test.py ..............................................                                                                               [100%]

================================================================== warnings summary ==================================================================
../../../../../../../../anaconda3/envs/openvino/lib/python3.7/site-packages/defusedxml/__init__.py:30
  /home/pratham/anaconda3/envs/openvino/lib/python3.7/site-packages/defusedxml/__init__.py:30: DeprecationWarning: defusedxml.cElementTree is deprecated, import from defusedxml.ElementTree instead.
    from . import cElementTree

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================================================== 46 passed, 1 warning in 1.63s ============================================================

**Comment by PRATHAM-SPS** [comment]
@rkazants @popovaan @mvafin ,  In the beginning, 54 test cases passed for generator_test, but after changes, it now shows 51 for unittest and 46 for pytest. Could you please clarify that I'm doing this correctly? I have shared the output for the same just above this comment.

Thankyou.

**Comment by rkazants** [comment]
> @rkazants @popovaan @mvafin , In the beginning, 54 test cases passed for generator_test, but after changes, it now shows 51 for unittest and 46 for pytest. Could you please clarify that I'm doing this correctly? I have shared the output for the same just above this comment.
> 
> Thankyou.

Try to experiment by replacing unit tests with pytest in this file and see if the number of cases is recovered. Pay attention to that in CI we run these tests via pytest.

Best regards,
Roman

**Comment by PRATHAM-SPS** [comment]
Hello, @rkazants . Unittest gives output 51, and the remaining 2 test cases from it are passed by pytest because they were converted from generator to pytest. All test cases are covered and none are missing.

**Comment by rkazants** [comment]
build_jenkins

**Comment by rkazants** [comment]
build_jenkins

**Review by rkazants — APPROVED** [review]

**Pull request merged**
