### PR TITLE
[IE][TOOLS] Fix for CCT two IR mode

### PR DESCRIPTION
**Pull request by rvyunov**
Fix of inconsistency of named arguments in CCT two IR mode.

### CODE REVIEW

**Comment by rvyunov** [comment]
@akuporos , I prepare a small fix to CCT. Could you please review it? Or may be you know who is owner of CCT?

**Review by akuporos — APPROVED** [review]
LGTM

**Comment by ilya-lavrenov** [comment]
@rvyunov please, merge with latest master to make CI green.

**Comment by rvyunov** [comment]
@akuporos , could you merge it, please?

**Pull request merged**
