### PR TITLE
[CPU] Supporting constant networks

### PR DESCRIPTION
**Pull request by mandrono**
### Details:
 - This PR contains only those changes that are needed to support constant networks in the CPU plug-in. These changes was extracted from this PR: https://github.com/openvinotoolkit/openvino/pull/4120. Updates for ConstantResultSubgraphTest will be merged separately.
### Tickets:
 - Issue: 40957

### CODE REVIEW

**Comment by mandrono** [comment]
@dmitry-gorokhov could you review please?

**Comment by ilyachur** [comment]
Is it a new PR for constant networks? Because I thought that I already reviewed such changes

**Review by dmitry-gorokhov — APPROVED** [review]
Will merge after internal validation

**Comment by mandrono** [comment]
> Is it a new PR for constant networks? Because I thought that I already reviewed such changes
Updated description for PR.
These are the same changes as in PR: https://github.com/openvinotoolkit/openvino/pull/4120, but without ConstantResultSubgraphTest updates

**Review by ilyachur — APPROVED** [review]

**Pull request merged**
