### PR TITLE
SIMD opt for the Resize 32F1C

### PR DESCRIPTION
**Pull request by anna-khakimova**
### Details:
 - *SIMD opt for the Resize 32F1C.*
 
Performance report:
[Resize32F1C_NEON_RPI3.xlsx](https://github.com/openvinotoolkit/openvino/files/6231184/Resize32F1C_NEON_RPI3.xlsx)

### CODE REVIEW

**Review by rgarnov — APPROVED** [review]
Looks good, thanks!

**Comment by anna-khakimova** [comment]
@ilyachur Could you tell me please who are gatekeeper now (while @ilya-lavrenov is absent)?

**Comment by ilyachur** [comment]
@anna-khakimova Honestly, I am also on vacation. 

Am I right that CI is running for 6 days? If yes, could you update your branch to the latest master and re-run validation?

Also I have a question. Do we have a test for this new code?

PS:
Please mention me in your answer in order to I get a notification and read your answer.

**Comment by anna-khakimova** [comment]
> Am I right that CI is running for 6 days? If yes, could you update your branch to the latest master and re-run validation?

@ilyachur Done.

**Comment by anna-khakimova** [comment]
> Also I have a question. Do we have a test for this new code?

Yes, we do. For example **ResizeTestFluid_F32** test set for preprocessing calls this code.

**Comment by anna-khakimova** [comment]
> Also I have a question. Do we have a test for this new code?

@ilyachur Yes, we do. For example ResizeTestFluid_F32 test set calls this code.

**Review by ilyachur — APPROVED** [review]

**Comment by ilyachur** [comment]
> > Am I right that CI is running for 6 days? If yes, could you update your branch to the latest master and re-run validation?
> 
> @ilyachur Done.

@anna-khakimova Cool! Please ping me when CI will be passed and I will merge this PR.

**Comment by anna-khakimova** [comment]
@ilyachur Do you have rights to merge the PR when CI checks finish?

**Comment by anna-khakimova** [comment]
@ilyachur CI have already passed. Please take a look.

**Pull request merged**
