### PR TITLE
ClDNN: Add OPENCL extension d3d11 sharing checking

### PR DESCRIPTION
**Pull request by sivanov-work**
### Crash in clDNN when gpu::make_shared_context is called:
Cannot create remote GPU context using ` make_shared_context` with DX11 device.
Windows 10 system on Intel Cote i7 10610U has 2 OPENCL contexts:
- Platform name: Intel(R) OpenCL HD Graphics
- Platform name: Intel(R) OpenCL

DX11Device had created  using Intel HD Graphics and passed into  `gpu::make_shared_context ` and crash happened.
ClDNNPlugin uses  iteration over both contexts (GPU & CPU) and call INTEL extension  request `pfn_clGetDeviceIDsFromMediaAdapterINTEL` 
 for getting interoperability devices from initial Dx11 device. This is extension external call happened successfully for the first (Intel GPU platform) which  definitely support DX11 sharing extension but has crash with AccessViolation message for the second CPU context

OpenCL said https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clGetExtensionFunctionAddressForPlatform.html
that user must check extension explicitly with before invoke external extension function by obtained address by ICD, because

```
A return value of NULL indicates that the specified function does not exist for the implementation or platform is not a valid platform. A non-NULL return value for clGetExtensionFunctionAddressForPlatform **does not guarantee** that an extension function is actually supported by the platform. The application must also make a corresponding query using clGetPlatformInfo (platform, CL_PLATFORM_EXTENSIONS, …​ ) or clGetDeviceInfo (device,CL_DEVICE_EXTENSIONS, …​ ) to determine if an extension is supported by the OpenCL implementation.
```

PR provided string extension matching on "cl_khr_d3d11_sharing" straight before invoke interop ext function to prevent crash with AccessViolation

### Tickets:
 - CVS-66895

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Can we add some tests that this path now works? Would be very beneficial

**Comment by sivanov-work** [comment]
ok, i'll add some tests on DX11

**Comment by ilya-lavrenov** [comment]
> ok, i'll add some tests on DX11

Great, thanks!

**Review by dmatveev — COMMENTED** [review]
👍

**Comment by sivanov-work** [comment]
closed as opened from upstream repo protected branch by mistake
new PR created  from forked-repo: https://github.com/openvinotoolkit/openvino/pull/7856

**Pull request closed without merging**
