### PR TITLE
[IE Myriad] Remove Myriad 2 from supported devices in XLink

### PR DESCRIPTION
**Pull request by nikita-kud**
#-35243

### CODE REVIEW

**Comment by gladilov-gleb** [comment]
@taka-no-me FYI

**Comment by Maxim-Doronin** [comment]
Please, update PR description and mention the task number

**Comment by Maxim-Doronin** [comment]
What about internal validation?

**Comment by nikita-kud** [comment]
> What about internal validation?

@Maxim-Doronin this is not necessary.  Pre-commit shows that MX works

**Pull request merged**
