### PR TITLE
OpenVINO-Colab project

### PR DESCRIPTION
**Pull request by alihussainia**
In this pull-request, I am requesting to submit the direct installation script used to build the openvino-colab pypi package. Using this script, the OpenVINO toolkit can be installed directly on google colab platform.

### CODE REVIEW

**Comment by AlexKoff88** [comment]
@alihussainia, did you have a chance to look here https://pypi.org/project/openvino-python/ ?

Starting from the last release OpenVINO is available via pip.

**Comment by alihussainia** [comment]
Brother @AlexKoff88, 

Thanks for sharing the link. Please don't mind it but the bad thing about the openvino-python package is that it is still not truly optimized for colab which my PR will solve as the users will not have to set any path in order to setup the environment and thus the colab uses linux kernel so there is no need to install additional files for Windows :D. My package is a direct install and import solution and will directly setup everything on its own in the content/ directory (kinda home) thus allowing everyone to use the openvino easily without getting much into env setting issue. Thirdly, I have also added a server function to the solution that will allow the users to directly open a free and fresh openvino pre-installed VS Code instance in browser that will allow the users to directly work on OpenVINO with scripts and terminals (+sudo privileges). In summary, the thing to understand is that I am not adding or removing anything in OpenVINO but my goal is to provide an optimized Colab only solution that will allow the Colab users to use OpenVINO easily. The true aim is to provide an environment in which users that fears from installing OpenVINO locally or cannot due to any hardware or software specific issue can easily focus on building applications rather than worrying about environments and infrastructure.   

Still if you think the project is not worthy to be added into the official repo, then no worries at all. We all share the love of opensource so I will say OpenVINO will be fine without my package and I will keep my package so that those who think mine one is easier and simpler to be used on colab can use it :). 

Thanks for the time and consideration.

Best regards,

Muhammad Ali

**Comment by AlexKoff88** [comment]
@alihussainia, thanks for the comments. 

I understand your point now. Your PR definitely brings value to the project. But it has some problems, e.g. hardcoded version of the package, documentation in docx format. 
I think it can be partially integrated. But I guess it does not make sense to distribute two packages instead of one.

Best regards,
Alexander Povetkin

**Comment by alihussainia** [comment]
@AlexKoff88 Thanks brother. Well I believe we can use my code as a sub version of the openvino-python package i.e. when the users want to use OpenVINO on Colab, they are recommended to use the openvino-colab package as it gives them best support with regards to Colab. Just imagine if we will be able to create ease for people who are taking interest in OpenVINO by providing them OpenVINO in an environment already they are familiar with i.e. Colab. Plus it is also a very good solution for people who are not using required OS like in my case when I made the project, I was using ElementryOS that despite of being an ubuntu based linux flavor does not support OpenVINO. Since, I am from a third world country I was not able to purchase a good computing hardware and the only way possible for me to work on OpenVINO was cloud but since it was costly so I went for colab and the rest is in front of you :) 

A great quote I always follow:
"Those who create ease for others, get ease for themselves" 

And that's why openly shared the source code so that another Muhammad Ali sitting somewhere in the world can use the package easily and freely without worrying about required hardware and OS. 

Plus if you believe that my package can be optimized by any way, I will always welcome you and every other contributor. Furthermore, since a man cannot drink whole ocean, I too cannot cover everything and I am still learning CS so you guys are expert and definitely can find a way to optimize it further..

Thanks for your time and consideration,

Muhammad Ali

**Comment by mryzhov** [comment]
@alihussainia, we have plans to improve (fix environment setup) and extend PyPI distribution (add additional components, like MO, OMZ), so we can enable one more wheel package for colab using you PR, but I think we can simplify your changes a bit.
- use official PyPi packages to install OpenVINO SDK (we would need to extend its content. Could you please provide the list of components )
- use IE samples or OMZ demo (is it possible?) or add the new one there
- build openvino-colab package as part of a PyPI distribution build (I hope we will commit it to master in a few weeks)

**Comment by alihussainia** [comment]
@mryzhov, check this out https://github.com/alihussainia/openvino-colab/blob/master/detailed_demo.ipynb

**Comment by alihussainia** [comment]
for OMZ model usage: https://github.com/alihussainia/openvino-colab/blob/master/demo.ipynb

**Comment by ilya-lavrenov** [comment]
@alihussainia could you please consider transferring this PR to https://github.com/openvinotoolkit/openvino_contrib ? We can keep such modules in OpenVINO contrib repo. 

Any kind of tests can be added to check your changes?

**Comment by alihussainia** [comment]
@ilya-lavrenov Yeah, for sure. But can you please tell me how can I transfer this PR directly or else if I have to go through forking, updating and opening the PR again, then it may take some time due to my some personal and professional commitments.

**Comment by ilya-lavrenov** [comment]
No way to transfer w/o forking :)

**Comment by lahiruakmeemana** [comment]
from openvino import IECore
ModuleNotFoundError: No module named 'openvino'
 I get this error when I try to import openvino but openvino environment is established and I ran demo too.
please help me

**Comment by mryzhov** [comment]
> from openvino import IECore
> ModuleNotFoundError: No module named 'openvino'
> I get this error when I try to import openvino but openvino environment is established and I ran demo too.
> please help me

Please use the following import: "from openvino.inference_engine import IECore"

**Pull request closed without merging**
