### PR TITLE
fix some bugs in mvnc_api.c

### PR DESCRIPTION
**Pull request by tdp2110**

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Scope of changes look too big. Feel free to create a new PR with less significant change.

**Comment by tdp2110** [comment]
@ilya-lavrenov this ancient PR (from last Oct) was just two commits of mine, 256ce5f and 87f321c. I can rebase and resubmit as a new PR.

**Comment by ilya-lavrenov** [comment]
@tdp2110 ok, lets do it.

**Comment by tdp2110** [comment]
The double free pointed out in 256ce5f fixed itself in the last 9 months, so there's no need for this at all!

**Comment by ilya-lavrenov** [comment]
Ok, thanks for your help!

**Pull request closed without merging**
