### PR TITLE
[IE][VPU] Removed Mish decomposition

### PR DESCRIPTION
**Pull request by novozhilov-m-m**
Removed Mish decomposition because new Mish kernel implemented, MDK PR: https://github.com/movidius/mdk/pull/14873
  | 10 Images | 100 Images | 1000 Images
-- | -- | -- | --
Myriad performance (FPS) | 1.39 | 1.39 | 1.39
CPU performance (FPS) | 2.27 | 2.22 | 2.26
Myriad map (%) | 59.61 | 60.39 | 73.26
CPU map (%) | 37.63 | 59.61 | 73.32
Myriad coco_precision (%) | 76.35 | 76.32 | 75.71
CPU coco_precision (%) | 71.1 | 76.35 | 75.7

### CODE REVIEW

**Review by elatkin — APPROVED** [review]

**Comment by alalek** [comment]
> from mn/vpu/mis

You should use your fork instead.

**Review by elatkin — CHANGES_REQUESTED** [review]
Do you also need to update the Myriad firmware?

**Review by Maxim-Doronin — CHANGES_REQUESTED** [review]
please, remove `inference-engine/src/vpu/common/include/vpu/ngraph/transformations/mish_decomposition.hpp` as well

**Comment by novozhilov-m-m** [comment]
Created new PR from fork: https://github.com/openvinotoolkit/openvino/pull/3663

**Pull request closed without merging**
