### PR TITLE
Fix ENABLE_UNSAFE_LOCATIONS build flag

### PR DESCRIPTION
**Pull request by tpwrules**
Previously, the ENABLE_UNSAFE_LOCATIONS flag did not work properly because even if the archive existed on disk and could be extracted, the download status was never set to OK so the script stopped.

This patch fixes that issue, and enables openvino to be built in scenarios where Internet access is not available at build time.

### CODE REVIEW

**Review by ilya-lavrenov — APPROVED** [review]

**Comment by tpwrules** [comment]
Is there anything I need to change to help get this merged?

**Comment by ilya-lavrenov** [comment]
> Is there anything I need to change to help get this merged?

We need to have green CI

**Comment by tpwrules** [comment]
I can't seem to access it to see what the problem is. Let me know if I need to fix something.

**Comment by tpwrules** [comment]
Can you tell me what the issue is with the CI? I do not have permission to access it and would like to get this fix merged.

**Pull request merged**
