### PR TITLE
Reduce CPU usage for idle VPU

### PR DESCRIPTION
**Pull request by dkurt**
Reduce CPU usage for idle VPU from 60-70% to almost 0%

### CODE REVIEW

**Review by esmirno — APPROVED** [review]

**Comment by gladilov-gleb** [comment]
@dkurt could you please explain the idea of the fix?

**Comment by dkurt** [comment]
@gladilov-gleb, `pthread_cond_timedwait` waits until the time point from `timeToWait` which is initialized by 

```cpp
clock_gettime(CLOCK_MONOTONIC, &timeToWait);
```

Before it, `pthread_cond_t  wakeUpPingThread` should be initialized properly to manage this time mode which is initialized by 

```cpp
pthread_condattr_t attr;
pthread_condattr_setclock(&attr, CLOCK_MONOTONIC);
```
but `attr` was not used after it.

**Comment by gladilov-gleb** [comment]
> @gladilov-gleb, `pthread_cond_timedwait` waits until the time point from `timeToWait` which is initialized by
> 
> ```c++
> clock_gettime(CLOCK_MONOTONIC, &timeToWait);
> ```
> 
> Before it, `pthread_cond_t wakeUpPingThread` should be initialized properly to manage this time mode which is initialized by
> 
> ```c++
> pthread_condattr_t attr;
> pthread_condattr_setclock(&attr, CLOCK_MONOTONIC);
> ```
> 
> but `attr` was not used after it:
> 
> ```c++
> pthread_cond_init(&wakeUpPingThread, NULL);
> ```
> 
> source: https://stackoverflow.com/a/14397906/6548453

Thanks for clarification!

**Review by nikita-kud — APPROVED** [review]

**Comment by Maxim-Doronin** [comment]
Let's wait for internal VPU validation
* [ ] 1588

I'll merge it after validation passed

**Pull request merged**
