### PR TITLE
constraints openvino-dev: Limit mpmath<1.4

### PR DESCRIPTION
**Pull request by artanokhov**
### Details:
 - Limit mpmath because of https://github.com/pytorch/pytorch/issues/120995 and https://github.com/sympy/sympy/issues/26273

### CODE REVIEW

**Review by jiwaszki — COMMENTED** [review]
This file might be needed to update as well:
https://github.com/openvinotoolkit/openvino/blob/12404fcc8b82b1df05d8f4ea9d72fb7e5ff03d6d/src/bindings/python/constraints.txt#L14

There is also dependency on `sympy`, I think the `mpmath` could be restricted as well here.

**Comment by artanokhov** [comment]
> This file might be needed to update as well:
> 
> https://github.com/openvinotoolkit/openvino/blob/12404fcc8b82b1df05d8f4ea9d72fb7e5ff03d6d/src/bindings/python/constraints.txt#L14
> 
> There is also dependency on `sympy`, I think the `mpmath` could be restricted as well here.

Thank you! Fixed

**Comment by jiwaszki** [comment]
And the last one to updated:
https://github.com/openvinotoolkit/openvino/blob/master/tests/constraints.txt#L11

Sorry for missing out on it. That should be all.

**Comment by artanokhov** [comment]
> And the last one to updated: https://github.com/openvinotoolkit/openvino/blob/master/tests/constraints.txt#L11
> 
> Sorry for missing out on it. That should be all.

Added limit for mpmath in tests constraints

**Review by evgenytalanin-intel — APPROVED** [review]

**Review by jiwaszki — APPROVED** [review]

**Pull request merged**
