### PR TITLE
[VPU]  Added support for 2 axis for MVN layer - duplicate (#6748)

### PR DESCRIPTION
**Pull request by DariaMityagina**
* [VPU]Added support for 2 axis for MVN layer

Co-authored-by: Polina <polina.brzezinskaya@intel.com>

### Details:
This pr adds support for Person-reidentification-retail model on VPU device by adding support for {2} axis in MVN layer

### Tickets:
 - 55666

### CODE REVIEW

**Comment by DariaMityagina** [comment]
@AntonDudchenko @Maxim-Doronin could you please take a look?
It is a cherry-picked commit from the master branch.

**Review by Maxim-Doronin — APPROVED** [review]

**Comment by Maxim-Doronin** [comment]
@ilya-lavrenov should it be targeted in releases/2021/4_0 or another branch to deliver in OV 2021.4.1?

**Comment by DariaMityagina** [comment]
@ilya-lavrenov is releases/2021/4 the right target branch?

**Comment by DariaMityagina** [comment]
@evgenytalanin-intel do you have any information on branching strategy? Questions as above.

**Comment by DariaMityagina** [comment]
@Maxim-Doronin should be the right branch. It was mentioned in the ticket.

**Comment by DariaMityagina** [comment]
@AntonDudchenko can you merge it please?

**Review by AntonDudchenko — APPROVED** [review]

**Pull request merged**
