### PR TITLE
DO NOT MERGE: Use windows soft affinity pinning

### PR DESCRIPTION
**Pull request by ivankochin**
A draft patch that replaces the hard affinity interface for Hybrid CPUs pinning to soft ones on Windows.

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
@wangleis @dmitry-gorokhov is it still applicable?

**Comment by wangleis** [comment]
This is PR for 2021.4 release.

Now we are optimizing Hybrid CPUs for Windows on master. Should we port the solution after we fully complete optimization on master?

**Comment by akladiev** [comment]
This PR will be closed in 2 weeks in case of no activity.

**Comment by akladiev** [comment]
This PR was closed because it has been stalled for 2 week with no activity.

**Pull request closed without merging**
