### PR TITLE
Align builds locations for ngraph and ie python bindings

### PR DESCRIPTION
**Pull request by slyubimt**
This PR allows to get directory structure ready to test OpenVINO python bindings right after a build. (#47189)

` 
cmake 
..
 -DENABLE_PYTHON=ON 
 -DNGRAPH_PYTHON_BUILD_ENABLE=ON 
 -DNGRAPH_ONNX_IMPORT_ENABLE=ON 
`

`export PYTHONPATH=<OPENVINO_ROOT>bin/intel64/<CONFIGURATION>/lib/python_api/python<version>:$PYTHONPATH `

Check modules by executing:

`python3 -c "import openvino"`
`python3 -c "import ngraph"`

### CODE REVIEW

**Review by ilya-lavrenov — APPROVED** [review]

**Review by mryzhov — APPROVED** [review]

**Review by jiwaszki — CHANGES_REQUESTED** [review]
As I make changes in _.../python_api/..._ directory my changes appear during test runs - that works. However they are **not** applied when changes are made to files in _openvino/ngraph/python/src/ngraph_

Instead of copying, maybe you could provide some symbolic linking to these sources? So developers could modify them without worrying about the redundant step of re-building project.

**Comment by ilyachur** [comment]
> Instead of copying, maybe you could provide some symbolic linking to these sources? So developers could modify them without worrying about the redundant step of re-building project.

I think it won't work for Windows.

**Comment by slyubimt** [comment]
@jiwaszki, 

Changes are propagated in a case of incremental build.  This is an alternative scenario used by developers, who prefer to test a product in a build directory.  
Symbolic links is not a solution, since this will only work on systems that support it. 

You can still use `setup.py develop`, when installed wheel package creates link to sources under git control. This PR does not cancel this approach.

**Comment by mryzhov** [comment]
> @jiwaszki,
> 
> Changes are propagated in a case of incremental build. This is an alternative scenario used by developers, who prefer to test a product in a build directory.
> Symbolic links is not a solution, since this will only work on systems that support it.
> 
> You can still use `setup.py develop`, when installed wheel package creates link to sources under git control. This PR does not cancel this approach.

I  agree with @jiwaszki, using symbolic links is more flexible solution here.  What systems do not support symlinks? Win <10  and fat32? We are informing users that the validated system is Win10 only now. + I guess cmake will create file copies on such systems

**Comment by slyubimt** [comment]
> What systems do not support symlinks? Win <10 and fat32? We are informing users that the validated system is Win10 only now. 
Windows historically has lack of symbolic link support, including Windows 10 and CMake: you are required to have administrator privileges to create symbolic links using `mklink` .

**Review by jiwaszki — APPROVED** [review]

**Comment by postrational** [comment]
We need to consider how to move away from making multiple copies of Python code pointed at by `PYTHONPATH` and towards to creating a Python wheel package which will install into `site-packages`.

**Pull request merged**
