### PR TITLE
[PyOV] Accept Python functions as Extension attrs

### PR DESCRIPTION
**Pull request by jiwaszki**
... and capture GIL.

### Details:
 - Fix a bug with hanging process while adding extensions.

### Tickets:
 - *115994*

### CODE REVIEW

**Review by p-wysocki — APPROVED** [review]

**Review by akuporos — APPROVED** [review]

**Comment by jiwaszki** [comment]
> Let'a add tests

I think these are here, right?

- https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/tests_python/test_frontendmanager.py#L457-L488
- https://github.com/openvinotoolkit/openvino/blob/master/tests/layer_tests/py_frontend_tests/test_torch_frontend.py#L217-L252

**Comment by ilya-lavrenov** [comment]
> > Let'a add tests
> 
> I think these are here, right?
> 
> * https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/tests_python/test_frontendmanager.py#L457-L488
> * https://github.com/openvinotoolkit/openvino/blob/master/tests/layer_tests/py_frontend_tests/test_torch_frontend.py#L217-L252

are they run by default?
I wonder that we fixed something, but have not made changes in tests :)

**Comment by jiwaszki** [comment]
> > > Let'a add tests
> > 
> > 
> > I think these are here, right?
> > 
> > * https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/tests_python/test_frontendmanager.py#L457-L488
> > * https://github.com/openvinotoolkit/openvino/blob/master/tests/layer_tests/py_frontend_tests/test_torch_frontend.py#L217-L252
> 
> are they run by default? I wonder that we fixed something, but have not made changes in tests :)

Guess you have a good intuition for the CIs. These are for example here but skipped for some reason:
https://dev.azure.com/openvinoci/dldt/_build/results?buildId=616518&view=logs&j=8e6fb299-7deb-52f1-2f4a-df91230aba00&t=f812e137-0344-51cb-e8b0-0ab752070263&l=5091

Maybe there is something in post-commit? Tbh this should be somehow covered by validation, the question is "where?" (if anywhere...)

> I wonder that we fixed something, but have not made changes in tests :)

It does not change a lot as it is only implementation. Nothing really moved with arguments and such. As pybind translates `std::function` anyway. Major change is how capturing GIL lock and calling function itself works. The reproducer either hangs or not hang (with my fix) -- I do not see how better test it than these two tests which are skipped.

Do we really need to duplicate testcases here? If you want I can add them somewhere but it will look nearly identical. Maybe some little validation of number of args or so. Still mentioned tests should be run somewhere first.

I hope you find this answer satisfying.

**Comment by ilya-lavrenov** [comment]
> Do we really need to duplicate testcases here? 

I suppose it's enough to ensure that those tests are not skipped

**Comment by popovaan** [comment]
> @popovaan please test my branch with your use-cases. BTW do you have knowledge where these (in comment above) tests are running?

The first test present in openvino-lin-debian in post-commit: 
https://dev.azure.com/openvinoci/dldt/_build/results?buildId=616768&view=logs&j=e0e676f4-9664-538a-6d6b-aa53516aa09f&t=60acdb3b-83c2-59f1-06ac-dd4873286a99
In openvino-lin in precommit it is present, but skipped for some reason.

The second test is present in openvino-lin in precommit:
https://dev.azure.com/openvinoci/dldt/_build/results?buildId=616515&view=logs&j=982848f2-7f8d-5e57-730a-8df1e5f991ba&t=3a277157-f6e9-5973-5d89-47cdf1b84060

But I would recommend to add a test where some frontend is loaded and some extension with function parameter is used, for example telemetry extension. On master it leads to process hanging and we don't have tests for this.

@jiwaszki current solution leads to segfault in some cases. Please check the reproduces I provided in the ticket.

**Pull request merged**
