### PR TITLE
Move OMZ to thirdparty/open_model_zoo

### PR DESCRIPTION
**Pull request by azhogov**
### Tickets:
 - CVS-73034

### CODE REVIEW

**Review by vladimir-dudnik — APPROVED** [review]
looks ok to me. if POT tests not affected then we are good with this

cc @eaidova @Wovchena @nignatovsky @jkamelin

**Comment by vladimir-dudnik** [comment]
@azhogov @akuporos BTW, it is not clear why accuracy_checker is needed when python benchmark_app wheel built?

14:18:41  Entry point: benchmark_app
14:18:41  Processing package: accuracy_checker
14:18:41  error: [WinError 267] The directory name is invalid

**Comment by MaximProshin** [comment]
Please don't merge it until we make necessary changes for POT.

**Comment by slyubimt** [comment]
Paths to OMZ shall be updated in packaging script: https://github.com/openvinotoolkit/openvino/blob/d2df884274cf5f00dff56ae0d6b9becdb1019996/tools/openvino_dev/setup.py#L51

**Comment by eaidova** [comment]
Also I think, we need update submodule as well (I'm trying to do it last 3 weeks, but my changes are still not merged due to some infra reasons)
https://github.com/openvinotoolkit/openvino/pull/8740

**Comment by vladimir-dudnik** [comment]
it seems not an ifra issues, but POT tests not updated to mo transfer to new location

18:34:25  ************* Module pot.openvino.tools.pot.graph.passes
18:34:25  openvino/tools/pot/graph/passes.py:13:0: E0611: No name 'mo' in module 'openvino.tools' (no-name-in-module)

**Comment by eaidova** [comment]
> it seems not an ifra issues, but POT tests not updated to mo transfer to new location
> 
> 18:34:25 ************* Module pot.openvino.tools.pot.graph.passes 18:34:25 openvino/tools/pot/graph/passes.py:13:0: E0611: No name 'mo' in module 'openvino.tools' (no-name-in-module)

right now yes, need adoption in pot, but every rebase error gave  different issue (error during checkout submodules in pot pipeline, errors in macos/centos builds). and BTW for making pot CI green except adoption for MO changes also need changes from latest omz

**Review by vladimir-dudnik — APPROVED** [review]

**Comment by vladimir-dudnik** [comment]
@azhogov can we merge this?

**Comment by vladimir-dudnik** [comment]
need to rebase (OMZ updated in POT)

**Pull request closed without merging**
