### PR TITLE
Move unit and func test utils

### PR DESCRIPTION
**Pull request by olpipi**
### Details:
 - Move unit and func test utils from src/tests/ie_test_utils to test_utils 
 - Rename targets from unitTestUtils to unit_test_utils and from funcTestUtils to func_test_utils

### Tickets:
 - [CVS-111358](https://jira.devtools.intel.com/browse/CVS-111358)

### CODE REVIEW

**Comment by olpipi** [comment]
Depends on product config change:
https://github.com/intel-innersource/frameworks.ai.openvino.ci.product-configs/pull/2461

**Comment by olpipi** [comment]
Hi @iefode. Could you please take a look?

**Review by vurusovs — APPROVED** [review]

**Review by ilyachur — APPROVED** [review]

**Comment by ilyachur** [comment]
@akladiev @ilya-lavrenov Please take a look, this PR requires changes in product config and can be merged only together with PR to product config

**Review by ilya-lavrenov — APPROVED** [review]

**Pull request merged**
