### PR TITLE
[Python Tools] Align namespace for cross_check_tool

### PR DESCRIPTION
**Pull request by jkamelin**
### Details:
 - align cross_check_tool with the new namespace convention
 - change imports to `openvino.tools.cross_check_tool`
 - added `setup.py` script to deploy cross_check_tool into `site-packages/openvino/tools/cross_check_tool`

### Tickets:
 - 66138

### CODE REVIEW

**Review by ilya-lavrenov — APPROVED** [review]

**Review by vladimir-dudnik — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
Can we also update `cross_check_tool`'s docs to inform that it can be installed via:
```sh
python -m pip install <openvino_repo>/tools/cross_check_tool
```
?

**Comment by vladimir-dudnik** [comment]
> Can we also update `cross_check_tool`'s docs to inform that it can be installed via:
> 
> ```shell
> python -m pip install <openvino_repo>/tools/cross_check_tool
> ```
> 
> ?

obsolete, as we decide to not include cross_check_tool to openvino-dev

**Comment by ilya-lavrenov** [comment]
> obsolete, as we decide to not include cross_check_tool to openvino-dev

No, it still has https://github.com/openvinotoolkit/openvino/blob/master/tools/cross_check_tool/README.md which needs to be updated

**Review by slyubimt — APPROVED** [review]

**Review by ilyachur — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
@jkamelin could you please merge with latest master?

**Pull request merged**
