### PR TITLE
Added opset docs

### PR DESCRIPTION
**Pull request by andrew-zaytsev**

### CODE REVIEW

**Comment by slyalin** [comment]
@andrew-zaytsev, @lazarevevgeny, are we going to merge the specification directly to ngraph classes for corresponding operations? Is it not a good moment to do that?

**Comment by lazarevevgeny** [comment]
> @andrew-zaytsev, @lazarevevgeny, are we going to merge the specification directly to ngraph classes for corresponding operations? Is it not a good moment to do that?

We didn't have such a plans. And if we plan to do this it will take significant amount of time, so I do not recommend to do this now.

**Comment by slyalin** [comment]
> > @andrew-zaytsev, @lazarevevgeny, are we going to merge the specification directly to ngraph classes for corresponding operations? Is it not a good moment to do that?
> 
> We didn't have such a plans. And if we plan to do this it will take significant amount of time, so I do not recommend to do this now.

We had. Operation class and documentation do not have cross references and aren't technically connected together. We had plans to merge it to a single source.

**Comment by lazarevevgeny** [comment]
> > > @andrew-zaytsev, @lazarevevgeny, are we going to merge the specification directly to ngraph classes for corresponding operations? Is it not a good moment to do that?
> > 
> > 
> > We didn't have such a plans. And if we plan to do this it will take significant amount of time, so I do not recommend to do this now.
> 
> We had. Operation class and documentation do not have cross references and aren't technically connected together. We had plans to merge it to a single source.

I have created a separate ticket CVS-33883 to track this request.

**Pull request merged**
