### PR TITLE
[GPU] Use parallel sum reduction in RMS BFYX OPT kernel

### PR DESCRIPTION
**Pull request by dnkurek**
### Details:
 - Use parallel sum reduction for RMS BFYX OPT kernel
 - Improve heuristics

### Tickets:
 - 148937

### CODE REVIEW

**Comment by yeonbok** [comment]
Could you add a performance data you observed either on this PR or in the corresponding ticket?

**Comment by dnkurek** [comment]
> Could you add a performance data you observed either on this PR or in the corresponding ticket?

Hi, it is hard to observe a performance improvement, since in llama 2 7b chat get_num_sub_groups() in each execution was 8, which means that there is not much benefit to this in this case (3 sums down from 7. However, theoretically this change should scale up better with bigger models where get_num_sub_groups() may be larger, since the final reduction across sub groups now resembles log n complexity better than the previous implementation, so it's actually a matter of finding a model where get_num_sub_groups() gets big enough to make a difference.

**Comment by dnkurek** [comment]
> Could you add a performance data you observed either on this PR or in the corresponding ticket?

Actually, good news. I was capable of improving llama2 performance from 34.5 it/s to 35.5 it/s. Turns out that the heuristic for determining group size in rms_kernel_bfyx_opt.cpp was designed to work with the older linear implementation (probably was found out empirically using the older kernel), however after a quick value update I managed to find a tangible performance improvement in A770 GPU

**Review by vladimir-paramuzov — APPROVED** [review]
LGTM if perf is good

**Pull request merged**
