### PR TITLE
[IE VPU] Support 3 outputs for LSTMSequence

### PR DESCRIPTION
**Pull request by DariaMityagina**
-26693 - Adding the possibility of obtaining the 3rd output (LSTMSequence)
mdk PR: 14214

### CODE REVIEW

**Comment by DariaMityagina** [comment]
@gladilov-gleb, @avershov, @andrejsokolov 
Could you take a look?

**Comment by avershov** [comment]
@DariaMityagina For the future: using of 'rebase' is much preferable than 'merge' to update your work with the latest target branch state. With merge, your branch will contain _your_ commits, and then a lot of other commits on top of yours, so comparison of HEAD vs HEAD~N will contain a myriads of extraneous files & changes - which of them are just yours? With rebase all your commits will be on top of target branch, so comparison of HEAD vs HEAD-N will show me only _your_ changes.

**Comment by andrejsokolov** [comment]
@gladilov-gleb, can we merge it? There is failed validation for openvino(Win) (but as I see it falls from time to time on different requests)

**Comment by gladilov-gleb** [comment]
> @gladilov-gleb, can we merge it? There is failed validation for openvino(Win) (but as I see it falls from time to time on different requests)

Which validation do you mean? If it's openvino `pre-commit` I cannot merge it with red CI - we need to ask openvino CI team. If it's VPU private Jenkins - please share a link - I'll look at it (BTW, I didn't see VPU private validation for that PR)

**Comment by andrejsokolov** [comment]
> @gladilov-gleb, can we merge it? There is failed validation for openvino(Win) (but as I see it falls from time to time on different requests)
> 
> Which validation do you mean? If it's openvino pre-commit I cannot merge it with red CI - we need to ask openvino CI team. If it's VPU private Jenkins - please share a link - I'll look at it (BTW, I didn't see VPU private validation for that PR)

Now, it is green!

**Pull request merged**
