### PR TITLE
[ICV][XLink] - port XLink changes from mdk

### PR DESCRIPTION
**Pull request by DariaMityagina**
### Tickets:
 - 76384

### CODE REVIEW

**Comment by DariaMityagina** [comment]
@beleiuandrei could you please take a look?

**Comment by DariaMityagina** [comment]
@AntonDudchenko, @Maxim-Doronin, @beleiuandrei could you review this, please?

**Review by beleiuandrei — APPROVED** [review]

**Comment by DariaMityagina** [comment]
@AntonDudchenko could you please review and merge if possible?

**Comment by AntonDudchenko** [comment]
LGTM, but could you please run DLB as well? Just to make sure everything is OK

**Comment by DariaMityagina** [comment]
> LGTM, but could you please run DLB as well? Just to make sure everything is OK

Sure. Build number is 916. Thanks!

**Review by AntonDudchenko — APPROVED** [review]

**Comment by DariaMityagina** [comment]
@Maxim-Doronin @AntonDudchenko can this PR be merged?

**Pull request merged**
