### PR TITLE
Allow FakeQuantize with output_low scalar to be transformed

### PR DESCRIPTION
**Pull request by mateusztabaka**
validation:
* accuracy: developer-services/job/accuracy/949/ (reference: developer-services/job/accuracy/958/, failed: developer-services/job/accuracy/952/)
* performance: developer-services/job/performance/502/ (reference: developer-services/job/performance/503/)

### CODE REVIEW

**Comment by GlebKazantaev** [comment]
@eshoguli please review

**Review by ilyachur — APPROVED** [review]

**Comment by ilyachur** [comment]
Let's wait for @eshoguli review. because it is LPT part

**Review by eshoguli — COMMENTED** [review]
Please, add new tests case here: inference-engine\tests\functional\inference_engine\lp_transformations\convolution_transformation.cpp or new test to cover updated functionality.

**Comment by eshoguli** [comment]
please, don't merge before validation (developer-services) is completed

**Review by eshoguli — APPROVED** [review]
good for me, let's wait validation completion

**Pull request merged**
