### PR TITLE
[CPU]disable and cleanup interp and resample that are covered by interpolate

### PR DESCRIPTION
**Pull request by chenhu-wang**
disable and cleanup interp and resample that are transformed and covered by interpolate

### CODE REVIEW

**Comment by chenhu-wang** [comment]
need rebase on https://github.com/openvinotoolkit/openvino/pull/2366

**Comment by chenhu-wang** [comment]
> need rebase on #2366

rebased.

**Comment by alexey-varyzgin** [comment]
@chenhu-wang could you update your branch to the last master. I'd like to make PR to you branch regarding BF16 functionality.

**Comment by chenhu-wang** [comment]
> @chenhu-wang could you update your branch to the last master. I'd like to make PR to you branch regarding BF16 functionality.

**Comment by chenhu-wang** [comment]
> @chenhu-wang could you update your branch to the last master. I'd like to make PR to you branch regarding BF16 functionality.

Rebased. Thanks.

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
@ilyachur Could you please take a look on ngraph changes?

**Review by ilyachur — APPROVED** [review]
nGraph changes LGTM

**Pull request merged**
