### PR TITLE
[CPU] Reorganize development documentation

### PR DESCRIPTION
**Pull request by EgorDuplensky**
By moving everything into intel_cpu/docs folder

### CODE REVIEW

**Comment by EgorDuplensky** [comment]
@dmitry-gorokhov
PR from a fork branch

**Comment by EgorDuplensky** [comment]
@maxnick Could you please take a look?

**Comment by akladiev** [comment]
This PR will be closed in 2 weeks in case of no activity.

**Comment by EgorDuplensky** [comment]
@dmitry-gorokhov ping

**Review by dmitry-gorokhov — APPROVED** [review]

**Pull request merged**
