### PR TITLE
fix typo in opset3 shuffle_channels docstrings

### PR DESCRIPTION
**Pull request by lucasalavapena**
### Details:
 - fix typo in opset3 shuffle_channels docstrings

### Tickets:
 - None, I thought this was simple enough to not need a ticket

### CODE REVIEW

**Review by jiwaszki — APPROVED** [review]
@lucasalavapena thanks for catching this! 🙇

**Comment by lucasalavapena** [comment]
@jiwaszki what is happening with `ci/jenkins`? It has been expected for some days now I think

**Comment by jiwaszki** [comment]
> @jiwaszki what is happening with `ci/jenkins`? It has been expected for some days now I think

@p-wysocki can you help here?

**Comment by p-wysocki** [comment]
Some checks need to be approved in PRs with first-time contributors. I ran them. Thanks for your contribution!

**Review by p-wysocki — APPROVED** [review]

**Review by ilya-lavrenov — APPROVED** [review]

**Pull request merged**
