### PR TITLE
Remove some methods from nGraph node

### PR DESCRIPTION
**Pull request by ilyachur**

### CODE REVIEW

**Comment by jane-intel** [comment]
Please fill in the description. If PR is not ready for review, please convert it to draft.

**Comment by ilyachur** [comment]
Rebuild

**Comment by postrational** [comment]
What is the benefit of removing these helper functions?

**Comment by ilyachur** [comment]
> What is the benefit of removing these helper functions?

Just try to make API more clear. You can use is_type for the same functionality.

**Comment by ilyachur** [comment]
Rebuild

**Comment by postrational** [comment]
I would argue that this makes the API less clear.
Users have to know that checking for output is now `->is_type<op::v0::Result>`, which is much less clear than simply writing `->is_output`.

**Comment by ilyachur** [comment]
> I would argue that this makes the API less clear.
> Users have to know that checking for output is now `->is_type<op::v0::Result>`, which is much less clear than simply writing `->is_output`.

In general case, the base class should know nothing about properties of child classes. We can use inheritance in order to resolve the issue with different versions of constant , parameter, result operations.

**Comment by postrational** [comment]
> In general case, the base class should know nothing about properties of child classes. 

My concern is with the readability of the code which will be produced.

**Pull request closed without merging**
