### PR TITLE
[CPU] Added operation HSigmoid-5

### PR DESCRIPTION
**Pull request by a-sidorova**
Issue: 37625
Added operation HSigmoid-5

PR on OneDNN: https://github.com/openvinotoolkit/oneDNN/pull/16

### CODE REVIEW

**Review by antonvor — CHANGES_REQUESTED** [review]
add please fusing support for ops `Swish`, `HSwish`, `Mish` and `HSigmoid` in method `FuseFullyConnectedAndSimpleOperation()`

**Comment by a-sidorova** [comment]
@antonvor, thanks! Fusing support was added

**Comment by iefode** [comment]
Where is single layer tests for HSigmoid?

**Comment by a-sidorova** [comment]
> Where is single layer tests for HSigmoid?

@iefode, HSigmoid has not been added in nGraph yet. So when PR where HSigmoid is enabled in nGraph will be merged into master single layer tests will be added.

**Comment by a-sidorova** [comment]
@iefode, HSigmoid has been enabled in nGraph so I added single layer tests. Check, please

@antonvor, please, review this PR after fusing supports fixes

**Review by iefode — APPROVED** [review]

**Review by antonvor — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
@a-sidorova Plug-in path looks good to me. Some changes are needed to be done inside mkldnn-fork.

**Review by dmitry-gorokhov — APPROVED** [review]

**Pull request merged**
