### PR TITLE
[CC]Add CC support for ir reader

### PR DESCRIPTION
**Pull request by riverlijunjie**
### Details:
 - Apply CC for IR reader case: IR10 with new API,  IR11 with old API

### Tickets:
 - CVS-103542

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Please, provide information about improvements

**Comment by riverlijunjie** [comment]
> Please, provide information about improvements

I collected some data on Ubuntu 20.04 with static build for 2 scenarios:

image

About ~20KB binary size benefit achieved.

**Review by ilya-lavrenov — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
> > Please, provide information about improvements
> 
> I collected some data on Ubuntu 20.04 with static build for 2 scenarios:
> 
> image
> 
> About ~20KB binary size benefit achieved.

I expected we can have better improvements because Prepostprocessor functionality is supposed to be removed.

**Comment by riverlijunjie** [comment]
> 
Actually, compiler only puts the Prepostprocessor functions that are used into the final app binaries, all unused prepost functions should have be excluded already. We can see that very limited number prepost functions are used for ir10_new_api or ir11_old_api, so CC only can achieve limited benefit for them.

**Comment by riverlijunjie** [comment]
@ilyachur any comments?

**Review by ilyachur — APPROVED** [review]

**Pull request merged**
