### PR TITLE
[Tests] Thresholds logs were moved to Debug build only.

### PR DESCRIPTION
**Pull request by nshchego**
### Details:
 - *Thresholds logs were moved to Debug build only. That should reduce the CI logs size and exec time.*

### Tickets:
 - *98677*

### CODE REVIEW

**Comment by nshchego** [comment]
@iefode please take a look

**Comment by iefode** [comment]
@nshchego These logs are using in conformance tests runs to understand the problem

**Comment by ilya-lavrenov** [comment]
> @nshchego These logs are using in conformance tests runs to understand the problem. I don't see any pro's to remove it

Can you print these logs by env var?
I agree that a lot of extra messages are useless for most of the users

**Review by iefode — CHANGES_REQUESTED** [review]
I don't see a reason to merge the changes

**Comment by nshchego** [comment]
> > > @nshchego These logs are using in conformance tests runs to understand the problem. I don't see any pro's to remove it
> > 
> > 
> > Can you print these logs by env var?
> > I agree that a lot of extra messages are useless for most of the users
> 
> The message is printed only in failure case. What is the problem? What do you want to solve?

@iefode please look here https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-ubuntu20-cpu/74892/consoleText for example.

**Comment by akladiev** [comment]
This PR will be closed in a week because of 2 weeks of no activity.

**Pull request closed without merging**
