### PR TITLE
add doxygen doc build configurations and scripts

### PR DESCRIPTION
**Pull request by ntyukaev**

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
@ntyukaev please, make CI green

**Comment by ilyachur** [comment]
@ntyukaev Please fix CI.

**Review by ilyachur — COMMENTED** [review]
Can you enable build documentation for nGraph code too?

**Comment by ilya-lavrenov** [comment]
> Can you enable build documentation for nGraph code too?

We don't have such infra for ngraph. We need to implement this from scratch.

**Comment by ntyukaev** [comment]
@ilyachur  @ilya-lavrenov  We're working on adding new dependencies (Doxygen, Latex e.tc.) to the CI environment. I hope this will be resolved in the near future.

**Comment by ilya-lavrenov** [comment]
@ntyukaev is the issue with CI still here? is it a target for 2021.1?

**Comment by ntyukaev** [comment]
@ilya-lavrenov  please do not merge until @andrew-zaytsev  reviews it

**Comment by ilya-lavrenov** [comment]
@ntyukaev will the fixes be ported to 2021.1?

**Review by andrew-zaytsev — APPROVED** [review]

**Comment by ntyukaev** [comment]
@ilya-lavrenov  yes. they will

**Pull request merged**
