### PR TITLE
[GHA] Enable parallel execution of MO Python API python tests

### PR DESCRIPTION
**Pull request by hub-bla**
### Details:
 - Enabled parallel call
 - Fixed tests to be compatible with pytest-xdist plugin (pass function name instead of reference)

### Tickets:
 -  [None](https://github.com/openvinotoolkit/openvino/issues/20921)

Without parallel execution
Screenshot from 2024-09-10 09-23-16

With parallel execution (8 cpu cores)
Screenshot from 2024-09-10 09-26-10

### CODE REVIEW

**Comment by mlukasze** [comment]
build_jenkins

**Review by rkazants — APPROVED** [review]
Cool, thank you very much!

**Comment by ilya-lavrenov** [comment]
build_jenkins

**Comment by ilya-lavrenov** [comment]
build_jenkins

**Comment by rkazants** [comment]
@hub-bla, @ilya-lavrenov, let us merge this PR first: https://github.com/openvinotoolkit/openvino/pull/26602
@hub-bla, please take a look at this one https://github.com/openvinotoolkit/openvino/issues/26601

**Comment by rkazants** [comment]
build_jenkins

**Pull request merged**
