### PR TITLE
[MO] move importlib-metadata into setup.py

### PR DESCRIPTION
**Pull request by pavel-esir**
**Root cause analysis**: during requirements check MO was not handling `and` marker when `sys_platform` and `python_version` are specified simultaneously, e.g. `importlib-metadata; python_version < "3.8" and sys_platform == "win32"` and shows warning:
```
[ WARNING ] The version checker doesn't support environment marker combination and it will be 
ignored: python_version < "3.8" and sys_platform == "win32"
```

**Solution**: Moved importlib-metadata from requirements.txt into setup.py

Ticket: CVS-77062

Code:
* [x]  Comments
* [x]  Code style (PEP8)
* [x]  Transformation generates reshape-able IR
* [x]  Transformation preserves original framework node names
* [x]  Transformation preserves tensor names

Validation:
* [x]  Unit tests: added new cases, existing tests didn't broke
* n/a  Framework operation tests - no new operations were added
* n/a  Transformation tests - no new transformation were added
* n/a  Model Optimizer IR Reader check

Documentation:
* n/a  Supported frameworks operations list
* n/a  Guide on how to convert the **public** model
* n/a  User guide update

### CODE REVIEW

**Review by rkazants — CHANGES_REQUESTED** [review]
Why do we need `importlib-metadata` in requirements.txt file? no other tools use it. I propose to remove it and this change is not needed at all

**Comment by pavel-esir** [comment]
> Why do we need `importlib-metadata` in requirements.txt file? no other tools use it. I propose to remove it and this change is not needed at all

We need `importlib-metadata` for `entry_points` on windows. Without that package calling `mo --input_model ...` would not work. 
It is needed only for windows and only if python version is < 3.7, on linux and py >= 3.8 `entry_points` work without this requirement.

We are willing to make this as default recommended path to use MO therefore we can not remove this from requirements. But if my changes look too risky we can make this package required for both windows and linux or/and for all versions of python. And close this PR. This should not cause any harm since the package is lightweight.

**Comment by rkazants** [comment]
@pavel-esir, please remove `importlib-metadata` from `requirements.txt` and leave it only in `setup.py` as we agreed. No other changes are needed.

**Comment by pavel-esir** [comment]
> @pavel-esir, please remove `importlib-metadata` from `requirements.txt` and leave it only in `setup.py` as we agreed. No other changes are needed.

ok, i'll do this

**Review by andrei-kochin — COMMENTED** [review]
LGTM

**Pull request merged**
