### PR TITLE
[API CONFORMANCE] [CPU PLUGIN] Support OPTIMAL_BATCH_SIZE

### PR DESCRIPTION
**Pull request by karanjakhar**
### Details:
 - *add ov::optimal_batch_size property*

### Tickets:
 - Closes *#22118*

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@tiger100256-hu Please review the PR

**Comment by tiger100256-hu** [comment]
@karanjakhar I think the **ov::optimal_batch_size** depend on **ov::hint:model**, so also need to implement it, thanks
https://github.com/openvinotoolkit/openvino/issues/22118#issuecomment-1951014645

**Comment by yuxu42** [comment]
Hello @karanjakhar , are you still working on it? Thanks!

**Comment by yuxu42** [comment]
@karanjakhar just reminder. Are you still working on the issue? If so, could you please see the comments? Thanks!

**Comment by karanjakhar** [comment]
Hi @yuxu42 , 
I won't be able to work on it.

**Pull request closed without merging**
