### PR TITLE
Revert "Fix experimental detectron do ref impl (#10621)"

### PR DESCRIPTION
**Pull request by jane-intel**
This reverts commit d87233863dcefcf01ec6e953f3c589b62b75a5c8.

### CODE REVIEW

**Comment by opoluektov-lohika** [comment]
There are other fixes in the reference implemenation in the PR you propose to revert.

Please double check that they are not needed. Also it would be nice to have a relevant changes in the specification, the discrepancy between the two is really confusing.

**Review by vladimir-paramuzov — APPROVED** [review]

**Comment by lohika-denis-kotov** [comment]
Hi @jane-intel,

I wondering, why support backward compatibility for "experimental" operation ?
Usually in other frameworks like TensorFlow, PyTorch and etc., if something is marked as "experimental" it means that user should use this operation at they own risk.
The new operations could have mistakes that is why usually it is marked as "experimental"

**Comment by jane-intel** [comment]
@lohika-denis-kotov most of our users don't use operation classes directly -- they convert models via model optimizer and don't look into IR. So our warning that it is an experimental operator doesn't reach their attention. So we take backward compatibility with already generated IRs seriously for all released operators.

**Comment by lohika-denis-kotov** [comment]
@jane-intel I think this experimental status could be reported at least in console during loading network after model optimizer and it will solve an issue that customer wasn't aware of this status.

I thought that "experimental" should protect developers of plugin from supporting backward compatibility if there are bugs in initial implementation otherwise I do not understand how to introduce new operations which obviously could have bugs in initial implementation,

Anyway my point is that I think "experimental" operation should not be a part of backward compatibility, there some methods to notify user (console logs, operation specification, model-optimizer could also print warning in console and etc.)

**Pull request merged**
