### PR TITLE
benchmark_app takes AUTO as default device instead of CPU

### PR DESCRIPTION
**Pull request by yangwang201911**
### Details:
 - Without "-d DeviceName", benchmark app need to use AUTO instead of CPU as default device
 - Update both C++ and Python version.

### Tickets:
 - CVS-88424

### CODE REVIEW

**Review by peterchen-intel — APPROVED** [review]

**Review by wangleis — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
how would I actually know which device was selected? can it be understood from BA logs?
What's about python BA?

**Comment by ilya-lavrenov** [comment]
how would I actually know which device was selected? can it be understood from BA logs?

**Comment by yangwang201911** [comment]
> how would I actually know which device was selected? can it be understood from BA logs?

Yes. Benchmark app will output the selected device information as below.
_[Step 7/11] Loading the model to the device
[ INFO ] Load network took 482.28 ms
[Step 8/11] Setting optimal runtime parameters
**[ INFO ] Device: AUTO**_

**Comment by ilya-lavrenov** [comment]
> > how would I actually know which device was selected? can it be understood from BA logs?
> 
> Yes. Benchmark app will output the selected device information as below. _[Step 7/11] Loading the model to the device [ INFO ] Load network took 482.28 ms [Step 8/11] Setting optimal runtime parameters **[ INFO ] Device: AUTO**_

What is under AUTO? CPU GPU ? Nobody knows?
Will not user complain that by default BA started slower? BEcause different device is used with compare to the previous OV versions

**Comment by wangleis** [comment]
> What is under AUTO? CPU GPU ? Nobody knows? Will not user complain that by default BA started slower? BEcause different device is used with compare to the previous OV versions

In release document, we mentioned compile_network() would load network to AUTO as default when user did not set target device. 
We expect benchmark app can follow this behavior as main sample app.

**Comment by nkogteva** [comment]
I think it would be great to print some warning in log about behaviour change. Nobody will check documents before running benchmark_app if it already familiar with this tool

**Comment by yangwang201911** [comment]
> I think it would be great to print some warning in log about behaviour change. Nobody will check documents before running benchmark_app if it already familiar with this tool

Add warning info when use AUTO as the default target device with no target device specified in cmd line.

**Pull request closed without merging**
