### PR TITLE
[IE VPU] Workaround to support parameter Beta for layer Swish

### PR DESCRIPTION
**Pull request by rvyunov**
#-39088
Workaround to full support Swish layer. It is faster than native Swish for now.

### CODE REVIEW

**Review by elatkin — APPROVED** [review]

**Comment by elatkin** [comment]
@rvyunov  
May I see results of ICV local CI testing? (IE MDK and Nets Validation)

**Comment by rvyunov** [comment]
> @rvyunov
> May I see results of ICV local CI testing? (IE MDK and Nets Validation)

Sorry, please look into ticket from description.

**Comment by rvyunov** [comment]
> @rvyunov
> May I see results of ICV local CI testing? (IE MDK and Nets Validation)

But I ran it recently.

**Review by Maxim-Doronin — APPROVED** [review]

**Comment by rvyunov** [comment]
@Maxim-Doronin , could you merge it please?

**Comment by Maxim-Doronin** [comment]
@rvyunov, there are many regressions from Nets-Validation report

**Comment by rvyunov** [comment]
> @rvyunov, there are many regressions from Nets-Validation report

My changes can't provoke that regressions.

**Comment by rvyunov** [comment]
@Maxim-Doronin , could you merge it, please?

**Pull request merged**
