### PR TITLE
[PYTHON API] support packed types for Tensor

### PR DESCRIPTION
**Pull request by AlexeyLebedev1**
### Details:
 - *Tensor data property returns linear array in case packed types*
 - *Add tool for packing and unpacking data*
 - *Add u4, i4 constants*
### Tickets:
 - *52715*

### CODE REVIEW

**Comment by AlexeyLebedev1** [comment]
Need to resolve conflicts, but where should i place this helper in current package structure? Maybe we should have `openvino.helpers` which will contain `layout_helpers` and `packing`,  @akuporos, @jiwaszki what do you think?

**Comment by akuporos** [comment]
@ilya-lavrenov should the PR be a part of 2022.1?

**Comment by ilya-lavrenov** [comment]
> @ilya-lavrenov should the PR be a part of 2022.1?

looks like already no :)

**Comment by AlexeyLebedev1** [comment]
Continue in https://github.com/openvinotoolkit/openvino/pull/11131

**Pull request closed without merging**
