### PR TITLE
Move transformation and lp transformations tests from IeFuncTests and IeUnitTests

### PR DESCRIPTION
**Pull request by olpipi**
### Details:
 - Move transformation test from ieFuncTests to new ov_transformation_tests executable
 - Move lp_transformation test from ieFuncTests and ieUnitTests to new ov_lp_transformation_tests executable
 - Fix clang-format

### Tickets:
 - CVS-95526, CVS-32587

### CODE REVIEW

**Comment by ilyachur** [comment]
@itikhono please take a look

**Comment by ilyachur** [comment]
@olpipi Please resolve merge conflicts

**Comment by olpipi** [comment]
> @olpipi Please resolve merge conflicts

done

**Comment by ilyachur** [comment]
Please resolve merge conflicts.

**Comment by itikhono** [comment]
looks like it can affect my PR https://github.com/openvinotoolkit/openvino/pull/13470 , please do not merge it until my PR is merged.
@t-jankowski do these changes affect your work on migration to ov namespace?

**Comment by t-jankowski** [comment]
> looks like it can affect my PR #13470 , please do not merge it until my PR is merged. @t-jankowski do these changes affect your work on migration to ov namespace?

@itikhono I'm unable to deduct it from the diff view. Most likely it breaks my PR.

**Comment by olpipi** [comment]
> > looks like it can affect my PR #13470 , please do not merge it until my PR is merged. @t-jankowski do these changes affect your work on migration to ov namespace?
> 
> @itikhono I'm unable to deduct it from the diff view. Most likely it breaks my PRs #13653 and #13558

Hi

Yes, our PRs conflict with each other

**Comment by olpipi** [comment]
I want to split this PR to some parts: fix code style (clang format), fix warnings, test moving
I hope it helps to avoid big conflicts with other PRs

**Comment by ilyachur** [comment]
> I want to split this PR to some parts: fix code style (clang format), fix warnings, test moving I hope it helps to avoid big conflicts with other PRs
> 
> 1st part: #14073

I think that movement of tests files will introduce less number of conflicts :)

**Pull request closed without merging**
