### PR TITLE
[CPU][ARM64] Add JIT emitter for Eltwise Greater operation

### PR DESCRIPTION
**Pull request by nashez**
### Details:
- Added a jit_greater_emitter derived class in aarch64/jit_eltwise_emitters
- Created entry Algorithm::EltwiseGreater in the get_supported_precisions in nodes/kernels/aarch64
- Add the EltwiseGreater entry in the aarch64 executors supported algorithms

### Tickets:
- Closes: #24421

### CODE REVIEW

**Comment by nashez** [comment]
@dmitry-gorokhov Please review the changes

**Comment by dmitry-gorokhov** [comment]
build_jenkins

**Comment by dmitry-gorokhov** [comment]
build_jenkins

**Comment by nashez** [comment]
@dmitry-gorokhov Does this need something from my end?
I see CI failing

**Comment by dmitry-gorokhov** [comment]
build_jenkins

**Pull request merged**
