### PR TITLE
[Myriad] Mish layer optimization

### PR DESCRIPTION
**Pull request by elatkin**
Accompanies MDK #[14702](https://github.com/movidius/mdk/pull/14702): Mish layer optimization

Corresponding issue: 38154

### CODE REVIEW

**Review by avershov — APPROVED** [review]

**Review by nikita-kud — APPROVED** [review]

**Comment by elatkin** [comment]
@Maxim-Doronin 
Could you please merge?

**Comment by Maxim-Doronin** [comment]
@elatkin, we have just merged https://github.com/openvinotoolkit/openvino/pull/2762 with the new firmware which doesn't contain Mish optimization. I've triggered a new firmware build #-1425. Please, wait for it and update this PR.
Sorry for inconvenience

**Comment by elatkin** [comment]
> ...we have just merged #2762 with the new firmware which doesn't contain Mish optimization...

Updating VPU firmware to version 1426

**Comment by elatkin** [comment]
@Maxim-Doronin
Could you please merge? (now with VPU firmware refreshed like you proposed)

**Pull request merged**
