### PR TITLE
[CPU] Fix incorrect offset to rsp

### PR DESCRIPTION
**Pull request by xuchen-intel**
### Details:
 - *Fix incorrect offset to rsp in bf16 depthwise convolution kernel in onednn fork.*
 - *https://github.com/openvinotoolkit/oneDNN/pull/156*

### Tickets:
 - *94463*

### CODE REVIEW

**Comment by xuchen-intel** [comment]
@dmitry-gorokhov Hi Dmitry, could you please take a look? Minor change.

**Review by dmitry-gorokhov — APPROVED** [review]
Thanks for the fix. 
We do have CPU Convolution single layer test which is expected to cover BF16 inference via emulation on AVX512 targets. In other words may I ask you to check why this case is not covered?

**Comment by xuchen-intel** [comment]
> Thanks for the fix. We do have CPU Convolution single layer test which is expected to cover BF16 inference via emulation on AVX512 targets. In other words may I ask you to check why this case is not covered?

@dmitry-gorokhov I've double checked. If the following two conditions are meet, then the specific "if" branch will be excuted, and this core dump can be revealed beforehand.
a. layout==nspc
b. jcp.nb_ch > jcp.nb_ch_blocking (requires bigger channel size)
But condition 'a' is not meet, because nspc layout is disabled by https://github.com/openvinotoolkit/openvino/blob/3de3e7b8fae3800adda1083277750fc5790bcc7e/src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp#L48
Further discussion is always welcomed. Thanks Dmitry!

**Comment by dmitry-gorokhov** [comment]
> 

Seems like this skip config is not actual anymore. Could you please try to remove it?

**Comment by xuchen-intel** [comment]
> > 
> 
> Seems like this skip config is not actual anymore. Could you please try to remove it?

@dmitry-gorokhov Removed the suppression of nspc_bf16 test cases for GroupConvolution layer, and added test cases that can reveal the issue in this ticket.
BTW, the similar suppression for Convolution layer remains, because otherwise some errors in test suites smoke_Conv_1D_BF16 and smoke_Conv_1D_1x1_BF16 show up, which can still be tracked by ticket 56143. Thanks Dmitry!

**Comment by dmitry-gorokhov** [comment]
@xuchen-intel  could you please update the PR?

**Comment by xuchen-intel** [comment]
> @xuchen-intel could you please update the PR?

The CI shows some of the new added group conv test cases don't pass on some Xeon platform. It could be an different issue from the original one. I'm trying to reproduce and fix it now.

**Comment by xuchen-intel** [comment]
> > @xuchen-intel could you please update the PR?
> 
> The CI shows some of the new added group conv test cases don't pass on some Xeon platform. It could be an different issue from the original one. I'm trying to reproduce and fix it now.

@dmitry-gorokhov Hi Dmitry, I've already fixed two more places, the CI still fail(though the same local Xeon Skylake machine pass these tests). I think the new added SLT suite reveal more issues than I fixed, and it will still take a while to fix them all. I suggest to split the PR into two, so that the first PR fixes the model core dump issue in this ticket, and I'll use the second PR deal with SLT coverage and the errors they reveal.  What do you think?
cc @yuxu42

**Comment by xuchen-intel** [comment]
@dmitry-gorokhov As we agreed, I split this PR into two. This one fixes the original core dump issue, and I use this separate PR https://github.com/openvinotoolkit/openvino/pull/14002 to track SLT coverage and new issues it reveals.

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by xuchen-intel** [comment]
@dmitry-gorokhov CI is green now. Thanks Dmitry!

**Pull request merged**
