### PR TITLE
[POT] Nodes with no/emply inputs translate to tuple/reshape errors.

### PR DESCRIPTION
**Pull request by vixadd**
### Details:
I have a node that doesn't have inputs to it in my mo graph. When I try to run weights statistics on it, it gives me problems since the weights value comes out at np.array(0) instead of np.array([0]). This causes the following error:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_1243/189182791.py in <module>
----> 1 compressed_model = pipeline.run(model)

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/pipeline/pipeline.py in run(self, model)
     52                 current_algo_seq = []
     53 
---> 54         result = self.collect_statistics_and_run(model, current_algo_seq)
     55         logger.update_progress(self._algorithms_steps)
     56         return result

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/pipeline/pipeline.py in collect_statistics_and_run(self, model, algo_seq)
     62         for algo in algo_seq:
     63             logger.info('Start algorithm: {}'.format(algo.name))
---> 64             model = algo.run(model)
     65             logger.info('Finished: {}\n {}'.format(algo.name, '=' * 75))
     66         return model

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/default/algorithm.py in run(self, model)
     98         for algo in self.algorithms[1:]:
     99             algo.default_steps_size = self.default_steps_size
--> 100             model = algo.run(model)
    101         logger.update_progress(self.default_steps_size)
    102         return model

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/minmax/algorithm.py in run(self, model)
     57                                          activation_statistics,
     58                                          self.fill_fq_range,
---> 59                                          self._config)
     60 
     61         if self._config.get('dump_intermediate_model', False):

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/fake_quantize.py in get_quantized_model(model, create_stats_collector, activations_statistics, fill_fq_range, config, qscheme)
    317 
    318     # compute weights statistics
--> 319     weights_stats = compute_weights_stats(model, weights_stats_layout)
    320 
    321     # calculate and fill min and max range for fq nodes

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/fake_quantize.py in compute_weights_stats(model, stats_layout)
    348             weights_stats[node.name] = {}
    349         for stat_name, stat_fn in stats.items():
--> 350             weights_stats[node.name][stat_name] = stat_fn(weights)
    351     return weights_stats
    352 

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/statistics/statistics.py in __call__(self, *argv, **kwargs)
     33 
     34     def __call__(self, *argv, **kwargs):
---> 35         return self.compute(*argv, **kwargs)
     36 
     37     def __hash__(self):

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/statistics/statistics.py in compute(self, *input_tensor, **kwargs)
     44 class TensorStatistic(Statistic):
     45     def compute(self, *input_tensor, **kwargs):
---> 46         return self.func(*(input_tensor + self.argv), **self.kwargs)
     47 
     48 

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/statistics/functions/weights.py in abs_max_per_filter(weights, transpose)
     73 @w_stats_fn_per_channel.register('abs_max')
     74 def abs_max_per_filter(weights, transpose=False):
---> 75     return max_per_filter(np.abs(weights), transpose=transpose)
     76 
     77 

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/statistics/functions/weights.py in max_per_filter(weights, transpose)
     63 @w_stats_fn_per_channel.register('max')
     64 def max_per_filter(weights, transpose=False):
---> 65     return calculate_per_filter_stats(weights, np.max, transpose=transpose)
     66 
     67 

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/statistics/functions/weights.py in calculate_per_filter_stats(weights, fn, transpose)
     32         weights_shape.extend(original_axes[2:])
     33         weights = np.transpose(weights, weights_shape)
---> 34     t = np.reshape(weights, (weights.shape[0], -1))
     35     return fn(t, axis=1)
     36 

IndexError: tuple index out of range


```

Then there's an issue in the broadcast function where an empty input shape causes an error during reshaping.
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_1243/189182791.py in <module>
----> 1 compressed_model = pipeline.run(model)

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/pipeline/pipeline.py in run(self, model)
     52                 current_algo_seq = []
     53 
---> 54         result = self.collect_statistics_and_run(model, current_algo_seq)
     55         logger.update_progress(self._algorithms_steps)
     56         return result

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/pipeline/pipeline.py in collect_statistics_and_run(self, model, algo_seq)
     62         for algo in algo_seq:
     63             logger.info('Start algorithm: {}'.format(algo.name))
---> 64             model = algo.run(model)
     65             logger.info('Finished: {}\n {}'.format(algo.name, '=' * 75))
     66         return model

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/default/algorithm.py in run(self, model)
     98         for algo in self.algorithms[1:]:
     99             algo.default_steps_size = self.default_steps_size
--> 100             model = algo.run(model)
    101         logger.update_progress(self.default_steps_size)
    102         return model

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/minmax/algorithm.py in run(self, model)
     57                                          activation_statistics,
     58                                          self.fill_fq_range,
---> 59                                          self._config)
     60 
     61         if self._config.get('dump_intermediate_model', False):

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/fake_quantize.py in get_quantized_model(model, create_stats_collector, activations_statistics, fill_fq_range, config, qscheme)
    284 
    285     # calculate and fill min and max range for fq nodes
--> 286     fill_fq_range(model, weights_stats, activations_statistics, fake_quantize_config, config)
    287     return model
    288 

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/minmax/algorithm.py in fill_fq_range(model, weights_stats, inputs_stats, fake_quantize_config, config)
    156             if fake_quantize_config[fq_.name]['mode'] == 'symmetric':
    157                 min_level_, max_level_ = fqut.symmetric_range(_node_input, fq_, batch_weights_stats,
--> 158                                                               batch_inputs_stats, fake_quantize_config)
    159             else:
    160                 min_level_, max_level_ = fqut.asymmetric_range(_node_input, fq_, batch_weights_stats,

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/fake_quantize.py in symmetric_range(node, fq, weights_stats, batch_inputs_stats, fake_quantize_config)
    229         raise Exception(
    230             'WARNING: Fake quantize node {} is missed'.format(fq.name))
--> 231     min_level, max_level = broadcast_fq_values(fq, node, min_level, max_level, fake_quantize_config)
    232     return min_level, max_level
    233 

/opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/fake_quantize.py in broadcast_fq_values(fq, node, min_level, max_level, fq_config)
    339             bounds_shape[1] = input_shape[1]
    340         else:
--> 341             bounds_shape[0] = input_shape[0]
    342     else:
    343         if fq_config[fq.name]['granularity'] == 'perchannel':

IndexError: index 0 is out of bounds for axis 0 with size 0
```

The two lines skirting both of these errors allows my model to be compressed.

### CODE REVIEW

**Comment by vixadd** [comment]
I've seen your question, I'm tagging up with some other people to see if the graph can be divulged. At the same time, I'll try setting the stat_requests_number to 4 or something greater than 1.

**Comment by vixadd** [comment]
Hi. I'm so sorry for the long wait. I cannot share the entire model itself, however, I've debugged the code, and I can show the specific topology that is causing this error. Observe the following layer from my XML file.

```xml
<layer id="200" name=".../topk_combine_classes__x" type="TopK" version="opset3">
    <data axis="1" index_element_type="i64" mode="max" sort="value"/>
    <input>
        <port id="0" precision="FP32">
            <dim>8</dim>
            <dim>256</dim>
        </port>
        <port id="1" precision="I32"/>
    </input>
    <output>
        <port id="2" names="scores" precision="FP32">
            <dim>8</dim>
            <dim>64</dim>
        </port>
        <port id="3" names=".../topk_combine_classes__x:1" precision="I64">
            <dim>8</dim>
            <dim>64</dim>
        </port>
    </output>
</layer>
```
So with this TopK layer, I'm feeding a scores layer that exists further down the topology.

I then wind up with the following layer spec for scores.
```xml
<layer id="242" name="scores" type="Add" version="opset1">
    <data auto_broadcast="numpy"/>
    <input>
        <port id="0" precision="FP32">
            <dim>8</dim>
            <dim>64</dim>
        </port>
        <port id="1" precision="FP32"/>
    </input>
    <output>
        <port id="2" precision="FP32">
            <dim>8</dim>
            <dim>64</dim>
        </port>
    </output>
</layer>
```
Its on the above node that I wind up with the first tuple error. One of the weight specifics that I will get will be ```np.array(0)``` This breaks the ```stat_fn``` function that is run in the next step.

**Comment by vixadd** [comment]
RE the stats_request_number, it didn't work. I still see the same error.

**Comment by vixadd** [comment]
To aid you guys further. I run a TopK functionality in the model that has something like the following: No where near what the model actually shows but close enough to be able to re-create this issue.

```python
import tensorflow as tf

k = # Some classification maxima
scores, _ = tf.math.top_k( out, k=k )

# combine classifications
scores_rshp = tf.reshape( scores, [x, y, z] )
score, _ = tf.math.top_k( topk_scores_rshp, k=k name="A")
```

**Comment by KodiaqQ** [comment]
> RE the stats_request_number, it didn't work. I still see the same error.

Try to increase not `stats_request_number` but `stat_subset_size` :)

**Comment by vixadd** [comment]
I still get the same error. Sorry.

**Comment by AlexKoff88** [comment]
@vixadd, it seems like your model has quite a specific pattern that causes the issue. The TF example that you posted above does not seem like something we can use since it does not contain any quantizable layer. 
Can you maybe point to the public UNet or similar model that has the same pattern? This is not just to reproduce the problem on our side but it is rather to include such a pattern in a regular validation.
BTW, it may turn out that the only thing you need to do is to exclude some layer from the quantization process by using "ignored" functionality of POT config. Please refer [here ](https://github.com/openvinotoolkit/openvino/blob/0071abffdff8f4f112ce70c7c7e6a9d559007bb0/tools/pot/configs/default_quantization_spec.json#L87)for more info.

**Comment by vixadd** [comment]
I can see the issue, I'm currently working on something to re-create the issue and give you a better idea of what I'm seeing.

**Comment by vixadd** [comment]
I'm so sorry for the delay, I'm investigating a potential issue with the way I've implemented things. The problem seems to be stemming from having a dict in one of the layers that has not convolutions, and just returns the final predictions that have gone through some post-processing. The key in that dict winds up being represented as a layer in the IR. This is due to the fact that I'm converting from keras to onnx to IR in my process.

**Comment by AlexKoff88** [comment]
@vixadd, any chance you share a model with random weights with us so that we can include it into our regular validation?

**Comment by vixadd** [comment]
Hey guys, since I have a workaround for this issue, I'm going to close it. I'm sorry for wasting your time. I'm too busy at the moment to hunt this down. Maybe in the future. That being said, you have a pretty solid product and it's amazing working with it. :) Thank you for all your help. The solution was putting the layer in the "ignored" portion for the POT config.

**Pull request closed without merging**
