### PR TITLE
[OV][VPUX] - Debug build flags

### PR DESCRIPTION
**Pull request by DariaMityagina**
### REPLACE "/Zi" -> "/Zi /FS" + https://github.com/openvinotoolkit/openvino/pull/13826

- **/Zi -> /Zi /FS**
As it turned out, there is a [similar change with overwriting cmake flags](https://github.com/openvinotoolkit/openvino/blob/master/cmake/developer_package/compile_flags/os_flags.cmake#L311-L314) (/Z7, /Zi, ..) on the OpenVino side.
But instead of doing it [the way it was done in vpux-plugin](https://github.com/intel-innersource/applications.ai.vpu-accelerators.vpux-plugin/pull/1310/files) (now reverted in master - which can be part of the reason of its re-appearance), they change /Zi -> /Z7, which results in object files that also contain full symbolic debug information, and this seems to cause different errors.

- **Remove the config for pdb directory to let each project use own vxxx.pdb file.**
On Windows, the current config makes all cmake projects use bin/intel64/Release directory as intermediate directory for pdb files. Multiple cl.exe and linker.exe randomly access the pdb file at same time and crash for this. Close the config can solve random error:
fatal error C1041: cannot open program database 'xxx\openvino\bin\intel64\Release\vc140.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS

**Ticket:** E#62173, E#58508

### CODE REVIEW

**Comment by DariaMityagina** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/dmityagi/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/dmityagi/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



  | /Zi -> /Z7   (current OV behavior) | /Zi ->   /Zi /FS (proposed in this PR)
-- | -- | --
Time: |   |  
Space: |   |  



</body>

</html>

**Comment by DariaMityagina** [comment]
<html>
<body>


  | /Zi -> /Z7 (current OV behavior) | /Zi -> /Zi /FS (proposed in this PR) | /Zi -> /Zi /FS + #13826
-- | -- | -- | --
Branch: | master | icv/dm/debug_build_flags | icv/dm/debug_build_separated_pdb
Link: | https://vpux-ci-vpuip.ir.intel.com/job/IE-Packages/job/try/job/OpenVINO-Windows10/21440/ | https://vpux-ci-vpuip.ir.intel.com/job/IE-Packages/job/try/job/OpenVINO-Windows10/21442/ |  https://vpux-ci-vpuip.ir.intel.com/job/IE-Packages/job/try/job/OpenVINO-Windows10/21443/
Time: |  |  | 
Package size: |  |  | 
Result: |  |  | 

CI-pipelines branch : [debug build without vpux_mlir_compiler](https://github.com/intel-innersource/applications.ai.vpu-accelerators.vpux-ci-pipelines/tree/icv/dm/debug_build_issues_without_vpux_mlir_compiler)

**Comment by DariaMityagina** [comment]
> Therefore, I see it this way:
the third way is more preferable (/Zi -> /Zi /FS + https://github.com/openvinotoolkit/openvino/pull/13826). The PR linked here lets each project use own vxx.pdb file.

This is why I added [832f0e521923ea3c45fc4cb7cf3d86ba52f93260](https://github.com/openvinotoolkit/openvino/pull/14651/commits/832f0e521923ea3c45fc4cb7cf3d86ba52f93260) to this PR.
Needs discussion.

**Comment by DariaMityagina** [comment]
@ilyachur @ilya-lavrenov @akladiev @evgenytalanin-intel @ababushk @OrestChura hi!
Could you please take a look?
Do you have any comments?
The discussion was started in the email thread.

**Review by ArtemySkrebkov — APPROVED** [review]

**Comment by OrestChura** [comment]
Hi!
Overall, I agree with the chosen direction - to use /Zi /FS + allow compiler use different .pdb's.

However, I have few comments.
- I'm not sure if it is needed to make /Zi -> /Zi /FS change. I think, if there is /Zi, then there should be /FS already. But it doesn't do anything bad, I think.
- However, flags can conflict when /Z7 and /Zi are in the same compiler call. That's why there is currently replacement /Zi -> /Z7. Therefore, I think, replacement /Z7 -> /Zi /FS has to be added too.

**Review by ilyachur — APPROVED** [review]

**Comment by DariaMityagina** [comment]
> Hi! Overall, I agree with the chosen direction - to use /Zi /FS + allow compiler use different .pdb's.
> 
> However, I have few comments.
> 
> * I'm not sure if it is needed to make /Zi -> /Zi /FS change. I think, if there is /Zi, then there should be /FS already. But it doesn't do anything bad, I think.
> * However, flags can conflict when /Z7 and /Zi are in the same compiler call. That's why there is currently replacement /Zi -> /Z7. Therefore, I think, replacement /Z7 -> /Zi /FS has to be added too.

Discussed in an email thread. We will look at the idea of ​​replacing `/Z7 -> /Zi /FS`. After experimenting, it can be added as part of another PR.
Thank you very much for your comments, @OrestChura !

**Pull request merged**
