### PR TITLE
Fix deformable_convolution

### PR DESCRIPTION
**Pull request by DingZhangIntel**
I think there is a error about the reference implementation of deformable_convolution.
The two parameters group and deformable_group is independent, and there are details about the parameter deformable_group in [MXNet](https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/nn/deformable_im2col.h#L230)
Suppose that the shape of input data is (1,6,5,5), the shape of filter is (2,3,3,3), the shape of the offset is (1,54,3,3), group is 2, deformable_group is 3. And an error will occur on line 256 when group_idx equals 1.

### CODE REVIEW

**Comment by ilyachur** [comment]
@DingZhangIntel Could you please add new tests?

**Comment by DingZhangIntel** [comment]
> @DingZhangIntel Could you please add new tests

**Comment by DingZhangIntel** [comment]
> @DingZhangIntel Could you please add new tests?

`const std::vector<InferenceEngine::Precision> netPrecisions = {InferenceEngine::Precision::FP32};
const std::vector<std::vector<size_t>> deformable_vals = {{1, 54, 28, 28}};
const std::vector<std::vector<size_t>> kernels = {{2, 3, 3, 3}};
const std::vector<std::vector<size_t>> strides = {{1, 1}};
const std::vector<std::vector<ptrdiff_t>> padBegins = {{0, 0}};
const std::vector<std::vector<ptrdiff_t>> padEnds = {{0, 0}};
const std::vector<std::vector<size_t>> dilations = {{1, 1}};
const std::vector<size_t> groups = {2};
const std::vector<size_t> defor_groups = {3};
const std::vector<size_t> numOutChannels = {2};

const auto deformableConv2DParams_ExplicitPadding = ::testing::Combine(      //
    ::testing::ValuesIn(deformable_vals),                                    //
    ::testing::ValuesIn(kernels), ::testing::ValuesIn(strides),              //
    ::testing::ValuesIn(padBegins), ::testing::ValuesIn(padEnds),            //
    ::testing::ValuesIn(dilations), ::testing::ValuesIn(groups),             //
    ::testing::ValuesIn(defor_groups), ::testing::ValuesIn(numOutChannels),  //
    ::testing::Values(ngraph::op::PadType::EXPLICIT));                       //

INSTANTIATE_TEST_CASE_P(                                                             //
    smoke_DeformableConvolution2D_ExplicitPadding, DeformableConvolutionLayerTest,   //
    ::testing::Combine(                                                              //
        deformableConv2DParams_ExplicitPadding, ::testing::ValuesIn(netPrecisions),  //
        ::testing::Values(InferenceEngine::Precision::UNSPECIFIED),                  //
        ::testing::Values(InferenceEngine::Precision::UNSPECIFIED),                  //
        ::testing::Values(InferenceEngine::Layout::ANY),                             //
        ::testing::Values(InferenceEngine::Layout::ANY),                             //
        ::testing::Values(std::vector<size_t>({1, 6, 30, 30})),                      //
        ::testing::Values(CommonTestUtils::DEVICE_CPU)),                             //
    DeformableConvolutionLayerTest::getTestCaseName);`
I think this is a simple test case to explain it, please check.

**Comment by DingZhangIntel** [comment]
> > @DingZhangIntel Could you please add new tests

I have added a single test case in the latest commit, please check.

**Comment by ilyachur** [comment]
> > > @DingZhangIntel Could you please add new tests
> 
> I have added a single test case in the latest commit, but I don't know whether this is what you want. If it is, I think it is a simple example to explain why I made these changes. If not, please contact me at any your time, I will give more details about this PR.

@DingZhangIntel Looks like new tests are failing.

**Comment by DingZhangIntel** [comment]
> > > > @DingZhangIntel Could you please add new tests
> > 
> > 
> > I have added a single test case in the latest commit, but I don't know whether this is what you want. If it is, I think it is a simple example to explain why I made these changes. If not, please contact me at any your time, I will give more details about this PR.
> 
> @DingZhangIntel Looks like new tests are failing.

I just made a little changes in the origin test file, but it still fails on CI. I think it's a little weird. I will appreciate it if you can check these changes at your convenience.  please contact me at any your time, thanks.

**Comment by ilyachur** [comment]
> > > > > @DingZhangIntel Could you please add new tests
> > > 
> > > 
> > > I have added a single test case in the latest commit, but I don't know whether this is what you want. If it is, I think it is a simple example to explain why I made these changes. If not, please contact me at any your time, I will give more details about this PR.
> > 
> > 
> > @DingZhangIntel Looks like new tests are failing.
> 
> I just made a little changes in the origin test file, but it still fails on CI. I think it's a little weird. I will very appreciate it if you can check these changes at your convenience. I will keep looking into this issue, thanks.

As I see the CPU plugin cannot create a network for your tests:
```
[ RUN      ] smoke_DeformableConvolution2D_DeformableGroups_ExplicitPadding/DeformableConvolutionLayerTest.CompareWithRefs/IS=(1.6.30.30)_DV(1.54.28.28)_K(2.3.3.3)_S(1.1)_PB(0.0)_PE(0.0)_D=(1.1)_G=2_DG=3_O=5_AP=explicit_netPRC=I32_inPRC=UNSPECIFIED_outPRC=UNSPECIFIED_inL=ANY_outL=ANY_trgDev=CPU

MEM_USAGE=79613952KB
C:\a\1\openvino\inference-engine\tests\functional\shared_test_classes\src\base\layer_test_utils.cpp(57): error: could not construct a memory descriptor using a format tag
[  FAILED  ] smoke_DeformableConvolution2D_DeformableGroups_ExplicitPadding/DeformableConvolutionLayerTest.CompareWithRefs/IS=(1.6.30.30)_DV(1.54.28.28)_K(2.3.3.3)_S(1.1)_PB(0.0)_PE(0.0)_D=(1.1)_G=2_DG=3_O=5_AP=explicit_netPRC=I32_inPRC=UNSPECIFIED_outPRC=UNSPECIFIED_inL=ANY_outL=ANY_trgDev=CPU (13 ms)
```

**Comment by DingZhangIntel** [comment]
> > > > > > @DingZhangIntel Could you please add new tests
> > > > 
> > > > 
> > > > I have added a single test case in the latest commit, but I don't know whether this is what you want. If it is, I think it is a simple example to explain why I made these changes. If not, please contact me at any your time, I will give more details about this PR.
> > > 
> > > 
> > > @DingZhangIntel Looks like new tests are failing.
> > 
> > 
> > I just made a little changes in the origin test file, but it still fails on CI. I think it's a little weird. I will very appreciate it if you can check these changes at your convenience. I will keep looking into this issue, thanks.
> 
> As I see the CPU plugin cannot create a network for your tests:
> 
> ```
> [ RUN      ] smoke_DeformableConvolution2D_DeformableGroups_ExplicitPadding/DeformableConvolutionLayerTest.CompareWithRefs/IS=(1.6.30.30)_DV(1.54.28.28)_K(2.3.3.3)_S(1.1)_PB(0.0)_PE(0.0)_D=(1.1)_G=2_DG=3_O=5_AP=explicit_netPRC=I32_inPRC=UNSPECIFIED_outPRC=UNSPECIFIED_inL=ANY_outL=ANY_trgDev=CPU
> 
> MEM_USAGE=79613952KB
> C:\a\1\openvino\inference-engine\tests\functional\shared_test_classes\src\base\layer_test_utils.cpp(57): error: could not construct a memory descriptor using a format tag
> [  FAILED  ] smoke_DeformableConvolution2D_DeformableGroups_ExplicitPadding/DeformableConvolutionLayerTest.CompareWithRefs/IS=(1.6.30.30)_DV(1.54.28.28)_K(2.3.3.3)_S(1.1)_PB(0.0)_PE(0.0)_D=(1.1)_G=2_DG=3_O=5_AP=explicit_netPRC=I32_inPRC=UNSPECIFIED_outPRC=UNSPECIFIED_inL=ANY_outL=ANY_trgDev=CPU (13 ms)
> ```

I just tested it in my local openvino repo and found that if i set the parameter group equals 2, the test will fail. And if I set the parameter group equals 1, the test will work. please check.

**Comment by DingZhangIntel** [comment]
> > > > > > > @DingZhangIntel Could you please add new tests
> > > > > 
> > > > > 
> > > > > I have added a single test case in the latest commit, but I don't know whether this is what you want. If it is, I think it is a simple example to explain why I made these changes. If not, please contact me at any your time, I will give more details about this PR.
> > > > 
> > > > 
> > > > @DingZhangIntel Looks like new tests are failing.
> > > 
> > > 
> > > I just made a little changes in the origin test file, but it still fails on CI. I think it's a little weird. I will very appreciate it if you can check these changes at your convenience. I will keep looking into this issue, thanks.
> > 
> > 
> > As I see the CPU plugin cannot create a network for your tests:
> > ```
> > [ RUN      ] smoke_DeformableConvolution2D_DeformableGroups_ExplicitPadding/DeformableConvolutionLayerTest.CompareWithRefs/IS=(1.6.30.30)_DV(1.54.28.28)_K(2.3.3.3)_S(1.1)_PB(0.0)_PE(0.0)_D=(1.1)_G=2_DG=3_O=5_AP=explicit_netPRC=I32_inPRC=UNSPECIFIED_outPRC=UNSPECIFIED_inL=ANY_outL=ANY_trgDev=CPU
> > 
> > MEM_USAGE=79613952KB
> > C:\a\1\openvino\inference-engine\tests\functional\shared_test_classes\src\base\layer_test_utils.cpp(57): error: could not construct a memory descriptor using a format tag
> > [  FAILED  ] smoke_DeformableConvolution2D_DeformableGroups_ExplicitPadding/DeformableConvolutionLayerTest.CompareWithRefs/IS=(1.6.30.30)_DV(1.54.28.28)_K(2.3.3.3)_S(1.1)_PB(0.0)_PE(0.0)_D=(1.1)_G=2_DG=3_O=5_AP=explicit_netPRC=I32_inPRC=UNSPECIFIED_outPRC=UNSPECIFIED_inL=ANY_outL=ANY_trgDev=CPU (13 ms)
> > ```
> 
> I just tested it in my local openvino repo and found that if i set the parameter group equals 2, the test will fail. And if I set the parameter group equals 1, the test will work. please check.

I tested it again and found that if I set set the parameter group greater than 1, the test will fail. Please check.

**Comment by DingZhangIntel** [comment]
> > > > > > > > @DingZhangIntel Could you please add new tests
> > > > > > 
> > > > > > 
> > > > > > I have added a single test case in the latest commit, but I don't know whether this is what you want. If it is, I think it is a simple example to explain why I made these changes. If not, please contact me at any your time, I will give more details about this PR.
> > > > > 
> > > > > 
> > > > > @DingZhangIntel Looks like new tests are failing.
> > > > 
> > > > 
> > > > I just made a little changes in the origin test file, but it still fails on CI. I think it's a little weird. I will very appreciate it if you can check these changes at your convenience. I will keep looking into this issue, thanks.
> > > 
> > > 
> > > As I see the CPU plugin cannot create a network for your tests:
> > > ```
> > > [ RUN      ] smoke_DeformableConvolution2D_DeformableGroups_ExplicitPadding/DeformableConvolutionLayerTest.CompareWithRefs/IS=(1.6.30.30)_DV(1.54.28.28)_K(2.3.3.3)_S(1.1)_PB(0.0)_PE(0.0)_D=(1.1)_G=2_DG=3_O=5_AP=explicit_netPRC=I32_inPRC=UNSPECIFIED_outPRC=UNSPECIFIED_inL=ANY_outL=ANY_trgDev=CPU
> > > 
> > > MEM_USAGE=79613952KB
> > > C:\a\1\openvino\inference-engine\tests\functional\shared_test_classes\src\base\layer_test_utils.cpp(57): error: could not construct a memory descriptor using a format tag
> > > [  FAILED  ] smoke_DeformableConvolution2D_DeformableGroups_ExplicitPadding/DeformableConvolutionLayerTest.CompareWithRefs/IS=(1.6.30.30)_DV(1.54.28.28)_K(2.3.3.3)_S(1.1)_PB(0.0)_PE(0.0)_D=(1.1)_G=2_DG=3_O=5_AP=explicit_netPRC=I32_inPRC=UNSPECIFIED_outPRC=UNSPECIFIED_inL=ANY_outL=ANY_trgDev=CPU (13 ms)
> > > ```
> > 
> > 
> > I just tested it in my local openvino repo and found that if i set the parameter group equals 2, the test will fail. And if I set the parameter group equals 1, the test will work. please check.
> 
> I tested it again and found that if I set the parameter group greater than 1, the test will fail. Please check.

I changed the tests back and added a single test case to explain why I made these changes in ref implementation, and the single test case will produce the mismatch results with MXNet. The error will occur on line 256 of the origin ref implementation, the offset of the variable `group_offsets` is too big. Please check.

**Comment by ilyachur** [comment]
@itikhono Please have a look.

**Comment by itikhono** [comment]
hello @DingZhangIntel,

As understood, you encounted 2 issues:
- CPU plugin doesn't work with group = 2, deformable_group = 3 attributes of DeformableConvolution. I re-checked a backlog and found the similar ticket (cpu impl doesn't work for group > 1),  I guess the bug will be fixed in this Release.
- a bug in the reference implementation: thanks for your fix, it looks correct, for some reason the current reference works with group = 2, deformable_group = 2 attributes, so we didn't find the problem earlier, it reproducible for deformable_group >2

**Review by itikhono — APPROVED** [review]

**Review by ilyachur — APPROVED** [review]

**Pull request merged**
