### PR TITLE
[GPU] Use ASSERT_* instead of EXPECT_* in most of the cases

### PR DESCRIPTION
**Pull request by vladimir-paramuzov**
### Details:
 - Use ASSERT macro in cldnn unit tests to avoid huge log files in case of massive failures

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
> Use ASSERT macro in cldnn unit tests to avoid huge log files in case of massive failures

why do we have massive failures? If it's connected with GPU health, maybe it's better to add GPU health check at the beginning of the tests and exit earlier?

**Comment by vladimir-paramuzov** [comment]
@ilya-lavrenov Massive failures may occur during development (enabling of new platforms for example) and log file in some cases >10GB while most of it's content is pretty much useless. Also, non-fatal assertion may lead to invalid memory access in case of failures, so it must be used carefully

**Review by sshlyapn — COMMENTED** [review]
Looks good to me
But there are also about 120 `EXPECT_NEAR` macro usages - are you going to replace them too?

**Comment by vladimir-paramuzov** [comment]
@sshlyapn replaced

**Review by sshlyapn — APPROVED** [review]

**Review by yeonbok — APPROVED** [review]

**Pull request merged**
