### PR TITLE
Docs: Benchmark Tool doc changes

### PR DESCRIPTION
**Pull request by EdjeElectronics**
This pull request makes a minor update to the Benchmark Tool C++ and Benchmark Tool Python pages. The "sample output from running benchmark_app" is updated with actual output from running the 2022.1 version of benchmark_app. Pawel requested that the full output be shown rather than just a portion of the output.

I removed the "sample static output" and "sample dynamic output" and just put the full output for a static network. Dynamic networks aren't explained anywhere else on the page, so I think showing the sample output for a dynamic network will just confuse the reader. If you disagree, let me know, and I'll be happy to add the sample dynamic output as well!

### Details:
 - see above

### Tickets:
 N/A

### CODE REVIEW

**Review by xu-yuan1 — APPROVED** [review]

**Comment by xu-yuan1** [comment]
Thanks Evan! I don't see any issues, but I'm adding @kblaszczak-intel to double-check: do we have/need someone from dev to review this?

**Review by kblaszczak-intel — APPROVED** [review]

**Comment by xu-yuan1** [comment]
Hi @EdjeElectronics , I think it's better to still have the sample for dynamic network. Could you help add it? While adding, could you use the tab format for the two samples so that the article won't get longer?
And we want to have this improvement for 2022.2 and master branches, but since the samples include version number (2022.1.0.xxxx), do you think it's still fine?

**Comment by EdjeElectronics** [comment]
Hi @xu-yuan1 , okay, I can add the dynamic network output too. Unfortunately, I can't figure out how to run a dynamic network with benchmark_app! I'm not familiar with how they work. Can you help me figure out the right model and command to use to run a dynamic network with benchmark_app?

I tried using the [asl-recognition-0004](https://docs.openvino.ai/latest/omz_models_model_asl_recognition_0004.html) OMZ model and this command:
```
benchmark_app -m omz_models/intel/asl-recognition-0004/FP16/asl-recognition-0004.xml -d CPU -shape [-1,3,16,224,224] -data_shape [1,3,224,224][2,3,224,224][4,3,224,224] -progress
```
I was hoping this would benchmark the model with batch size 1, 2, and 4. However, I didn't get the expected output. I was expecting it to report latency for each data shape group (as shown in the existing Dynamic network sample output).
```
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading Inference Engine
[ INFO ] OpenVINO: OpenVINO Runtime version ......... 2022.1.0
[ INFO ] Build ........... 2022.1.0-7019-cdb9bec7210-releases/2022/1
[ INFO ]
[ INFO ] Device info:
[ INFO ] CPU
[ INFO ] openvino_intel_cpu_plugin version ......... 2022.1.0
[ INFO ] Build ........... 2022.1.0-7019-cdb9bec7210-releases/2022/1
[ INFO ]
[ INFO ]
[Step 3/11] Setting device configuration
[ WARNING ] Performance hint was not explicitly specified in command line. Device(CPU) performance hint will be set to THROUGHPUT.
[Step 4/11] Reading network files
[ INFO ] Loading network files
[ INFO ] Read network took 18.48 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Number of test configurations is calculated basing on -data_shape parameter
[ INFO ] Reshaping network: 'input': {?,3,16,224,224}
[ INFO ] Reshape network took 2.21 ms
[Step 6/11] Configuring input of the model
Network inputs:
    input (node: input) : f32 / [N,C,D,H,W]
Network outputs:
    output (node: output) : f32 / [...]
[Step 7/11] Loading the model to the device
[ INFO ] Load network took 153.47 ms
[Step 8/11] Setting optimal runtime parameters
[ INFO ] Device: CPU
[ INFO ]   { NETWORK_NAME , torch-jit-export }
[ INFO ]   { OPTIMAL_NUMBER_OF_INFER_REQUESTS , 5 }
[ INFO ]   { NUM_STREAMS , 5 }
[ INFO ]   { AFFINITY , HYBRID_AWARE }
[ INFO ]   { INFERENCE_NUM_THREADS , 0 }
[ INFO ]   { PERF_COUNT , NO }
[ INFO ]   { INFERENCE_PRECISION_HINT , f32 }
[ INFO ]   { PERFORMANCE_HINT , THROUGHPUT }
[ INFO ]   { PERFORMANCE_HINT_NUM_REQUESTS , 0 }
[Step 9/11] Creating infer requests and preparing input blobs with data
[ INFO ] Test Config 0
[ INFO ] input  ([N,C,D,H,W], f32, {1, 3, 16, 224, 224}, dyn:{?,3,16,224,224}): random (binary data is expected)
[ INFO ] Test Config 1
[ INFO ] input  ([N,C,D,H,W], f32, {2, 3, 16, 224, 224}, dyn:{?,3,16,224,224}): random (binary data is expected)
[ INFO ] Test Config 2
[ INFO ] input  ([N,C,D,H,W], f32, {4, 3, 16, 224, 224}, dyn:{?,3,16,224,224}): random (binary data is expected)
[Step 10/11] Measuring performance (Start inference asynchronously, 5 inference requests, limits: 60000 ms duration)
[ INFO ] BENCHMARK IS IN FULL MODE.
[ INFO ] Inputs setup stage will be included in performance measurements.
[ INFO ] First inference took 63.43 ms
Progress: [....................] 100% done

[Step 11/11] Dumping statistics report
[ INFO ] Count:      1925 iterations
[ INFO ] Duration:   60322.39 ms
[ INFO ] Latency:
[ INFO ]        Median:     131.98 ms
[ INFO ]        Average:    156.30 ms
[ INFO ]        Min:        54.89 ms
[ INFO ]        Max:        576.28 ms
[ INFO ] Throughput: 74.43 FPS
```

**Review by ilya-lavrenov — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
@nkogteva please, have a look

**Comment by xu-yuan1** [comment]
@nkogteva Just to be more specific, could you help provide the sample code of dynamic network output? 
And is there any difference between 2022.1 and 2022.2? If not, I suppose we can use the same sample code for 2022.2, even without changing the version number in it. Thanks.

**Review by nkogteva — APPROVED** [review]

**Comment by nkogteva** [comment]
> @nkogteva Just to be more specific, could you help provide the sample code of dynamic network output? And is there any difference between 2022.1 and 2022.2? If not, I suppose we can use the same sample code for 2022.2, even without changing the version number in it. Thanks.

I don't know whether there is a difference between 2022.1 and 2022.2. It has to be checked. 

But as far as I see from current README `-data_shape [1, 3, 224, 224],[1, 3, 448, 448]` was used as example. But it can't be inputs for `asl-recognition-0004` due to shape mismatch. So we need update instructions anyway to be aligned with previous steps.

**Comment by nkogteva** [comment]
Also I noticed that `-progress` is used in intstructions. This must be removed, because progress bar kills performance. We should not recomend to use it

**Comment by EdjeElectronics** [comment]
Hi @nkogteva and @xu-yuan1, I apologize for the slow response on this one.

I still can't figure out how to get dynamic shapes to work with benchmark_app. I tried using the [googlenet-v1 model](https://docs.openvino.ai/latest/omz_models_model_googlenet_v1.html) (which is what was used in the old instructions) and specifying `-shape [1,3,?,?] -data_shape [1,3,224,224][1,3,448,448]`. Here is the full command I used:
```
./benchmark_app -m public/googlenet-v1/FP16/googlenet-v1.xml -d CPU -shape [1,3,?,?] -data_shape [1,3,224,224][1,3,448,448]
```

Here is the resulting output. It still only prints one set of results. How can I get it to print results for `[1,3,224,224]` and `[1,3,448,448]` shapes like it does in the old Dynamic network example output?

```
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO: OpenVINO Runtime version ......... 2022.2.0
[ INFO ] Build ........... 2022.2.0-7713-af16ea1d79a-releases/2022/2
[ INFO ] 
[ INFO ] Device info: 
[ INFO ] CPU
[ INFO ] openvino_intel_cpu_plugin version ......... 2022.2.0
[ INFO ] Build ........... 2022.2.0-7713-af16ea1d79a-releases/2022/2
[ INFO ] 
[ INFO ] 
[Step 3/11] Setting device configuration
[ WARNING ] Performance hint was not explicitly specified in command line. Device(CPU) performance hint will be set to THROUGHPUT.
[Step 4/11] Reading network files
[ INFO ] Loading network files
[ INFO ] Read network took 22.48 ms
[ INFO ] Original network I/O parameters:
Network inputs:
    data (node: data) : f32 / [N,C,H,W]
Network outputs:
    prob (node: prob) : f32 / [...]
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Number of test configurations is calculated basing on -data_shape parameter
[ INFO ] Reshaping network: 'data': {1,3,?,?}
[ INFO ] Reshape network took 3.27 ms
[Step 6/11] Configuring input of the model
Network inputs:
    data (node: data) : u8 / [N,C,H,W]
Network outputs:
    prob (node: prob) : f32 / [...]
[Step 7/11] Loading the model to the device
[ INFO ] Load network took 108.20 ms
[Step 8/11] Setting optimal runtime parameters
[ INFO ] Device: CPU
[ INFO ]   { NETWORK_NAME , GoogleNet }
[ INFO ]   { OPTIMAL_NUMBER_OF_INFER_REQUESTS , 4 }
[ INFO ]   { NUM_STREAMS , 4 }
[ INFO ]   { AFFINITY , CORE }
[ INFO ]   { INFERENCE_NUM_THREADS , 0 }
[ INFO ]   { PERF_COUNT , NO }
[ INFO ]   { INFERENCE_PRECISION_HINT , f32 }
[ INFO ]   { PERFORMANCE_HINT , THROUGHPUT }
[ INFO ]   { PERFORMANCE_HINT_NUM_REQUESTS , 0 }
[Step 9/11] Creating infer requests and preparing input blobs with data
[ INFO ] Test Config 0
[ INFO ] data  ([N,C,H,W], u8, {1, 3, 224, 224}, dyn:{1,3,?,?}):	random (image is expected)
[ INFO ] Test Config 1
[ INFO ] data  ([N,C,H,W], u8, {1, 3, 448, 448}, dyn:{1,3,?,?}):	random (image is expected)
[Step 10/11] Measuring performance (Start inference asynchronously, 4 inference requests, limits: 60000 ms duration)
[ INFO ] BENCHMARK IS IN FULL MODE.
[ INFO ] Inputs setup stage will be included in performance measurements.
[ INFO ] First inference took 25.45 ms

[Step 11/11] Dumping statistics report
[ INFO ] Count:      2264 iterations
[ INFO ] Duration:   60186.89 ms
[ INFO ] Latency: 
[ INFO ] 	Median:     107.80 ms
[ INFO ] 	Average:    106.21 ms
[ INFO ] 	Min:        26.80 ms
[ INFO ] 	Max:        247.01 ms
[ INFO ] Throughput: 37.62 FPS
```

**Comment by nkogteva** [comment]
> Hi @nkogteva and @xu-yuan1, I apologize for the slow response on this one.
> 
> I still can't figure out how to get dynamic shapes to work with benchmark_app. I tried using the [googlenet-v1 model](https://docs.openvino.ai/latest/omz_models_model_googlenet_v1.html) (which is what was used in the old instructions) and specifying `-shape [1,3,?,?] -data_shape [1,3,224,224][1,3,448,448]`. Here is the full command I used:
> 
> ```
> ./benchmark_app -m public/googlenet-v1/FP16/googlenet-v1.xml -d CPU -shape [1,3,?,?] -data_shape [1,3,224,224][1,3,448,448]
> ```
> 
> Here is the resulting output. It still only prints one set of results. How can I get it to print results for `[1,3,224,224]` and `[1,3,448,448]` shapes like it does in the old Dynamic network example output?
> 
> ```
> [Step 1/11] Parsing and validating input arguments
> [ INFO ] Parsing input parameters
> [Step 2/11] Loading OpenVINO Runtime
> [ INFO ] OpenVINO: OpenVINO Runtime version ......... 2022.2.0
> [ INFO ] Build ........... 2022.2.0-7713-af16ea1d79a-releases/2022/2
> [ INFO ] 
> [ INFO ] Device info: 
> [ INFO ] CPU
> [ INFO ] openvino_intel_cpu_plugin version ......... 2022.2.0
> [ INFO ] Build ........... 2022.2.0-7713-af16ea1d79a-releases/2022/2
> [ INFO ] 
> [ INFO ] 
> [Step 3/11] Setting device configuration
> [ WARNING ] Performance hint was not explicitly specified in command line. Device(CPU) performance hint will be set to THROUGHPUT.
> [Step 4/11] Reading network files
> [ INFO ] Loading network files
> [ INFO ] Read network took 22.48 ms
> [ INFO ] Original network I/O parameters:
> Network inputs:
>     data (node: data) : f32 / [N,C,H,W]
> Network outputs:
>     prob (node: prob) : f32 / [...]
> [Step 5/11] Resizing network to match image sizes and given batch
> [ INFO ] Number of test configurations is calculated basing on -data_shape parameter
> [ INFO ] Reshaping network: 'data': {1,3,?,?}
> [ INFO ] Reshape network took 3.27 ms
> [Step 6/11] Configuring input of the model
> Network inputs:
>     data (node: data) : u8 / [N,C,H,W]
> Network outputs:
>     prob (node: prob) : f32 / [...]
> [Step 7/11] Loading the model to the device
> [ INFO ] Load network took 108.20 ms
> [Step 8/11] Setting optimal runtime parameters
> [ INFO ] Device: CPU
> [ INFO ]   { NETWORK_NAME , GoogleNet }
> [ INFO ]   { OPTIMAL_NUMBER_OF_INFER_REQUESTS , 4 }
> [ INFO ]   { NUM_STREAMS , 4 }
> [ INFO ]   { AFFINITY , CORE }
> [ INFO ]   { INFERENCE_NUM_THREADS , 0 }
> [ INFO ]   { PERF_COUNT , NO }
> [ INFO ]   { INFERENCE_PRECISION_HINT , f32 }
> [ INFO ]   { PERFORMANCE_HINT , THROUGHPUT }
> [ INFO ]   { PERFORMANCE_HINT_NUM_REQUESTS , 0 }
> [Step 9/11] Creating infer requests and preparing input blobs with data
> [ INFO ] Test Config 0
> [ INFO ] data  ([N,C,H,W], u8, {1, 3, 224, 224}, dyn:{1,3,?,?}):	random (image is expected)
> [ INFO ] Test Config 1
> [ INFO ] data  ([N,C,H,W], u8, {1, 3, 448, 448}, dyn:{1,3,?,?}):	random (image is expected)
> [Step 10/11] Measuring performance (Start inference asynchronously, 4 inference requests, limits: 60000 ms duration)
> [ INFO ] BENCHMARK IS IN FULL MODE.
> [ INFO ] Inputs setup stage will be included in performance measurements.
> [ INFO ] First inference took 25.45 ms
> 
> [Step 11/11] Dumping statistics report
> [ INFO ] Count:      2264 iterations
> [ INFO ] Duration:   60186.89 ms
> [ INFO ] Latency: 
> [ INFO ] 	Median:     107.80 ms
> [ INFO ] 	Average:    106.21 ms
> [ INFO ] 	Min:        26.80 ms
> [ INFO ] 	Max:        247.01 ms
> [ INFO ] Throughput: 37.62 FPS
> ```

@EdjeElectronics Are you asking about latency per group? If yes, please look at the `-pcseq` flag. This detailed latency statistics is disabled by default, because it can affect overall performance.

**Comment by EdjeElectronics** [comment]
Thank you, I got it figured out! I changed the example to use `googlenet-v1` and updated the output for both static and dynamic networks.

This pull request is currently targeted at the `2022/1` branch, which I know is outdated. Should I rebase the pull request to the `master` branch?

**Comment by EdjeElectronics** [comment]
> I think we should change target branch to `master`. If it will be easy create a new PR, let's do it. Just to be sure: benchmark_app outputs were get from master?

Actually, I used 2022.2 to get the benchmark_app outputs. Should I do a PR to the 2022/2 branch instead?

**Comment by nkogteva** [comment]
> > I think we should change target branch to `master`. If it will be easy create a new PR, let's do it. Just to be sure: benchmark_app outputs were get from master?
> 
> Actually, I used 2022.2 to get the benchmark_app outputs. Should I do a PR to the 2022/2 branch instead?

I don't know who is requester of this feature and whether it is actually needed in release branch. I think we just need to fix in master.

**Comment by EdjeElectronics** [comment]
Okay, sounds good! I'll recreate this as a new PR to the master branch. I'll close this PR once the other one is created.

Thanks for your help!

**Comment by EdjeElectronics** [comment]
@xu-yuan1 @nkogteva I created a new PR at #13555 . I will go ahead and close this one.

**Pull request closed without merging**
