### PR TITLE
Support LATENCY and THROUGHPUT config for AUTO plugin

### PR DESCRIPTION
**Pull request by mashoujiang**
### Tickets:
 - *CVS-55563*

### CODE REVIEW

**Comment by myshevts** [comment]
I see no latency and throughput in the code (is the PR misnamed?)

**Comment by mashoujiang** [comment]
> I see no latency and throughput in the code (is the PR misnamed?)

Yes, Maxim, this PR is trying to address ticket CVS-55563, which introduces too less information about these two work mode. 
I just add SetConfig() for this two config hint here. 
As I know no device plugin support these two config, so I am not clear should I pass down these two config to device plugin? or set streaming config like *_THROUGHPUT_STREAMS  to device plugin?
Wanglei is on vacation, could you please add more comments to the CVS-55563? Thanks!

**Comment by mashoujiang** [comment]
@wangleis please help to review

**Comment by wangleis** [comment]
@mashoujiang Please hold this PR first. Maxim will merge patch for overall OpenVINO hints. Let's align the hints format with Maxim.

**Pull request closed without merging**
