### PR TITLE
Avoid using xmm0 for input to store_emitter

### PR DESCRIPTION
**Pull request by usstq**
### Details:
 - *Avoid using xmm0 for input to store_emitter in jit_uni_roi_pooling_kernel_f32*

### Tickets:
 - *59358*

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@yury-intel please take a look

**Review by yury-intel — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
@usstq Could you please rebase the PR on latest master and I will merge it?

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
@usstq the PR is still red. Could you please rebase it one more time?

**Comment by usstq** [comment]
@dmitry-gorokhov I cannot make the CI test green by simply rebuild, it seems to be not related to my code.

**Comment by dmitry-gorokhov** [comment]
@usstq Seems like you merged not the latest state of master (5 days from now). Lets rebase on current master. Should help I guess.

**Comment by dmitry-gorokhov** [comment]
@usstq I see conflicts here. Could you please rebase one more time? Sorry for inconvenience

**Comment by usstq** [comment]
@dmitry-gorokhov Done, Sorry for late response!

**Pull request merged**
