### PR TITLE
Update ConstantFolding transformation to support Gather with dynamic input

### PR DESCRIPTION
**Pull request by mateusztabaka**
Ticket: 101315

### CODE REVIEW

**Review by praasz — APPROVED** [review]
Is it OK from my perspective.
What about performance comment from  https://github.com/openvinotoolkit/openvino/pull/16973#issuecomment-1512711723 ?

**Comment by mateusztabaka** [comment]
> Is it OK from my perspective. What about performance comment from [#16973 (comment)](https://github.com/openvinotoolkit/openvino/pull/16973#issuecomment-1512711723) ?

@itikhono do you have any data on this maybe?

**Review by itikhono — APPROVED** [review]

**Comment by itikhono** [comment]
> > Is it OK from my perspective. What about performance comment from [#16973 (comment)](https://github.com/openvinotoolkit/openvino/pull/16973#issuecomment-1512711723) ?
> 
> @itikhono do you have any data on this maybe?

Unfortunately, I don't have any. I will ask our validation team to run the checks

**Comment by itikhono** [comment]
I believe https://github.com/openvinotoolkit/openvino/pull/16973 is a correct solution for this bug.
We can close this PR after merging the PR above.

**Pull request closed without merging**
