### PR TITLE
Fixing error returned by add_outputs_recursive transformation for GNMT

### PR DESCRIPTION
**Pull request by sadolini**
Root cause analysis: 
Error was raised because several internal nodes have the same internal_id. These nodes were added during transformation. 

Solution: 
Find out that function that add new nodes change max_internal_layer_id but doesn't return it back. Also during check I have found that transformation always return only 1 added Result, but for GNMT last node is Split with 2 outputs, so 2 Results are added. So fixed finding of newly added results.

Ticket: 73397

Code:
* [x]  Comments
* [x]  Code style (PEP8)
* [x]  Transformation generates reshape-able IR **NA small fix in existing transformation**
* [x]  Transformation preserves original framework node names **NA small fix in existing transformation**

Validation:
* [x]  Unit tests
* [x]  Framework operation tests **NA small fix in existing transformation**
* [x]  Transformation tests **NA small fix in existing transformation**
* [x]  Model Optimizer IR Reader check **NA small fix in existing transformation**

Documentation:
* [x]  Supported frameworks operations list **NA small fix in existing transformation**
* [x]  Guide on how to convert the **public** model **NA small fix in existing transformation**
* [x]  User guide update **NA small fix in existing transformation**

### CODE REVIEW

**Review by vgavrilo — APPROVED** [review]

**Review by l-bat — APPROVED** [review]

**Review by popovaan — APPROVED** [review]

**Review by evolosen — APPROVED** [review]

**Review by rkazants — COMMENTED** [review]
Looks good to me.

**Comment by rkazants** [comment]
@l-bat, could you please validate this PR on all models required this transformation? Is it possible? Thanks!

**Comment by rkazants** [comment]
@sadolini, could you please rebase it? I will merge it then

**Comment by sadolini** [comment]
> @sadolini, could you please rebase it? I will merge it then

done

**Review by rkazants — APPROVED** [review]

**Pull request merged**
