### PR TITLE
[IE VPU] update firmware version

### PR DESCRIPTION
**Pull request by KorA6**
#-46181
**What's changed:** 
Little fixes in EltWise kernel

### CODE REVIEW

**Comment by gladilov-gleb** [comment]
@KorA6 check [this](https://github.com/openvinotoolkit/openvino/pull/4157) out. I update firmware there as well. If it contains changes you need - you can close this PR

**Comment by KorA6** [comment]
> @KorA6 check [this](https://github.com/openvinotoolkit/openvino/pull/4157) out. I update firmware there as well. If it contains changes you need - you can close this PR

@gladilov-gleb  
Thanks, but #4157 doesn't contain changes whatever I need.

**Comment by gladilov-gleb** [comment]
> > @KorA6 check [this](https://github.com/openvinotoolkit/openvino/pull/4157) out. I update firmware there as well. If it contains changes you need - you can close this PR
> 
> @gladilov-gleb
> Thanks, but #4157 doesn't contain changes whatever I need.

Which changes exactly do you need? I cannot find them from ticket.

**Comment by KorA6** [comment]
> > > @KorA6 check [this](https://github.com/openvinotoolkit/openvino/pull/4157) out. I update firmware there as well. If it contains changes you need - you can close this PR
> > 
> > 
> > @gladilov-gleb
> > Thanks, but #4157 doesn't contain changes whatever I need.
> 
> Which changes exactly do you need? I cannot find them from ticket.

I added info about this in the ticket.

**Comment by KorA6** [comment]
The new firmware version will be merged in #4421

**Pull request closed without merging**
