### PR TITLE
Enable android arm ngraph build tests

### PR DESCRIPTION
**Pull request by allnes**
Failed android arm build with cmake key `-DENABLE_TESTS=ON`

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Why tests are failed? Looks like we just need to fix them

**Comment by allnes** [comment]
> Why tests are failed? Looks like we just need to fix them 

Unit tests can't build. Because ngraph unit tests was disabled for Android. This request correct it.

**Comment by ilya-lavrenov** [comment]
> Unit tests couldn't build. Because ngraph unit tests was disabled for Android. This request correct it.

your request disables unit tests on ARM / ARM64, but they can be built

**Comment by allnes** [comment]
I'm sorry, the error has stopped reproducing.

**Pull request closed without merging**
