### PR TITLE
[TF FE] Saved Model improvements

### PR DESCRIPTION
**Pull request by gkrivor**
### Details:
 - Added pre-commit tests for Saved Model
 - Applied shared_ptr when it possible
 - Added names to input/output ports
 - Removed internal input saver_filename
 - Fixed behavior in case we have custom parameters
 - Fixed issues with VariableV2 in freezed models

### Tickets:
 - ...

### CODE REVIEW

**Comment by gkrivor** [comment]
First of all, tests aren't a subject of this PR. We have corresponding tasks for later implementation.

Second, if you somehow missed, misalignment in names was found... by existing e2e test.

**Review by rkazants — CHANGES_REQUESTED** [review]
please provide tests

**Comment by gkrivor** [comment]
I'm not sure I can decide is it possible to share or not. Check with your manager, please.

**Comment by akladiev** [comment]
This PR will be closed in 2 weeks in case of no activity.

**Comment by akladiev** [comment]
This PR was closed because it has been stalled for 2 week with no activity.

**Pull request closed without merging**
