### PR TITLE
Support for Yolov4 sample

### PR DESCRIPTION
**Pull request by 942860759**
Support for yolov4 sample, use author's resize method and yolov4 post-processing

### CODE REVIEW

**Comment by mryzhov** [comment]
@vladimir-dudnik could you please take a look at the PR, maybe we can include it to OMZ? 
@942860759 we are trying to keep in the samples only openVINO API showcases, such demo is part of OMZ scope

**Comment by 942860759** [comment]
@vladimir-dudnik I submit this sample, and create a merge in omz.
https://github.com/openvinotoolkit/open_model_zoo/pull/1798

**Comment by vladimir-dudnik** [comment]
@942860759 there were number of changes since OpenVINO 2021.1. We have implemented support for YoloV4 and YoloV4-Tiny models in Open Model Zoo C++ and Python demos, please take a look at them. I'm going to close this PR (as we do not want to duplicate similar functionality in IE Samples)

**Comment by vladimir-dudnik** [comment]
closing this in favour OMZ demos

**Pull request closed without merging**
