### PR TITLE
[GPU] Support rope for glm4v

### PR DESCRIPTION
**Pull request by zhaohb**
support rope kernel for glm4v

**Tickets:** CVS-157422

### CODE REVIEW

**Comment by sammysun0711** [comment]
@ahnyoung-paul, @isanghao @yeonbok @itikhono, could you please kindly review this PR. Thanks!

**Review by zhangYiIntel — CHANGES_REQUESTED** [review]
Please add test for this new pattern at
src/common/transformations/tests/common_optimizations/fuse_rotary_positional_embeddings.cpp

**Comment by p-durandin** [comment]
build_jenkins

**Comment by zhaohb** [comment]
> Please add test for this new pattern at src/common/transformations/tests/common_optimizations/fuse_rotary_positional_embeddings.cpp

Hi @zhangYiIntel Test cases have been added.

**Review by zhangYiIntel — APPROVED** [review]
LGTM, please go head to make CI green

**Comment by sammysun0711** [comment]
build_jenkins

**Comment by FionaZZ92** [comment]
@itikhono Can you please help to review and check able to merge.

**Comment by sammysun0711** [comment]
build_jenkins

**Comment by sammysun0711** [comment]
build_jenkins

**Comment by sammysun0711** [comment]
build_jenkins

**Comment by itikhono** [comment]
we have checked the updated transformation with @sammysun0711 
And it looks like the transformation works on GPU with glm4 model but it doesn't  work on CPU.
This is a common transformation so we expect it works on both GPU and CPU.
For CPU we are going to create a separate ticket and investigate the case.

This is not a blocker for this PR.

**Comment by sammysun0711** [comment]
Thanks @itikhono confirmation, we will follow up RoPE fusion for CPU part in separate ticket.

**Pull request merged**
