### PR TITLE
[DOCS] Update the quantizing with accuracy control documentation

### PR DESCRIPTION
**Pull request by alexsu52**
### Details:
 - Added the prepare model topic to the quantizing with accuracy control documentation

### CODE REVIEW

**Comment by alexsu52** [comment]
cc' @yury-gorbachev, @AlexKoff88, @MaximProshin

**Review by yury-gorbachev — APPROVED** [review]

**Comment by akladiev** [comment]
build_jenkins

**Comment by MaximProshin** [comment]
@alexsu52 @tsavina is it still actual? can it be merged?

**Review by tsavina — APPROVED** [review]

**Comment by tsavina** [comment]
reviewed and addressed in https://github.com/openvinotoolkit/openvino/pull/22267

**Pull request closed without merging**
