### PR TITLE
[CPU]Apply SDL requirement for MLAS

### PR DESCRIPTION
**Pull request by zhangYiIntel**
### Details:
 - *Align the link name with repo name*

### Tickets:
 - *CVS-119071*

### CODE REVIEW

**Comment by zhangYiIntel** [comment]
@yssemaev This is the PR to fix the license name from mlas to Microsoft onnxruntime

**Comment by zhangYiIntel** [comment]
@yssemaev This is the link for fix repo name for master branch, could you also approve it ?

**Comment by zhangYiIntel** [comment]
@moslex Since the license fix is merged into 2023.1 #19441 , could you also approve this fix for master ?

**Comment by zhangYiIntel** [comment]
@ilya-lavrenov Since this license is merged into 2023.1 #19441  could you help merge this to the master branch ?

**Review by ilya-lavrenov — APPROVED** [review]

**Pull request merged**
