### PR TITLE
Reverted to Remote Context

### PR DESCRIPTION
**Pull request by apankratovantonp**

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
@apankratovantonp please, resolve merge conflicts.

**Review by ilya-lavrenov — APPROVED** [review]

**Review by ilyachur — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
@apankratovantonp please, resolve merge conflicts.

**Comment by ilya-lavrenov** [comment]
tests failed.

**Comment by azhogov** [comment]
CI passed: https://github.com/intel-innersource/frameworks.ai.openvino.ci.product-configs/pull/242

**Pull request merged**
