### PR TITLE
[install_dependencies.sh] install latest cmake if current version is lower 3.13

### PR DESCRIPTION
**Pull request by asuhov**

### CODE REVIEW

**Comment by mshabunin** [comment]
Perhaps not caused by this PR, but I get an error while building using the instruction (ubuntu:20.04 container):
```
[ 11%] Running gen_proto.py on onnx/onnx.in.proto
/bin/sh: 1: python: not found
make[2]: *** [_deps/ext_onnx-build/CMakeFiles/gen_onnx_proto.dir/build.make:88: _deps/ext_onnx-build/onnx/onnx_ngraph_onnx-ml.proto] Error 127
make[1]: *** [CMakeFiles/Makefile2:3169: _deps/ext_onnx-build/CMakeFiles/gen_onnx_proto.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
```
Perhaps python should be added somewhere too.

**Comment by asuhov** [comment]
@mshabunin Python 2.7 is needed for clDNN and onnx components:
https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/thirdparty/clDNN/CMakeLists.txt#L467
https://github.com/onnx/onnx/blob/master/onnx/gen_proto.py#L1

Ubuntu 20 doesn't include python 2.7 by default, I've added it to the script. Thanks!

**Comment by mshabunin** [comment]
Since Python 2.7 is [EOLed](https://pythonclock.org/), we should consider migrating these tools to Python 3.

**Comment by ilya-lavrenov** [comment]
> https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/thirdparty/clDNN/CMakeLists.txt#L467
> https://github.com/onnx/onnx/blob/master/onnx/gen_proto.py#L1

Please, create tickets for dedicated components to migrate to newer version of python.

**Pull request merged**
