### PR TITLE
[IE VPU] Enable variable number of inputs for ExpPriorGridGenerator

### PR DESCRIPTION
**Pull request by monicael**
**Description**

ExperimentalPriorGridGenerator layer has at least one input tensor and at most three. The second and third tensors are required only if the parameters `w`, `h` and `stride_x`, `stride_y`, respectively, are zero. In such cases, the width/height dimensions of the last two layers are used to compute replacements for the parameters. 

In the current implementation, graph transformer does not allow the ExperimentalPriorGridGenerator layer to have less then three inputs.

Here is an example of how an ExpPriorGridGenerator layer with two inputs is described in xml:

```
<layer id=*id* name=*layer_name* type="ExperimentalDetectronPriorGridGenerator" version="experimental">
    <data flatten="1" h="0" stride_x=*stride_x* stride_y=*stride_y* w="0"/>
    <input>
            <port id="0">
                    <dim> *anchors_num* </dim>
                    <dim>4</dim>
            </port>
            <port id="1">
                    <dim>1</dim>
                    <dim>*feature map channels num*</dim>
                    <dim>*layer_height*</dim>
                    <dim>*layer_width*</dim>
            </port>
            <port id="2">
                    <dim>1</dim>
                    <dim>1</dim>
                    <dim>1</dim>
                    <dim>1</dim>
            </port>
    </input>
    <output>
            <port id="3" precision="FP32">
                    <dim>*num_boxes*</dim>
                    <dim>4</dim>
            </port>
    </output>
</layer>

```

### CODE REVIEW

**Comment by gladilov-gleb** [comment]
@monicael should test be updated as well (add new test cases where another amount of inputs?)

**Comment by monicael** [comment]
> @monicael should test be updated as well (add new test cases where another amount of inputs?)

I don't think that's necessary. In the example in the description, the xml still has three inputs, but the last one (which should have been the input image of the net) has a 1x1x1x1 shape and is not connected to the input of the net. I'm not sure exactly why it appears in this form, instead of missing altogether. But in the current form, the shape of one of the optional inputs doesn't matter if the associated params are not 0. So, for example, in a test where `stride_x` and `stride_y` are non-zero, it doesn't matter if the test dimensions for the third input are 1x1x1x1 or 1x3x225x225, because they will never be taken into consideration and the layer will run the same way in both cases.

**Comment by gladilov-gleb** [comment]
> > @monicael should test be updated as well (add new test cases where another amount of inputs?)
> 
> I don't think that's necessary. In the example in the description, the xml still has three inputs, but the last one (which should have been the input image of the net) has a 1x1x1x1 shape and is not connected to the input of the net. I'm not sure exactly why it appears in this form, instead of missing altogether. But in the current form, the shape of one of the optional inputs doesn't matter if the associated params are not 0. So, for example, in a test where `stride_x` and `stride_y` are non-zero, it doesn't matter if the test dimensions for the third input are 1x1x1x1 or 1x3x225x225, because they will never be taken into consideration and the layer will run the same way in both cases.

Still you add new feature (optional inputs) and there is no tests for that. If there is a concern that such a case should not happen and operation always should have all inputs, so it's better to investigate the root cause rather adding this feature. I understand that in some cases values of optional inputs are ignored, but we need to check that (by writing tests). In addition, through tests it'd be clear under which circumstances some inputs may be omitted.

**Comment by monicael** [comment]
> > > @monicael should test be updated as well (add new test cases where another amount of inputs?)
> > 
> > 
> > I don't think that's necessary. In the example in the description, the xml still has three inputs, but the last one (which should have been the input image of the net) has a 1x1x1x1 shape and is not connected to the input of the net. I'm not sure exactly why it appears in this form, instead of missing altogether. But in the current form, the shape of one of the optional inputs doesn't matter if the associated params are not 0. So, for example, in a test where `stride_x` and `stride_y` are non-zero, it doesn't matter if the test dimensions for the third input are 1x1x1x1 or 1x3x225x225, because they will never be taken into consideration and the layer will run the same way in both cases.
> 
> Still you add new feature (optional inputs) and there is no tests for that. If there is a concern that such a case should not happen and operation always should have all inputs, so it's better to investigate the root cause rather adding this feature. I understand that in some cases values of optional inputs are ignored, but we need to check that (by writing tests). In addition, through tests it'd be clear under which circumstances some inputs may be omitted.

Alright, that makes sense. I'll write tests for the optional input cases and will let you know when they're done :)

**Pull request merged**
