### PR TITLE
VPU: firmware 1378 (MDK develop for OV 2021.2)

### PR DESCRIPTION
**Pull request by elatkin**
Update VPU firmware built from fresh MDK develop (to gain all commits we made to R13 and 2021.1)

Details: #-39108

### CODE REVIEW

**Comment by Maxim-Doronin** [comment]
Has internal CI been started?

**Comment by elatkin** [comment]
ICV Jenkins/CI
* IE MKD #[1670](https://dsp-ci-icv.inn.intel.com/job/IE-MDK/job/manual/job/RunTests-MYRIAD/1670/)
* Nets Validation #[204](https://dsp-ci-icv.inn.intel.com/job/Nets-Validation/job/manual/job/MYRIAD/204/)

**Comment by elatkin** [comment]
@gladilov-gleb 
@Maxim-Doronin 
Could you please review?

**Comment by Maxim-Doronin** [comment]
I've just re-triggered internal validation. The previous report is too old.

**Comment by elatkin** [comment]
Re-triggered additional ICV validation test cycles

ICV Jenkins/CI
* IE MKD #[1703](https://dsp-ci-icv.inn.intel.com/job/IE-MDK/job/manual/job/RunTests-MYRIAD/1703/)
* Nets Validation #[211](https://dsp-ci-icv.inn.intel.com/job/Nets-Validation/job/manual/job/MYRIAD/211/)

**Comment by elatkin** [comment]
@gladilov-gleb
@Maxim-Doronin
Could you please review?

**Review by gladilov-gleb — APPROVED** [review]

**Review by Maxim-Doronin — APPROVED** [review]

**Pull request merged**
