### PR TITLE
Update jinja version to 3.x+

### PR DESCRIPTION
**Pull request by sbalandi**
### Details:
 - *+ fix of fail on analyzing of "implemented" tag*

### Tickets:
 - *CVS-96841*

### CODE REVIEW

**Comment by akuporos** [comment]
Please, update `jinja` [here](https://github.com/openvinotoolkit/openvino/blob/master/src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/requirements.txt) and remove `markupsafe` requirement.

**Review by akuporos — COMMENTED** [review]
Please, update jinja [here](https://github.com/openvinotoolkit/openvino/blob/master/src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/requirements.txt) and remove markupsafe from the requirements file.

**Comment by sbalandi** [comment]
> Please, update `jinja` [here](https://github.com/openvinotoolkit/openvino/blob/master/src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/requirements.txt) and remove `markupsafe` from the requirements file.

Updated. Thank you ! It looks like I pulled up very old version cloning repo 😥

**Review by akuporos — APPROVED** [review]
LGTM, but need to check the validation (the problem occurred in nightly).

**Pull request merged**
