### PR TITLE
Centos7 install guide

### PR DESCRIPTION
**Pull request by yangsu2022**
### Details: *OV22.1 support on Centos 7* 
Provide a sample script for user to build OV and test OV built package with openvino tools. 
Build OV22.1 with CMake 3.18.4 on CentOS 7.6.
Install Devtoolset to install two version GCC (7.3.1 or 8.3.1).
Install Anaconda3 to create four Python virtual env (3.6, 3.7, 3.8, 3.9).
Install OV Python wheels after building OV with CMake.
Provide two options of benchmark_app to evaluate the model (Python and C++).
Prepare OV CLI sample.

*Usage: [-g <7 or 8>] [-p <6, 7, 8 or 9>] [-c < Cmake Dir >] [-m < evaluation model >] [-b benchmark_app C++ < true or false >]*
*E.g.*
`$ cd openvino && ./scripts/centos_install_guide.sh -g 7 -p 8 -c ~ -m resnet-50-pytorch -b true`
### Tickets: *82831*

### CODE REVIEW

**Comment by FionaZZ92** [comment]
@ryanloney Could you please help to add people for reviewing. Thank you very much.

**Comment by ilya-lavrenov** [comment]
Why OpenVINO needs this script?

It looks like a Dockerfile, should not such configuration be distributed like a docker image? And you can push it to a dockerhub somewhere.

**Comment by ma7555** [comment]
@yangsu2022 Thank you for this script. It is the only one that worked for me after wasting 7 days trying to compile it.
@ilya-lavrenov I suggest that you merge it as it would help many people like myself.

**Comment by ilya-lavrenov** [comment]
Replaced by https://github.com/openvinotoolkit/openvino/wiki/Building-OpenVINO-on-CentOS-7-Guide

**Pull request closed without merging**
