### PR TITLE
Don't fuse Add or Mul to FakeQuantize if the result is not supported b…

### PR DESCRIPTION
**Pull request by mateusztabaka**
…y the plugin

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@mateusztabaka Is it possible to propagate the same logic to `FakeQuantizeMulFusion` transformation?

**Comment by dmitry-gorokhov** [comment]
@mateusztabaka So may I ask you to update the transformation in bounds of this PR?

**Comment by mateusztabaka** [comment]
> @mateusztabaka So may I ask you to update the transformation in bounds of this PR?

Yes, it's in progress.

**Review by dmitry-gorokhov — APPROVED** [review]
LGTM
I think we can merge after internal validation. @eshoguli  @v-Golubev could you please help with that?

**Review by GlebKazantaev — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
@mateusztabaka Internal validation passed. Could you please rebase on latest master in order to get fresh CI?

**Review by v-Golubev — APPROVED** [review]

**Pull request merged**
