### PR TITLE
Fluid update for vpux 2021 2

### PR DESCRIPTION
**Pull request by dbudniko**

### CODE REVIEW

**Review by ArtemySkrebkov-intel — APPROVED** [review]
I am OK if CI is green. :+1:

**Comment by dbudniko** [comment]
What should I do with such error? ##[error]We stopped hearing from agent vmssa7a4c000L2H. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610

**Comment by ilya-lavrenov** [comment]
@dbudniko you just need to re-start Windows build. I've done this for you.

**Comment by dbudniko** [comment]
@ilya-lavrenov thank you! But I don't think that I have enough rights to do it. I don't see any restart buttons for particular build.

**Comment by ilya-lavrenov** [comment]
> @ilya-lavrenov thank you! But I don't think that I have enough rights to do it. I don't see any restart buttons for particular build.

It's Azure CI, all have an access. You just need to open a link and near a build name for failed build we can see "Re-run" label.

**Review by ilya-lavrenov — APPROVED** [review]

**Comment by dbudniko** [comment]
@evgenytalanin-intel  We need to merge it to unblock vpux ci

**Pull request merged**
