### PR TITLE
fix input issuse of ScatterNDUpdate conformance test

### PR DESCRIPTION
**Pull request by tiger100256-hu**
### Details:
 - *fix input issuse of ScatterNDUpdate conformance test*

### Tickets:
 - *96718*

### CODE REVIEW

**Comment by iefode** [comment]
@tiger100256-hu In general, LGTM. Have you checked the conformance result after your fix? We need to be confident that the fix works. (Please run conformance before fix and after fix to check fix)

**Comment by tiger100256-hu** [comment]
I  already test it locally, I think this PR fix the issue

**Comment by tiger100256-hu** [comment]
uploaded the report in the ticket, please check

**Comment by tiger100256-hu** [comment]
fix conflict with master

**Comment by tiger100256-hu** [comment]
@iefode any update?

**Comment by tiger100256-hu** [comment]
any update?

**Pull request merged**
