### PR TITLE
[CPU] NormalizeL2 - unsorted axes are not supported

### PR DESCRIPTION
**Pull request by egorshul**
### Details:
 - *Added sorting of axes*

### Tickets:
 - *59794*

### CODE REVIEW

**Review by mitruska — COMMENTED** [review]
Please update this PR to the latest master and enable also cpu shared single layer tests:

https://github.com/openvinotoolkit/openvino/blob/015ad868ef05a18fea98f36f39993e1cf6d18dfa/inference-engine/tests/functional/plugin/cpu/shared_tests_instances/single_layer_tests/normalize_l2.cpp#L79-L80

https://github.com/openvinotoolkit/openvino/blob/015ad868ef05a18fea98f36f39993e1cf6d18dfa/inference-engine/tests/functional/plugin/cpu/shared_tests_instances/single_layer_tests/normalize_l2.cpp#L111-L112

and try remove related tests from ie/unit_test.manifest:
https://github.com/openvinotoolkit/openvino/blob/015ad868ef05a18fea98f36f39993e1cf6d18dfa/ngraph/test/runtime/ie/unit_test.manifest#L915-L919

**Review by dmitry-gorokhov — APPROVED** [review]
LGTM. @mitruska do you have any comments?

**Comment by dmitry-gorokhov** [comment]
@egorshul Please rebase on latest master and make CI green

**Review by mitruska — APPROVED** [review]
I have no other comments

**Pull request merged**
