### PR TITLE
[VPU][TESTS] adding test case for ROIPooling test, firmware version update

### PR DESCRIPTION
**Pull request by KorA6**
## Description
adding test case for ROIPooling test, firmware version update

## Task
- 31452

### CODE REVIEW

**Comment by KorA6** [comment]
@rvyunov  
@elatkin  
Could you please review?

**Comment by elatkin** [comment]
@KorA6  
May I see testing results? (IE-MDK)

**Comment by KorA6** [comment]
@elatkin  
> May I see testing results? (IE-MDK)
Validation is running now (link in ticket)

**Comment by elatkin** [comment]
> > May I see testing results? (IE-MDK)
> 
> Validation is running now (link in ticket)

Well, the testing has failed. Could you please let me know when testing passes?

**Comment by KorA6** [comment]
> > > May I see testing results? (IE-MDK)
> > 
> > 
> > Validation is running now (link in ticket)
> 
> Well, the testing has failed. Could you please let me know when testing passes?

Ok. I'll do it.

**Pull request closed without merging**
