### PR TITLE
Fix bug in Reduce node concerning model accuracy

### PR DESCRIPTION
**Pull request by xuchen-intel**
### Details:
 - *Fix bug in Reduce node concerning model accuracy*

### Tickets:
 - *76735*

### CODE REVIEW

**Comment by xuchen-intel** [comment]
@dmitry-gorokhov Hi Dmitry, could you please take a look?

**Comment by dmitry-gorokhov** [comment]
@xuchen-intel I am wondering why existing single layer tests haven't caught that? Can they be extended?

**Comment by xuchen-intel** [comment]
> @xuchen-intel I am wondering why existing single layer tests haven't caught that? Can they be extended?

@dmitry-gorokhov The direct reason is we don't have int8 test cases. As we know, int8-in-int8-out data type is not inclueded in Reduce node SLT, because arithmatic reduce cases will naturally suffer accuracy loss. However the cases in ticket 76735 are int8-in-fp32-out data type. I tried to support such test cases by set netPrecision=fp32, inType=int8, outType=undefined in SLT. The problem is the input_precision we get from getOriginalInputPrecisionAtPort inside CPU plugin is only depend on netPrecision=fp32 set by SLT. Though inType=int8 make the input blob to be int8 data type, it will be converted to fp32, before CPU plugin access to the input blob. So from the perspective of CPU plugin, the test case always has a fp32-in-fp32-out data type. Among all the CPU SLTs, I found conv node and mvn node also support such int8-in-fp32-out data type in SLT, but same thing happens in  CPU plugin, fp32-in-fp32-out data type are acutally been tested. So my conclusion is current SLT infrastructures don't actually support such int8-in-fp32-out hybrid data type test cases. Please correct me if I'm wrong, and further discussion is always welcomed. Thanks Dmitry!

**Comment by dmitry-gorokhov** [comment]
> clusion is current SLT infrastructures don't actually support such int8-in-fp32-out hybrid data type test cases. Please correct me i

Thanks for explanation. @antonvor FYI. Another one candidate for int8 test coverage.

**Comment by dmitry-gorokhov** [comment]
> > @xuchen-intel I am wondering why existing single layer tests haven't caught that? Can they be extended?
> 
> @dmitry-gorokhov The direct reason is we don't have int8 test cases. As we know, int8-in-int8-out data type is not inclueded in Reduce node SLT, because arithmatic reduce cases will naturally suffer accuracy loss. However the cases in ticket 76735 are int8-in-fp32-out data type. I tried to support such test cases by set netPrecision=fp32, inType=int8, outType=undefined in SLT. The problem is the input_precision we get from getOriginalInputPrecisionAtPort inside CPU plugin is only depend on netPrecision=fp32 set by SLT. Though inType=int8 make the input blob to be int8 data type, it will be converted to fp32, before CPU plugin access to the input blob. So from the perspective of CPU plugin, the test case always has a fp32-in-fp32-out data type. Among all the CPU SLTs, I found conv node and mvn node also support such int8-in-fp32-out data type in SLT, but same thing happens in CPU plugin, fp32-in-fp32-out data type are acutally been tested. So my conclusion is current SLT infrastructures don't actually support such int8-in-fp32-out hybrid data type test cases. Please correct me if I'm wrong, and further discussion is always welcomed. Thanks Dmitry!

**Comment by dmitry-gorokhov** [comment]
> > @xuchen-intel I am wondering why existing single layer tests haven't caught that? Can they be extended?
> 
> @dmitry-gorokhov The direct reason is we don't have int8 test cases. As we know, int8-in-int8-out data type is not inclueded in Reduce node SLT, because arithmatic reduce cases will naturally suffer accuracy loss. However the cases in ticket 76735 are int8-in-fp32-out data type. I tried to support such test cases by set netPrecision=fp32, inType=int8, outType=undefined in SLT. The problem is the input_precision we get from getOriginalInputPrecisionAtPort inside CPU plugin is only depend on netPrecision=fp32 set by SLT. Though inType=int8 make the input blob to be int8 data type, it will be converted to fp32, before CPU plugin access to the input blob. So from the perspective of CPU plugin, the test case always has a fp32-in-fp32-out data type. Among all the CPU SLTs, I found conv node and mvn node also support such int8-in-fp32-out data type in SLT, but same thing happens in CPU plugin, fp32-in-fp32-out data type are acutally been tested. So my conclusion is current SLT infrastructures don't actually support such int8-in-fp32-out hybrid data type test cases. Please correct me if I'm wrong, and further discussion is always welcomed. Thanks Dmitry!

Thanks for explanation. @antonvor FYI. Another one candidate for int8 test coverage.

**Review by dmitry-gorokhov — APPROVED** [review]

**Pull request merged**
