### PR TITLE
[ARM]: Implement CPU plugin just-in-time emitter for LogicalOr operation #27504

### PR DESCRIPTION
**Pull request by shivam5522**
### Details:
- Added a jit_logical_or_emitter derived class in aarch64/jit_eltwise_emitters
- Created entry Algorithm::EltwiseLogicalOr in the get_supported_precisions in nodes/kernels/aarch64
- Add the EltwiseLogicalOr entry in the aarch64 executors supported algorithms

### Tickets:
 - #27504

### CODE REVIEW

**Comment by shivam5522** [comment]
I think my formatter, made changes to the visual looks of the code, if that would be an issue. Please let me know

**Comment by a-sidorova** [comment]
> I think my formatter, made changes to the visual looks of the code, if that would be an issue. Please let me know

@shivam5522 thank you for the contribution!
I think we need remove all formatter changes. Could you please leave only the task-related changes in the PR?

**Comment by shivam5522** [comment]
Sure will do, sorry for the issue

**Comment by shivam5522** [comment]
Hello, I reversed the formatter changes. Should I create a new PR?

**Comment by a-sidorova** [comment]
> Hello, I reversed the formatter changes. Should I create a new PR?

No need because you pushed the commit with removed formatter changes to the current branch - now PR contains only relevant JIT emitter implementation 😊

**Comment by a-sidorova** [comment]
@shivam5522 there are build errors in GitHub Actions jobs (for example, [Android ARM64](https://github.com/openvinotoolkit/openvino/actions/runs/12250579217/job/34174284777?pr=27987)). Please take a look and fix them.

**Comment by shivam5522** [comment]
Hello, I have fixed the issue, can you run the tests again? Thanks.

**Comment by a-sidorova** [comment]
build_jenkins

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by a-sidorova** [comment]
build_jenkins

**Review by a-sidorova — APPROVED** [review]
@shivam5522 good job! 👍🏼

**Comment by shivam5522** [comment]
Thank you so much. Picking up more issues to learn and contribute!

**Pull request merged**
