### PR TITLE
Apply changes from 2020/4.0.1

### PR DESCRIPTION
**Pull request by dorloff**

### CODE REVIEW

**Comment by alalek** [comment]
Why is there cherry-pick approach instead of real "git merge" which is designed for that (to apply all changes from another branch)?

You have here 7 commits and can do that in manual mode. But
- it is not a good option to process 100+ commits
- how to ensure that something is not missed?
- it is hard to review

---

Why these steps doesn't work?
- reset branch `releases/2020/4` to `releases/2020/4.0.1` content
- remove `releases/2020/4.0.1` completely.

(Answer: because changes from 2020.4 were not propagated to 4.0.1 properly in #1729 and these branches are still diverged)

**Comment by dorloff** [comment]
@alalek, I used the cherry-pick approach because of potential conflicts in the documentation (as you mentioned, the branches had diverged). I thought this way would be the fastest and easiest - this is an urgent request. All commits in that branch have been reviewed and merged to 2020/4.0.1, so I didn't expect them to be reviewed once again.
So do you still propose to merge and resolve conflicts (by resetting the conflicting files to 2020.4 content)?

**Comment by dorloff** [comment]
I created another PR: #1764 ; can close this one.

**Comment by alalek** [comment]
@dorloff Main question here is used "processes" and git BKMs. #1764 looks much better :+1:

**Pull request closed without merging**
