### PR TITLE
[ONNX] Extend ONNX Frontend with BitwiseNot-18 operator

### PR DESCRIPTION
**Pull request by rupeshs**
### Details:
 - Added BitwiseNot operator to ONNX FrontEnd

### Tickets:
 - 118961

### CODE REVIEW

**Comment by p-wysocki** [comment]
build_jenkins

**Comment by p-wysocki** [comment]
@mitruska @gkrivor could you please take a look?

**Review by mitruska — COMMENTED** [review]
Please sync this branch with the latest openvino master and update the following test config file to enable BitwiseNot ONNX compliance [tests](https://github.com/openvinotoolkit/openvino/actions/runs/7404838247/job/20262611011?pr=21872#step:15:1858). 
Remove xfail `test_bitwise_not_2d_cpu`, `test_bitwise_not_4d_cpu`:
https://github.com/openvinotoolkit/openvino/blob/a561a2a484049cc63fd0959646ef5c1cb8f3c2e6/src/frontends/onnx/tests/tests_python/test_backend.py#L420-L423

Unfortunately `test_bitwise_not_3d_cpu`, is still failing. Beside the shape, the difference in this test case is the element type uint16 ([the tests source file](https://github.com/onnx/onnx/blob/609282efe8d4871f620141223139bbb99bdbe9f6/onnx/backend/test/case/node/bitwisenot.py#L22-L35)), it can be plugin or test runner related issue. I've checked that the test is failing at the results comparison, because the output is filled with zeros:

```
E           Mismatched elements: 60 / 60 (100%)
E           Max absolute difference: 32623
E           Max relative difference: 1.
E            x: array([[[0, 0, 0, 0, 0],
E                   [0, 0, 0, 0, 0],
E                   [0, 0, 0, 0, 0],...
E            y: array([[[ 3034, 32532, 53363, 60343, 33024],
E                   [15478, 21812, 57722, 13488, 44095],
E                   [32623, 44926, 16435, 57784, 21778],...
```
The frontend code looks ok, this failing test case can be investigated separately.

**Comment by rupeshs** [comment]
> Please sync this branch with the latest openvino master and update the following test config file to enable BitwiseNot ONNX compliance [tests](https://github.com/openvinotoolkit/openvino/actions/runs/7404838247/job/20262611011?pr=21872#step:15:1858). Remove xfail `test_bitwise_not_2d_cpu`, `test_bitwise_not_4d_cpu`:
> 
> https://github.com/openvinotoolkit/openvino/blob/a561a2a484049cc63fd0959646ef5c1cb8f3c2e6/src/frontends/onnx/tests/tests_python/test_backend.py#L420-L423
> 
> Unfortunately `test_bitwise_not_3d_cpu`, is still failing. Beside the shape, the difference in this test case is the element type uint16 ([the tests source file](https://github.com/onnx/onnx/blob/609282efe8d4871f620141223139bbb99bdbe9f6/onnx/backend/test/case/node/bitwisenot.py#L22-L35)), it can be plugin or test runner related issue. I've checked that the test is failing at the results comparison, because the output is filled with zeros:
> 
> ```
> E           Mismatched elements: 60 / 60 (100%)
> E           Max absolute difference: 32623
> E           Max relative difference: 1.
> E            x: array([[[0, 0, 0, 0, 0],
> E                   [0, 0, 0, 0, 0],
> E                   [0, 0, 0, 0, 0],...
> E            y: array([[[ 3034, 32532, 53363, 60343, 33024],
> E                   [15478, 21812, 57722, 13488, 44095],
> E                   [32623, 44926, 16435, 57784, 21778],...
> ```
> 
> The frontend code looks ok, this failing test case can be investigated separately.

@mitruska  Thanks, rebased and enabled bitwise_not_2d and bitwise_not_4d tests.

**Comment by gkrivor** [comment]
build_jenkins

**Comment by mitruska** [comment]
The PR seems to be ready for merge, the code LGTM and all of the CI checks passed.
@gkrivor Would you like to review?

**Review by gkrivor — APPROVED** [review]

**Pull request merged**
