### PR TITLE
[MO] fixed loading version of default opset (ONNX)

### PR DESCRIPTION
**Pull request by ivkalgin**
### Details:
Default opset version can be found on any position. For example onnxruntime sets default opset import on last position.
 - fixed loading version of default opset (ONNX)

### CODE REVIEW

**Comment by andrei-kochin** [comment]
@ivkalgin thanks for you interest in OpenVINO and  you contribution!

ModelOptimizer has switched to the the new Frontend path for the ONNX models on the latest 'master'. Could you please check if you face same issue on latest?

Best regards,
Andrei

**Comment by ivkalgin** [comment]
Hi @andrei-kochin,

On latest master model optimizer works fine. Should I close PR or create new one for branch "release/2021/4". 

Best regards,
Igor

**Comment by andrei-kochin** [comment]
Hi @ivkalgin,

Next release would be 2022.1 which will be based on master so in coming release there would be no such issue. Do you have any specific reason to have this in 2021.4?

**Comment by ivkalgin** [comment]
> Hi @ivkalgin,
> 
> Next release would be 2022.1 which will be based on master so in coming release there would be no such issue. Do you have any specific reason to have this in 2021.4?

Ok, we wait new release. Thanks for answer.

**Pull request closed without merging**
