### PR TITLE
[HDDL] - Update path

### PR DESCRIPTION
**Pull request by DariaMityagina**
**This should be merged after changes in hddl-plugin.** 

Related PRs:
- https://gitlab-icv.toolbox.iotg.sclab.intel.com/inference-engine/hddl-plugin/-/merge_requests/308
- https://github.com/intel-innersource/frameworks.ai.openvino.inference-engine.hddl-plugin/pull/1

New location:
- https://storage.openvinotoolkit.org/drivers/vpu/hddl/2022.3/

### CODE REVIEW

**Comment by DariaMityagina** [comment]
Error in the Code Style check:
```
gmake[3]: *** [scripts/CMakeFiles/ie_shellcheck.dir/build.make:94: shellcheck/scripts/install_dependencies/install_NEO_OCL_driver.sh.txt] Error 1
gmake[3]: *** Deleting file 'shellcheck/scripts/install_dependencies/install_NEO_OCL_driver.sh.txt'
gmake[2]: *** [CMakeFiles/Makefile2:5725: scripts/CMakeFiles/ie_shellcheck.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:5732: scripts/CMakeFiles/ie_shellcheck.dir/rule] Error 2
gmake: *** [Makefile:1954: ie_shellcheck] Error 2
Error: Process completed with exit code 2.
```
I did not modify this file: `/install_dependencies/install_NEO_OCL_driver.sh`

**Review by Maxim-Doronin — COMMENTED** [review]
This solution looks weird to me. Can we re-use the logic which was applied for Myriad? 
```
RESOLVE_DEPENDENCY(VPU_FIRMWARE_${firmware_name_upper}
        ARCHIVE_UNIFIED myriad/firmware_${firmware_name}_${FIRMWARE_PACKAGE_VERSION}.zip
        TARGET_PATH "${TEMP}/vpu/firmware/${firmware_name}"
        ENVIRONMENT "VPU_FIRMWARE_${firmware_name_upper}_FILE"
        FOLDER
        SHA256 ${hash}
        USE_NEW_LOCATION TRUE)
```

At least, it didn't require any changes here, in common cmake scripts

**Comment by Maxim-Doronin** [comment]
If it's put with the same approach as myriad binaries that those RESOLVE_DEPENDENCY calls should be the same I hope

**Comment by DariaMityagina** [comment]
> If it's put on file shares with the same approach as myriad binaries that those RESOLVE_DEPENDENCY calls should be the same I hope

Sure, I will check this. Thanks a lot!

**Comment by DariaMityagina** [comment]
> This solution looks weird to me. Can we re-use the logic which was applied for Myriad?
> 
> ```
> RESOLVE_DEPENDENCY(VPU_FIRMWARE_${firmware_name_upper}
>         ARCHIVE_UNIFIED myriad/firmware_${firmware_name}_${FIRMWARE_PACKAGE_VERSION}.zip
>         TARGET_PATH "${TEMP}/vpu/firmware/${firmware_name}"
>         ENVIRONMENT "VPU_FIRMWARE_${firmware_name_upper}_FILE"
>         FOLDER
>         SHA256 ${hash}
>         USE_NEW_LOCATION TRUE)
> ```
> 
> At least, it didn't require any changes here, in common cmake scripts

Done. I completely forgot about USE_NEW_LOCATION :) Thanks!

**Comment by DariaMityagina** [comment]
Corresponding change in hddl-plugin:
- https://github.com/intel-innersource/frameworks.ai.openvino.inference-engine.hddl-plugin/pull/1/commits/d16e4baaea4cfed2e2b449b97f1d6452f06d121a
- https://gitlab-icv.toolbox.iotg.sclab.intel.com/inference-engine/hddl-plugin/-/merge_requests/308/diffs?commit_id=f66f2032929dc46dfa29d7b2449aba7a9a025f53

**Comment by DariaMityagina** [comment]
This USE_NEW_LOCATION broke the loading of other dependencies. I'll fix it.

**Comment by DariaMityagina** [comment]
> This USE_NEW_LOCATION broke the loading of other dependencies. I'll fix it.

It is not possible to apply the same logic as for the Myriad firmware because not all dependencies using the new location have the same path structure.
Therefore, if we use USE_NEW_LOCATION here, additional conditions will be required for other dependencies relevant to the situation described above.

**Comment by DariaMityagina** [comment]
@ilya-lavrenov, @ilyachur hi!
Could you please take a look?

This should be merged after changes in hddl-plugin. See links in PR description

**Comment by DariaMityagina** [comment]
@artanokhov hi!
Could you please take a look?

**Comment by DariaMityagina** [comment]
For some reason only the new version of the archive is used, but not the location:
```
--2023-02-06 14:37:27--  http://10-211-120-125.iotg.sclab.intel.com/dl_score_engine/hddl_ubuntu18_1910.tar.gz
[2023-02-06T14:37:39.427Z] Resolving 10-211-120-125.iotg.sclab.intel.com (10-211-120-125.iotg.sclab.intel.com)... 10.211.120.125
[2023-02-06T14:37:39.427Z] Connecting to 10-211-120-125.iotg.sclab.intel.com (10-211-120-125.iotg.sclab.intel.com)|10.211.120.125|:80... connected.
[2023-02-06T14:37:39.427Z] HTTP request sent, awaiting response... 404 Not Found
[2023-02-06T14:37:39.427Z] 2023-02-06 14:37:27 ERROR 404: Not Found.
```

**Pull request closed without merging**
