### PR TITLE
Fixed headers for doxygen generation

### PR DESCRIPTION
**Pull request by ilyachur**

### CODE REVIEW

**Review by ntyukaev — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
Q: do we need the same for Tranformations API? Looks like doxygen parses those headers correctly, why these ones don't work?

**Comment by ilyachur** [comment]
> Q: do we need the same for Tranformations API? Looks like doxygen parses those headers correctly, why these ones don't work?

We didn't generate doxygen documentation for transformation API. Looks like we need to do the same changes for Transformations API if we start to generate doxygen documentation.

**Comment by ilya-lavrenov** [comment]
> We didn't generate doxygen documentation for transformation API

See https://docs.openvinotoolkit.org/2021.1/ie_plugin_api/group__ie__transformation__api.html

**Comment by ilyachur** [comment]
> > We didn't generate doxygen documentation for transformation API
> 
> See https://docs.openvinotoolkit.org/2021.1/ie_plugin_api/group__ie__transformation__api.html

You can see the problem on this page: https://docs.openvinotoolkit.org/latest/ngraph_cpp_api/annotated.html
Doxygen adds a class `ngraph` instead of namespace.
@ntyukaev tried to fix this issue, but he found that only changes in the code help to solve the problem.
@ntyukaev Could you comment the case with Transformation API?

**Review by ilya-lavrenov — APPROVED** [review]

**Pull request merged**
