### PR TITLE
NPUW: Adding a new dcoff pattern

### PR DESCRIPTION
**Pull request by ujjayant-kadian**
### Details:
Implemented a new pattern in continuation of the [PR:2587](https://github.com/openvinotoolkit/openvino/pull/25827).

### Tickets:
 - *121052*

### CODE REVIEW

**Review by smirnov-alexey — APPROVED** [review]

**Review by dmatveev — APPROVED** [review]

**Comment by dmatveev** [comment]
@ujjayant-kadian can you please 1) squash your branch to a single commit and 2) review what are the builds are failing/

**Comment by ujjayant-kadian** [comment]
Sorry about it I rebased it wrong. Making corrections!

**Comment by ujjayant-kadian** [comment]
Messed up the history too many times. Will reopen a new PR with fewer commits and lesser history.

**Comment by dmatveev** [comment]
@ujjayant-kadian you shouldn't close the PR

**Pull request closed without merging**
