### PR TITLE
Create documentation.yml

### PR DESCRIPTION
**Pull request by hbalasu1**
This is for customers to report any issue regarding documentation.

### Details:
 - new documentation issue template 

### Tickets:
 - *ticket-id*

### CODE REVIEW

**Comment by devangaggarwal** [comment]
LGTM.

**Comment by hbalasu1** [comment]
Hi @ilya-lavrenov @ilyachur could you help to review this and merge if possible? 
Thank you

**Review by ilyachur — APPROVED** [review]

**Comment by hbalasu1** [comment]
Hi @ilyachur the test failed at build with this error
Error: No files were found with the provided path: /home/runner/work/openvino/openvino/build/openvino_tests.tar.gz. No artifacts will be uploaded.

I don't think this error comes from my template, but anything I can do to avoid this error when testing is run?

**Comment by ilyachur** [comment]
Right now we have an issue with master branch. Please wait

**Pull request merged**
