### PR TITLE
[GPU] Fix different element types of MatMul dequantization scales issue

### PR DESCRIPTION
**Pull request by yuanxion**
### Details:
 - MatMul dequantization
Convert both dequantization scale variables (mulConst1 & mulConst2) to f32 instead of just one (mulConst2), to avoid different data type complaint issue (f16 & f32).

### Tickets:
 - 151988

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@v-Golubev Please take a look

**Review by v-Golubev — COMMENTED** [review]
May I ask you to cover the fix by functional test? I'd suggest to add a test case to src/common/low_precision_transformations/tests/mat_mul_with_constant_transformation.cpp: you can copy [the existing test case](https://github.com/openvinotoolkit/openvino/blob/master/src/common/low_precision_transformations/tests/mat_mul_with_constant_transformation.cpp#L160-L175), but create [dequantizationOnData](https://github.com/openvinotoolkit/openvino/blob/master/src/common/low_precision_transformations/tests/mat_mul_with_constant_transformation.cpp#L30).multiply with constant precision = f16 (you can use `setConstantPrecision` API for that).

**Comment by yuanxion** [comment]
> May I ask you to cover the fix by functional test? I'd suggest to add a test case to src/common/low_precision_transformations/tests/mat_mul_with_constant_transformation.cpp: you can copy [the existing test case](https://github.com/openvinotoolkit/openvino/blob/master/src/common/low_precision_transformations/tests/mat_mul_with_constant_transformation.cpp#L160-L175), but create [actual.dequantizationOnData](https://github.com/openvinotoolkit/openvino/blob/master/src/common/low_precision_transformations/tests/mat_mul_with_constant_transformation.cpp#L30).multiply with constant precision = f16 (you can use `setConstantPrecision` API for that).

@v-Golubev Thanks for your advice.
Added one new testcase for it, which can be only passed when applying this PR.
```
(ov_env) Debug$ ./ov_lp_transformations_tests --gtest_filter=smoke_LPT/MatMulWithConstantTransformation*
[----------] 56 tests from smoke_LPT/MatMulWithConstantTransformation (1385 ms total)

[----------] Global test environment tear-down
[==========] 56 tests from 1 test suite ran. (1385 ms total)
[  PASSED  ] 56 tests.
```

**Review by v-Golubev — APPROVED** [review]
LGTM

**Comment by v-Golubev** [comment]
build_jenkins

**Comment by v-Golubev** [comment]
build_jenkins

**Pull request merged**
