### PR TITLE
nGraph API: convert docstrings to doxygen format, add doc layouts for ngraph

### PR DESCRIPTION
**Pull request by ntyukaev**
http://openvino-docs.inn.intel.com/ngraph-api/ngraph_python_api/files.html

http://openvino-docs.inn.intel.com/ngraph-api/ngraph_cpp_api/annotated.html

### CODE REVIEW

**Review by akuporos — APPROVED** [review]

**Review by postrational — CHANGES_REQUESTED** [review]
Operations from opsets are organized using imports in `__init__.py` files (module level), not `ops.py` files as the generated documentation suggests.

https://github.com/openvinotoolkit/openvino/blob/78f1fcfa63c71d7f988b536a8535bfa00f53184c/ngraph/python/src/ngraph/opset3/__init__.py

Users are supposed to use:
```python
from ngraph.opset2 import abs 
```
not:
```
from ngraph.opset2.ops import abs 
```
The latter will cause problems when op is imported into `__init__.py` from previous opset.

Also, do we need to add `!` to every docstring? Can we avoid this?

**Review by andrew-zaytsev — APPROVED** [review]

**Comment by ntyukaev** [comment]
@postrational "!" is required for doxygen in order to parse python comments.

**Comment by ntyukaev** [comment]
@postrational Please have a look once again at the page with python api (http://openvino-docs.inn.intel.com/ngraph-api/ngraph_python_api/files.html)

**Comment by postrational** [comment]
I still don't see the commands listed here:
http://openvino-docs.inn.intel.com/ngraph-api/ngraph_python_api/opset1_2____init_____8py.html

Can we change doxygen configuration to use `"""` docstring and not require the strange `"""!` style?

**Comment by postrational** [comment]
CI is now failing with errors:
```
src/ngraph/opset1/ops.py:809:111: E501 line too long (113 > 110 characters)
src/ngraph/opset1/ops.py:2645:1: D301 Use r""" if any backslashes in a docstring
src/ngraph/opset1/ops.py:2787:1: D205 1 blank line required between summary line and description
src/ngraph/opset1/ops.py:2787:1: D400 First line should end with a period
```

**Review by postrational — APPROVED** [review]
I can approve this PR provisionally on the proviso that we address the following issues in the next release:

1. Move documentation from `ops.py` files to `__init__.py` files. (or just add to `__init__.py`)
2. Remove the need for the `"""! ` docstrings.

CI must pass before this can be merged.

**Comment by andrew-zaytsev** [comment]
Closing. The changes were made and merged within the #PR2629.

**Pull request closed without merging**
