### PR TITLE
[IE][TF2] MaxPool exception in include padding case

### PR DESCRIPTION
**Pull request by alexey-varyzgin**
Ticket: 35367
There is a bug in MaxPool layer, and uses only exclude padding mode in MaxPool layer for 2 different modes: exclude padding and include padding.
In this fix throws an exception in include padding case of MaxPool layer.

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@alexey-varyzgin I think we will not merge this since it will break more than hundred of our models. Lets wait for the fix in implementations.

**Comment by AlexPeskov** [comment]
We should not merge this changes while we have no updates for MapPool specs. Originally this request was initiated by wrong usage of MaxPool padding related attributes.

**Comment by rblaczkowski** [comment]
Please merge current master to your branch if you want to pass CI - it is around 5 months out o date

**Comment by dmitry-gorokhov** [comment]
Closing since we are not going to merge it.

**Pull request closed without merging**
