### PR TITLE
Renamed CUDA device name to NVIDIA device name

### PR DESCRIPTION
**Pull request by lohika-denis-kotov**
### Details:
This PR introduce `NVIDIA` device name

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Could you please also update files in `.ci` folder and replace `-DBUILD_cuda_plugin=OFF` with -DBUILD_nvidia_plugin=OFF`?

**Comment by lohika-denis-kotov** [comment]
> Could you please also update files in `.ci` folder and replace `-DBUILD_cuda_plugin=OFF` with `-DBUILD_nvidia_plugin=OFF`?

@ilya-lavrenov 
Done

**Comment by lohika-denis-kotov** [comment]
>

**Review by ilya-lavrenov — APPROVED** [review]

**Review by ilyachur — APPROVED** [review]

**Comment by lohika-denis-kotov** [comment]
Looks like now we have cross dependencies on each other between this PR and the following:
https://github.com/openvinotoolkit/openvino_contrib/pull/405

If we merge this PR first than ci will crash due to new name of plugin: nvidia_plugin.
But to merge nvidia_plugin first also not possible because MULTI (aka AUTO) device tests not passed due to old registed name "CUDA" in openvino

@ilya-lavrenov @ilyachur How do you usually handle such cases ?

**Comment by ilyachur** [comment]
> Looks like now we have cross dependencies on each other between this PR and the following: [openvinotoolkit/openvino_contrib#405](https://github.com/openvinotoolkit/openvino_contrib/pull/405)
> 
> If we merge this PR first than ci will crash due to new name of plugin: nvidia_plugin. But to merge nvidia_plugin first also not possible because MULTI (aka AUTO) device tests not passed due to old registed name "CUDA" in openvino
> 
> @ilya-lavrenov @ilyachur How do you usually handle such cases ?

@lohika-denis-kotov We have 2 possible ways for this case:

- Extend AUTO device tests to support both names "NVIDIA" and "CUDA" in order to unblock PRs and step by step merge all dependent PRs, at the end create an additional PR to revert change in auto tests.
- If you have an access to one source, you can create a custom product config in order to validate these changes and merge it immediately

**Comment by lohika-denis-kotov** [comment]
> > Looks like now we have cross dependencies on each other between this PR and the following: [openvinotoolkit/openvino_contrib#405](https://github.com/openvinotoolkit/openvino_contrib/pull/405)
> > If we merge this PR first than ci will crash due to new name of plugin: nvidia_plugin. But to merge nvidia_plugin first also not possible because MULTI (aka AUTO) device tests not passed due to old registed name "CUDA" in openvino
> > @ilya-lavrenov @ilyachur How do you usually handle such cases ?
> 
> @lohika-denis-kotov We have 2 possible ways for this case:
> 
>     * Extend AUTO device tests to support both names "NVIDIA" and "CUDA" in order to unblock PRs and step by step merge all dependent PRs, at the end create an additional PR to revert change in auto tests.
> 
>     * If you have an access to one source, you can create a custom product config in order to validate these changes and merge it immediately


@ilyachur I think it is more difficult than that, because that once I rename cuda_plugin to nvidia_plugin in Azure CI it will crash on openvino.
According what you've said, I think it is possible to fix with 2 PR in openvino and one PR in openvino_contrib.
In first openvino PR, I will add new device name like NVIDIA without removing old one. Once it will be merged we could merge openvino_contrib PR with renaming. And then I will create last PR in openvino with renaming in CI cuda_plugin folder to nvidia_plugin folder.
Is that what you meant ?

**Comment by lohika-denis-kotov** [comment]
@ilya-lavrenov @ilyachur Leaved for now both devices CUDA and NVIDIA.
Will be removed later when CUDAPlugin would be renamed and merged

**Review by ilya-lavrenov — APPROVED** [review]

**Pull request merged**
