### PR TITLE
[SMART RESHAPE] Replacing the HC constant for Reshape in Reshape-->Matmul sequence

### PR DESCRIPTION
**Pull request by yekruglov**
JIRA: 37084

### CODE REVIEW

**Review by jane-intel — CHANGES_REQUESTED** [review]
1. Lets accept any_input as reshape_pattern and add a separate test for that. It would work for 2D case and for ND -- we should check if it is constant.
2. Lets avoid static shape requirement for reshape output as this is SmartReshape transformations
3. Also we should check if old reshape pattern had 0 or -1 values but only for ND case, 2D works fine.
4. Do we really want to make D first dimensions? I thought we would like to perform relaxation over the 0 dimension (insert "-1" there) as it is usually batch dimension.

**Comment by jane-intel** [comment]
Also, please add a check for resulting output shape after the reshaping in the test -- so we can see that extra data goes to the right place.

**Review by GlebKazantaev — COMMENTED** [review]
@yekruglov are you going to complete this PR? or we can close it?

**Comment by yekruglov** [comment]
> @yekruglov are you going to complete this PR? or we can close it?

I suppose @jane-intel should know. Is it still relevant for SSR?

**Pull request closed without merging**
