### PR TITLE
[Snippets] Fixed SnippetsMarkSkipped pass for dynamic branches

### PR DESCRIPTION
**Pull request by a-sidorova**
### Details:
 - *At the moment Snippets doesn't support dynamic models. Plugin pass `SnippetsMarkSkipped` is called before tokenization which is safe for dynamic cases. So `SnippetsMarkSkipped` should be safe for dynamic branches as well. It means that we should check partial shapes firstly. The PR adds safe checks for shapes*

### Tickets:
 - *95424*

### CODE REVIEW

**Comment by a-sidorova** [comment]
@IvanNovoselov could you please take a look? Thanks in advance!

**Review by IvanNovoselov — APPROVED** [review]
Looks good, no suggestions

**Comment by a-sidorova** [comment]
@IvanNovoselov thank you!

@dmitry-gorokhov take a look please

**Review by dmitry-gorokhov — APPROVED** [review]
As we agreed lets create corresponding tickets for further SnippetsMarkSkipped coverage improvements

**Pull request merged**
