### PR TITLE
Moved ie tests

### PR DESCRIPTION
**Pull request by ilyachur**
### Details:
 - Moved IE tests to new inference folder
     - `inference-engine/tests` -> `src/tests`
     - `inference-engine/tests_deprecated` -> `src/tests_deprecated`

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
```
src/inference/tests_deprecated
```
Contains not IE tests, but plugins once - GNA and MYRIAD. Maybe we need to split them to 2 plugins binaries?

**Comment by ilyachur** [comment]
> ```
> src/inference/tests_deprecated
> ```
> 
> Contains not IE tests, but plugins once - GNA and MYRIAD. Maybe we need to split them to 2 plugins binaries?

Will take a look

**Comment by ilya-lavrenov** [comment]
> inference-engine/tests

They contains not only IE tests, but plugins one, common infra etc. IE only tests are here https://github.com/openvinotoolkit/openvino/tree/master/inference-engine/tests/functional/inference_engine and here https://github.com/openvinotoolkit/openvino/tree/master/inference-engine/tests/unit/inference_engine

**Comment by ilyachur** [comment]
> > inference-engine/tests
> 
> They contains not only IE tests, but plugins one, common infra etc. IE only tests are here https://github.com/openvinotoolkit/openvino/tree/master/inference-engine/tests/functional/inference_engine and here https://github.com/openvinotoolkit/openvino/tree/master/inference-engine/tests/unit/inference_engine

Discussed offline I will move all tests to src/tests

**Pull request closed without merging**
