### PR TITLE
[CPU] fix strided_slice with new axis

### PR DESCRIPTION
**Pull request by xczhai**
### Details:
 - *fix new axis for stridedslice node*
 - *...*

### Tickets:
 - *152198*

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@xczhai Is it final impl?

**Comment by dmitry-gorokhov** [comment]
@xczhai btw, could you please extend existing shape infer test to cover the issue? https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_cpu/tests/unit/shape_inference_test/custom_shape_infer/strided_slice.cpp

**Comment by alanzhai219** [comment]
@dmitry-gorokhov 

1. For impl, current code is for verification for now. Not final solution. I am optimizing a new version.
2. For test, I will add a new test to cover such cases.

**Comment by xczhai** [comment]
Hi @dmitry-gorokhov 
1. For impl, current code is for verification for now. Not final solution. I am optimizing a new version.
2. For test, I will add a new test to cover such cases.

**Comment by xczhai** [comment]
rebase after #27171

**Review by maxnick — APPROVED** [review]
LGTM.
@dmitry-gorokhov , do you have any further comments?

**Review by dmitry-gorokhov — APPROVED** [review]

**Pull request merged**
