### PR TITLE
don't fold ShapeOf in TransposeSinking

### PR DESCRIPTION
**Pull request by evkotov**
### Details:
**This fix is a workaround for this Release only, we will investigate side effects of deleting  `shape_size(shape.get_shape()) != 1` condition from the pattern in the next Release.**

 - TransposeSinking prevents folding ShapeOf using DisableShapeOfConstantFolding transformation. But this transformation doesn't set disable_folding rt_info flag if shape_size(shape.get_shape()) != 1. Ticket describes the case of reshapability when we need to prevent doing folding ShapeOf node with shape [1,1,1].

 - add flag that leads to disable ShapeOf folding anyway
 - add unit test

### Tickets:
 - CVS-123305

### CODE REVIEW

**Comment by jane-intel** [comment]
Please describe the change and link a ticket -- I don't quite get why this change is needed.

**Comment by itikhono** [comment]
Please check the failed tests:
[  FAILED  ] CompileModelsTests.ModelWithShapeOf
[  FAILED  ] FrontEndConversionWithReferenceTestsF.ModelWithDilatedGroupConvolution

**Comment by jane-intel** [comment]
I believe this PR unraveled some issues in Transpose Sinking:

>     raise e.with_traceback(None)
> RuntimeError: Check 'input_order_shape.compatible(ov::PartialShape{arg_shape.rank()}) || (input_order_shape.is_static() && input_order_shape.rank() == 1 && input_order_shape[0] == 0)' failed at src/core/src/op/transpose.cpp:36:
> While validating node 'opset1::Transpose Transpose_21391 (Unsqueeze_21389[0]:f32[1,1,1,128], Constant_21390[0]:i64[1]) -> (dynamic[...])' with friendly_name 'Transpose_21391':
> Input order must have shape [n], where n is the rank of arg.
>

**Comment by evkotov** [comment]
I see multiple errors in ov_gna_func_tests caused by this fix. I need to investigate. Maybe it could be fixed by using ConstantFolding just after TransposeSinking in GnaPlugin::LoadNetwork

**Comment by evkotov** [comment]
Created [PR](https://github.com/openvinotoolkit/openvino/pull/20742) with the base idea adding flag

**Comment by evkotov** [comment]
> Please check the failed tests: [ FAILED ] CompileModelsTests.ModelWithShapeOf [ FAILED ] FrontEndConversionWithReferenceTestsF.ModelWithDilatedGroupConvolution

Fixed in another PR. Here it is not relevant

**Comment by evkotov** [comment]
> I see multiple errors in ov_gna_func_tests caused by this fix. I need to investigate. Maybe it could be fixed by using ConstantFolding just after TransposeSinking in GnaPlugin::LoadNetwork

Fixed by adding ConstantFolding

**Pull request closed without merging**
