### PR TITLE
[CPU][SSE41] linear_onnx interpolation mode was added to unfused cases for sse41

### PR DESCRIPTION
**Pull request by alexey-varyzgin**
'Linear_onnx' interpolation mode was added to unfused cases for sse41 as well as 'linear' mode in interpolation layer.

Ticket: 50484

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@chenhu-wang  could you please review.

Shouldn't we disable fusing for all modes is case sse42 is not available?

**Comment by dmitry-gorokhov** [comment]
@alexey-varyzgin @chenhu-wang  any updates?

**Comment by chenhu-wang** [comment]
> @alexey-varyzgin @chenhu-wang any updates?

@dmitry-gorokhov @alexey-varyzgin This change seems like an overkill to disable onnx-linear fusion for all target. What's more, the root cause is on sse41 mask used in eltwise fusion must be index of 0, while input idx is also 0(Vmm vmm_val = Vmm(0)). Too many diff when I apply patch to this branch.  Take a look please this separate [PR](https://github.com/openvinotoolkit/openvino/pull/5114).

**Comment by dmitry-gorokhov** [comment]
@alexey-varyzgin  @chenhu-wang  Closing because of proper fix: https://github.com/openvinotoolkit/openvino/pull/5114. Feel free to reopen in case any concerns.

**Pull request closed without merging**
