### PR TITLE
Fixed tbb behavior in case of single thread in arena

### PR DESCRIPTION
**Pull request by apankratovantonp**

### CODE REVIEW

**Comment by myshevts** [comment]
and where is re-enabling of the tbb-executor? :)

**Comment by apankratovantonp** [comment]
> and where is re-enabling of the tbb-executor? :)

Added

**Comment by apankratovantonp** [comment]
@dmitry-gorokhov Can it be merged?

**Comment by ilya-lavrenov** [comment]
@myshevts is it planned to be merged for 2022.1?

**Comment by apankratovantonp** [comment]
merged https://github.com/openvinotoolkit/openvino/pull/7455

**Comment by ilya-lavrenov** [comment]
@wangleis @sunxiaoxia2022  could you please finalize with this?

**Comment by wangleis** [comment]
@ilya-lavrenov Which platform and which plugin should be used to validate this PR?

**Comment by ilya-lavrenov** [comment]
> @ilya-lavrenov Which platform and which plugin should be used to validate this PR?

I suppose it's reproduced on any platform.

**Comment by akladiev** [comment]
This PR will be closed in 2 weeks in case of no activity.

**Comment by akladiev** [comment]
This PR was closed because it has been stalled for 2 week with no activity.

**Pull request closed without merging**
