### PR TITLE
[PP] Support for FP16 in Reorder cases

### PR DESCRIPTION
**Pull request by anton-potapov**
This tiny PR fixes up FP16 support introduced in #4141 

### Details:
 - added basic support for FP16 (plain wrapper over uint16_t)
 - extended Split/Merge operations to support it
 - tests

@nikita-kud , FYI

### CODE REVIEW

**Comment by ilyachur** [comment]
Can we move pre-processing tests from deprecated folder?

**Comment by anton-potapov** [comment]
> Can we move pre-processing tests from deprecated folder?

Sure we can, but IMHO it should be done as a separate PR

**Review by smirnov-alexey — APPROVED** [review]
Looks good to me

**Comment by anna-khakimova** [comment]
@anton-potapov please fix Split and Merge test failure for Debian 9 ARM and Ubuntu18.

**Review by rgarnov — APPROVED** [review]
Looks good, thanks!

**Comment by anton-potapov** [comment]
@ilya-lavrenov could you please merge it ?

**Comment by anna-khakimova** [comment]
@ilyachur Please take a look.

**Comment by anna-khakimova** [comment]
Looks good for me.

**Review by anna-khakimova — APPROVED** [review]
Looks good. Thanks.

**Review by ilyachur — APPROVED** [review]
Please move preproc tests from deprecated folder in the next PR.

**Comment by anton-potapov** [comment]
@ilyachur  thank you very much!

**Pull request merged**
