### PR TITLE
[GPU] program_helpers::are_layouts_identical fix

### PR DESCRIPTION
**Pull request by Lyamin-Roman**
### Tickets:
 - *76587*

### CODE REVIEW

**Review by byungilm — DISMISSED** [review]

**Comment by byungilm** [comment]
Hi @Lyamin-Roman,
Does this PR resolve the accuracy issue of the  target model resnest?
Did It change the result value?

**Comment by Lyamin-Roman** [comment]
> Hi @Lyamin-Roman, Does this PR resolve the accuracy issue of the target model resnest? Did It change the result value?

Yes, it solves the problem

**Review by vladimir-paramuzov — APPROVED** [review]
No perf regressions are detected for DLB scope.

**Comment by isanghao** [comment]
This is a revert of PR-8798

**Pull request merged**
