### PR TITLE
[Python API] Remove IENetLayer class

### PR DESCRIPTION
**Pull request by akuporos**
Removed IENetLayer class from Python API and removed using of the property layers from tests.

FYI: @artyomtugaryov @eaidova @ematroso @AlexKoff88 @vladimir-dudnik

### CODE REVIEW

**Review by ilya-lavrenov — APPROVED** [review]

**Review by ilyachur — APPROVED** [review]

**Review by nkogteva — APPROVED** [review]

**Comment by eaidova** [comment]
can not agree with these changes until issue with difference between network representation in ngraph and query network will not be solved.
We are blocked with affinity setting

**Comment by ilya-lavrenov** [comment]
What is the issue with QueryNetwork? Which device?

**Comment by ilyachur** [comment]
> What is the issue with QueryNetwork? Which device?

It is an issue that for some layers we set affinity: HETERO:CPU,GPU (for operations which were constant folded).
But it looks like it already should works after this PR:  https://github.com/openvinotoolkit/openvino/pull/2572

**Review by eaidova — APPROVED** [review]
OMZ migration on ngraph python API usage instead of layers prepared:
demos (layer param extraction and search parent node case) https://github.com/openvinotoolkit/open_model_zoo/pull/1700 - tests passed, can be merged right now
AC (affinity setting case) https://github.com/openvinotoolkit/open_model_zoo/pull/1671 - locally passed on current master branch, await update package on CI. Also recommended update ngraph python API docs about constant networks affinity (#41179) setting

**Pull request merged**
