### PR TITLE
Fix IE_CPU.exp_* nGraph UT on Mac

### PR DESCRIPTION
**Pull request by jdanieck**
### Details:
 - Revert commit c9672ee9ecf59effb500c73b2a8c93a778ca1225 which disables IE_CPU.exp_* tests in CI on mac
 - Increased tolerance on IE_CPU.exp_* tests by +2 compared to default, this translates to 16 [ULP](https://en.wikipedia.org/wiki/Unit_in_the_last_place) 

### Tickets:
 - 54227

### CODE REVIEW

**Review by azhogov — APPROVED** [review]

**Comment by jdanieck** [comment]
@ilyachur do we have or can agree on some tolerance threshold for ngraph backend tests? In case of 54227 issue CPU plugin fails on mac with default tolerance. Now, I can either increase tolerance or file a bug for CPU to investigate it (ref impl is based on std::exp hence most likely correct). 

From what I see tolerance is used like "if it fails on tolerance lets increase it" and it can result running tests with tolerance of 2^10 [ULT](https://en.wikipedia.org/wiki/Unit_in_the_last_place) (like in [here](https://github.com/openvinotoolkit/openvino/blob/master/ngraph/test/onnx/onnx_import_rnn.in.cpp#L1162);) which effectively tests nothing.

**Review by dmitry-gorokhov — APPROVED** [review]

**Review by jane-intel — APPROVED** [review]

**Review by ilyachur — APPROVED** [review]

**Pull request merged**
