### PR TITLE
added third party programs files

### PR DESCRIPTION
**Pull request by ttroilov**
added third party programs files for Inference Engine and Model Optimizer

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Do we really need this in root? We already have significant number of files in root folder

**Comment by ttroilov** [comment]
location changed to licensing/

**Review by ilya-lavrenov — APPROVED** [review]

**Review by ilyachur — APPROVED** [review]
LGTM, but one question:

Why do we have a separate file for mkl-dnn? We don't have another files for other OpenVINO components.
Moreover in this file for mkl-dnn we have next components:
- Googletest
- CMake
- Some fonts

Does it means that we use these components only for mkl-dnn?

**Comment by ilyachur** [comment]
@ttroilov Please re-run validation.

**Review by azhogov — APPROVED** [review]

**Comment by azhogov** [comment]
CI passed: https://openvino-ci.intel.com/job/private-ci/job/github_trigger/job/openvino/job/PR-2751/2/

**Pull request merged**
