### PR TITLE
[DOCS] Add docs about ignored subgraphs

### PR DESCRIPTION
**Pull request by andrey-churkin**
### Details:
- Add documentation about `nncf.Subgraph`

### Tickets:
 - 100999

### CODE REVIEW

**Comment by andrey-churkin** [comment]
@MaximProshin @tsavina Please have a look

**Comment by MaximProshin** [comment]
@andrey-churkin , please share the reference to html version

**Comment by andrey-churkin** [comment]
@tsavina Could you please guide me to where I can find the link to the HTML version?

**Comment by tsavina** [comment]
> @andrey-churkin , please share the reference to html version

http://openvino-doc.iotg.sclab.intel.com/nncf-docs/openvino-workflow/model-optimization-guide/quantizing-models-post-training/basic-quantization-flow.html

**Review by MaximProshin — APPROVED** [review]

**Pull request merged**
