### PR TITLE
Add asinh acosh atanh to python api

### PR DESCRIPTION
**Pull request by iimironov**

### CODE REVIEW

**Comment by postrational** [comment]
Overall looks good. Can we add some unit tests for these?

**Comment by lazarevevgeny** [comment]
@postrational, could you review this PR?

**Comment by lazarevevgeny** [comment]
There are some merge conflicts. Please, resolve

**Comment by lazarevevgeny** [comment]
Please, resolve merge conflicts.

**Comment by iimironov** [comment]
@lazarevevgeny please review.

**Comment by lazarevevgeny** [comment]
> @lazarevevgeny please review.

Approved. But I would like to see the review from @postrational since I am not deeply familiar with the PythonAPI.

**Pull request merged**
