### PR TITLE
Memory leaks in gemm module

### PR DESCRIPTION
**Pull request by vladislav-volkov**
### Details:
 - Several memory leaks fixed in the gemm module.

### Tickets:
 - CVS-61304

PR in oneDNN-fork: https://github.com/openvinotoolkit/oneDNN/pull/66

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
is it valid for 2021.4? should be ported?

**Comment by vladislav-volkov** [comment]
Yes on 2021.4 it is also should be fixed.

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
@antonvor FYI. Could you please check is it fixed in oneDNN 2.3 or not.

**Comment by vladislav-volkov** [comment]
@dmitry-gorokhov In oneDNN 2.3 the bug is also present.

**Pull request merged**
