### PR TITLE
Xp/revise embedding bag

### PR DESCRIPTION
**Pull request by xipingyan**
### Details:
 - *Revise EmbeddingSegmentsSum*
 - *Revise EmbeddingBagOffsetsSum*
 - *Revise EmbeddingBagPackedSum. Replace EmbeddingBag.*

### Tickets:
 - *37493*
 - *44632*
 - *44633*

### CODE REVIEW

**Comment by andrei-kochin** [comment]
@xipingyan could you please split this to 3 separate PRs as it would be hard to review. Thanks!

**Review by mitruska — APPROVED** [review]
Actually as I can see, this PR doesn't contain any operation or reference implementation changes, but only additional tests and one line spec changes, what can be approved from my side.

**Comment by andrei-kochin** [comment]
@ilyachur please take a look

**Review by ilyachur — APPROVED** [review]

**Comment by ilyachur** [comment]
The last commit to this branch was 18 day ago. Please update this branch to the latest master

**Comment by xipingyan** [comment]
> The last commit to this branch was 18 day ago. Please update this branch to the latest master

Rebased and built pass.

**Pull request merged**
