### PR TITLE
[PT FE] Add support for ones_like and zeros in fx.

### PR DESCRIPTION
**Pull request by AsakusaRinne**
### Details:
 - *Add support of ones_like and zeros in fx*

These two ops appear in LLaVA and AudioCraft models respectively.

### Tickets:
 - *No ticket id*

### CODE REVIEW

**Comment by AsakusaRinne** [comment]
@mvafin I'll appreciate it if you'd like to review it. It seems that all the necessary implementations in c++ part has been completed. I added them to the table of supported fx ops and add `mark.precommit_fx_backend` attribute to the unit test functions and they passed. Please correct me if I misunderstand it. :)

**Comment by mvafin** [comment]
Tests fail with unexpected arguments. You can skip tests for specific arguments that aren't supported on torch.compile

**Comment by AsakusaRinne** [comment]
Just noticed that #23310 also adds some fx ops and it fixed a BUG which I also met in `src/frontends/pytorch/src/input_model.cpp`. Should I pick the fix and move on, or wait until #23310 get merged?

**Comment by mvafin** [comment]
> Just noticed that #23310 also adds some fx ops and it fixed a BUG which I also met in `src/frontends/pytorch/src/input_model.cpp`. Should I pick the fix and move on, or wait until #23310 get merged?

You can pick the fix. No need to wait for other PR

**Review by mvafin — APPROVED** [review]

**Comment by mvafin** [comment]
build_jenkins

**Comment by mvafin** [comment]
build_jenkins

**Comment by mvafin** [comment]
Please merge master

**Comment by AsakusaRinne** [comment]
Conflicts have been resolved. :)

**Comment by mvafin** [comment]
build_jenkins

**Pull request merged**
