### PR TITLE
[DOCS] Use `gpg` instead of `apt-key add` to add the GPG key to APT keyrings directory

### PR DESCRIPTION
**Pull request by ytxmobile98**
### Details:

Since `apt-key add` is deprecated, I tried by myself to instead use the `gpg` command to add the GPG key to APT keyrings directory.

This is what I tried on my own: <https://gist.github.com/ytxmobile98/b198a8ef4d2affd713780b16159a6618#file-install-md>

### Tickets:
 - *ticket-id*

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Could you please also change it here https://github.com/openvinotoolkit/openvino/blob/master/.github/workflows/job_debian_packages.yml#L53 ?
It will be validated by CI service and we can check whether the change is valid on wider range of OSes

**Comment by ytxmobile98** [comment]
> Could you please also change it here https://github.com/openvinotoolkit/openvino/blob/master/.github/workflows/job_debian_packages.yml#L53 ? It will be validated by CI service and we can check whether the change is valid on wider range of OSes
> 
> Will it work on Ubuntu 20.04? It's minimal version supported by OpenVINO.

@ilya-lavrenov Hi, I have updated the yml file.

**Review by artanokhov — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
build_jenkins

**Comment by ytxmobile98** [comment]
@ilya-lavrenov @artanokhov It came to my attention that the `requirements_pytorch` file uses `optimum==1.22.0` which is the latest version as of now, but [`optimum-intel`](https://github.com/huggingface/optimum-intel) uses `optimum` of version `1.23.0.dev0`. Should I do something to fix this problem at the moment, or can it be safely ignored?

**Comment by ilya-lavrenov** [comment]
> @ilya-lavrenov @artanokhov It came to my attention that the `requirements_pytorch` file uses `optimum==1.22.0` which is the latest version as of now, but [`optimum-intel`](https://github.com/huggingface/optimum-intel) uses `optimum` of version `1.23.0.dev0`. Should I do something to fix this problem at the moment, or can it be safely ignored?

It will be fixed by @mvafin soon

**Comment by ilya-lavrenov** [comment]
build_jenkins

**Pull request merged**
