### PR TITLE
[CPU] Added GELU-7 support

### PR DESCRIPTION
**Pull request by a-sidorova**
### Details:
 - Added GELU-7 support

### Tickets:
 - 49913

### CODE REVIEW

**Comment by a-sidorova** [comment]
@dmitry-gorokhov take a look please

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
@ilyachur  could you please take a look on ngraph part?

**Comment by dmitry-gorokhov** [comment]
@a-sidorova  please rebase the PR on latest master

**Review by ilyachur — APPROVED** [review]
nGraph part LGTM

**Comment by ilyachur** [comment]
Please resolve merge conflicts

**Comment by a-sidorova** [comment]
@dmitry-gorokhov, @ilyachur merged master and resolved conflicts
Thank you!

**Comment by dmitry-gorokhov** [comment]
@a-sidorova Could you please rebase on latest master, cause I need fresh CI to merge the PR.

**Comment by a-sidorova** [comment]
@dmitry-gorokhov Done

**Pull request merged**
