### PR TITLE
[CPU] Topk node extend to support horizontal sort for all layouts for top_k == 1

### PR DESCRIPTION
**Pull request by xuchen-intel**
### Details:
 - *For corner cases sorting top_1 out of a large amount of elements for the innermost dim of planar layout, vectorized vertical sorting and algorithm optimization(heap sort) lost their advantages over previous bubble sort of c++ impl. This issue is fixed by adding a horizontal sorting routine to increase the vectorized sorting efficiency. And it turns out the existing topk_bubble_BLK_on_channel_horiz routine can be perfectly reused.*

### Tickets:
 - *79058*

### CODE REVIEW

**Comment by xuchen-intel** [comment]
@dmitry-gorokhov Hi Dmitry, could you please take a look?

**Comment by dmitry-gorokhov** [comment]
@a-sidorova could you please review the patch and also help with internal performance validation?

**Review by a-sidorova — APPROVED** [review]
LGTM

DLB has been passed. Analysis is attached to the ticket

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
@a-sidorova thanks!

**Comment by dmitry-gorokhov** [comment]
@xuchen-intel Could you please rebase the PR on latest master to get fresh CI?

**Comment by xuchen-intel** [comment]
> @xuchen-intel Could you please rebase the PR on latest master to get fresh CI?

@dmitry-gorokhov Rebased and CI is green now. Thanks Dmitry!

**Pull request merged**
