### PR TITLE
[67541] - face-detection-0205, 0206 issues fixed (incorrect dimensions error)

### PR DESCRIPTION
**Pull request by DariaMityagina**
Ticket: C#67541
Error: `21:01:06  RuntimeError: Const layer Constant_23182 has incorrect dimensions in the output data 0`

### CODE REVIEW

**Comment by DariaMityagina** [comment]
JFYI: I see `onnx_expand_function_greater_or_equal_inside_if` test failure in pre-commit. Will take care of it.

**Comment by DariaMityagina** [comment]
I am not sure if the solution is perfectly valid.
Here are my conclusions on the issue:
- In [this PR ](https://github.com/openvinotoolkit/openvino/pull/7705)transformation `convert_reduce_to_pooling` has been changed. The check for empty shape has been removed. So since then it is possible to add a Reshape with an empty shape -> reshape to scalar there.
- But it is not possible to further work with such a change in case of some models.
- The ability to add a Reshape with an empty shape makes the check, which I propose to remove, redundant.
This way face-detection-0205, 0206 models can be compiled.

I will continue checking if there are other ways to fix this. Other than
- https://github.com/openvinotoolkit/openvino/pull/14687/commits/679bf37f445effbe8dbd53ea980a1701897635df
- or https://github.com/openvinotoolkit/openvino/pull/14687/commits/c6dbe0bd19bfa7a2c09c267e572068e520062ee5

**Comment by DariaMityagina** [comment]
@AdrianVarlan , @AndreeaAtudorei hi!
Could you please take a look at this PR?

**Review by AndreeaAtudorei — APPROVED** [review]

**Comment by DariaMityagina** [comment]
@Maxim-Doronin hi!
Could you please take a look and merge this PR please?

**Review by Maxim-Doronin — APPROVED** [review]

**Review by Maxim-Doronin — COMMENTED** [review]
High risk of performance degradation. Please attach validation reports

**Comment by DariaMityagina** [comment]
DL-Benchmark is in progress: https://ci-dlbenchmark-icv.iotg.sclab.intel.com/job/DL-Benchmark/job/master/job/BenchmarkApp/1866/

**Comment by DariaMityagina** [comment]
DLB re-run: https://ci-dlbenchmark-icv.iotg.sclab.intel.com/job/DL-Benchmark/job/master/job/BenchmarkApp/1974/

**Comment by DariaMityagina** [comment]
DLB re-run: https://ci-dlbenchmark-icv.iotg.sclab.intel.com/job/DL-Benchmark/job/master/job/BenchmarkApp/1982/

**Comment by DariaMityagina** [comment]
> High risk of performance degradation. Please attach validation reports

Performance results are in the ticket.
Could you please take a look at them?

**Comment by DariaMityagina** [comment]
@Maxim-Doronin hi!
Is it possible to merge this PR judging by the latest results in the ticket?

**Review by Maxim-Doronin — APPROVED** [review]

**Pull request merged**
