### PR TITLE
DOCS: Quantization doc rewrites for 22.2

### PR DESCRIPTION
**Pull request by msmykx-intel**
Rewrites for [Quantizing Models Post-training](https://docs.google.com/document/d/1bRPBFv_-hTtukoNm5ACeINNIzOcEFYPV_d_0vE1OM1g/edit?usp=sharing) & [Compressing Models During Training](https://docs.google.com/document/d/166JvRiaNmcE9TnaZ9ga-1VkaZr_UyQRoPoqnWFJJkCY/edit?usp=sharing) based on changes by Evan Juras.

Additional Changes:

* Replaced graph format from png to svg.

### CODE REVIEW

**Review by kblaszczak-intel — APPROVED** [review]

**Comment by ilyachur** [comment]
@akladiev Why do we have Jenkins run for this PR?

**Comment by ilyachur** [comment]
@AlexKoff88 Could you take a look to PoT documentation?

**Comment by kblaszczak-intel** [comment]
This PR is one of 3 (original and 2 ports). One of them, we were able to merge successfully:
https://github.com/openvinotoolkit/openvino/pull/14514
If there are any corrections necessary, we would appreciate if we could make them in separate PRs, just not to lose alignment between branches.

**Comment by kblaszczak-intel** [comment]
@AlexKoff88 Yep. Fortunately, it seems there is just one file conflict. The file is "introduction.md" and in the https://github.com/openvinotoolkit/openvino/pull/14437 PR the only changes are the title and removal of one block of text. 
Could we remove these changes entirely from that PR? We could merge this one first, based on BDTi's rewrite, and then merge your PR without conflicts - I also suggest merging it with just a basic review, later we can improve but for now we shouldn't wait too long with merging.

**Pull request merged**
