### PR TITLE
Fixed c samples build

### PR DESCRIPTION
**Pull request by mryzhov**
fixed 38816 - Failure to build samples in C

### CODE REVIEW

**Review by ilyachur — COMMENTED** [review]
You added the `format_reader` folder to the paths.
How these changes help you to solve the issue?

**Comment by mryzhov** [comment]
> You added the `format_reader` folder to the paths.
> How these changes help you to solve the issue?
we use universal CMakeLists for all samples:
if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/common/format_reader")
    add_subdirectory(common/format_reader)
endif()

So, I just aligned cpp and c "common directory" structure instead of changing cmakelists.

**Comment by ilya-lavrenov** [comment]
Proper fix https://github.com/openvinotoolkit/openvino/pull/2293

**Review by ilya-lavrenov — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
@mryzhov please, port this to the master branch as well

**Pull request merged**
