### PR TITLE
Update build-instruction.md for MacOsX

### PR DESCRIPTION
**Pull request by andrew-zaytsev**
Update build instructions for macOS according to comments from https://github.com/openvinotoolkit/openvino/issues/1566

### CODE REVIEW

**Comment by ryanloney** [comment]
@andrew-zaytsev When trying to install dependencies on MacOS 10.15.5, I see this message `Unknown OS, please install build dependencies manually` From Step 2. of the Build instructions. Is this expected behavior?

**Comment by ryanloney** [comment]
For Step 3. of the instructions, it would be more clear to change `mkdir build` to `mkdir build && cd build`

**Comment by ilya-lavrenov** [comment]
@AlexPeskov could you please check that docs is updated properly?

**Comment by azhogov** [comment]
please create branch in a fork

**Pull request closed without merging**
