### PR TITLE
Revise ExtractImagePatches op - specification

### PR DESCRIPTION
**Pull request by blesniewski**
### Details:
 - *Example inputs were changed to increase readability*

### Tickets:
 - *37494*

### CODE REVIEW

**Comment by blesniewski** [comment]
Changed inputs look like this:
image

**Review by jdanieck — APPROVED** [review]
We tend to remove references to other frameworks, so I would remove bellow sentence.
`The *ExtractImagePatches* operation is similar to the TensorFlow* operation [ExtractImagePatches](https://www.tensorflow.org/api_docs/python/tf/image/extract_patches).`

**Comment by jdanieck** [comment]
@tomdol maybe you'll have time to review & merge to offload @ilyachur ? Unreviewed PR's started to pile up because of the release. CC: @andrei-kochin

**Comment by ilyachur** [comment]
@lazarevevgeny Please have a look

**Review by lazarevevgeny — CHANGES_REQUESTED** [review]
Please, remove link to the TF operation.

**Review by lazarevevgeny — APPROVED** [review]

**Pull request merged**
