### PR TITLE
[CI] [GHA] Add retries for APT, update deadsnakes action

### PR DESCRIPTION
**Pull request by akashchi**
### Details:
 - Hopefully, this should improve the `apt update` and `apt install` stability and mitigate things like [`Could not connect to ppa.launchpad.net:80 (185.125.190.80), connection timed out`](https://github.com/openvinotoolkit/openvino/actions/runs/7667587744/job/20898079075) and [`W: Some index files failed to download. They have been ignored, or old ones used instead.`](https://github.com/openvinotoolkit/openvino/actions/runs/7667587744/job/20898079075) when installing Python using the deadsnakes action.

The corresponding [changes in the deadsnakes action](https://github.com/akashchi/deadsnakes-action/commit/92417281055a5878a0450f240a5b95883eb2d7e2).

### Tickets:
 - *130955*

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
> The corresponding [changes in the deadsnakes action](https://github.com/akashchi/deadsnakes-action/commit/92417281055a5878a0450f240a5b95883eb2d7e2).

should we move this action to OpenVINO repo?

**Comment by akashchi** [comment]
> > The corresponding [changes in the deadsnakes action](https://github.com/akashchi/deadsnakes-action/commit/92417281055a5878a0450f240a5b95883eb2d7e2).
> 
> should we move this action to OpenVINO repo?

good point. the deadsnakes action repository has an [MIT license](https://github.com/deadsnakes/action?tab=MIT-1-ov-file#readme), is it possible to use a LICENSE file for a custom action in a repository with an already stated license? I am unsure.

**Review by akladiev — APPROVED** [review]

**Comment by akladiev** [comment]
Hopefully one day we'll be able to move copy-pasted apt configuration from pipelines to Dockerfiles

**Comment by ilya-lavrenov** [comment]
Looks like we still have similar issues https://github.com/openvinotoolkit/openvino/actions/runs/7737321765/job/21096103460?pr=22472

**Pull request merged**
