### PR TITLE
update dump_check.py and readme.md in cpu/tools

### PR DESCRIPTION
**Pull request by xczhai**
### Details:
 - *better display the command line at the end of the README.md*
 - *fix the runtime error of register_pass*

### Tickets:
 - N/A

### CODE REVIEW

**Review by luweizhou2016 — APPROVED** [review]
Okay for me.

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
@xczhai Could you please rebase the PR on latest master to get green CI?

**Comment by xczhai** [comment]
> @xczhai Could you please rebase the PR on latest master to get green CI?

Sure. I will.

**Comment by xczhai** [comment]
> @xczhai Could you please rebase the PR on latest master to get green CI?

@dmitry-gorokhov  CI is green and ready to merge. Could you trigger the merge operation? Thanks.

**Pull request merged**
