### PR TITLE
[CPU] Reimplement TopologicalSort

### PR DESCRIPTION
**Pull request by EgorDuplensky**
to simplify and get rid of extra Node class member variables

TODO:
- [x] Performance regression check

### Tickets:
- 129699

### CODE REVIEW

**Review by dmitry-gorokhov — APPROVED** [review]
LGTM. Lets just make sure `SortTopologically` is not degradated from performance perspective as long as it is called multiple times during graph optimization

**Comment by EgorDuplensky** [comment]
> LGTM. Lets just make sure `SortTopologically` is not degradated from performance perspective as long as it is called multiple times during graph optimization

SortTopologically itself is now 3x+ times faster, mainly because elements are always pushed to the back of the vector.
DLB regression check is in progress.

**Comment by dmitry-gorokhov** [comment]
@EgorDuplensky Please resolve merge conflicts

**Comment by EgorDuplensky** [comment]
@dmitry-gorokhov rebased

**Comment by EgorDuplensky** [comment]
@dmitry-gorokhov Rebased. Regression check showed no issues.

**Pull request merged**
