### PR TITLE
[CPU][ARM64] Add JIT emitter for Eltwise LogicalAnd operation

### PR DESCRIPTION
**Pull request by nashez**
### Details:

* Added a jit_logical_and_emitter derived class in aarch64/jit_eltwise_emitters
* Created entry Algorithm::EltwiseLogicalAnd in the get_supported_precisions in nodes/kernels/aarch64
* Add the EltwiseLogicalAnd entry in the aarch64 executors supported algorithms

### Tickets:
Closes: #27503

### CODE REVIEW

**Comment by nashez** [comment]
@a-sidorova @dmitry-gorokhov Please review the changes

**Comment by a-sidorova** [comment]
build_jenkins

**Review by a-sidorova — APPROVED** [review]
@nashez thank you for the one more contribution! 👍🏼 

One Jenkins job is red due to internal problem which has been fixed. Could you please rebase the branch? I will relaunch CI

**Comment by a-sidorova** [comment]
build_jenkins

**Pull request merged**
