### PR TITLE
[Tools] Support NumPy 1.24

### PR DESCRIPTION
**Pull request by rkazants**
**Details:** Avoid use of NumPy deprecated types in Tools

**Ticket:** 99501

Signed-off-by: Kazantsev, Roman <roman.kazantsev@intel.com>

### CODE REVIEW

**Review by l-bat — APPROVED** [review]

**Comment by rkazants** [comment]
Failed due to Python bindings tests. Need to re-run after https://github.com/openvinotoolkit/openvino/pull/14726 merge.

**Comment by tomdol** [comment]
I think this PR should also remove the upper bound for numpy from all of the places in OV to make sure those changes actually have an effect on the code in runtime. There's a chance that more numpy symbols cause an error now and the CI pipelines should be able to check that.

**Comment by rkazants** [comment]
> I think this PR should also remove the upper bound for numpy from all of the places in OV to make sure those changes actually have an effect on the code in runtime. There's a chance that more numpy symbols cause an error now and the CI pipelines should be able to check that.

We should leave upper bounds for extras installation because these versions correspond to frameworks validated together with OV. Now I top-up these versions to 1.24 NumPy and the testing performs against 1.24 version.

**Comment by AlexKoff88** [comment]
POT CI is down due to MO incompatibility with Numpy 1.24 (MO version is fixed in POT CI). Once this PR is merged POT CI branches should be moved forward.

**Review by AlexKoff88 — APPROVED** [review]

**Review by eaidova — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
Can we increase supported lumpy version in 2022.3 and port these changes?
Looks like useful content for LTS

**Comment by rkazants** [comment]
> Can we increase supported lumpy version in 2022.3 and port these changes? Looks like useful content for LTS

Are we removing upper-bound for 2022.3.1 release? If yes, then we need it. Otherwise, we anyway override numpy version to less 1.24

**Comment by ilya-lavrenov** [comment]
> 

I think we should increase upper bound for 2022.3.1, but not to remove it completely. 
So, users could use newer numpy versions with LTS.

**Pull request merged**
