### PR TITLE
Intel copyright year update to 2024

### PR DESCRIPTION
**Pull request by jacekpawlak**
Updated the copyright year from 2018-2023 to 2018-2024 in all openvino files

Ref. to script: CVS-101144

Command used:
```bash
git grep -lz '2018-2023 Intel Corporation' | xargs -0 sed -i '' -e 's/2018-2023 Intel Corporation/2018-2024 Intel Corporation/g'
```

### CODE REVIEW

**Review by ilya-lavrenov — APPROVED** [review]

**Review by rkazants — CHANGES_REQUESTED** [review]
guys, how did you review these changes? This is impossible. We are not sure now that all changes are valid and do not break functionality.
Let us split copyright update into parts.

**Comment by ilya-lavrenov** [comment]
> guys, how did you review these changes?

Random sampling 😄

**Comment by rkazants** [comment]
> > guys, how did you review these changes?
> 
> Random sampling 😄

My random sampling is hang on after the fifth file:)

**Review by mlukasze — APPROVED** [review]

**Comment by mlukasze** [comment]
Please merge branch to the master & resolve conflicts

**Comment by t-jankowski** [comment]
> guys, how did you review these changes?

```
git remote add -t copyright2 --fetch --no-tags jacekpawlak https://github.com/jacekpawlak/openvino.git
git merge-base upstream/master jacekpawlak/copyright2
git diff -U0 6330dfda1212b1772fa83c273814247880a4c84c..jacekpawlak/copyright2 | sed -En -e '/^[+-]{3}/ d' -e '/^[+-]/ p' | awk '!_[$0]++'

```

**Review by t-jankowski — APPROVED** [review]
There are 'flavors' than 2018-2023 over there. Please address those in a separate PR.
```
$ grep -PIrh --exclude-dir=build --exclude-dir=bin '2[\d-\s]+Intel' | grep -v '2018-2023' | awk '!_[$0]++' | wc -l
219

```

**Review by PiotrKrzem — APPROVED** [review]

**Review by p-wysocki — APPROVED** [review]

**Comment by jacekpawlak** [comment]
Closing due to merge conflicts. New PR: https://github.com/openvinotoolkit/openvino/pull/23370

**Pull request closed without merging**
