### PR TITLE
FreezeNodes external transformation

### PR DESCRIPTION
**Pull request by itikhono**
ticket: 42975
Introducing a new external transformation to replace Nodes in ngraph::function with Constants.
1. Implemented ngraph transformation
2. Implemented CNNNetwork interface
3. Added unit tests

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Why do we need this transformation for end user?

**Comment by itikhono** [comment]
> Why do we need this transformation for end user?

1. Parity with MO: we can freeze Parameters (or any other Nodes) using ngraph instead of re-generate IR
2. resolve the special case of LowLatency transformation (more details in 42975 ticket)

**Comment by ilya-lavrenov** [comment]
> resolve the special case of LowLatency transformation (more details in 42975 ticket)

Can this special case be handled inside `LowLatency` transformation without direct call to `FreezeNodes`?

**Comment by itikhono** [comment]
> > resolve the special case of LowLatency transformation (more details in 42975 ticket)
> 
> Can this special case be handled inside `LowLatency` transformation without direct call to `FreezeNodes`?

Unfortunately not

**Comment by GlebKazantaev** [comment]
@itikhono should we close this PR?

**Comment by itikhono** [comment]
After discussion, it was decided to postpone this task. PR -> draft

**Comment by ilya-lavrenov** [comment]
is it still valid?

**Pull request closed without merging**
