### PR TITLE
[DO NOT MERGE]Fix shape mismatching in fusing per channel

### PR DESCRIPTION
**Pull request by xuchen-intel**
### Details:
 - *Fix shape mismatching in fusing per channel, when shape[1] is not the channel dimension*

### Tickets:
 - *62846*

### CODE REVIEW

**Comment by xuchen-intel** [comment]
@dmitry-gorokhov Hi Dmitry, could you please take a look?

**Comment by dmitry-gorokhov** [comment]
@EgorDuplensky could you please check how we can align this with changes we do on spr branch

**Comment by andrei-kochin** [comment]
#8009 is rebased so you are free to proceed with rebase

**Comment by dmitry-gorokhov** [comment]
@xuchen-intel Any news here? Could you please also elaborate current behavior: can current impl on **master** lead to incorrect accuracy results or we just disable fusing in case of unusual axis?

**Comment by xuchen-intel** [comment]
> @xuchen-intel Any news here? Could you please also elaborate current behavior: can current impl on **master** lead to incorrect accuracy results or we just disable fusing in case of unusual axis?

@dmitry-gorokhov Hi Dmitry. I don't have the bandwidth to update this PR now. However I don't think current impl will lead to any accuracy results. Just some test cases about fusing per channel in reduce node is disabled. I think it's OK to include the PR in the next milestone.

**Comment by dmitry-gorokhov** [comment]
Was fixed in separate PR: https://github.com/openvinotoolkit/openvino/pull/11162

**Pull request closed without merging**
