### PR TITLE
Use Zi FS instead of Z7

### PR DESCRIPTION
**Pull request by ilyachur**
### Details:
 - Use the same approach with `Zi` flags as we use for plugins: https://github.com/openvinotoolkit/openvino/pull/14651

### Tickets:
 -  NA

### CODE REVIEW

**Comment by itikhono** [comment]
Could you elaborate more on this change in the description?

**Comment by ilyachur** [comment]
> Could you elaborate more on this change in the description?

@itikhono I think the best investigation you can find here: https://github.com/openvinotoolkit/openvino/pull/14651

**Comment by olpipi** [comment]
I launched 5 Windows debug builds. 3 of them are failed with liker error (255)
Next test binaries are failed to build: myriadFuncTests ov_core_unit_tests conformanceTests

So probably this change introduce some kind of regression

**Comment by olpipi** [comment]
> I launched 5 Windows debug builds. 3 of them are failed with liker error (255) Next test binaries are failed to build: myriadFuncTests ov_core_unit_tests conformanceTests
> 
> So probably this change introduce some kind of regression

hmm.. Probably I'm wrong. Here is Windows debug build from last merged commit. And it failed with the same error:
https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/build-windows-vs2019/207782/

**Review by itikhono — APPROVED** [review]

**Pull request merged**
