### PR TITLE
[CPU] Fixed data storing for AVG Pooling with PostOps on avx2

### PR DESCRIPTION
**Pull request by egorshul**
### OneDNN PR:
- https://github.com/openvinotoolkit/oneDNN/pull/105

### Tickets:
 - *74131*

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@antonvor Please review the PR

**Review by antonvor — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
@egorshul please rebase the PR on latest master.

**Comment by dmitry-gorokhov** [comment]
Can be merged after internal validation

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by egorshul** [comment]
DLB is passed. The result is attached in the ticket.

**Comment by dmitry-gorokhov** [comment]
Left comment in https://github.com/openvinotoolkit/oneDNN/pull/105

**Pull request merged**
