### PR TITLE
Revert "Header length for supported model detection is increased"

### PR DESCRIPTION
**Pull request by rblaczkowski**
Reverts openvinotoolkit/openvino#1340 to check if this is a case of regression in ONNX CI check

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
@rblaczkowski could you please provide logs where that commit brake something?

**Comment by ilya-lavrenov** [comment]
don't merge

**Comment by ilyachur** [comment]
How is it related? This PR didn't touch ONNX code...

**Comment by ilyachur** [comment]
@rblaczkowski @vladislav-volkov Could you please take a look?

```
    def test_import_onnx_function():
        model_path = os.path.join(os.path.dirname(__file__), "models/add_abc.onnx")
        ie = IECore()
>       ie_network = ie.read_network(model=model_path)

tests/test_onnx/test_onnx_import.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ie_api.pyx:261: in openvino.inference_engine.ie_api.IECore.read_network
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   RuntimeError: Failure parsing data from the provided input stream
```

As I can see from this stack trace, in this test we shouldn't touch code from this PR.
This PR affects only IR pipeline or loading models from memory. But you load model from disk and we shouldn't touch IR reader because based on extension we can select ONNX reader.

I don't understand how this code can affect this test.

**Comment by rblaczkowski** [comment]
Hi,

I added team members to investigate this.

Current situation is that the change: https://github.com/openvinotoolkit/openvino/pull/1340

Provided regression in ONNX CI tests:
https://crackerjack.intel.com/blue/organizations/jenkins/onnx%2Fopenvino_ci/detail/PR-1340/1/pipeline/


After create a new PR with revert this affected PR (here: https://github.com/openvinotoolkit/openvino/pull/1354)  it resolves this regression – so it is the proof that the #1340 PR was the root cause of regression.


Thanks,
Rafal

**Comment by rblaczkowski** [comment]
OK, guys, so it seems that this Adam’s workaround resolves this problem:
https://github.com/openvinotoolkit/openvino/pull/1355

ONNX CI tests passes – it is important to resolve regression, so two ways we have:
1) Revert affected PR
2) Add Adam’s workaround

Regards,
Rafal

From: "Blaczkowski, Rafal" <rafal.blaczkowski@intel.com>
Date: Thursday, 16 July 2020 at 16:24
To: openvinotoolkit/openvino <reply@reply.github.com>, openvinotoolkit/openvino <openvino@noreply.github.com>
Cc: IOTG VMC PL ONNX <iotg.vmc.pl.onnx@intel.com>
Subject: Re: [openvinotoolkit/openvino] Revert "Header length for supported model detection is increased" (#1354)

Hi,

I added team members to investigate this.

Current situation is that the change: https://github.com/openvinotoolkit/openvino/pull/1340

Provided regression in ONNX CI tests:
https://crackerjack.intel.com/blue/organizations/jenkins/onnx%2Fopenvino_ci/detail/PR-1340/1/pipeline/


After create a new PR with revert this affected PR (here: https://github.com/openvinotoolkit/openvino/pull/1354)  it resolves this regression – so it is the proof that the #1340 PR was the root cause of regression.


Thanks,
Rafal

**Comment by ilyachur** [comment]
@rblaczkowski I propose to wait for @arogowie-intel PR if it is ready.

Because I really don't understand how this code can affect these tests.

**Comment by postrational** [comment]
Let's merge this PR to fix the current CI build break. Later we can combine the original PR with Adam's workaround.

**Comment by ilyachur** [comment]
> Let's merge this PR to fix the current CI build break. Later we can combine the original PR with Adam's workaround.

I just want to avoid situation that it is a false positive result. Because I don't see any reason why this code should affect ONNX tests.

**Pull request merged**
