### PR TITLE
Revert "[BENCHMARK_APP] Show input command in output"

### PR DESCRIPTION
**Pull request by nkogteva**
Reverts openvinotoolkit/openvino#13402

Windows looks like:
image

### CODE REVIEW

**Comment by Wovchena** [comment]
I already reported that to @PiotrKrzem. As I understand, https://github.com/openvinotoolkit/openvino/pull/12814/commits/e92c9f6d612957ab416f82c54213df0b3a6e09ec#diff-e7a536b4318b2270a4ee67f723b8ff57e9a5aed0928c11fa46e5a0b02db6300fR46 fixes that

**Comment by nkogteva** [comment]
> I already reported that to @PiotrKrzem. As I understand, [e92c9f6#diff-e7a536b4318b2270a4ee67f723b8ff57e9a5aed0928c11fa46e5a0b02db6300fR46](https://github.com/openvinotoolkit/openvino/commit/e92c9f6d612957ab416f82c54213df0b3a6e09ec#diff-e7a536b4318b2270a4ee67f723b8ff57e9a5aed0928c11fa46e5a0b02db6300fR46) fixes that

I think we don't need this printing from tool at all.

**Comment by PiotrKrzem** [comment]
> I already reported that to @PiotrKrzem. As I understand, [e92c9f6#diff-e7a536b4318b2270a4ee67f723b8ff57e9a5aed0928c11fa46e5a0b02db6300fR46](https://github.com/openvinotoolkit/openvino/commit/e92c9f6d612957ab416f82c54213df0b3a6e09ec#diff-e7a536b4318b2270a4ee67f723b8ff57e9a5aed0928c11fa46e5a0b02db6300fR46) fixes that

Yes, this should work just fine now! Compiled on Windows & it does not appear to print empty spaces anymore
image


> > I already reported that to @PiotrKrzem. As I understand, [e92c9f6#diff-e7a536b4318b2270a4ee67f723b8ff57e9a5aed0928c11fa46e5a0b02db6300fR46](https://github.com/openvinotoolkit/openvino/commit/e92c9f6d612957ab416f82c54213df0b3a6e09ec#diff-e7a536b4318b2270a4ee67f723b8ff57e9a5aed0928c11fa46e5a0b02db6300fR46) fixes that
> 
> I think we don't need this printing from tool at all.

Personally, I found the realpath of the executable to be quite useful, other arguments are most often printed in the Step #8 of the application anyways. I'll add @helena-intel to the reviewers so she could also add her insights to this conversation

**Review by Wovchena — APPROVED** [review]
Approving following @p-durandin's mail

**Review by PiotrKrzem — APPROVED** [review]

**Comment by nkogteva** [comment]
Rebased PR https://github.com/openvinotoolkit/openvino/pull/14027

**Pull request closed without merging**
