### PR TITLE
Create pre_release_feedback.yml

### PR DESCRIPTION
**Pull request by hbalasu1**
Adding pre-release feedback template submission

### Details:
 - Add pre-release feedback submission template 
 - Customer able to provide feedback on the pre-release for improvement

### Tickets:
 - *NIL*

### CODE REVIEW

**Comment by devangaggarwal** [comment]
Can you please add links to this line - "Have a new feature you would like to see in OpenVINO? File a feature request here <link to feature request issue>. You can also implement the feature yourself by following the CONTRIBUTING.MD <link this to contributing.md file>."

Please hyperlink first "here" to https://github.com/openvinotoolkit/openvino/issues/new/choose. Please add this hyperlink for Contributing.Md - https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md.

**Comment by sorenk** [comment]
Please also ask for the pre-release version, just in case they are adding a comment to an old pre-release.  We want to associate the comment with the correct drop.  Thx.

**Comment by hbalasu1** [comment]
> Can you please add links to this line - "Have a new feature you would like to see in OpenVINO? File a feature request here . You can also implement the feature yourself by following the CONTRIBUTING.MD ."
> 
> Please hyperlink first "here" to https://github.com/openvinotoolkit/openvino/issues/new/choose. Please add this hyperlink for Contributing.Md - https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md.

Done adding the link

**Comment by devangaggarwal** [comment]
LGTM. @ilya-lavrenov please review.

**Review by ilya-lavrenov — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
Hi @hbalasu1 @devangaggarwal 
Could you please update this template to match nightly releases?
As you know, we currently made monthly => release, pre-release => nightly release

**Comment by devangaggarwal** [comment]
@hbalasu1 can you please update accordingly and request review by me? Here is nightly: https://pypi.org/project/openvino-nightly/

**Comment by devangaggarwal** [comment]
@hbalasu1 any update on this?

**Pull request merged**
