### PR TITLE
[POT] Unroll GRUCell for GNA

### PR DESCRIPTION
**Pull request by l-bat**
### Details:
 - *Add transformations to unroll GRUCell*
 - *Merge after PR #12922*

### Tickets:
 - *55649*

### CODE REVIEW

**Comment by l-bat** [comment]
@AlexKoff88 Should I add test for GNA with [nsnet2-20ms-baseline.onnx](https://github.com/microsoft/DNS-Challenge/blob/master/NSNet2-baseline/nsnet2-20ms-baseline.onnx) model?

**Comment by l-bat** [comment]
> Maybe we just need own simple one RNN model with random weights.

Yes. But GRU is decomposed into TI. Quantization inside subgraphs is not enabled by default now. T

**Comment by AlexKoff88** [comment]
>

**Comment by AlexKoff88** [comment]
> > Maybe we just need own simple one RNN model with random weights.
> 
> Yes. But GRU is decomposed into TI. Quantization inside subgraphs is not enabled by default now. T
The model is large, anyway. I suggest introducing unit tests only for now.

**Comment by AlexKoff88** [comment]
> > Maybe we just need own simple one RNN model with random weights.
> 
> Yes. But GRU is decomposed into TI. Quantization inside subgraphs is not enabled by default now. T
I get confused with a different PR from you, sorry. I am ok with the changes as well.

**Review by AlexKoff88 — APPROVED** [review]

**Pull request merged**
