### PR TITLE
Fix for thread local storage issue in MKLDNNMemoryNode

### PR DESCRIPTION
**Pull request by EgorDuplensky**
### Tickets:
 - CVS-62746

### CODE REVIEW

**Comment by EgorDuplensky** [comment]
This is RE-push of
* https://github.com/openvinotoolkit/openvino/pull/7696

**Comment by EgorDuplensky** [comment]
I propose to not merge this one for now.
The issue itself is very rare but the solution is quite severe.
Should be discussed.

**Comment by maxnick** [comment]
@EgorDuplensky did you have a chance to discuss the solution?

**Comment by ilya-lavrenov** [comment]
is it still valid?

**Comment by akladiev** [comment]
This PR will be closed in 2 weeks in case of no activity.

**Comment by akladiev** [comment]
This PR was closed because it has been stalled for 2 week with no activity.

**Pull request closed without merging**
