### PR TITLE
[IE TESTS] Add missing inputs for ActivationParamLayerTest.

### PR DESCRIPTION
**Pull request by XinWangIntel**
### Details:
The inputs of ActivationParamLayerTest are missing.

### CODE REVIEW

**Review by iefode — APPROVED** [review]

**Review by mikhail-treskin — APPROVED** [review]

**Comment by XinWangIntel** [comment]
Looks like lack of right to merge,  get:
 "Merging is blocked.  The base branch restricts merging to authorized users"
Can anybody help to solve this?

**Comment by iefode** [comment]
> Looks like lack of right to merge, get:
> "Merging is blocked. The base branch restricts merging to authorized users"
> Can anybody help to solve this?

Hi,

I have enabled auto-merge. The changes will be merged to the master after CI is passed

Best regards,
Irina

**Comment by mitruska** [comment]
I suppose the CI passed because the ActivationParamLayerTests are skipped
https://github.com/openvinotoolkit/openvino/blob/c77b4dc4edec6053f814c44c7ad1f37a91e931d5/inference-engine/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp#L39 
But with this PR changes all of the ActivationParamLayerTests fail with error: 
`Got function (Function_558) with 2 parameters, but 4 input blobs`

So the blobs are generated twice.
It can be fixed by `inputs.clear()` at the begining of the `ActivationParamLayerTest::Infer()` function or 
as I proposed in PR 5915 by `GenerateInput` override without custom `Infer()` function at all.

**Comment by XinWangIntel** [comment]
> I suppose the CI passed because the ActivationParamLayerTests are skipped
> https://github.com/openvinotoolkit/openvino/blob/c77b4dc4edec6053f814c44c7ad1f37a91e931d5/inference-engine/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp#L39
> 
> 
> But with this PR changes all of the ActivationParamLayerTests fail with error:
> `Got function (Function_558) with 2 parameters, but 4 input blobs`
> So the blobs are generated twice.
> It can be fixed by `inputs.clear()` at the begining of the `ActivationParamLayerTest::Infer()` function or
> as I proposed in PR 5915 by `GenerateInput` override without custom `Infer()` function at all.

The changes here are to solve the missing inputs when we run ActivationParamLayerTest (if not do this, may not find the input with the given name),  not see double inputs on my side when i run tests. And not get other codes to set the inputs after checking the codes.  FYI.

**Pull request merged**
