### PR TITLE
[CPU] [DEBUG CAPS] Implicitly enable perf counters for verbose mode

### PR DESCRIPTION
**Pull request by EgorDuplensky**
### Details:
 - Refactor debug capabilities configuration. Now debug caps config parameters are the part of plugin configuration.
 - Automatically fixes issue with multithreading

### CODE REVIEW

**Comment by EgorDuplensky** [comment]
@dmitry-gorokhov Could you please take a look

**Comment by EgorDuplensky** [comment]
rebased

**Comment by EgorDuplensky** [comment]
Rebased

**Comment by EgorDuplensky** [comment]
Rebased

**Comment by EgorDuplensky** [comment]
@dmitry-gorokhov Could you please take a look

**Review by dmitry-gorokhov — APPROVED** [review]
Please rebase on latest master

**Comment by EgorDuplensky** [comment]
@azhogov Can we merge this despite failed Doc Build (known CI issue)?
No documentation were updated in scope of this PR

**Pull request merged**
