### PR TITLE
Update open_model_zoo submodule

### PR DESCRIPTION
**Pull request by Wovchena**
Depends on https://github.com/openvinotoolkit/open_model_zoo/pull/3907

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
build_jenkins

**Review by ilya-lavrenov — APPROVED** [review]

**Comment by Wovchena** [comment]
It points to my fork. I'm waiting for https://github.com/openvinotoolkit/open_model_zoo/pull/3907

**Comment by ilya-lavrenov** [comment]
> It points to my fork. I'm waiting for [openvinotoolkit/open_model_zoo#3907](https://github.com/openvinotoolkit/open_model_zoo/pull/3907)

Unblocked

**Comment by ilya-lavrenov** [comment]
have you changed something related to numpy dependency? It starts to build for some reason, looks like upper bound is added somewhere
```
[2024-02-13T13:35:17.094Z]         × Building wheel for numpy (pyproject.toml) did not run successfully.

[2024-02-13T13:35:17.094Z]         │ exit code: 1

[2024-02-13T13:35:17.094Z]         ╰─> [941 lines of output]

[2024-02-13T13:35:17.094Z]             setup.py:67: RuntimeWarning: NumPy 1.19.3 may not yet support Python 3.11.

[2024-02-13T13:35:17.094Z]               warnings.warn(
```

**Comment by Wovchena** [comment]
Yes: https://github.com/openvinotoolkit/open_model_zoo/pull/3911 But it passed yesterday when it was on my fork [f9674df](https://github.com/openvinotoolkit/openvino/pull/22683/commits/f9674df16389fba175576f4af7d0e4e4f050ffe1)

**Pull request merged**
