### PR TITLE
NPUW: Regularized REP pipeline

### PR DESCRIPTION
**Pull request by dmatveev**
### Details:
 - Introduce a pattern-guided REG pipeline and make it default. If there's no known patterns, it falls back into REP.

### Tickets:
 - *E-142355*

### CODE REVIEW

**Review by smirnov-alexey — APPROVED** [review]

**Comment by dmatveev** [comment]
A downside of this.. SPATIAL config now explicitly requires PIPELINE set to REP - as REG discards the user-driven ISOLATE preference.. @smirnov-alexey thoughts?

**Comment by smirnov-alexey** [comment]
> A downside of this.. SPATIAL config now explicitly requires PIPELINE set to REP - as REG discards the user-driven ISOLATE preference.. @smirnov-alexey thoughts?

How about we distinguish user-driven isolate tag from the default one we set? E.g. add a prefix to the `isol_tag` string. Then in `dontIsolate()` we only drop our tag and not user one

**Comment by dmatveev** [comment]
> REP with SPATIAL every time for now (since we know the use case) 

No that's dangerous

**Comment by smirnov-alexey** [comment]
> > REP with SPATIAL every time for now (since we know the use case)
> 
> No that's dangerous to do automatically, but if you mean for config, once user wants to use SPATIAL, he should also set REP? Yeah that's what I do now

Yeah, I meant in config

**Comment by dmatveev** [comment]
@smirnov-alexey looking at the code and the flow, _probably_ using a designated tag for internal isolation is a way to go. However, with SPATIAL we get this:

```
    "NPUW_ONLINE_ISOLATE" : COMPUTE"
```
..so, if we want to configure SPATIAL, we'll get into the same tag here.

The default value for `ONLINE_ISOLATE` is currently empty - in the config. If we go for the

```
   "NPUW_ONLINE_PIPELINE" : "COMPUTE"
```
..then we take the internal-defined ISOLATEs and completely ignore the user-specified ones...

All this behavioral mess needs a good clean-up. Probably, having said that, it is OK to have `NPUW_ONLINE_ISOLATE` be ignored in the `REG` pipeline. At least I'll add warnings

**Review by smirnov-alexey — APPROVED** [review]

**Pull request merged**
