### PR TITLE
Rename "pdpd" frontend to "paddle"

### PR DESCRIPTION
**Pull request by nosovmik**
### Details:
 - Pdpd abbreviation was used in code before and was ok. However for end user it was confirmed with Baidu that "pdpd" frontend shall be renamed to "paddle"
 - Also renamed mo_pdpd.py+main_pdpd.py to mo_paddle.py+main_paddle.py
 - Class names and local variables were not renamed

### Tickets:
 - 61091

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
> Class names and local variables were not renamed

Is it not planned to going to be done as a separate task?

**Review by zhangYiIntel — APPROVED** [review]
looks good to me

**Review by itikhono — APPROVED** [review]

**Comment by itikhono** [comment]
Do we have any plans to rename the class names, e.g. PDPD_Place -> Paddle_Place?

**Comment by nosovmik** [comment]
> Do we have any plans to rename the class names, e.g. PDPD_Place -> Paddle_Place?

> > Class names and local variables were not renamed
> 
> Is it not planned to going to be done as a separate task?

@itikhono @ilya-lavrenov I'll check it, at least renaming frontend name for end user is a 'must have'. Regarding class names, I guess it is up to us but let me check

**Comment by nosovmik** [comment]
@ilya-lavrenov I have confirmed that renaming of all classes (from PDPD to "Paddle") may need to be done later, not needed in 'phase 1'. I have created ticket 61361 to address this later

**Pull request merged**
