### PR TITLE
Added quantized_decomposed quantization unit tests

### PR DESCRIPTION
**Pull request by cavusmustafa**

### CODE REVIEW

**Comment by suryasidd** [comment]
build_jenkins

**Comment by suryasidd** [comment]
build_jenkins

**Comment by cavusmustafa** [comment]
Please add label for code freeze

**Comment by suryasidd** [comment]
build_jenkins

**Comment by suryasidd** [comment]
build_jenkins

**Comment by mvafin** [comment]
build_jenkins

**Comment by mvafin** [comment]
For some reason I can't run these tests locally. I get error:

```
E               AttributeError: '_OpNamespace' 'quantized_decomposed' object has no attribute 'quantize_per_channel'
```

**Comment by suryasidd** [comment]
build_jenkins

**Comment by cavusmustafa** [comment]
> For some reason I can't run these tests locally. I get error:
> 
> ```
> E               AttributeError: '_OpNamespace' 'quantized_decomposed' object has no attribute 'quantize_per_channel'
> ```

The test was broken due to one of the recent changes in the master branch (Removing "import openvino.torch"). I added the required import into the test.

**Comment by suryasidd** [comment]
build_jenkins

**Pull request merged**
