### PR TITLE
Add nGraph Python API versioning

### PR DESCRIPTION
**Pull request by postrational**
### Details:
Exposes nGraph version string in Python API as `ngraph.__version__`

```python
>>> import ngraph as ng
>>> ng.__version__
'custom_master_5847b35ed2d30529efc0fd69476e2fd47ada2dc2'
```

### Tickets:
 - *56076*

### CODE REVIEW

**Comment by ilyachur** [comment]
@jiwaszki @akuporos I think we need to introduce only OpenVINO version to new Python API. What do you think?

**Review by jiwaszki — APPROVED** [review]
@ilyachur I think we should add it - ngraph python api will be around for some time and some changes may still come in.

**Comment by GlebKazantaev** [comment]
@postrational does ngraph version equal to IE version?

**Review by ilyachur — APPROVED** [review]
In new API we should return only OV version

**Pull request merged**
