### PR TITLE
[PyOV] Extend Python API with a new `model.reshape()` overload

### LINKED ISSUE #18347: Extend Python API with a new `model.reshape()` overload
## Context
Currently there are multiple ways to reshape model inputs in Python API. They are defined as [bindings to C++ code](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/pyopenvino/graph/model.cpp#L266-L405).

A new way to reshape has been suggested - implicit input reshaping with a list of input shapes. An example of new, desired overload/Python API function:
1. `model` has three inputs: A, B and C
2. `model` is being reshaped with a list of shapes:
`model.reshape([[2,2], [1, 3, 224, 244], [10]])`
3. the given shapes are assigned to respective inputs:
`A.shape = [2, 2]`
`B.shape = [1, 3, 244, 244]`
`C.shape = [10]`

[Python API model binding](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/pyopenvino/graph/model.cpp#L266-L405) needs to be extended with a new overload which will add this functionality.

## What needs to be done?
1. Add a new overload for `model.reshape` in `model` [C++ bindings](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/pyopenvino/graph/model.cpp#L266-L405)
2. Add tests for the new functionality in the [correct test file](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/tests/test_runtime/test_model.py) - `test_model.py`
3. Submit a PR
4. Wait for review

## Resources

- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [How to extend OpenVINO Python API](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/code_examples.md)
- [How to test OpenVINO Python API](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/test_examples.md)
- [Blog post on contributing to OpenVINO](https://medium.com/openvino-toolkit/how-to-contribute-to-an-ai-open-source-project-c741f48e009e)

## Contact points

@p-wysocki
@jiwaszki
@akuporos 

Don't hesitate to reach out, we're here to help!

Ticket: 110444

### PR DESCRIPTION
**Pull request by siddhant-0707**
### Details:
 - Added new overload for `model.reshape` in model C++ bindings
 - Added tests

### Tickets:
 - Closes #18347

### CODE REVIEW

**Comment by p-wysocki** [comment]
build_jenkins

**Comment by siddhant-0707** [comment]
@p-wysocki ping, thanks!

**Review by akuporos — CHANGES_REQUESTED** [review]
Please, build locally and fix compilation errors

**Comment by siddhant-0707** [comment]
I'm a little confused here. All of the tests for reshape in [test_model.py](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/tests/test_runtime/test_model.py#L290-L365) either are singular dimensions or take `min` and `max` value(for dynamic dims) however the issue description describes an example of format:
`model.reshape([[2,2], [1, 3, 224, 244], [10]])`. Shouldn't the `[1, 3, 224, 244]` just be `[1, 3]`? If so then this functionality is already covered through [this overload](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/pyopenvino/graph/model.cpp#L327-L343) which calls [partial_shape_from_list](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/pyopenvino/core/common.cpp#L422-L453) which handles the case of list[list]. Please correct me if I understood something wrong. 👍🏻

**Comment by siddhant-0707** [comment]
Hey guys, please take a look @akuporos @p-wysocki, thanks

**Comment by mlukasze** [comment]
build_jenkins

**Comment by akuporos** [comment]
Hello @siddhant-0707 ,
Sorry for late response.

The original idea of the ticket was that currently if a user wants to reshape multi input model, it's need to pass dict for each input, where key of the dict maybe index or name of an input.
We wants to have `list` in addition to `dict`, so index of input (0, 1...)  just matches with index in array.
For example dict like this {0: [2,2], 1:  [1, 3, 224, 244], 2: [10]} is equal to list like this [[2,2], [1, 3, 224, 244], [10]].
You may see that `generate_add_model()` returns a model with two inputs, so use it at you test case.

**Comment by mlukasze** [comment]
hey @siddhant-0707 :)
are instructions clear? are you able to deliver changes Anastasia asked for?

**Comment by mlukasze** [comment]
last ping

**Comment by siddhant-0707** [comment]
@mlukasze I require a bit more time, sorry for the delay

**Comment by mlukasze** [comment]
no problem, thanks for letting me know :)

**Comment by akuporos** [comment]
Hi @siddhant-0707,

Will you find  time to finish this PR?

**Pull request closed without merging**
