### PR TITLE
fix pdpd model load error

### PR DESCRIPTION
**Pull request by xczhai**
### Details:
 - CVS-112501

### Tickets:
 - *fix PDPD model loading error*

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
should we merge to master first?

**Comment by yuxu42** [comment]
@ceciliapeng2011 could you please review? Thanks!

**Comment by xczhai** [comment]
> should we merge to master first?

No, it has been merged to the master. This is a new request to merge the feature to 2022.3.1.

**Comment by xczhai** [comment]
```bash
../_w/install_pkg/tests/pyngraph/tests_compatibility/test_ngraph/test_basic.py:7: in <module>
    from _pyngraph import VariantInt, VariantString
E   ImportError: cannot import name 'VariantInt' from '_pyngraph'
```
@ilya-lavrenov Hi 
This case failed for a long time and occurred many times in this branch.
It seems my change should not trigger this failure. 
This PR should be merged manually?

**Comment by xczhai** [comment]
@ilya-lavrenov could you please take a look? Thanks.

**Comment by xczhai** [comment]
@ceciliapeng2011 Hi, could you help review the PR? thanks.

**Review by ceciliapeng2011 — APPROVED** [review]

**Pull request merged**
