### PR TITLE
Avoid OpenCL linkage for app using make_shared_blob_nv12

### PR DESCRIPTION
**Pull request by mikhail-nikolskiy**
### Details:
 - Change header-only function `make_shared_blob_nv12` to not use VAContext/D3DContext
 - This change allows media analytics (video decode + inference) applications to avoid linkage with OpenCL, thus noticeably simplify build scripts and allow decode+inference on CPU device to start&run on systems without OpenCL installed. The `make_shared_blob_nv12` is the only place introducing unnecessary linkage dependency on OpenCL.

### CODE REVIEW

**Review by ilya-lavrenov — APPROVED** [review]

**Review by vladimir-paramuzov — APPROVED** [review]

**Comment by vladimir-paramuzov** [comment]
@mikhail-nikolskiy Could you rebase please? We need green CI to merge this PR.

**Comment by ilya-lavrenov** [comment]
@mikhail-nikolskiy ping

**Comment by mikhail-nikolskiy** [comment]
Sorry for delay with rebase to latest master.
> 48 successful, 1 errored, and 3 failing checks

Is it real problem or CI instability issue?

**Comment by ilya-lavrenov** [comment]
Ci issue

Cc @azhogov

**Comment by azhogov** [comment]
Just rebuild the job

**Pull request merged**
