### PR TITLE
Fixed convert to legacy call from different threads

### PR DESCRIPTION
**Pull request by ilyachur**

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
The question is - why the implicit conversion happens during `LoadNetwork`?

**Comment by ilyachur** [comment]
> The question is - why the implicit conversion happens during `LoadNetwork`?

because plugin calls this conversion in order to convert to legacy representation.

**Comment by ilya-lavrenov** [comment]
> > The question is - why the implicit conversion happens during `LoadNetwork`?
> 
> because plugin calls this conversion in order to convert to legacy representation.

I understand, but from my point of view plugin should do this on cloned network. So, no parallel access to `CNNNetwork` in this case

**Comment by ilyachur** [comment]
> > > The question is - why the implicit conversion happens during `LoadNetwork`?
> > 
> > 
> > because plugin calls this conversion in order to convert to legacy representation.
> 
> I understand, but from my point of view plugin should do this on cloned network. So, no parallel access to `CNNNetwork` in this case
> 
> So, plugin call explicit conversion instead of explicit. Is not it?

Answered in offline.

**Comment by ilya-lavrenov** [comment]
Let's make CI green and merge.

**Comment by ilyachur** [comment]
I found another issue with nGraph clone function.

When we use `get_argument()` method we works with GOE element which can be removed in copyFunction method.

**Comment by ilyachur** [comment]
Some of my changes affects nGraph unit test: IE_CPU.backwards_cos. I am investigating the problem.

**Comment by vurusovs** [comment]
@ilyachur you may observe failure of memory tests. Please, refer to the last available results on master commit - https://openvino-ci.intel.com/job/private-ci/job/ie/job/ie-tests-linux-ubuntu18-stress/6361/memcheck/ to check your results

**Comment by ilyachur** [comment]
Switched back to `specialize_function()`, `clone_function()` caused some issues in nGraph tests. Will investigate it separately. Changed the logic of conversion in order to avoid data races.

**Comment by ilyachur** [comment]
Fixed in the PR: https://github.com/openvinotoolkit/openvino/pull/1523

**Pull request closed without merging**
