### PR TITLE
Rename AvgPool to attribute exclude-pad to align with MO and layer creator

### PR DESCRIPTION
**Pull request by ggalieroc**
ticket: 42998

### CODE REVIEW

**Review by ilyachur — APPROVED** [review]

**Comment by ilyachur** [comment]
Could you create a test for this issue?

**Review by jdanieck — APPROVED** [review]

**Comment by jdanieck** [comment]
> Could you create a test for this issue?

Can we do it when https://github.com/openvinotoolkit/openvino/pull/3431 will be merged and we can add serialization SLT ?

**Comment by ilyachur** [comment]
> > Could you create a test for this issue?
> 
> Can we do it when #3431 will be merged and we can add serialization SLT ?

Yes we can, but we should remember about it. Maybe we can create a ticket.

**Comment by jdanieck** [comment]
> > > Could you create a test for this issue?
> > 
> > 
> > Can we do it when #3431 will be merged and we can add serialization SLT ?
> 
> Yes we can, but we should remember about it. Maybe we can create a ticket.

SLT PR looks like ready to merge, @iefode is there anything that stopping us?  If we can merge it today/tomorrow then we can add serialization SLT in this PR, if it'll take longer then we'll create a ticket.

**Comment by ilyachur** [comment]
> SLT

W

**Comment by ilyachur** [comment]
> > > > Could you create a test for this issue?
> > > 
> > > 
> > > Can we do it when #3431 will be merged and we can add serialization SLT ?
> > 
> > 
> > Yes we can, but we should remember about it. Maybe we can create a ticket.
> 
> SLT PR looks like ready to merge, @iefode is there anything that stopping us? If we can merge it today/tomorrow then we can add serialization SLT in this PR, if it'll take longer then we'll create a ticket.

We discussed this PR today. Irina should change some things in this PR before that we will be able to merge it.

**Pull request merged**
