### PR TITLE
M_PI(math.h) using fix & dirent.h is existed in MinGW

### PR DESCRIPTION
**Pull request by testdrive-profiling-master**
M_PI using fix in MinGW
image
image
image
&
'direct.h' header is existed in MinGW

### CODE REVIEW

**Review by rkazants — APPROVED** [review]

**Comment by rkazants** [comment]
build_jenkins

**Comment by ilya-lavrenov** [comment]
@testdrive-profiling-master please, fix code style

**Review by vurusovs — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
build_jenkins

**Comment by ilya-lavrenov** [comment]
build_jenkins

**Review by Wovchena — APPROVED** [review]

**Pull request merged**
