### PR TITLE
[CPU][ARM64] Added Greater JIT emitter (#24421)

### LINKED ISSUE #24421: [Good First Issue] [ARM]: Implement CPU plugin just-in-time emitter for Greater operation
### Context

[JIT Emitters](https://github.com/openvinotoolkit/openvino/blob/42f1cb095143f19c0b9ee25836c29748bc8d9bf2/src/plugins/intel_cpu/src/emitters/README.md) are part of code generation feature (a.k.a. tensor compiler) that automatically produces highly-efficient optimized fused subgraph binary code. Each emitter implements specific operation from low level OpenVINO dialect.

### Prerequisites
Recommended to use ARM CPU based platform for development (e.g. Mac, Raspberry Pi etc). Emulators (e.g. QEMU) is still an option, but not that convenient, especially for final performance evaluation. 

### What needs to be done?

* Create `fp32` [Greater](https://docs.openvino.ai/2024/documentation/openvino-ir-format/operation-sets/operation-specs/comparison/greater-1.html) operation JIT emitter for ARM64 SIMD platform. Use OpenVINO [CPU plugin JIT emitters](https://github.com/openvinotoolkit/openvino/blob/42f1cb095143f19c0b9ee25836c29748bc8d9bf2/src/plugins/intel_cpu/src/emitters/README.md) documentation and [Arm A-profile A64 Instruction Set Architecture](https://developer.arm.com/documentation/ddi0602/2024-03/SIMD-FP-Instructions) documentation for details.
* Modify [ARM64 executor](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp#L20) and [ARM64 kernel](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.hpp#L80) (in both places: [create_eltwise_emitter](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp#L601) and [get_supported_precisions](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp#L766)) to apply developed JIT emitter.

Before emitter implementation, please, modify tests to be sure that deveoped functionality is covered by test:
  * Add `jit` kernel check in [element-wise](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/eltwise.cpp#L257) or [activation](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp#L155) test, the test must fail.
  * If test doesn't fail then add supported operation in [element-wise test instantiation](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/eltwise.cpp) or [activation test instantiation](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp) if it's absent.

### Tests
Tests are disabled in default build, so ensure to add `-DENABLE_TESTS=ON` into cmake command.

[GoogleTest](https://github.com/google/googletest) is used for testing. CPU functional test target is [ov_cpu_func_tests](https://github.com/openvinotoolkit/openvino/tree/master/src/plugins/intel_cpu/tests/functional). You can use two `GoogleTest` filters for element-wise and activation operations:
* for element-wise operations:
```sh
./bin/[platform]/[build_type]/ov_cpu_func_tests --gtest_filter="*smoke*Eltwise*"
```
* for activations:
```sh
./bin/[platform]/[build_type]/ov_cpu_func_tests --gtest_filter="*smoke*Activation*"
```

### Example Pull Requests

* [Abs](https://docs.openvino.ai/2023.3/openvino_docs_ops_arithmetic_Abs_1.html) operation: https://github.com/openvinotoolkit/openvino/pull/23692
* [Sigmoid](https://docs.openvino.ai/2023.3/openvino_docs_ops_activation_Sigmoid_1.html) operation, which reuses [Exp emitter](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp#L820): https://github.com/openvinotoolkit/openvino/pull/23065

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [CPU plugin JIT emitters](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_cpu/src/emitters/README.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

@eshoguli, @dmitry-gorokhov

### Ticket

CVS-140694

### PR DESCRIPTION
**Pull request by jvr0123**
### Details:
 - Implemented Greater jit emitter
 - Added relevant unit test

### Tickets:
 - Closes #24421

### CODE REVIEW

**Comment by jvr0123** [comment]
I'm somewhat confused by some of the checks failing. I'm currently running `./bin/aarch64/Debug/ov_cpu_func_tests --gtest_filter="*smoke*Type=Greater*"` and only getting passes. Is there a different test that should be ran and that is failing?

**Comment by jvr0123** [comment]
@eshoguli gentle reminder this PR is still open. Any feedback on the general approach?

**Review by eshoguli — COMMENTED** [review]
Thanks for your contribution.
Can you, please, update `ActivationLayerCPUTest::generate_inputs` to cover `Greater` emitter functionality. There is an example for `Sign` activation. You can do something similar but use more then one value, please: 
1. Two input tensor values should be different: less, equal and greater.
2. Please, update to have special values: negative zero, NaN (several values), Infinity values, ... in test input tensor.

**Comment by dmitry-gorokhov** [comment]
build_jenkins

**Comment by dmitry-gorokhov** [comment]
build_jenkins

**Comment by dmitry-gorokhov** [comment]
Hey @jvr0123! I see some Ci failures caused by this PR. Could you please fix them?

**Comment by mlukasze** [comment]
hey @jvr0123 please update a status of the PR - will you have time to finish it?

**Pull request closed without merging**
