### PR TITLE
[PT FE] Support aten::masked_select for pytorch models

### PR DESCRIPTION
**Pull request by hub-bla**
### Details:
 - support `aten::masked_select` operator

### Tickets:
 - [None](https://github.com/openvinotoolkit/openvino/issues/23325)

### CODE REVIEW

**Comment by mvafin** [comment]
Thank you for the contribution, could you please resolve merge conflicts so we can merge you PR

**Comment by hub-bla** [comment]
Done!

**Review by mvafin — APPROVED** [review]

**Comment by mvafin** [comment]
build_jenkins

**Review by mvafin — CHANGES_REQUESTED** [review]
Build failed. Please add includes for `Transpose`, `NonZero` and `GatherND`

**Comment by mvafin** [comment]
build_jenkins

**Comment by mvafin** [comment]
build_jenkins

**Review by mvafin — APPROVED** [review]

**Pull request merged**
