### PR TITLE
Fixed "NPU_USE_NPUW" : "NO" case

### PR DESCRIPTION
**Pull request by AsyaPronina**
### Details:
 - When "NPU_USE_NPUW" : "NO"/`false` is passed to `intel_npu::Plugin::compile_model(...)`, it is not removed from incoming OV properties and passes on right to npu plugin's `intel_npu::Config` config causing:
```
    [ NOT_FOUND ] Option 'NPU_USE_NPUW' is not supported for current configuration
```

- However, workaround for issue is available: just not passing "NPU_USE_NPUW" : "NO" will result in right behavior is you don't need NPUW.

### Tickets:
 - *ticket-id*

### CODE REVIEW

**Review by dmatveev — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
is it possible to add a test fox this fix?

**Comment by AsyaPronina** [comment]
> is it possible to add a test fox this fix?

Hello, sure, but only for future releases, because infrastructure for tests is not merged yet: [Added MockNPU/CPU, FakeNPU/CPU and functional tests by AsyaPronina · Pull Request #25236 · openvinotoolkit/openvino (github.com)](https://github.com/openvinotoolkit/openvino/pull/25236)

**Review by TolyaTalamanov — APPROVED** [review]

**Comment by dmatveev** [comment]
@ilya-lavrenov could you please help with a merge? it seems the only failure in this PR checks is somewhere in PyTorch and changes in the PR has no effect on it

**Comment by dmatveev** [comment]
@AsyaPronina this PR is merged, do you have the same for `master` ?

**Pull request merged**
