### PR TITLE
Implement CPU plugin just-in-time emitter for IsNaN operation

### PR DESCRIPTION
**Pull request by awayzjj**
Closes: https://github.com/openvinotoolkit/openvino/issues/24420
### Details:
 - *item1*
 - *...*

### Tickets:
 - [CVS-137700](https://jira.devtools.intel.com/browse/CVS-137700)

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@eshoguli Please take a look

**Comment by awayzjj** [comment]
@eshoguli  Hi, I tried implemented the tests as the PR shows, and expect the test cases of is_nan to failed. But all tests passed, when I run 
```
nohup ./bin/aarch64/Debug/ov_cpu_func_tests --gtest_filter="*smoke*Activation*" &
```
I add a print log in `src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp`
```
std::string ActivationLayerCPUTest::getPrimitiveType(const utils::ActivationTypes& activation_type,
                                                     const ov::element::Type_t& element_type,
                                                     const std::vector<std::pair<ov::PartialShape, std::vector<ov::Shape>>>& input_shapes) const {
#if defined(OV_CPU_WITH_ACL)
#if defined(OPENVINO_ARCH_ARM64)
    std::cout << "debug: " << element_type << " " << activation_type << std::endl;
    if ((element_type == ov::element::f32) &&
        ((activation_type == utils::ActivationTypes::Clamp) ||
        (activation_type == utils::ActivationTypes::Elu) ||
        (activation_type == utils::ActivationTypes::Exp) ||
        (activation_type == utils::ActivationTypes::HSwish) ||
        (activation_type == utils::ActivationTypes::HardSigmoid) ||
        (activation_type == utils::ActivationTypes::IsNaN) ||
        (activation_type == utils::ActivationTypes::Mish) ||
        (activation_type == utils::ActivationTypes::Relu) ||
        (activation_type == utils::ActivationTypes::Sigmoid) ||
        (activation_type == utils::ActivationTypes::Swish) ||
        (activation_type == utils::ActivationTypes::Tanh))) {
        std::cout << "debug2: " << element_type << " " << activation_type << std::endl;
        return "jit";
    }
```
But I did not found the index 41 for isNan in `utils::ActivationTypes`
```
root@ecs-4abe:~/openvino# cat nohup.out|grep "debug:"|cut -d " " -f3|sort -n|uniq -c
     24 1
     24 2
     24 3
     24 5
      6 6
      6 7
     24 10
      6 12
      6 13
      6 14
      6 15
      6 16
      6 17
      6 18
      6 19
     24 23
      6 24
     24 25
      6 27
      6 28
      6 29
     24 30
     24 32
     24 33
     24 34
     24 38
     24 39
     30 40
root@ecs-4abe:~/openvino# cat nohup.out|grep "debug2:"|cut -d " " -f3|sort -n|uniq -c
     24 1
     24 2
     24 3
     24 5
     24 10
     24 25
      6 27
     24 32
     24 34
```
Could you please give me some suggestions? Thank you very much!

**Comment by awayzjj** [comment]
I modifiled `activationTypes ` and `activationTypesDynamicMath` in src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp, and got segmentation fault, and I am trying to solve it.
```
const std::map<utils::ActivationTypes, std::vector<std::vector<float>>>& activationTypes() {
    static const std::map<utils::ActivationTypes, std::vector<std::vector<float>>> activationTypes {
        {Sqrt,        {{}}},
        {Sigmoid,     {{}}},
        {Tanh,        {{}}},
        {Relu,        {{}}},
        {Exp,         {{}}},
        {Clamp,       {{-2.0f, 2.0f}}},
        {Elu,         {{0.1f}}},
        {Swish,       {{0.1f}}},
        {HSwish,      {{}}},
        {PReLu,       {{-0.01f}}},
        {GeluErf,     {{}}},
        {GeluTanh,    {{}}},
        {SoftSign,    {{}}},
        {SoftPlus,    {{}}},
        {IsNaN,    {{}}},
    };
```

```
const std::map<utils::ActivationTypes, std::vector<std::vector<float>>>& activationTypesDynamicMath() {
    static const std::map<utils::ActivationTypes, std::vector<std::vector<float>>> activationTypesDynamicMath {
        {Log,         {{}}},
        {Sign,        {{}}},
        {Acos,        {{}}},
        {Acosh,       {{}}},
        {Asin,        {{}}},
        {Asinh,       {{}}},
        {Atan,        {{}}},
        {Atanh,       {{}}},
        {Cos,         {{}}},
        {Cosh,        {{}}},
        {Tan,         {{}}},
        {HardSigmoid, {{0.2f, 0.5f}}},
        {Selu,        {{1.6732f, 1.0507f}}},
        {Ceiling,     {{}}},
        {SoftSign,    {{}}},
        {IsNaN,    {{}}},
    };
```

**Comment by awayzjj** [comment]
Hello @dmitry-gorokhov @eshoguli , just a gentle reminder to review this PR. Your feedback would be greatly appreciated!

**Comment by dmitry-gorokhov** [comment]
@awayzjj Great job! I triggered the CI
@eshoguli Please help to review the changes.

**Comment by eshoguli** [comment]
> Hello @dmitry-gorokhov @eshoguli , just a gentle reminder to review this PR. Your feedback would be greatly appreciated!

Hi @awayzjj, thanks for contribution. Unfortunatelly, some tests faild. Can you, please, explore them, please?
```
../bin/arm64/Debug/ov_cpu_func_tests --gtest_filter="*smoke*Type=IsNan*"
```

**Comment by awayzjj** [comment]
@eshoguli @dmitry-gorokhov  I was wondering how to debug, and I would greatly appreciate any suggestions you might have.

**Comment by dmitry-gorokhov** [comment]
> @eshoguli @dmitry-gorokhov I was wondering how to debug, and I would greatly appreciate any suggestions you might have.

@awayzjj Please take a look on this section https://github.com/openvinotoolkit/openvino/blob/42f1cb095143f19c0b9ee25836c29748bc8d9bf2/src/plugins/intel_cpu/src/emitters/README.md#debugging. This doc describes hot to debug Jitted code in inference time. Feel free to ask any additional questions if the instruction is not clear.

**Comment by awayzjj** [comment]
@dmitry-gorokhov  Thank you very much for your suggestion. As the doc shows 2 ways to help us debugging.
截屏2024-06-09 00 33 43

I still have 2 questions,
1. The doc suggests adding breakpoint in appropriate platform dependent kernel(in my case it is the is_nan kernel?) before JIT generated code execution. But I can not find the right place. Could you tell me how to find the kernel?
2. The doc introduces the [register printer](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_cpu/src/emitters/plugin/x64/utils.hpp). But is it  only availeble for the normal x86-64 platform? So I can only relay on the first way to debug the code in my ` void jit_is_nan_emitter::emit_isa` method in arm platform?

**Comment by dmitry-gorokhov** [comment]
> @dmitry-gorokhov Thank you very much for your suggestion. As the doc shows 2 ways to help us debugging. 截屏2024-06-09 00 33 43
> 
> I still have 2 questions,
> 
> 1. The doc suggests adding breakpoint in appropriate platform dependent kernel(in my case it is the is_nan kernel?) before JIT generated code execution. But I can not find the right place. Could you tell me how to find the kernel?
> 2. The doc introduces the [register printer](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_cpu/src/emitters/plugin/x64/utils.hpp). But is it  only availeble for the normal x86-64 platform? So I can only relay on the first way to debug the code in my ` void jit_is_nan_emitter::emit_isa` method in arm platform?

Hi @awayzjj. Yes, since register printing is not implemented for aarch64, you need to use option 1. You need to put breakpoint where generated kernel (Eltwise kernel in you case, not emitter itself) is called: https://github.com/openvinotoolkit/openvino/blob/aea8d967d39bdd902df621ea9e6c860ae3f4ad57/src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp#L19. Once debugger reached the breakpoint you need to switch into disassembly view and use "step into" to enter the kernel (since generated kernel is emitted as function call).

**Comment by awayzjj** [comment]
@dmitry-gorokhov Thank you so much for your detailed suggestions on debugging. I followed your advice.
1. When the debugger reached the breakpoint, I opened the switch to disassembly view and clicked 'step into':
截屏2024-06-12 00 11 25
2. I clicked 'step over' for 5 instructions, and the view switched to another piece of code. I clicked 'step over' about 27 times and reached the region I marked:
截屏2024-06-12 00 23 00

I have 2 questions:
1. Did I find the correct region? It seems to correspond almost perfectly with the emitter I implemented, as the middle part of the picture above shows.
The value of the v10 register is 0x7fc00000, the value of the v18 register is 0xff800000, and the value of the v9 register is 0x0. I think v10 is the input element, and v9 is the result of the is_nan operation. It should be zero, but why failed test report the expected value 1 and the actual value 0?

Could you please give me some suggestions? Thank you very much!

**Comment by awayzjj** [comment]
@dmitry-gorokhov @eshoguli Could you please give me some suggestions on the above questions? Thank you very much!

**Comment by eshoguli** [comment]
Test: `./bin/arm64/Debug/ov_cpu_func_tests --gtest_filter="*smoke_IsOp/ComparisonLayerTest.Inference/IS=([]_[])_TS={(2.18)_(1)}_comparisonOpType=IsNaN_secondInputType=CONSTANT_in_type=f32_targetDevice=CPU*"`

1. put breakpoint here:
image

2. `blr x8` is jump into emitter implementation
image

3. your emitter implementation here:
image

4. tests `float32` input values (first 4 values):
```
0: inf
1: -inf
2: nan
3: nan
```

5. `v10` is stored `NaN` value. After `ld1r.4s {v10}, [x28]` in lldb console (definetelly what you store in emitter: `0x7fc00000`), as expected:
```
(lldb) register read v10 --format float32
     v10 = {NaN NaN NaN NaN}
(lldb) register read v10
     v10 = {0x00 0x00 0xc0 0x7f 0x00 0x00 0xc0 0x7f 0x00 0x00 0xc0 0x7f 0x00 0x00 0xc0 0x7f}
```
`v18` is input, as expected:
```
(lldb) register read v18 --format float32
     v18 = {+Inf -Inf NaN NaN}
```

**Comment by awayzjj** [comment]
@eshoguli Thank you so much for your detailed explanation! I will take some time to figure out how to display values from Eltwise::execute() in C++ as you showed in step 4.

What confuses me is the value of v9. I ran the same test case as yours and the values of registers is as follows:
截屏2024-06-14 21 57 05


In my case:

v10: {0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000}
v18: {0x7f800000, 0xff800000, 0x7f800006, 0x7fc00000} (In your case, it is v18 = {+Inf, -Inf, NaN, NaN}, the third value seems a little different. I will try to figure that out later.)
v9: {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
I expected the value of v9 to be {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1}. Could you show the value of v9 in your case and give me some tips on why the last element of v9 is zero (0) instead of one (1)?

**Comment by awayzjj** [comment]
@eshoguli @dmitry-gorokhov  Hi, I finished the debugging according your guidence and passed the tests on my local PC.
Could you please review the PR and trigger the CI ? Thank you very much!

**Comment by awayzjj** [comment]
Hello, @eshoguli @dmitry-gorokhov Just a friendly reminder to review this PR and trigger the CI when you have some time. I believe I’ve almost fixed the bug!

**Comment by mlukasze** [comment]
hey @awayzjj there is a list of conflicts to solve, before we will trigger CIs, could you, please?

**Comment by awayzjj** [comment]
@mlukasze Hi, I have solved the conflicts now!

**Comment by mlukasze** [comment]
thanks, I'm starting CIs now then

**Comment by mlukasze** [comment]
build_jenkins

**Comment by awayzjj** [comment]
@mlukasze Hi, there are still several failed tests. 
One of the failed tests is ` iGPU Tests`, but I thought my PR does not directly involve iGPU functionality since I implement the op on arm cpu plugin.
```
FAILED TESTS (1/31673):
     968 ms: /__w/openvino/openvino/install/tests/ov_gpu_func_tests smoke_TestsROIAlign_average/ROIAlignLayerTest.Inference/IS=([])_TS={(3.8.16.16)}_coordShape=(2.4)_pooledH=2_pooledW=2_spatialScale=0.625_poolingRatio=2_poolingMode=avg_modelType=f32_trgDev=GPU
Error: Process completed with exit code 1.
```

Meanwhile could you please show me the other failed test cases? Thank you very much!

**Comment by mlukasze** [comment]
let us check, someone will back to you soon.

**Comment by awayzjj** [comment]
> let us check, someone will back to you soon.

OK, look forward to someone's reply, so I can continue to work on the PR! Thank you very much!

**Comment by eshoguli** [comment]
**debian_9_arm**
ARM32 machine, jit emitters should not used.

Failed tests:
```
[smoke_Activation3D_Eltwise_CPU/ActivationLayerCPUTest.CompareWithRefs/IsNaN_TS=(2.4.4)_AS=()_ConstantsValue=()_netPRC=f32_inPRC=f32_outPRC=f32__inFmts=nwc_outFmts=nwc](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-debian_9_arm-cpu/10447/testReport/junit/(root)/smoke_Activation3D_Eltwise_CPU_ActivationLayerCPUTest/CompareWithRefs_IsNaN_TS__2_4_4__AS____ConstantsValue____netPRC_f32_inPRC_f32_outPRC_f32__inFmts_nwc_outFmts_nwc/)
[smoke_Activation3D_Eltwise_CPU/ActivationLayerCPUTest.CompareWithRefs/IsNaN_TS=(2.4.4)_AS=()_ConstantsValue=()_netPRC=f32_inPRC=f32_outPRC=f32__inFmts=ncw_outFmts=ncw](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-debian_9_arm-cpu/10447/testReport/junit/(root)/smoke_Activation3D_Eltwise_CPU_ActivationLayerCPUTest/CompareWithRefs_IsNaN_TS__2_4_4__AS____ConstantsValue____netPRC_f32_inPRC_f32_outPRC_f32__inFmts_ncw_outFmts_ncw/)
[smoke_Activation3D_Eltwise_CPU/ActivationLayerCPUTest.CompareWithRefs/IsNaN_TS=(2.17.5)_AS=()_ConstantsValue=()_netPRC=f32_inPRC=f32_outPRC=f32__inFmts=nwc_outFmts=nwc](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-debian_9_arm-cpu/10447/testReport/junit/(root)/smoke_Activation3D_Eltwise_CPU_ActivationLayerCPUTest/CompareWithRefs_IsNaN_TS__2_17_5__AS____ConstantsValue____netPRC_f32_inPRC_f32_outPRC_f32__inFmts_nwc_outFmts_nwc/)
[smoke_Activation3D_Eltwise_CPU/ActivationLayerCPUTest.CompareWithRefs/IsNaN_TS=(2.17.5)_AS=()_ConstantsValue=()_netPRC=f32_inPRC=f32_outPRC=f32__inFmts=ncw_outFmts=ncw](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-debian_9_arm-cpu/10447/testReport/junit/(root)/smoke_Activation3D_Eltwise_CPU_ActivationLayerCPUTest/CompareWithRefs_IsNaN_TS__2_17_5__AS____ConstantsValue____netPRC_f32_inPRC_f32_outPRC_f32__inFmts_ncw_outFmts_ncw/)
[smoke_Activation4D_Eltwise_CPU/ActivationLayerCPUTest.CompareWithRefs/IsNaN_TS=(2.4.4.1)_AS=()_ConstantsValue=()_netPRC=f32_inPRC=f32_outPRC=f32__inFmts=nhwc_outFmts=nhwc](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-debian_9_arm-cpu/10447/testReport/junit/(root)/smoke_Activation4D_Eltwise_CPU_ActivationLayerCPUTest/CompareWithRefs_IsNaN_TS__2_4_4_1__AS____ConstantsValue____netPRC_f32_inPRC_f32_outPRC_f32__inFmts_nhwc_outFmts_nhwc/)
[smoke_Activation4D_Eltwise_CPU/ActivationLayerCPUTest.CompareWithRefs/IsNaN_TS=(2.4.4.1)_AS=()_ConstantsValue=()_netPRC=f32_inPRC=f32_outPRC=f32__inFmts=nchw_outFmts=nchw](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-debian_9_arm-cpu/10447/testReport/junit/(root)/smoke_Activation4D_Eltwise_CPU_ActivationLayerCPUTest/CompareWithRefs_IsNaN_TS__2_4_4_1__AS____ConstantsValue____netPRC_f32_inPRC_f32_outPRC_f32__inFmts_nchw_outFmts_nchw/)
[smoke_Activation4D_Eltwise_CPU/ActivationLayerCPUTest.CompareWithRefs/IsNaN_TS=(2.17.5.4)_AS=()_ConstantsValue=()_netPRC=f32_inPRC=f32_outPRC=f32__inFmts=nhwc_outFmts=nhwc](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-debian_9_arm-cpu/10447/testReport/junit/(root)/smoke_Activation4D_Eltwise_CPU_ActivationLayerCPUTest/CompareWithRefs_IsNaN_TS__2_17_5_4__AS____ConstantsValue____netPRC_f32_inPRC_f32_outPRC_f32__inFmts_nhwc_outFmts_nhwc/)
[smoke_Activation4D_Eltwise_CPU/ActivationLayerCPUTest.CompareWithRefs/IsNaN_TS=(2.17.5.4)_AS=()_ConstantsValue=()_netPRC=f32_inPRC=f32_outPRC=f32__inFmts=nchw_outFmts=nchw](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-debian_9_arm-cpu/10447/testReport/junit/(root)/smoke_Activation4D_Eltwise_CPU_ActivationLayerCPUTest/CompareWithRefs_IsNaN_TS__2_17_5_4__AS____ConstantsValue____netPRC_f32_inPRC_f32_outPRC_f32__inFmts_nchw_outFmts_nchw/)
[smoke_Activation5D_Eltwise_CPU/ActivationLayerCPUTest.CompareWithRefs/IsNaN_TS=(2.4.3.4.1)_AS=()_ConstantsValue=()_netPRC=f32_inPRC=f32_outPRC=f32__inFmts=ndhwc_outFmts=ndhwc](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-debian_9_arm-cpu/10447/testReport/junit/(root)/smoke_Activation5D_Eltwise_CPU_ActivationLayerCPUTest/CompareWithRefs_IsNaN_TS__2_4_3_4_1__AS____ConstantsValue____netPRC_f32_inPRC_f32_outPRC_f32__inFmts_ndhwc_outFmts_ndhwc/)
[smoke_Activation5D_Eltwise_CPU/ActivationLayerCPUTest.CompareWithRefs/IsNaN_TS=(2.4.3.4.1)_AS=()_ConstantsValue=()_netPRC=f32_inPRC=f32_outPRC=f32__inFmts=ncdhw_outFmts=ncdhw](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-debian_9_arm-cpu/10447/testReport/junit/(root)/smoke_Activation5D_Eltwise_CPU_ActivationLayerCPUTest/CompareWithRefs_IsNaN_TS__2_4_3_4_1__AS____ConstantsValue____netPRC_f32_inPRC_f32_outPRC_f32__inFmts_ncdhw_outFmts_ncdhw/)
[smoke_Activation5D_Eltwise_CPU/ActivationLayerCPUTest.CompareWithRefs/IsNaN_TS=(2.17.7.5.4)_AS=()_ConstantsValue=()_netPRC=f32_inPRC=f32_outPRC=f32__inFmts=ndhwc_outFmts=ndhwc](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-debian_9_arm-cpu/10447/testReport/junit/(root)/smoke_Activation5D_Eltwise_CPU_ActivationLayerCPUTest/CompareWithRefs_IsNaN_TS__2_17_7_5_4__AS____ConstantsValue____netPRC_f32_inPRC_f32_outPRC_f32__inFmts_ndhwc_outFmts_ndhwc/)
[smoke_Activation5D_Eltwise_CPU/ActivationLayerCPUTest.CompareWithRefs/IsNaN_TS=(2.17.7.5.4)_AS=()_ConstantsValue=()_netPRC=f32_inPRC=f32_outPRC=f32__inFmts=ncdhw_outFmts=ncdhw](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-debian_9_arm-cpu/10447/testReport/junit/(root)/smoke_Activation5D_Eltwise_CPU_ActivationLayerCPUTest/CompareWithRefs_IsNaN_TS__2_17_7_5_4__AS____ConstantsValue____netPRC_f32_inPRC_f32_outPRC_f32__inFmts_ncdhw_outFmts_ncdhw/)
[smoke_Activation5D_dynamicMath_CPU/ActivationLayerCPUTest.CompareWithRefs/IsNaN_IS=([?.?])_TS=(1.50)_(5.128)_(3.64)_AS=()_ConstantsValue=()_netPRC=f32_inPRC=f32_outPRC=f32_](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-debian_9_arm-cpu/10447/testReport/junit/(root)/smoke_Activation5D_dynamicMath_CPU_ActivationLayerCPUTest/CompareWithRefs_IsNaN_IS_________TS__1_50___5_128___3_64__AS____ConstantsValue____netPRC_f32_inPRC_f32_outPRC_f32_/)
[smoke_Activation5D_dynamicMath_CPU/ActivationLayerCPUTest.CompareWithRefs/IsNaN_IS=([?.?.?.?.?.?.?.?])_TS=(2.2.2.2.2.2.2.2)_(2.3.2.3.2.3.2.3)_(3.3.3.3.3.3.3.3)_AS=()_ConstantsValue=()_netPRC=f32_inPRC=f32_outPRC=f32_](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-debian_9_arm-cpu/10447/testReport/junit/(root)/smoke_Activation5D_dynamicMath_CPU_ActivationLayerCPUTest/CompareWithRefs_IsNaN_IS_____________________TS__2_2_2_2_2_2_2_2___2_3_2_3_2_3_2_3___3_3_3_3_3_3_3_3__AS____ConstantsValue____netPRC_f32_inPRC_f32_outPRC_f32_/)
[smoke_Activation5D_dynamicMath_CPU/ActivationLayerCPUTest.CompareWithRefs/IsNaN_IS=([1..5.128])_TS=(1.128)_(3.128)_(5.128)_AS=()_ConstantsValue=()_netPRC=f32_inPRC=f32_outPRC=f32_](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-debian_9_arm-cpu/10447/testReport/junit/(root)/smoke_Activation5D_dynamicMath_CPU_ActivationLayerCPUTest/CompareWithRefs_IsNaN_IS___1__5_128___TS__1_128___3_128___5_128__AS____ConstantsValue____netPRC_f32_inPRC_f32_outPRC_f32_/)
```
ACL should be used, not reference, error message:
```
../../../../../../../repos/openvino/src/plugins/intel_cpu/tests/functional/utils/cpu_test_utils.cpp:220
Value of: primTypeCheck(primType)
  Actual: false
Expected: true
primType is unexpected : ref_f32 Expected : acl_f32
```

**Comment by awayzjj** [comment]
@eshoguli I think I fixed the issues, could you please review the PR and trigger the CI? Thank you very much!

**Comment by mlukasze** [comment]
build_jenkins

**Comment by awayzjj** [comment]
@eshoguli Hi, I made some changes similar to my implement for [Mod operation](https://github.com/openvinotoolkit/openvino/pull/24574/commits/5335a1a7b8871c86742a1d56b160240438b446d7), but the debian_9_arm tests still failed,  (Meanwhile invisible tests like build_ubuntu22_release and Windows CPU functional tests failed too.)
Could you give me some suggestions? Thank you very much!

**Comment by awayzjj** [comment]
> @eshoguli Hi, I made some changes similar to my implement for [Mod operation](https://github.com/openvinotoolkit/openvino/pull/24574/commits/5335a1a7b8871c86742a1d56b160240438b446d7), but the debian_9_arm tests still failed, (Meanwhile invisible tests like build_ubuntu22_release and Windows CPU functional tests failed too.) Could you give me some suggestions? Thank you very much!

Hello, @eshoguli @dmitry-gorokhov  Just a friendly reminder to kindly assist in rechecking the failed tests and offering any suggestions you may have. (Unfortunately, I don't have access to an ARM32 machine for debugging purposes.) Thank you very much!

**Comment by dmitry-gorokhov** [comment]
> > @eshoguli Hi, I made some changes similar to my implement for [Mod operation](https://github.com/openvinotoolkit/openvino/pull/24574/commits/5335a1a7b8871c86742a1d56b160240438b446d7), but the debian_9_arm tests still failed, (Meanwhile invisible tests like build_ubuntu22_release and Windows CPU functional tests failed too.) Could you give me some suggestions? Thank you very much!
> 
> Hello, @eshoguli @dmitry-gorokhov Just a friendly reminder to kindly assist in rechecking the failed tests and offering any suggestions you may have when you have some time. (Unfortunately, I don't have access to an ARM32 machine for debugging purposes.) Thank you very much!

Hi @awayzjj. As far as I can see remaining issue is not caused by your changes, but rather some bug in Eltwise node itself. Please remove `IsNan` type from `activationTypesDynamicMath` list. It will help to make your CI green. We will investigate mentioned issue separately.

**Comment by dmitry-gorokhov** [comment]
build_jenkins

**Comment by awayzjj** [comment]
@dmitry-gorokhov The CI is full green !!!  Can you merge it into master? Thank you very much!

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
> @dmitry-gorokhov The CI is full green !!! Can you merge it into master? Thank you very much!
> 
> Still a question, why some emitter like IsNaN and Floor need make the following changes ,while others don not. 截屏2024-06-24 21 41 54

PR added to the merge queue!

Regarding your question. CPU plugin have different kernel types for elementwise operations:
1. JIT code - OV emitters like you just implemeted (available for ARM 64 bit systems only)
2. ACL - [kernels](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_cpu/src/nodes/executors/acl/acl_eltwise.cpp#L41-L74) executed via thirdparty ARM compute library (available both for ARM32 and ARM64).
3. Ref kernels - pure OV C++ code ((available both for ARM32 and ARM64).
Tests checks implementation type (jit, acl or ref). So for activations which are not supported by ACL on ARM32 platfrom you need to directly set 'ref" type as expected.

**Comment by awayzjj** [comment]
> > @dmitry-gorokhov The CI is full green !!! Can you merge it into master? Thank you very much!
> > Still a question, why some emitter like IsNaN and Floor need make the following changes ,while others don not. 截屏2024-06-24 21 41 54
> 
> PR added to the merge queue!
> 
> Regarding your question. CPU plugin have different kernel types for elementwise operations:
> 
> 1. JIT code - OV emitters like you just implemeted (available for ARM 64 bit systems only)
> 2. ACL - [kernels](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_cpu/src/nodes/executors/acl/acl_eltwise.cpp#L41-L74) executed via thirdparty ARM compute library (available both for ARM32 and ARM64).
> 3. Ref kernels - pure OV C++ code ((available both for ARM32 and ARM64).
>    Tests checks implementation type (jit, acl or ref). So for activations which are not supported by ACL on ARM32 platfrom you need to directly set 'ref" type as expected.

Got it! Thank you for guiding me on how to debugging, I will continue to finish other emitters!

**Pull request merged**
