### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by co63oc**
### Details:
 - *item1*
 - *...*
Fix some typos

### Tickets:
 - *ticket-id*

### CODE REVIEW

**Review by rkazants — APPROVED** [review]

**Comment by rkazants** [comment]
build_jenkins

**Comment by co63oc** [comment]
build_jenkins

**Comment by co63oc** [comment]
@rkazants  CI is not continuing, do I need to run any commands?
image

**Comment by rkazants** [comment]
build_jenkins

**Pull request merged**
