### PR TITLE
[VPU] TopK: Relax requirement for supporting Sort::None mode if K==1

### PR DESCRIPTION
**Pull request by AndrewBakalinIntel**
Ticket - #-40347

### CODE REVIEW

**Comment by AndrewBakalinIntel** [comment]
@andreychekhoninintel @elatkin could you please take a look?

**Review by elatkin — CHANGES_REQUESTED** [review]
HDDL build on Windows fails due to compilation error. Could you please fix this problem?

**Comment by AndrewBakalinIntel** [comment]
> HDDL build on Windows fails due to compilation error. Could you please fix this problem?

Done, the CI is green now.

**Review by elatkin — APPROVED** [review]

**Review by andreychekhoninintel — APPROVED** [review]

**Comment by AndrewBakalinIntel** [comment]
@Maxim-Doronin could you please merge?

**Pull request merged**
