### PR TITLE
[IE VPU] Support 3 outputs for LSTMSequence

### PR DESCRIPTION
**Pull request by andrejsokolov**
-26693 - Adding the possibility of obtaining the 3rd output (LSTMSequence)
mdk PR: 14214

### CODE REVIEW

**Comment by andrejsokolov** [comment]
@gladilov-gleb, @avershov, it is duplicate of PR: https://github.com/openvinotoolkit/openvino/pull/656, but without test modification.

**Comment by DariaMityagina** [comment]
I will change output storing according to Gleb's comment.

**Comment by andrejsokolov** [comment]
> I will change output storing according to Gleb's comment.

I think we can leave these changes for the future. Let's take current implementation.

**Comment by azhogov** [comment]
Please create a dev branch in your fork

**Pull request closed without merging**
