### PR TITLE
[ONNX] Aligned ReduceL1 behavior #20559

### PR DESCRIPTION
**Pull request by RitikaxShakya**
### Details:
 -I've aligned the ReduceL1 operation with opset 11, 13, and 18. created test models, and added them inside onnx_import.in.cpp.

### Tickets:
 - **https://github.com/openvinotoolkit/openvino/issues/20559**

### CODE REVIEW

**Comment by RitikaxShakya** [comment]
@gkrivor I have few question regarding 
1. I can't find reduce.hpp file.
2. There aren't any registered ops in ops_bridge.cpp so do i still need to register there ?

**Comment by gkrivor** [comment]
@RitikaxShakya you are correct. I moved registration near translator's definition.

**Comment by RitikaxShakya** [comment]
> @RitikaxShakya you are correct. I moved registration near translator's definition.

Oh okay, let me know if there's anything i have to do from my side. Thank you!

**Comment by gkrivor** [comment]
build_jenkins

**Comment by gkrivor** [comment]
build_jenkins

**Comment by gkrivor** [comment]
build_jenkins

**Review by gkrivor — APPROVED** [review]

**Pull request merged**
