### PR TITLE
generator functionality to pytest

### PR DESCRIPTION
**Pull request by PRATHAM-SPS**
**Details:** Replaced the generator's functionality with pytest

**Tickets:** 110705

### CODE REVIEW

**Comment by PRATHAM-SPS** [comment]
**Pylint for the same file:-**(assert on tupple)
image

**Output of pytest :-** 

================================================================ test session starts =================================================================
platform linux -- Python 3.7.13, pytest-7.2.2, pluggy-1.2.0
rootdir: /home/pratham/Desktop/openvino/openvino/tools/mo
collected 27 items                                                                                                                                   

compress_quantized_weights_test.py ...........................                                                                                 [100%]

================================================================== warnings summary ==================================================================
compress_quantized_weights_test.py:342
  /home/pratham/Desktop/openvino/openvino/tools/mo/unit_tests/mo/back/compress_quantized_weights_test.py:342: PytestAssertRewriteWarning: assertion is always true, perhaps remove parentheses?
    assert (len(const_node), 1)

compress_quantized_weights_test.py:263
  /home/pratham/Desktop/openvino/openvino/tools/mo/unit_tests/mo/back/compress_quantized_weights_test.py:263: PytestAssertRewriteWarning: assertion is always true, perhaps remove parentheses?
    assert (len(fq_nodes), 1, error_message.format('FakeQuantize', 'before', len(fq_nodes)))

compress_quantized_weights_test.py:271
  /home/pratham/Desktop/openvino/openvino/tools/mo/unit_tests/mo/back/compress_quantized_weights_test.py:271: PytestAssertRewriteWarning: assertion is always true, perhaps remove parentheses?
    assert (len(fq_nodes), 0, error_message.format('FakeQuantize', 'after', len(fq_nodes)))

../../../../../../../../anaconda3/envs/openvino/lib/python3.7/site-packages/defusedxml/__init__.py:30
  /home/pratham/anaconda3/envs/openvino/lib/python3.7/site-packages/defusedxml/__init__.py:30: DeprecationWarning: defusedxml.cElementTree is deprecated, import from defusedxml.ElementTree instead.
    from . import cElementTree

unit_tests/mo/back/compress_quantized_weights_test.py: 12 warnings
  /home/pratham/Desktop/openvino/openvino/tools/mo/openvino/tools/mo/ops/Cast.py:111: DeprecationWarning: Converting `np.generic` to a dtype is deprecated. The current result is `np.dtype(np.void)` which is not strictly correct.
    if dst_type in [packed_U4, packed_I4]:  # custom types conversion

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================== 27 passed, 16 warnings in 4.51s ===========================================================

**Comment by PRATHAM-SPS** [comment]
@rkazants  @popovaan @mvafin this file also contains the unittest functionality , so  is there need to switch from unittest to pytest?

**Comment by rkazants** [comment]
build_jenkins

**Review by rkazants — APPROVED** [review]

**Comment by rkazants** [comment]
> @rkazants @popovaan @mvafin this file also contains the unittest functionality , so is there need to switch from unittest to pytest?

Not needed if this test still presents in the scope and not skipped. Please check that all tests are preserved.

**Comment by rkazants** [comment]
build_jenkins

**Comment by PRATHAM-SPS** [comment]
> > @rkazants @popovaan @mvafin this file also contains the unittest functionality , so is there need to switch from unittest to pytest?
> 
> Not needed if this test still presents in the scope and not skipped. Please check that all tests are preserved.

yes all tests are preserved but i have to use 2 diffrent comands to check unnitest and pytest  (test-cases)  respectively.

**command for UNIT_TEST:**-  python -m unittest discover -p "compress_quantized_weights_test.py" 

**command for PYTEST:**- pytest "compress_quantized_weights_test.py"

**Comment by rkazants** [comment]
build_jenkins

**Comment by PRATHAM-SPS** [comment]
@rkazants  CI is failling again and again

**Comment by rkazants** [comment]
build_jenkins

**Comment by rkazants** [comment]
@PRATHAM-SPS, I upstreamed your branch. Looks sporadic issue in CI.

**Comment by rkazants** [comment]
build_jenkins

**Comment by rkazants** [comment]
build_jenkins

**Comment by rkazants** [comment]
@PRATHAM-SPS, CI looks fixed now in the end of this day. Let us anticipate green CI.

**Pull request merged**
