### PR TITLE
[GPU] Moved plugin to new source dir

### PR DESCRIPTION
**Pull request by vladimir-paramuzov**
### Details:
 - Plugin code is moved to src/plugins/intel_gpu w/o any code changes
 - Split headers and source files into separate directories to be aligned with new component structure proposal
 - Minimal changes in CMake config
 - Added new ENABLE_INTEL_GPU cmake option to enable/disable gpu plugin built (ENABLE_CLDNN is kept for backward compatibility)
 - Updated CODEOWNERS

Out of scope:
 - cldnn merge with plugin
 - any renaming & refactoring of plugin sources
 
### Tickets:
 - Part of *71044*

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
should we remove `cldnn` from filenames like `cldnn_transformations_pipeline.cpp`?

**Comment by vladimir-paramuzov** [comment]
> should we remove `cldnn` from filenames like `cldnn_transformations_pipeline.cpp`?
> 
> Example #8872

Yes, filenames will be refactored along with namespaces and class names, but it'll be done in separate PR(s)

**Comment by ilya-lavrenov** [comment]
* `plugins/intel_gpu/src/plugin/` - why do we need plugin here? Are we going to add more folders here like cldnn?
* `plugins/intel_gpu/include/intel_gpu/plugin/`  - why do we need `intel_gpu` here?

**Comment by vladimir-paramuzov** [comment]
> * `plugins/intel_gpu/src/plugin/` - why do we need plugin here? Are we going to add more folders here like cldnn?
> * `plugins/intel_gpu/include/intel_gpu/plugin/`  - why do we need `intel_gpu` here inside `include`?

More sub-components will be added with cldnn merge with plugin.
So it'll be something as follows:
```
src/
  plugins/
    intel_gpu/
      include/
        intel_gpu/
          plugin/
          runtime/
          graph/
          primitives/
      src/
        plugin/
        runtime/
        kernel_selector
        ...
        
```
target include directory will be src/plugins/intel_gpu/include/ and sources will include it as 
```
#include "intel_gpu/plugin/infer_request.hpp"
#include "intel_gpu/runtime/engine.hpp"
etc
```
That's the current idea. Technically we can shorten include path to "plugin/infer_request.hpp", but I'd want to clearly specify that given header is a part of plugin (not core or something else).

**Comment by ilya-lavrenov** [comment]
Just an alternative aligned with other OV:
```
src/
  plugins/
    intel_gpu/
      kernel_selector
        include/
        src/      
      plugin/
        include/
        src/      
     runtime/
        include/
        src/      
     graph/
        include/
        src/      
```

**Comment by vladimir-paramuzov** [comment]
> Just an alternative aligned with other OV, but up to you:
> 
> ```
> src/
>   plugins/
>     intel_gpu/
>       kernel_selector
>         include/
>         src/      
>       plugin/
>         include/
>         src/      
>      runtime/
>         include/
>         src/      
>      graph/
>         include/
>         src/      
> ```

Most of the team members voted for approach implemented in this PR, so let's keep it as is.

**Review by sshlyapn — APPROVED** [review]

**Pull request merged**
