### PR TITLE
Added print ov::Tensor

### PR DESCRIPTION
**Pull request by ilyachur**
### Details:
 - Add `std::cout` for `ov::Tensor`
 - `std::setprecision` can be used to set minimal number of variables which will be printed (min: 10)

### Tickets:
 - *ticket-id*

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
why do we need it? debug capability?

**Comment by ilyachur** [comment]
Binary size:

- Before 21843859 Feb 16 14:33 libopenvino.2023.0.0.dylib
- After 21844419 Feb 16 14:28 libopenvino.2023.0.0.dylib
Diff: 21844419 - 21843859 = 560 bytes

**Comment by akladiev** [comment]
This PR will be closed in 2 weeks in case of no activity.

**Comment by akladiev** [comment]
This PR was closed because it has been stalled for 2 week with no activity.

**Pull request closed without merging**
