### PR TITLE
[CPU] Reload childConf local copy after child node initOptimalPrimitiveDesc

### PR DESCRIPTION
**Pull request by usstq**
### Details:
 - *childConf is a local copy of an entry of inConfs[], and it needs to be updated after child node's initOptimalPrimitiveDescriptor() is called, since initOptimalPrimitiveDescriptor() may change inConfs[] insdie*

### Tickets:
 - *CVS-82485*

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@usstq Is the PR ready for review?

**Comment by usstq** [comment]
@dmitry-gorokhov Yes, please, Thanks!

**Comment by akladiev** [comment]
This PR will be closed in 2 weeks in case of no activity.

**Comment by akladiev** [comment]
This PR was closed because it has been stalled for 2 week with no activity.

**Pull request closed without merging**
