### PR TITLE
[GHA] Fix for premature sccache server shutdown on Windows

### PR DESCRIPTION
**Pull request by ababushk**
### Details:
This should fix the following sporadic issues:

```
2024-02-16T21:40:26.9140419Z sccache: error: failed to execute compile
2024-02-16T21:40:26.9141391Z sccache: caused by: Failed to send data to or receive data from server
2024-02-16T21:40:26.9142455Z sccache: caused by: Failed to read response header
2024-02-16T21:40:26.9144951Z sccache: caused by: A connection attempt
failed because the connected party did not properly respond after a
period of time, or established connection failed because connected
host has failed to respond. (os error 10060)
```

and

```
2024-02-16T21:40:26.9140419Z sccache: error: failed to execute compile
2024-02-16T21:40:26.9141391Z sccache: caused by: Failed to send data to or receive data from server
2024-02-16T21:40:26.9142455Z sccache: caused by: Failed to read response header
2024-02-16T21:40:26.9144951Z sccache: caused by: A connection attempt
failed because the connected party did not properly respond after a
period of time, or established connection failed because connected
host has failed to respond. (os error 10060)
```

### CODE REVIEW

**Review by akladiev — APPROVED** [review]

**Review by ilya-lavrenov — APPROVED** [review]
is it Windows specific only?

**Comment by ababushk** [comment]
> is it Windows specific only?

@ilya-lavrenov Yes, for some reason these sccache errors occur only on Windows

**Comment by mryzhov** [comment]
SCCACHE_IDLE_TIMEOUT how long the local daemon process waits for more client requests before exiting, in seconds. Set to 0 to run sccache permanently 

Maybe 300 seconds is better then 0?

**Comment by mryzhov** [comment]
btw the default value is
const DEFAULT_IDLE_TIMEOUT: u64 = 600;

**Pull request merged**
