### PR TITLE
[CPU] Changed output blobs creation used output info

### PR DESCRIPTION
**Pull request by mandrono**
### Tickets:
 - Issue: 45611

### CODE REVIEW

**Comment by mandrono** [comment]
@dmitry-gorokhov could you take a look please?

**Comment by akuporos** [comment]
Please, also remove this skip https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/ie_bridges/python/tests/test_Blob.py#L103

This is python API test for this PR

**Comment by akuporos** [comment]
Please also uncomment this: https://github.com/openvinotoolkit/openvino/blob/d116613da9a3b2e66e06e6aa0237d394cc125944/inference-engine/ie_bridges/python/tests/test_InferRequest.py#L569

In case of any question please contact me directly

**Comment by dmitry-gorokhov** [comment]
@mandrono  I guess we decided to resolve this in bounds of https://github.com/openvinotoolkit/openvino/pull/9456? Seems like the PR is not relevant anymore.

**Pull request closed without merging**
