### PR TITLE
Eliminated invalid sub-graphs with constant, parameter and result layers

### PR DESCRIPTION
**Pull request by apankratovantonp**

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
is it valid for GPU / VPU?

**Comment by apankratovantonp** [comment]
> is it valid for GPU / VPU?

This plugin process constants correctly

**Review by ilya-lavrenov — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
@apankratovantonp please, resubmit to 2021.1 release branch as well.

**Comment by ilya-lavrenov** [comment]
@apankratovantonp looks like we need to re-apply the patch once again.

**Pull request merged**
