### PR TITLE
[PT FE] Add skip for prim::device

### PR DESCRIPTION
**Pull request by mmikolajcz**
### Details:
 - *Skip prim::device operation*
Operator `prim::device` in PyTorch is used to indicate on with device Tensors will be allocated. Skipping it, since in OV we don't have operations that support such actions

### Tickets:
 - *99232*

### CODE REVIEW

**Review by sikorsl1 — APPROVED** [review]
Impressive piece of code!

**Comment by mvafin** [comment]
I don't think we can just skip `prim::device`

**Comment by eaidova** [comment]
@mmikolajcz  are you looked how it is used in models?

I see some conditional usage for if like that https://github.com/pytorch/vision/blob/main/torchvision/ops/boxes.py#L72
where device detection used for selecting implementation details, so just skipping is not variant here

**Comment by mmikolajcz** [comment]
Thanks @mvafin @eaidova. I mostly though for cases like "aten::to" where device is just ignored, didn't though about it used in control flow like that with prim::type.
How output from deice is used is quite depended at consumer op, maybe best way would be to not skip device or do anything on this op level like @mvafin suggested and rely on consumers of this op to remove it?
I guess hardcoding it to always return "cpu" probably wouldn't be best solution, and I don't think we can retrieve in OV on what device tensors were located.

**Pull request closed without merging**
