### PR TITLE
Change reshape_for_mvn shape to match reference

### PR DESCRIPTION
**Pull request by bsledz**
### Details:
This PR is related with:
https://github.com/openvinotoolkit/openvino/pull/4579

After fixes in ONNX Importer, the model can be imported, but there is a minimal result mismatch compared to the MO.
Reason:
Model optimizer for MVN input is preparing following shape: [num_groups*N, C // num_groups, H, W],
but according to this paper: https://arxiv.org/pdf/1803.08494.pdf, the shape should be as follows:
[N, num_groups, C // num_groups, H, W]. This causes little numerical mismatch.
### Tickets:
49728
52832 (new)

### CODE REVIEW

**Comment by lazarevevgeny** [comment]
@mvafin , please, take a look at these changes

**Review by mvafin — COMMENTED** [review]
@lazarevevgeny, We need to verify that it works for existing models, could you run DL Bench for this?

**Comment by lazarevevgeny** [comment]
I think that the MO generates tensor of 4D shape `[num_groups*N, C // num_groups, H, W]` because not all plugins support MVN with 5D input. So if we apply this change then some model may stop working with a new version of the model. 

@jane-intel , @mvafin , am I right? Do you recall some other reasons?

@bsledz , please, contact all plugin owners and make sure that their plugins support MVN with 5D input.

**Review by lazarevevgeny — CHANGES_REQUESTED** [review]
Left a comment to contact with plugin owners to check that 5D MVN is supported.

**Comment by bsledz** [comment]
> I think that the MO generates tensor of 4D shape `[num_groups*N, C // num_groups, H, W]` because not all plugins support MVN with 5D input. So if we apply this change then some model may stop working with a new version of the model.
> 
> @jane-intel , @mvafin , am I right? Do you recall some other reasons?
> 
> @bsledz , please, contact all plugin owners and make sure that their plugins support MVN with 5D input.

After week I have response only from two plugin owners... (I wrote an email to all plugin owners)

@lazarevevgeny, @mvafin, @jane-intel  Do you have any news on this? There is also an option to adjust onnx importer, but then it won't be OK with article.

**Comment by lazarevevgeny** [comment]
> > I think that the MO generates tensor of 4D shape `[num_groups*N, C // num_groups, H, W]` because not all plugins support MVN with 5D input. So if we apply this change then some model may stop working with a new version of the model.
> > @jane-intel , @mvafin , am I right? Do you recall some other reasons?
> > @bsledz , please, contact all plugin owners and make sure that their plugins support MVN with 5D input.
> 
> After week I have response only from two plugin owners... (I wrote an email to all plugin owners)
> 
> @lazarevevgeny, @mvafin, @jane-intel Do you have any news on this? There is also an option to adjust onnx importer, but then it won't be OK with article.

Ping them again. 

Anyway, from the mathematical perspective the results of both formulas should be equal because the normalization is performed over the same dimensions (`C // num_groups, H, W`). May be this is some bug in CPU plugin? Can you compare results with other plugin, for example, GPU?

**Comment by bsledz** [comment]
> > > I think that the MO generates tensor of 4D shape `[num_groups*N, C // num_groups, H, W]` because not all plugins support MVN with 5D input. So if we apply this change then some model may stop working with a new version of the model.
> > > @jane-intel , @mvafin , am I right? Do you recall some other reasons?
> > > @bsledz , please, contact all plugin owners and make sure that their plugins support MVN with 5D input.
> > 
> > 
> > After week I have response only from two plugin owners... (I wrote an email to all plugin owners)
> > @lazarevevgeny, @mvafin, @jane-intel Do you have any news on this? There is also an option to adjust onnx importer, but then it won't be OK with article.
> 
> Ping them again.
> 
> Anyway, from the mathematical perspective the results of both formulas should be equal because the normalization is performed over the same dimensions (`C // num_groups, H, W`). May be this is some bug in CPU plugin? Can you compare results with other plugin, for example, GPU?

@lazarevevgeny
Yes I agree that from a mathematical point of view the results should be the same, but the mismatch looks like a numerical error.
The difference is small (for the model mentioned in the ticket):
Max Rel diff: 0.0526663
Max Abs diff: 00129782
(comparison of 5D and 4D input)

I got answers from some plugin owners and one answer is interesting:
"5D shape for MVN is supported in GPU plugin, but 4d tensor formats are usually better optimized, so there’s a high chance of performance regressions. Please consider running DL benchmark for fp16/int8 precisions to verify your patch."

Maybe that was the reason for this approach? In that case, I suggest changing ONNX Importer instead of MO.

BTW. I'm working on comparing the CPU and GPU results

**Comment by bsledz** [comment]
"VPU part supports only 4D input as for Myriad as KMB. And batch size must be 1.
To support one more dimention == 1 is not so expensive. But the implementation for full 5D input needs new low-level code."

@lazarevevgeny You were right.

**Pull request closed without merging**
