### PR TITLE
[ONNX] Extended BatchNorm to support opsets 1-6-7-9-14-15

### PR DESCRIPTION
**Pull request by Bepitic**
### Details:
 - *Addition of Batchnorm opset 1 6 7 9 14 & 15*
 - *Creation of the tests CPP for the respective opset, and their prototxt models.*

### Tickets:
 - 20554 : [20554](https://github.com/openvinotoolkit/openvino/issues/20554)
 - 18485 :  [18485](https://github.com/openvinotoolkit/openvino/issues/18485)

### CODE REVIEW

**Comment by Bepitic** [comment]
Hello @p-wysocki and @gkrivor, Should I do something else in the PR, or wait for the reviewer?

**Comment by p-wysocki** [comment]
Hello @Bepitic, thanks for the contribution! Let's wait for @gkrivor.

**Comment by gkrivor** [comment]
Hi @Bepitic , could you clarify difference between added implementations? I tried to understand difference between opset-14 and opset-15, as example, and see it only for training case:
> Opset-14
> If set to true, it indicates BatchNormalization is being used for training, and outputs 1, 2, 3, and 4 would be populated.
> Opset-15
> If set to true, it indicates BatchNormalization is being used for training, and outputs 1 and 2 are to be computed.

Also I see a notification about internal implementation for Opset-15:
> The computation of ReduceMean and ReduceVar uses float to avoid overflow for float16 inputs.

It also should be mentioned, but because we are translating BatchNormalization to OpenVINO's BatchNormalization - it is hidden from Frontend in internal implementation of an exact plugin. And it would be meaningful in case we will get accuracy issues later.

If there is no difference I suggest to add a comment why we don't want to implement redundant logic because there is no difference from OpenVINO perspective (like here https://github.com/openvinotoolkit/openvino/pull/23429/files in reduce.cpp about opset-11 and opset-1). In case we will need to implement some training features - we will lay on this information later to understand why we skipped it before.

**Comment by Bepitic** [comment]
There is no noticeable difference, at least for the frontend part.
The mentioned training case with multiple outputs, I believe that is a typo in the changelog documentation.
 Since it does not have that many outputs the opset BNorm-14.
 
 The most noticeable difference is the mentioned internal implementation and rearranging and renaming of the 'Type Constraints', which I believe is not linked to the frontend or internal OpenVINO implementation,( it didn't change the type of any variable).
 
 I'll add the comment and update the PR.

**Comment by Bepitic** [comment]
Hello, @gkrivor, I already removed the duplicity of the multiple opsets, leaving the ones that change significantly, and leaving comments on the skipped opsets.

**Comment by Bepitic** [comment]
Hello, @mitruska and @gkrivor, should I modify something or improve something?
Thank you for your time.

**Comment by gkrivor** [comment]
build_jenkins

**Review by gkrivor — APPROVED** [review]

**Pull request merged**
