### PR TITLE
[TRANSFORMATIONS][CPU] Move RoPE to common part

### PR DESCRIPTION
**Pull request by Lyamin-Roman**
### Details:
 - *Transferring RoPE operation and transformations for subsequent reuse in GPU plugin*

### CODE REVIEW

**Comment by itikhono** [comment]
it looks like, it will conflict with Slice op supporting in RoPE fusion patterns https://github.com/openvinotoolkit/openvino/pull/24379

**Review by p-durandin — APPROVED** [review]
OK for transferring current CPU implementation for common part for CPU/GPU

**Review by usstq — COMMENTED** [review]
Can we also move `src/plugins/intel_cpu/src/utils/print_model.hpp` into some subfolders of `src/common/transformations/....`  since this tools is designed to be working together with gen_pattern.hpp, [PR20729](https://github.com/openvinotoolkit/openvino/pull/20729) has some example usage in description.

**Review by usstq — COMMENTED** [review]
One important consideration on RoPE pattern matching is, where it should be located in the whole transformation pipeline (since it's a big&complex pattern), if it was too late, then any small change in previous transformation-stage would fail the pattern easily. I have met such case several times and the pattern maintenance is extremely painful.

So when do pattern matching on such big&complex pattern, we should do it as early as possible, unfortunately current design is not early enough, so when GPU plugin is trying to match RoPE pattern too, the matching may fail due to the fact that GPU plugin may have different transformation stages before calling RoPE Fusion.

Ideally it should be placed in the earliest possible stage of the whole transformation pipeline, which is frontend, I think OV should add a new complex OP RoPE, just like [ov::op::v13::ScaledDotProductAttention](https://docs.openvino.ai/2024/api/c_cpp_api/classov_1_1op_1_1v13_1_1_scaled_dot_product_attention.html), and following same usage:
  - transform to it in frontend or even in raw-pytorch modules
  - decompose it when plugin do not support it.

This way it can benefit all plugin in a much better way.

**Review by usstq — APPROVED** [review]
LGTM!

**Pull request merged**
