### PR TITLE
[PT FE] Inherit signature from forward while patching

### PR DESCRIPTION
**Pull request by mvafin**
### Details:
 - *Inherit signature from forward while patching*

### Tickets:
 - *ticket-id*

### CODE REVIEW

**Review by rkazants — COMMENTED** [review]
can you add a test please to reproduce this case?

**Review by eaidova — APPROVED** [review]

**Comment by eaidova** [comment]
in my case it works:
```python

import openvino as ov
from openvino.frontend.pytorch.patch_model import __make_16bit_traceable
import torch
embeddings =  torch.nn.Embedding(10, 20)
with torch.no_grad():
    __make_16bit_traceable(embeddings)
    ov_model = ov.convert_model(embeddings, example_input=torch.ones([1, 2], dtype=torch.long))
```

before changes:
```
<Model: 'Model0'
inputs[
<ConstOutput: names[args] shape[?,?] type: i64>
]
outputs[
<ConstOutput: names[] shape[?,?,20] type: f32>
]>
```

after changes:
```
<Model: 'Model2'
inputs[
<ConstOutput: names[input] shape[?,?] type: i64>
]
outputs[
<ConstOutput: names[] shape[?,?,20] type: f32>
]>
```

input signature:
```
>>> inspect.signature(embeddings.forward)
<Signature (input: torch.Tensor) -> torch.Tensor>
```

**Comment by rkazants** [comment]
> ```python
> _make_16bit_traceable(embeddings)
> ```

Let us add such test case.

**Comment by rkazants** [comment]
> in my case it works:
> 
> ```python
> import openvino as ov
> from openvino.frontend.pytorch.patch_model import __make_16bit_traceable
> import torch
> embeddings =  torch.nn.Embedding(10, 20)
> with torch.no_grad():
>     __make_16bit_traceable(embeddings)
>     ov_model = ov.convert_model(embeddings, example_input=torch.ones([1, 2], dtype=torch.long))
> ```
> 
> before changes:
> 
> ```
> <Model: 'Model0'
> inputs[
> <ConstOutput: names[args] shape[?,?] type: i64>
> ]
> outputs[
> <ConstOutput: names[] shape[?,?,20] type: f32>
> ]>
> ```
> 
> after changes:
> 
> ```
> <Model: 'Model2'
> inputs[
> <ConstOutput: names[input] shape[?,?] type: i64>
> ]
> outputs[
> <ConstOutput: names[] shape[?,?,20] type: f32>
> ]>
> ```
> 
> input signature:
> 
> ```
> >>> inspect.signature(embeddings.forward)
> <Signature (input: torch.Tensor) -> torch.Tensor>
> ```

Let us add such test case.

**Pull request merged**
