### PR TITLE
Revise data generators used in layout tests

### PR DESCRIPTION
**Pull request by davidsnam-intel**
### Details:
 - *Change uniform_int_distribution to uniform_real_distribution*

### Tickets:
 - *32904*

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
@iefode @andrei-kochin is it still valid?

**Comment by iefode** [comment]
> @iefode @andrei-kochin is it still valid?

yes. it's valid.
i will rebase it soon. Thanks!

**Comment by akladiev** [comment]
This PR will be closed in 2 weeks in case of no activity.

**Comment by akladiev** [comment]
This PR was closed because it has been stalled for 2 week with no activity.

**Pull request closed without merging**
