### PR TITLE
Hot Fix: using all small core as Ecore

### PR DESCRIPTION
**Pull request by wangleis**
### Details:
 - *using all small core as Ecore as legacy behavior*

### Tickets:
 - *108497*

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
As we agree on the sync lets cover small cores configuration with tests. The logic itself looks good.

**Review by DariaMityagina — APPROVED** [review]
Thanks a lot for the hot fix 👍

**Comment by wangleis** [comment]
> As we agree on the sync lets cover small cores configuration with tests. The logic itself looks good.

Updated

**Comment by DariaMityagina** [comment]
Thanks @dmitry-gorokhov for merging this PR :)

**Pull request merged**
