### PR TITLE
feat: add pre-commit hook and format all files

### PR DESCRIPTION
**Pull request by NripeshN**
Added a pre-commit hook and formatted all the files in the repo

### CODE REVIEW

**Comment by rkazants** [comment]
@NripeshN, what is a point of this PR? Please elaborate its value.

**Comment by NripeshN** [comment]
> @NripeshN, what is a point of this PR? Please elaborate its value.

Hi @rkazants 

This PR introduces a few pre-commit hooks to help maintain code quality and consistency across our project. Here's a quick rundown:

1. **clang-format**: Ensures our C/C++ code follows our style guidelines.
2. **black**: Automatically formats our Python code to be clean and readable, except for the specified file which isn't compatible with black's rules.
3. **isort**: Organizes our Python imports neatly, aligned with the Black profile for consistency.

These tools catch common formatting issues before they make it into our codebase, making code reviews smoother and saving us time. Plus, they keep our project looking professional, no matter how many people contribute.

We could also have a CI test that runs on every PR, `push to main` that checks if the PR is properly formatted. We could also make a bot push the formatted changes into the PR too if it is necessary.

Hope this clarifies things! Let me know if there are any other questions.

Cheers,
Nripesh

**Comment by rkazants** [comment]
> Hi @rkazants
> 
> This PR introduces a few pre-commit hooks to help maintain code quality and consistency across our project. Here's a quick rundown:
> 
> 1. **clang-format**: Ensures our C/C++ code follows our style guidelines.
> 2. **black**: Automatically formats our Python code to be clean and readable, except for the specified file which isn't compatible with black's rules.
> 3. **isort**: Organizes our Python imports neatly, aligned with the Black profile for consistency.
> 
> These tools catch common formatting issues before they make it into our codebase, making code reviews smoother and saving us time. Plus, they keep our project looking professional, no matter how many people contribute.
> 
> We could also have a CI test that runs on every PR, `push to main` that checks if the PR is properly formatted. We could also make a bot push the formatted changes into the PR too if it is necessary.
> 
> Hope this clarifies things! Let me know if there are any other questions.
> 
> Cheers, Nripesh

This PR introduces huge changes and it is impossible to review. Also, we already have formatting requirements to our code base and job checking code-style.

@ilya-lavrenov, please take a look.

**Comment by NripeshN** [comment]
> > Hi @rkazants
> > This PR introduces a few pre-commit hooks to help maintain code quality and consistency across our project. Here's a quick rundown:
> > 
> > 1. **clang-format**: Ensures our C/C++ code follows our style guidelines.
> > 2. **black**: Automatically formats our Python code to be clean and readable, except for the specified file which isn't compatible with black's rules.
> > 3. **isort**: Organizes our Python imports neatly, aligned with the Black profile for consistency.
> > 
> > These tools catch common formatting issues before they make it into our codebase, making code reviews smoother and saving us time. Plus, they keep our project looking professional, no matter how many people contribute.
> > We could also have a CI test that runs on every PR, `push to main` that checks if the PR is properly formatted. We could also make a bot push the formatted changes into the PR too if it is necessary.
> > Hope this clarifies things! Let me know if there are any other questions.
> > Cheers, Nripesh
> 
> This PR introduces huge changes and it is impossible to review. Also, we already have formatting requirements to our code base and job checking code-style.
> 
> @ilya-lavrenov, please take a look.

Yeah, it definitely looks like a lot at first glance! 😅 But the good news is, these tools—`clang-format`, `black`, and `isort`—are focused solely on formatting. They won't change the functionality of our code at all.

**Pull request closed without merging**
