### PR TITLE
[CPU] Added improvements for Mish

### PR DESCRIPTION
**Pull request by a-sidorova**
### Details:
 - Changed Mish implementation: added more optimal and easier function (after math transformations)
 - PR in onednn: https://github.com/openvinotoolkit/oneDNN/pull/43

### Tickets:
 - 52396

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@maxnick could you please review?

**Comment by maxnick** [comment]
Does `Mish` activation single layer test check results for `x > 20`?

**Comment by a-sidorova** [comment]
@maxnick, added. Thanks!

**Review by maxnick — APPROVED** [review]

**Comment by a-sidorova** [comment]
@maxnick, thank you!

@dmitry-gorokhov, could you review please?

**Review by dmitry-gorokhov — APPROVED** [review]

**Comment by dmitry-gorokhov** [comment]
@a-sidorova  @lazarevevgeny  Not sure but it might be worthwhile to include description of this optimization into the spec itself so all the plug-in can reuse it.

**Comment by lazarevevgeny** [comment]
> @a-sidorova @lazarevevgeny Not sure but it might be worthwhile to include description of this optimization into the spec itself so all the plug-in can reuse it.

To be honest, I don't like the idea to put such kind of notices into the spec. The implementation details are on the plugin owners shoulders. The spec should provide clear and concise description of the operation.

**Pull request merged**
