### PR TITLE
[Bugfix] Remove Structural Attributes from Proposal op

### PR DESCRIPTION
**Pull request by Ewa21**
The main goal of the proposed changes is to resolve the inconsistency of the Proposal implementation and the IR specification. Currently, the operation spec does not support Structural Attributes. Therefore the Structural Attributes are deleted from the Proposal op.

### CODE REVIEW

**Comment by lazarevevgeny** [comment]
Can you merge changes from the master branch? It may resolve the compilation issues.

**Review by postrational — APPROVED** [review]

**Review by ilyachur — APPROVED** [review]

**Review by arogowie-intel — APPROVED** [review]
LGTM. I'd only consider adding `get_*` and `set_*` pairs of methods for all attributes in C++ class to have uniform API from Python and C++.

**Review by lazarevevgeny — APPROVED** [review]

**Comment by ilyachur** [comment]
> LGTM. I'd only consider adding `get_*` and `set_*` pairs of methods for all attributes in C++ class to have uniform API from Python and C++.

I think we can do it in the separate PR.

**Comment by pavel-esir** [comment]
Was merged right before I intended to approve and write a comment. There are some other operations with AttributeAdapters `Interpolate`, `DetectionOutput` maybe other and I think similar changes with AttributeAdapters have to be done for them as well, in the future.

**Comment by ilyachur** [comment]
> Was merged right before I intended to approve and write a comment. There are some other operations with AttributeAdapters `Interpolate`, `DetectionOutput` maybe other and I think similar changes with AttributeAdapters have to be done for them as well, in the future.

Right. Now we have several operations which have the same issue `Interpolate`, `DetectionOutput`, `PriorBox` and etc.
I propose to create tickets for each operation which has the same structure and resolve all these tickets separately.

**Pull request merged**
