### PR TITLE
[BF16] Restore convert layer after input

### PR DESCRIPTION
**Pull request by EgorDuplensky**
### Details:
 - Bring back insertion of convert layer after input to avoid extra FP32->BF16 reorders

### Tickets:
 - 48232

### CODE REVIEW

**Comment by EgorDuplensky** [comment]
@alexey-varyzgin, @maxnick
Please take a look

**Comment by EgorDuplensky** [comment]
FYI
I decided to not bring back bf16transformer class since this implementation is temporary anyway.

**Comment by EgorDuplensky** [comment]
Postponed till ngraph migration.

**Comment by dmitry-gorokhov** [comment]
Closing since the PR is not supposed to be merged.

**Pull request closed without merging**
