### PR TITLE
Add ONNX reader in dev package

### PR DESCRIPTION
**Pull request by omaskovx**

### CODE REVIEW

**Comment by gladilov-gleb** [comment]
@ilyachur FYI

**Comment by ilya-lavrenov** [comment]
It's not needed. Why external project need onnx reader target?

**Comment by ilya-lavrenov** [comment]
Alternative solution https://github.com/openvinotoolkit/openvino/pull/693

**Comment by gladilov-gleb** [comment]
@ababushk it looks like for some reason ci/jenkins pipeline has not been started automatically for that request. I tried to do it manually. Could you please look at that issue?

@ilya-lavrenov we need this to unblock development in KMB and MYRIAD plugins. Our CI builds tests applications using `ie_dev_targets`, but onnx readers is not here, so it's trying to load this library during tests run and fails..

**Pull request closed without merging**
