### PR TITLE
[CPU] Fix RNN node isSupported check

### PR DESCRIPTION
**Pull request by EgorDuplensky**
Incorrect check resulted into a decomposition of different RNN operations

### CODE REVIEW

**Comment by dmitry-gorokhov** [comment]
@EgorDuplensky Do we have any ticket? 
Also is it possible to extend CPU func test to cover such cases? (just wondering if existing test checks that execution actaully matched on oneDNN RNN prim)

**Comment by dmitry-gorokhov** [comment]
@ceciliapeng2011  please review

**Comment by EgorDuplensky** [comment]
> @EgorDuplensky Do we have any ticket? Also is it possible to extend CPU func test to cover such cases? (just wondering if existing test checks that execution actaully matched on oneDNN RNN prim)

There is no ticket for this issue yet.
The problem is the non-fusing slt tests are not checking (for the last few years) for the presence of the node for some reason.
There is a PR which removed the check:
- https://github.com/openvinotoolkit/openvino/pull/7684
I have created a PR to bring it back:
- https://github.com/openvinotoolkit/openvino/pull/24146
There are many other slt's which start to fail with the check enabled.

**Comment by CuriousPanCake** [comment]
Hello!
Can we expect this to be merged in the nearest future?

**Comment by EgorDuplensky** [comment]
> Hello! Can we expect this to be merged in the nearest future?

Probably can be expected to be merged by the end of this week

**Comment by EgorDuplensky** [comment]
@ceciliapeng2011 Gentle reminder

**Review by usstq — APPROVED** [review]
LGTM

**Comment by usstq** [comment]
> @ceciliapeng2011 Gentle reminder

Cecilia is

**Comment by wenjiew** [comment]
Tingqian reviewed on behalf. What is the next step? @EgorDuplensky

**Comment by EgorDuplensky** [comment]
rebased

**Review by maxnick — APPROVED** [review]

**Comment by EgorDuplensky** [comment]
rebased one more time to pull ci fixes from master

**Pull request merged**
