### PR TITLE
[OV][VPUX] - add replacement /Z7 -> /Zi /FS

### PR DESCRIPTION
**Pull request by DariaMityagina**
Applying this comment: https://github.com/openvinotoolkit/openvino/pull/14651#issuecomment-1357538476

There are many 'workarounds' related to debug build flags. In different places they are replaced by each other, which causes confusion and possible problems. Examples:

- 17:47:04 C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\bin\intel64\Debug\vpux_mlir_compiler_staticd.lib : fatal error LNK1248: image size (1005C0F3F) exceeds maximum allowable size (FFFFFFFF)
- fatal error C1033: cannot open program database
- fatal error C1041: cannot open program database

### Current way:

</head>

<body link="#0563C1" vlink="#954F72">

Check: | https://vpux-ci-vpuip.ir.intel.com/job/IE-Packages/job/try/job/OpenVINO-Windows10/22207/ | https://vpux-ci-vpuip.ir.intel.com/job/IE-Packages/job/try/job/OpenVINO-Windows10/22234/
-- | -- | --
Time: |  1 h 26 min | 1h 24 min
Package   size: | 5.95 GB | 5.96 GB
Result: |  success | success

</body>

</html>

### /Z7 -> /Zi /FS (changes in this PR)

</head>

<body link="#0563C1" vlink="#954F72">

Check: | https://vpux-ci-vpuip.ir.intel.com/job/IE-Packages/job/try/job/OpenVINO-Windows10/22203/ | https://vpux-ci-vpuip.ir.intel.com/job/IE-Packages/job/try/job/OpenVINO-Windows10/22235/
-- | -- | --
Time: |  1 h | 1h 13 min
Package   size: | 5.99 GB  | 6 GB
Result: |  success | success

</body>

</html>

### CODE REVIEW

**Review by OrestChura — APPROVED** [review]
I agree, this is a better way.
We'll need to monitor that problems are solved, though.
Thank you!

**Comment by DariaMityagina** [comment]
> We'll need to monitor that problems are solved, though.

Absolutely!

**Review by ArtemySkrebkov — APPROVED** [review]

**Comment by DariaMityagina** [comment]
@ilyachur hi!
Could you please review this PR?

**Comment by DariaMityagina** [comment]
@ilyachur hi!
Could you please review this PR?

**Review by ilyachur — APPROVED** [review]

**Comment by DariaMityagina** [comment]
@ilyachur thanks for merging it :)

**Pull request merged**
