### PR TITLE
[CPU] Fix performance issue for some cases of Reduce node

### PR DESCRIPTION
**Pull request by xuchen-intel**
### Details:
 - *Support dequantization fusing for Reduce node*
 - *Support division directly in first JIT kernel for some cases of ReduceMean*

### Tickets:
 - *79072*

### CODE REVIEW

**Comment by xuchen-intel** [comment]
@dmitry-gorokhov Hi Dmitry, could you please take a look?

**Comment by dmitry-gorokhov** [comment]
@chenhu-wang may I ask you to start the review?

**Review by chenhu-wang — APPROVED** [review]

**Comment by chenhu-wang** [comment]
In general looks good. Need DLB to check perf and accuracy

**Comment by dmitry-gorokhov** [comment]
@xuchen-intel do we still need this PR?

**Comment by xuchen-intel** [comment]
@dmitry-gorokhov Hi Dmitry, updated, could you please take a look?

**Comment by xuchen-intel** [comment]
rebased.

**Comment by ilya-lavrenov** [comment]
Please, fix merge conflicts

**Comment by akladiev** [comment]
This PR was closed because it has been stalled for 2 week with no activity.

**Comment by xuchen-intel** [comment]
@dmitry-gorokhov Hi Dmitry, I've rebased on the latest master. Feel free to comment. Thanks!

**Review by dmitry-gorokhov — APPROVED** [review]
LGTM in general.
@xuchen-intel  Please launcg internal performance validation to make sure the PR doesn't introduce any regressions (eps in combination with latest your changes to Reduce). If perf regressions will not be found the PR can be merged.

**Comment by xuchen-intel** [comment]
> LGTM in general. @xuchen-intel Please launcg internal performance validation to make sure the PR doesn't introduce any regressions (eps in combination with latest your changes to Reduce). If perf regressions will not be found the PR can be merged.

@dmitry-gorokhov Hi Dmitry, I've launched internal performance validation. No regression is found. Details are attached in the ticket. Thanks!

**Comment by dmitry-gorokhov** [comment]
@xuchen-intel please rebase the PR on latest master and I will merge it

**Comment by xuchen-intel** [comment]
> @xuchen-intel please rebase the PR on latest master and I will merge it

@dmitry-gorokhov Rebased. Thanks Dmitry!

**Pull request merged**
