### PR TITLE
[ONNX] Extend ONNX Frontend with `com.microsoft.GatherND`

### LINKED ISSUE #17577: Extend ONNX Frontend with `com.microsoft.GatherND` operator
## Context
Neural networks are graphs consisting of nodes called operators. Each operator corresponds to a mathematical function, usually described in framework's documentation or an AI standard, such as ONNX.

OpenVINO ONNX Frontend is a component responsible for working with ONNX graphs and requires implementation of different ONNX operators in order to use ONNX models.

This task requires extending OpenVINO ONNX Frontend with `com.microsoft.GatherND` operator.

Necessary help will be provided by ONNX Fronted team.

## Operator specification
Operator details can be found in [official ONNX Runtime docs](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.GatherND).

## Todo list
1. Create `.hpp` and `.cpp` files for `com.microsoft.GatherND` [here](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/frontend/src/op)
2. Prepare an implementation of this operator in form of a function. It should be placed in [opset 1 namespace](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/unique.hpp#L13). You can use the implementation of standard [ONNX GatherND operator](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/gather_nd.cpp) as a reference
3. Register the function in [ops_bridge.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/ops_bridge.cpp#L554-L560) while keeping alphabetical order
4. Create test model(s) in [ONNX models directory](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/tests/models/com.microsoft). OpenVINO test infrastructure then converts prototxt files to ONNX models - you will use those models later in tests
5. Add tests covering all use cases [here](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/onnx_import_com_microsoft.in.cpp)

More details in [adding operators to ONNX Frontend guide](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/how_to_add_op.md)

## Resources
- Guides on [ONNX Frontend architecture](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/architecture.md) and [ONNX Frontend tests](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/tests.md) are also available
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- You can also see a [blog post on contributing to OpenVINO](https://medium.com/openvino-toolkit/how-to-contribute-to-an-ai-open-source-project-c741f48e009e)

## Example PRs
- https://github.com/openvinotoolkit/openvino/pull/15076
- https://github.com/openvinotoolkit/openvino/pull/14936
- https://github.com/openvinotoolkit/openvino/pull/12510

## Contact points
@tomdol
@mbencer
@p-wysocki
Don't hesitate to reach out, we're here to help!

### PR DESCRIPTION
**Pull request by siddhant-0707**
### Details:
 - created implementation for `com.microsoft.GatherND`
 - created test

### Tickets:
 - Closes #17577

### CODE REVIEW

**Comment by gkrivor** [comment]
Hi, thanks for you contribution! Could you fix merge conflicts? It is due to refactored tests.

**Comment by gkrivor** [comment]
build_jenkins

**Comment by gkrivor** [comment]
Hi @siddhant-0707 ! Could you take a look on discussion in this PR: https://github.com/openvinotoolkit/openvino/pull/21653

I think we also don't need to create separate implementation for com.microsoft domain.

I don't see any difference with default implementation. I suggest to do same - just add a registration record and the test.

**Comment by siddhant-0707** [comment]
@gkrivor Please review

**Comment by mitruska** [comment]
build_jenkins

**Review by mitruska — APPROVED** [review]

**Pull request merged**
