### PR TITLE
[LPT] Correct a check for whether model is quantized

### PR DESCRIPTION
**Pull request by EgorDuplensky**
### Details:
 - Look inside subgraph operations, such as TensorIterator, Loop, If, etc
 
 ### Tickets:
 - 88600

### CODE REVIEW

**Comment by EgorDuplensky** [comment]
@dmitry-gorokhov Could you please take a look?

**Review by dmitry-gorokhov — APPROVED** [review]
LGTM

**Comment by dmitry-gorokhov** [comment]
@EgorDuplensky Please make CI green

**Comment by EgorDuplensky** [comment]
@dmitry-gorokhov done

**Pull request merged**
