### PR TITLE
Removed saved_model_tags from OVC, improved help.

### PR DESCRIPTION
**Pull request by popovaan**
Description:

- Removed "saved_model_tags" parameter from OVC.
- Improved help.
- Corrected tests of shared memory in TF decoder.
- Removed intermediate conversion to string of tools.ovc.convert_model() arguments.
- Renamed 'extensions' parameter to 'extension'.

Ticket: 115752

Code:
* [x]  Comments
* [x]  Code style (PEP8)
* [x]  Transformation generates reshape-able IR - N/A
* [x]  Transformation preserves original framework node names - N/A
* [x]  Transformation preserves tensor names - N/A

Validation:
* [x]  Unit tests
* [x]  Framework operation tests - N/A
* [x]  Transformation tests - N/A
* [x]  Model Optimizer IR Reader check - N/A

Documentation:
* [x]  Supported frameworks operations list - N/A
* [x]  Guide on how to convert the **public** model - N/A
* [x]  User guide update - N/A

### CODE REVIEW

**Comment by popovaan** [comment]
> > Improved help.
> 
> @popovaan, please insert the resulting output of `ovc -h` here to review the improvement.

usage: ovc.py [-h] [--output_model OUTPUT_MODEL] [--compress_to_fp16]
              [--version] [--input INPUT] [--output OUTPUT]
              [--extensions [EXTENSIONS]] [--verbose]
              input_model

positional arguments:
  input_model           Input model file(s) from TensorFlow, ONNX,
                        PaddlePaddle. Use openvino.convert_model in Python to
                        convert models from Pytorch.

optional arguments:
  -h, --help            show this help message and exit
  --output_model OUTPUT_MODEL
                        This parameter is used to name output .xml/.bin files
                        with converted model.
  --compress_to_fp16    Compress weights in output IR .xml/bin files to FP16.
  --version             Print ovc version and exit.
  --input INPUT         Information for model input required for model
                        conversion. This is a comma separated list with
                        optional input names, shapes, data types, and values
                        for freezing. The order of inputs in converted model
                        will match the order of specified inputs. The shape
                        and value are specified as comma-separated lists. The
                        data type of input node is specified in braces and can
                        have one of the values: f64 (float64), f32 (float32),
                        f16 (float16), i64 (int64), i32 (int32), u8 (uint8),
                        boolean (bool). Data type is optional. If it's not
                        specified explicitly then there are two options: if
                        input node is a parameter, data type is taken from the
                        original node dtype, if input node is not a parameter,
                        data type is set to f32. Example, to set `input_1`
                        with shape [1,100], and Parameter node `sequence_len`
                        with scalar input with value `150`, and boolean input
                        `is_training` with `False` value use the following
                        format:
                        "input_1[1,100],sequence_len->150,is_training->False".
                        Another example, use the following format to set input
                        port 0 of the node `node_name1` with the shape [3,4]
                        as an input node and freeze output port 1 of the node
                        "node_name2" with the value [20,15] of the int32 type
                        and shape [2]:
                        "0:node_name1[3,4],node_name2:1[2]{i32}->[20,15]".
  --output OUTPUT       The name of the output operation of the model or list
                        of names. For TensorFlow*, do not add :0 to this
                        name.The order of outputs in converted model is the
                        same as order of specified operation names.
  --extensions [EXTENSIONS]
                        Paths or a comma-separated list of paths to libraries
                        (.so or .dll) with extensions. For the legacy MO path
                        (if `--use_legacy_frontend` is used), a directory or a
                        comma-separated list of directories with extensions
                        are supported. To disable all extensions including
                        those that are placed at the default location, pass an
                        empty string.
  --verbose             Print detailed information about conversion.

**Comment by ilya-lavrenov** [comment]
is not it better to have:
```
usage: ovc.py [-h] [--output_model OUTPUT_MODEL]
              [--compress_to_fp16 [True | False]] [--version] [--input INPUT]
              [--output OUTPUT] [--extensions [EXTENSIONS]] [--verbose] INPUT_MODEL
```
? 
If we compare with git:
```
SYNOPSIS
       git clone [--template=<template_directory>]
                 [-l] [-s] [--no-hardlinks] [-q] [-n] [--bare] [--mirror]
                 [-o <name>] [-b <name>] [-u <upload-pack>] [--reference <repository>]
                 [--dissociate] [--separate-git-dir <git dir>]
                 [--depth <depth>] [--[no-]single-branch] [--no-tags]
                 [--recurse-submodules[=<pathspec>]] [--[no-]shallow-submodules]
                 [--[no-]remote-submodules] [--jobs <n>] [--sparse] [--] <repository>
                 [<directory>]
```
We can see that `repository` comes last
The same for `ls`:
```
$ ls --help
Usage: ls [OPTION]... [FILE]...
List information about the FILEs (the current directory by default).
Sort entries alphabetically if none of -cftuvSUX nor --sort is specified.
```

**Comment by slyalin** [comment]
> is not it better to have:
> 
> ```
> usage: ovc.py [-h] [--output_model OUTPUT_MODEL]
>               [--compress_to_fp16 [True | False]] [--version] [--input INPUT]
>               [--output OUTPUT] [--extensions [EXTENSIONS]] [--verbose] INPUT_MODEL
> ```

I don't think it's better because `INPUT_MODEL` is only required parameter and we hope most users will always call `ovc` with a single parameter. Also please use `...` after `INPUT_MODEL` because there could be multiple files defining a single model (example: TF). And also this indentation can focus on `INPUT_MODEL` as the main parameter keeping apart optional parameters:

> ```
> usage: ovc INPUT_MODEL... [-h] [--output_model OUTPUT_MODEL]
>                                              [--compress_to_fp16 [True | False]] [--version] [--input INPUT]
>                                              [--output OUTPUT] [--extensions [EXTENSIONS]] [--verbose] 
> ```

BTW, why `[EXTENSIONS]` in square brackets? Are they optional?

**Comment by popovaan** [comment]
> > is not it better to have:
> > ```
> > usage: ovc.py [-h] [--output_model OUTPUT_MODEL]
> >               [--compress_to_fp16 [True | False]] [--version] [--input INPUT]
> >               [--output OUTPUT] [--extensions [EXTENSIONS]] [--verbose] INPUT_MODEL
> > ```
> 
> I don't think it's better because `INPUT_MODEL` is only required parameter and we hope most users will always call `ovc` with a single parameter. Also please use `...` after `INPUT_MODEL` because there could be multiple files defining a single model (example: TF). And also this indentation can focus on `INPUT_MODEL` as the main parameter keeping apart optional parameters:
> 
> > ```
> > usage: ovc INPUT_MODEL... [-h] [--output_model OUTPUT_MODEL]
> >                           [--compress_to_fp16 [True | False]] [--version] [--input INPUT]
> >                           [--output OUTPUT] [--extensions [EXTENSIONS]] [--verbose] 
> > ```
> 
> BTW, @popovaan, why is `[EXTENSIONS]` in square brackets? Are they optional?

In MO extensions are not optional, so it looks like a mistake in OVC. Corrected it.

**Review by slyalin — APPROVED** [review]

**Pull request merged**
