### PR TITLE
[GPU] Apply is_non_decompression_multiply() callback only for compressed models

### PR DESCRIPTION
**Pull request by sshlyapn**
### Details:
 - Fix quantized models performance issue caused by unintentional applying is_non_decompression_multiply() callback to quantized constants

### Tickets:
 - 127833

### CODE REVIEW

**Review by vladimir-paramuzov — APPROVED** [review]
lgtm if perf is ok

**Review by e-ddykim — COMMENTED** [review]
I think `initial_transformations_manager.run_passes(func)` needs to be called somewhere, doesn't it?

**Comment by sshlyapn** [comment]
> I think `initial_transformations_manager.run_passes(func)` needs to be called somewhere, doesn't it?

Absolutely, thank you!

**Review by p-durandin — APPROVED** [review]

**Comment by isanghao** [comment]
Target network execution graph was recovered. Did not check the entire test scope.

**Review by e-ddykim — APPROVED** [review]

**Pull request merged**
