### PR TITLE
Using OV RTTI: part1 (transformations)

### PR DESCRIPTION
**Pull request by itikhono**
### Details:
Due to the issues on Android system with the standart c++ RTTI, it was proposed to switch to the ov RTTI
So we are going to replace dynamic_ptr_cast to ov::as_type_ptr, dynamic_cast to ov::as_type

### Tickets:
 - *CVS-151640*

### CODE REVIEW

**Review by ilya-lavrenov — APPROVED** [review]
Let's check whether performance of transformations is not affected and then, merge.

**Comment by itikhono** [comment]
the validation job failed.
I will re-run it after rebase

**Comment by itikhono** [comment]
the Validation job failed again due to a new model conversion mode.
waiting for re-run

**Comment by itikhono** [comment]
the additional validation jobs passed. no visible regressions

**Pull request merged**
