### PR TITLE
[Python API] Remove unused dependency on onnx_frontend

### PR DESCRIPTION
**Pull request by akuporos**

### CODE REVIEW

**Comment by tomdol** [comment]
The old bindings rely on the ONNX reader but it uses `import_onnx_model` underneath. This symbol is located in the ONNX FE library which is excluded from the wheel because of the changes in this PR. It should probably be caught by the CI if this happens to be a problem though.

**Comment by ilya-lavrenov** [comment]
> The old bindings rely on the ONNX reader but it uses `import_onnx_model` underneath. This symbol is located in the ONNX FE library which is excluded from the wheel because of the changes in this PR. It should probably be caught by the CI if this happens to be a problem though.

Why do they need Onnx?

**Comment by akuporos** [comment]
> The old bindings rely on the ONNX reader but it uses `import_onnx_model` underneath. This symbol is located in the ONNX FE library which is excluded from the wheel because of the changes in this PR. It should probably be caught by the CI if this happens to be a problem though.

all azure CI jobs passed, `openvino-ngraph-onnx-lin` calls setup.py and it hasn't failed due-to removal of `onnx_frontend` as dependency

**Comment by tomdol** [comment]
> > The old bindings rely on the ONNX reader but it uses `import_onnx_model` underneath. This symbol is located in the ONNX FE library which is excluded from the wheel because of the changes in this PR. It should probably be caught by the CI if this happens to be a problem though.
> 
> Why do they need Onnx?

The old bindings can also be used to load ONNX models so I though the `import_onnx_model` symbol has to be available. The CI hasn't failed so it's still working, perhaps it loads the models some different way now.

**Review by jiwaszki — COMMENTED** [review]
@tomdol as for importing:
```python
def import_onnx_model(model: onnx.ModelProto) -> Function:
    onnx.checker.check_model(model)  # onnx method
    model_byte_string = model.SerializeToString()  # onnx method as well
    ie = Core()  # OV
    func = ie.read_model(bytes(model_byte_string), Tensor(type=np.uint8, shape=[]))  # OV loads model via bytes and empty Tensors

    return func
```
So it seems that it is all right, no symbols here.

**Pull request merged**
